local my_language = {
	give_vehicle = "You added ~b~%s~w~ to your inventory.",
	store_vehicle_command = "Store the vehicle you are driving",
	no_entity_vehicle = "~r~The vehicle does not exist or is too far from you.",
	no_entity_vehicle_id = "~r~The vehicle is not binded to any id, you can't store it.",
	store_vehicle = "~b~You stored your car.",
	teleported_former_position = "~g~You have been teleported to your latest saved position.",
	not_enough_of = "~r~You don't have enough %s.",
	max_storage_chest = "~r~The storage box is full.",
	cant_carry_more_items = "~r~Your inventory can't store more items (full).",
	put_item = "You put ~g~x%s~w~ %s~w~.",
	take_item = "You took ~g~x%s~w~ %s~w~.",
	delete_item = "You removed ~r~x%s~w~ %s~w~.",
	you_equiped_item = "You have equipped your ~g~%s~w~.",
	bind_weapon_command = "Shortcut for weapon slot %s",
	kevlar_broke = "~r~AHH!~n~~w~Your armor broke.",
	inventory_command = "Toggle inventory",
	press_enter_to_join = "Press ~g~ENTER~w~ to start playing.",
	new_character = "New character",
	survivor = "Survivor",
	right = "Right",
	left = "Left",
	male = "Male",
	female = "Female",
	ped = "Ped",
	name = "Name",
	sex = "Sex",
	title = "Title",
	select_this_character = "Select this character",
	no_entity_zombie = "The zombie does not exist or is too far from you.",
	you_found = "You found ~g~%sx %s~w~.",
	you_found_nothing = "You found ~g~nothing~w~.",
	press_e_to_loot = "Press ~b~[E]~w~ to loot",
	full_for_item = "~r~There is not enough room for this item.",
	put_item_container = "You put ~g~x%s~w~ %s~w~ in your container.",
	take_item_container = "You took ~g~x%s~w~ %s~w~ from your container.",
	not_allowed_here = "~r~You are not allowed to do that here.",
	cant_store_moving_veh = "~r~You can't store a moving vehicle.",
	use_repair_tool = "use the repair tool",
	please_get_closer = "~b~Please get closer, no entity in range.",
	you_cancel_action = "~r~You canceled the action.",
	selected_target_message = "Selected target:~n~%s~n~~r~Press ~b~Y~r~ to cancel~n~~r~Press ~g~X~r~ to continue.",
	target_you = "~b~YOU",
	target_screen = "~g~Displayed",
	take_this_path = "take this path",

	-- hud
	default_hud = "Default HUD",
	cinema_hud = "Cinema HUD",
	no_hud = "No HUD",

	-- perms
	kick_member = "Kick members",
	edit_member = "Edit members",
	edit_rank = "Edit ranks",
	create_rank = "Create ranks",
	delete_rank = "Delete ranks",
	edit_structure = "Edit crew info",
	edit_permissions = "Edit permissions",
	permission_level = "Permission grant",
	red_delete = "Delete",
	rank = "Rank",
	red_kick = "Kick",
	crew_name = "Crew name",
	slogan = "Catchphrase",
	information = "information",
	boss_rank = "Boss rank name",
	member_rank = "Newbie rank name",
	member = "Member",

	permissions_manager = "permissions manager",
	members_manager = "members manager",
	ranks_manager = "ranks manager",
	ranks_list = "ranks list",
	members_list = "members list",
	create_a_rank = "create a rank",
	invite_someone = "invite someone",
	stats = "Stats",
	total_ranks = "Rank count",
	total_members = "Member count",
	level = "Level",
	actions = "actions",
	crew_manager = "crew manager",
	you_created_a_new_crew = "You created a new crew: %s",
	you_deleted_your_crew = "You deleted your crew.",
	you_are_not_in_a_crew = "You are not in a crew",
	you_joined_the_crew = "You joined a new Crew '%s'",
	kick_failed = "The kick failed, reason: %s",
	already_in_crew = "You are already in a crew",
	no_invitation = "You haven't received any invitation.",
	left_crew = "You left your crew.",
	permission_updated = "The permissions of <C>~g~%s</C>~w~ have been updated.",
	incorrect_name = "~r~The name format is incorrect",
	incorrect_rank_perm = "~r~Error\n~w~The rank name or the permission level is invalid.",
	warn_rank_limit = "~r~You reached the ranks limit.",
	create_rank_success = "~g~Success\n~w~You created a new rank <C>~b~%s</C>~w~ with a permission level of <C>~b~%s</C>~w~.",
	crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~You cannot interact with a member that have a permission level above yours.",
	you_sent_an_invitation = "You sent an invitation to <C>~g~%s</C>~w~ to join your crew.",
	you_received_an_invitation = "You received an invitation to join a crew.\n~b~/%s to accept.",
	invitation_expired = "The invitation expired",
	crew_kick_success = "You kicked <C>~b~%s</C>~w~ from your crew.",
	first_rank_warning = "The first rank is the 'default' rank.",

	you_updated_this = "You updated %s to ~g~<C>%s</C>~w~.",
	changes_saved_on = "The changes made on <C>~g~%s</C>~w~ have been saved.",
	yes = "yes",
	no = "no",
	none = "None",
	character_id = "Character ID",
	server_id = "Server ID",
	report = "Report",
	rename = "Rename",
	trade_with = "Trade",
	
	please_wait_x_before = "~r~Please wait %s seconds before doing that.",

	-- cloth
	take_outfit = "Buy this outfit",
	wardrobe_options = "wardrobe options",
	wardrobe = "wardrobe",
	manual_options = "manual options",
	manual_mode = "manual mode",
	save_outfit = "Save this outfit",
	variation = "variation",
	outfits = "outfits",
	cloth_shop = "Cloth shop",
	ped_cloth_shop = "Ped cloth shop",
	manual_props = "manual props",
	manuel = "manual",
	new_name = "New name",
	outfit_name = "Outfit name",
	variations_saved = "~g~Success.~n~~w~Your character variations have been saved.",
	equipped_new_outfit = "You equipped your new outfit: ~b~%s",
	warning_limit_outfits = "You reached the limit of saved outfits. ~g~(%s)",
	saved_new_outfit = "You saved a new outfit: ~b~%s~w~.",
	rename_outfit = "Your outfit ~b~%s~w~ has been renamed to ~g~%s~w~.",
	delete_outfit = "Your outfit: ~b~%s~w~ has been deleted.",

	torso = "Torso",
	props = "Props",
	top = "Top",
	tops = "Tops",
	badge = "Badge",
	pants = "Pants",
	pant = "Pant",
	shoes = "Shoes",
	bags = "Bags",
	undershirt = "undershirt",
	neck = "neck",
	bracelets = "bracelets",
	montres = "watches",
	earrings = "earrings",
	glasses = "glasses",
	hats = "hats",
	graphiques = "decorations",

	-- health
	inconscious = "Unconscious",
	doing_something = "Doing something",
	time_before_respawn = "Time before respawning",
	you_died = "~r~You died.",
	healing_wounds = "Healing wounds",
	already_doing_something = "~r~You are already doing something.",
	you_have_been_healed = "~g~You have been healed.",
	you_respawned = "~g~You respawned.",

	player_too_far_to_interact = "~r~The player you want to interact with is too far from you.",
	send_trade_invitation_to = "You sent an invitation to exchange to ~b~%s~w~.\n~b~Wait for the other player to accept it.",
	receive_invitation_from = "You received an invitation to exchange from ~b~%s~w~.\n~b~Type ~w~/trade accept %s~b~ to start the trade.",

	invalid_command_args = "Invalid command arguments: %s",
	start_trade_command_help = "Start a trade with another player",
	accept_trade_command_help = "Accept a trade invitation",
	deny_trade_command_help = "Deny a trade invitation",
	invalid_invitation = "The invitation is invalid or no longer exists",
	name_accepted_your_trade_invitation = "~b~%s~w~ accepted your trade invitation",
	you_accepted_trade_invitation_of_name = "You accepted the trade invitation of %s",
	name_denied_your_trade_invitation = "~b~%s~w~ denied your trade invitation",
	you_denied_trade_invitation_of_name = "You denied the trade invitation of %s",
	you_already_trading = "You are already trading",
	other_already_trading = "The other player is already trading",

	other_player_not_enough_money = "~r~The trade failed. The other player did not have enough money.",
	you_player_not_enough_money = "~r~The trade failed. You did not have enough money.",
	other_player_not_enough_item = "~r~The trade failed. The other player did not have enough of some item.",
	you_player_not_enough_item = "~r~The trade failed. You did not have enough of some item.",
	success_trade = "~g~The trade has been confirmed.",
	fail_trade_other_player = "~r~The trade failed, the other player left.",
	trade_other_full_item = "~r~The trade failed, the other player has not enough storage.",
	trade_full_for_item = "~r~The trade failed, you do not have enough storage.",

	press_e_to_loot_inv = "Press ~INPUT_CONTEXT~ to loot the inventory.",
	press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~Press ~INPUT_CONTEXT~ to interact with ~b~%s~HUD_COLOUR_NET_PLAYER27~.",
	press_e_to = "Press ~INPUT_CONTEXT~ to ~b~%s~w~.",
	press_e_to_open_catalog = "Press ~b~E~w~ to read the ~g~catalog~w~.",
	this_person = "this person",
	the_shop = "this shop",
	you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~You are not allowed to do that.",

	no_weapon = "~r~You do not have any weapon equipped.",
	no_need_ammo = "~r~You do not need to use any ammo with this weapon.",
	not_right_ammo = "~r~You are not using the right ammo, you need ~b~%s~w~.",
	you_used_ammo = "You loaded your ~b~%s~w~ with ~b~x%s~w~ of ~b~%s~w~.",

	choose_a_destination = "choose a ~b~destination",
	open_your_chest = "open your chest",
	no_enough_money = "~r~You can't afford that.",
	you_paid = "You paid ~g~$%s~w~ for ~b~%s~w~.",
	you_paid_basket = "You paid ~g~$%s~w~ for your basket.",
	you_sell_basket = "You received ~g~$%s~w~ for selling ~b~x%s~w~ item(s).",

	you_repaired_your_vehicle = "~g~You repaired your vehicle.",
	repairing_your_vehicle = "Repairing your vehicle",
	wheels_are_fine = "~r~The vehicle wheels are already fine.",
	changing_wheel = "Changing the wheel",
	you_repaired_the_wheels = "~g~You repaired the vehicle's wheels.",

	front_post_ls = "Front post Los Santos",
	front_post_ls_2 = "Front post Los Santos 2",
	front_post_bc = "Front post Blaine County",
	front_post_bc_2 = "Front post Blaine County 2",
	main_post_ls = "Safe City Los Santos",
	main_post_bc = "Safe City Blaine County",
	random_zone = "Random zone (landing)",

	this_item_is_equipped = "~r~This item is equipped, remove it from your shortcuts.",
	only_in_safezone = "~r~You cannot do that outside a safe-zone.",
	-- Commerce
	feature_gold_only = "This feature is only for ~y~gold members~w~.",
	feature_diamond_only = "This feature is only for ~b~diamond members~w~.",
	you_turned_into = "You turned into a ~g~%s~w~.",
	wait_between_transformation = "~r~Please wait a moment before using the Morph Mode again.",
	wait_between = "~r~Please wait a moment before doing that again.",
	available_morphs = "Available morphs",
	animal_models = "Animal models",
	zombie_models = "Zombie models",
	success_update_name = "You changed your character's name to ~b~%s~w~.",
	success_reset_stats = "~g~You successfuly reset your stats. (Leaderboards will be updated later)",

	-- animals
	boar = "Boar",
	cat = "Cat",
	chop = "Rottweiler (Chop)",
	rottweiler = "Rottweiler",
	cow = "Cow",
	coyote = "Coyote",
	deer = "Deer",
	hen = "Hen",
	husky = "Husky",
	mtlion = "Lion",
	pig = "Pig",
	poodle = "Poodle",
	pug = "Pug",
	rabbit = "Rabbit",
	rat = "Rat",
	retriever = "Retriever",
	shepherd = "Shepherd",
	westy = "Westy",

	player_id = "ID of the player",
	bounty = "Bounty",
	reason = "Reason",
	id_player_not_found = "~r~No player is binded to this id.",

	ammo_dealer = "Ammo dealer",
	misc_dealer = "Equipment shop",
	veh_dealer = "Vehicle shop",
	custom_dealer = "LS Custom",
	gun_dealer = "Gun shop",

	bounty_created = "You paid ~g~$%s~w~ to create a bounty contract on ~b~%s~w~.",
	contract_success = "The bounty you created on ~r~%s~w~ has been sent to ~b~%s~w~.",
	a_contract_on_your_head = "~r~You had a bounty on your head. Your killer received the bounty.",
	reward_for_contract = "Bounty Hunter! You got rewarded ~g~$%s~w~ for killing ~b~%s~w~.",

	hey_can_help_you = "Hey, how can I help you?",
	i_want_to_buy_items = "I want to buy items",
	i_want_to_sell_items = "I want to sell items",

	press_context_or_jump_to_get_up = "Press ~INPUT_CONTEXT~ or ~INPUT_JUMP~ to ~b~get up~w~.",
	server_restart_warning = "The server is going to restart..",
	auto_restart_in = "Automatic restart in %s seconds.",

	not_allowed_create_character = "You are not allowed to create a new character.",
	character_not_yours = "This character is not yours.",
	character_does_not_exist = "This character does not exist or does not longer exist.",
	loading_character = "Loading your character...",

	playtime_is = "~b~Your playtime on Extinction:\n~w~%s",
	dont_spam = "^1Do not spam!",

	babygod_warning = "~b~You left the safe-zone, you are invincible for some time find a safe place!",

	-- LS Custom
	modifications_classiques = "Classic modifications",
	modifications_custom = "Special modifications",
	modifications_benny = "Benny's modifications",
	paint = "paint",
	custom_your_car = "Custom your car",
	wheels_modifications = "Wheels modifications",
	performances = "Performances",
	neons = "Neons",
	extra = "Extra",
	klaxon = "Horn",
	teinte_fenetre = "Windows tint",
	phares_xenons = "Xenon headlights",
	modele_plaque = "Plate model",
	livery = "Livery",
	headlight_color = "Headlights color",
	wheel_type = "Wheel type",
	primary_wheel_type = "Primary wheel type",
	back_wheel_type = "Back wheel type",
	wheel_color = "Wheel color",
	tire_smoke = "Tire smoke",
	custom_color = "Custom color",
	custom_wheel = "Custom wheel",
	custom_back_wheel = "Custom back wheel",
	suspension = "Suspension",
	transmission = "Transmission",
	moteur = "Engine",
	frein = "Brake",
	turbo = "Turbo",
	primary_color = "Primary color",
	secondary_color = "Secondary color",
	interior_color = "Interior color",
	dashboard_color = "Dashboard color",
	color_effect = "Color effect",
	left_neon = "Left neon",
	right_neon = "Right neon",
	front_neon = "Front neon",
	back_neon = "Back neon",

	aileron = "Spoiler",
	pc_front = "Front bumper",
	pc_back = "Rear bumper",
	carroserie = "Side skirt",
	exhaust = "Exhaust",
	cadre = "Frame",
	calandre = "Grille",
	capot = "Hood",
	gb_left = "Left fender",
	gb_right = "Right fender",
	roof = "Roof",
	plate_support = "Plate holders",
	front_plate = "Front plate",
	interior_style = "Interior style",
	figurine = "Figurine",
	motif_dashboard = "Dashboard style",
	cadran = "Dial design",
	haut_parleur_portes = "Speaker doors",
	motif_sieges = "Seat style",
	volant = "Steering wheel",
	levier = "Shifter leavers",
	logo_custom = "Logo",
	ice = "ICE",
	haut_parleur_coffre = "Speaker back doors",
	hydrolique = "Hydraulics",
	moteur = "Engine",
	filtres_air = "Air filter",
	entretoises = "Spacers",
	arc_couverture = "Arch",
	antenne = "Antenna",
	motif_exterieur = "Exterior style",
	reservoir = "Tank",
	window = "Window",
	style = "Style",
	default = "Default",
	type = "Type",
	normal = "Normal",
	black = "Black",
	black_smoke = "Black smoke",
	simple_smoke = "Simple smoke",
	stock = "Stock",
	limo = "Limousine",
	sa_black = "San Andreas black",
	sa_blue = "San Andreas blue",
	sa_white = "San Andreas white",
	simple_white = "Simple white",
	ny_white = "North Yankton white",
	race = "Race",
	sport = "Sport",
	stock = "Stock",
	street = "Street",
	discount = "Discount",
	select_your_car = "Select your car",
	select_car_custom = "Select the vehicle you want to customize. The number between arrows is the item key.",
	loading_vehicle = "Creating vehicle",
	invalid_vehicle = "~r~Invalid vehicle entity.",
	invalid_vehicle_please_spawn = "~r~Invalid vehicle item. Please spawn it one time before trying to do anything.",
	free_take_and_validate = "Everything is free. Take what you want and confirm!",
	car_custom_saved = "~g~You car modifications have been saved.",

	-- Character creation
	character_creation = "Character creation",
	confirm = "confirm",
	start_playing = "Start playing",
	appearance = "appearance",
	character_list = "character list",
	face_features = "face features",
	parents = "parents",
	parent = "parent",
	mix = "mix",
	skin = "skin",
	desc_mix = "Select if the shape of your face is more influenced by your father / mother.",
	desc_skin = "Select if your skin is more influenced by your father / mother.",
	identity = "identity",
	player_name = "player name",
	new_character = "new character",
	warning_headblend = "~r~You have not selected your character's parents.",
	warning_overlays = "~r~You have not selected hairs, eyebrows or beard.",
	warning_identity = "~r~Warning.~n~~w~You forgot to fill the identity tab.",

	-- kits
	kit_does_not_exist = "~r~This kit does not exist.",
	kit_needs_rank = "You do not have the ~r~%s~w~ rank.",
	wait_before_using_kit = "Please wait ~r~%s~w~ before using this kit.",
	received_kit = "You received your kit ~b~%s~w~.",
	no_kit = "You do not have any kit.",

	unable_to_find_booster = "Unable to find a booster with this id.",
	wait_already_player_boost = "Please wait a moment before using this booster. There is already one player booster active.",
	wait_already_crew_boost = "Please wait a moment before using this booster. There is already one crew booster active.",
	wait_already_server_boost = "Please wait a moment before using this booster. There is already one server booster active.",
	booster_activated = "Booster activated for ~g~%s minutes~w~! ~b~XP +%s%%",
	server_booster_activated = "~b~%s~w~ activated a server booster for ~g~%s minutes~z~! ~b~XP +%s%%",
	crew_booster_activated = "~b~%s~w~ activated a crew booster for ~g~%s minutes~z~! ~b~XP +%s%%",
	no_booster = "You do not have any booster.",

	rank_expired = "~r~Your supporter role expired.",
	supporter_role = "~g~Supporter role:~w~ %s",
	no_rank_warning = "You do not have any supporter role.\n~r~If you've purchased something link your fivem account.",
	no_fivem_id = "Your FiveM is not linked with the game.\n~r~Verify that you have a FiveM account and that it is linked to the game.",
	no_queue_warning = "You do not have any package in queue.\n~r~Wait a moment or try /getRank if you're looking for your rank.",
	package_sync_success = "~g~Your packages have correctly been synced, enjoy!\n~w~Useful commands: /getRank, /booster",

	level_required = "You need to be level %s.",
	rank_required = "You need to have the %s rank.",
	level_required_2 = "~r~You need to be level %s.",

	updated_deathmessage = "~g~You updated your death message.",
	updated_deatheffect = "~g~You updated your kill effect.",
	use = "Use",
	test = "Test",

	-- zombie
	you_bitten = "~r~You have been bitten.",
	infection_rate = "Infection rate: ~r~%s%%",

	-- ranks
	thug = "Thug",
	hustler = "Hustler",
	soldier = "Soldier",
	trigger = "Trigger",
	enforcer = "Enforcer",
	facilitator = "Facilitator",
	public_enemy = "Public Enemy",
	shot_caller = "Shot Caller",
	street_boss = "Street Boss",
	kingpin = "Kingpin",
	-- Tattoo
	tattoo = "tattoo",
	tattoos = "tattoos",
	torso = "torso",
	head = "head",
	left_arm = "left arm",
	right_arm = "right arm",
	left_leg = "left leg",
	right_leg = "right leg",
	unknown = "unknown",
	other = "other",
	remove_tattoo = "Remove all tattoos",
	-- Hairdress
	haircuts = "Haircuts",
	makeup = "Make up",
	face = "Face",
	eyebrows = "Eyebrows",
	facial_hair = "Facial hair",
	body_hair = "Body hair",
	barber_shop = "Barber shop",
	face_makeup = "Face make up",
	lipstick = "Lipstick",
	face_foundation = "Face foundation",
	skin_blemishes = "Skin blemishes",
	skin_ageing = "Skin ageing",
	moles_freckles = "Moles & Freckles",
	sun_damage = "Skin damage",
	skin_complexion = "Skin complexion",
	body_blemishes = "Body blemishes",
	body_blemishes_2 = "Body blemishes 2",
	opacity = "Alpha",
	variations = "Variations",
	filter = "Filter",
	eyes_color = "Eyes color",
	-- Mask
	masks = "Masks",
	-- Items
	money = "Money",
	-- Ammo
	["9mm"] = "9mm",
	["300_mag"] = ".300 Magnum",
	["7_62mm"] = "7.62mm",
	["calibre_12"] = "Calibre 12",
	["45_acp"] = ".45 ACP",
	["5_56mm"] = "5.56mm",
	rocket = "Rocket",
	flare = "Flare",
	grenade = "Grenade Ammo",
	-- Food
	["fish_1"] = "Largemouth Bass",
	["fish_2"] = "Rainbow Trout",
	["fish_3"] = "Kokanee",
	["fish_4"] = "Arctic Grayling",
	["fish_5"] = "Rock Bass",
	["fish_6"] = "Smallmouth Bass",
	["fish_7"] = "Paddlefish",
	["fish_8"] = "Bull Trout",
	["fish_9"] = "Lake Trout",
	["fish_10"] = "Chinook",
	["fish_11"] = "Pallid Sturgeon",
	["fish_12"] = "Salmon",

	misc_meat = "Raw meat",
	rabbit_meat = "Raw rabbit",
	lion_meat = "Raw lion",
	rare_plume = "Rare feather",
	dog_meat = "Raw dog",
	cat_meat = "Raw cat",
	rare_fish = "Rare fish",

	mask = "Mask",
	malette = "Suitcase",
	malette_metal = "Metal suitcase",
	ciseaux = "Scissors",
	clean_kit = "Clean kit",
	fishing_rod = "Fishing rod",
	meuble = "Furniture",
	tissu = "Cloth",
	accessory = "Accessory",
	radio = "Radio",
	recyclor = "Recycler",
	medkit = "Medkit",
	kevlar = "Kevlar",
	gps = "GPS",
	repair_tool = "Repair kit",
	jvn = "JVN",
	engine_veh = "Engine",
	bag = "Sac",
	wheel_veh = "Wheel",
	vetement = "Top",
	bloc_note = "Notepad",
	paint_spray = "Paint spray",
	spike = "Spike strip",
	paracetamol = "Paracetamol",
	bandage = "Bandage",
	gaz_mask = "Gaz mask",
	filter = "Filter",
	tattoo_tool = "Tattoo tool",
	drug_med = "Drug",
	drug_antizin = "Antizin shot",
	drug_stamina = "Stamina shot",
	drug_berserker = "Health shot",

	pickup_spikestrip = "pickup the spike strip",
	you_dropped_spikestrip = "You dropped a ~g~spike strip~w~.",
	you_pickup_spikestrip = "You picked up a ~g~spike strip~w~.",

	you_have_been_killed_by = "You have been killed by ~r~%s",
	kill_notif = "~m~Killed",
	you_killed = "You killed ~r~%s~w~",
	already_used_reset_only = "~r~You already have reset your character.\n~w~Only %s~w~ members can redo their character more than one time.",
	already_used_reset_only2 = "~r~You already did that.\n~w~Only %s~w~ members can do that more than one time.",

	hud_options = "HUD options",
	advanced_hud = "Display advanced HUD",
	players = "Players",
	health = "Health",
	player_menu = "Player menu",

	you_are_now_zombie = "~r~You are now a zombie.",

	my_weapons = "my weapons",
	customize_weapons = "customize my weapon",
	weapon_skin = "Tint",

	-- camo
	skin_classic = "Default",
	skin_green = "Green",
	skin_yellow = "Yellow",
	skin_pink = "Pink",
	skin_gold = "Gold",
	skin_blue = "Blue",
	skin_orange = "Orange",

	weapon_katana = "Katana",
	weapon_sledgehammer = "Sledge Hammer",

	-- new
	airdrop_coming = "~r~An airdrop is coming check your map.",
	killed_by_cheater = "~r~You have been killed by a cheater.\n~w~We banned him and your death has been canceled.",

	corrupted_vehicle = "~r~This vehicle is corrupted and has been duplicated in the past, it has been removed from your inventory. Sorry if you got scammed.",

	-- Discord
	join_discord_for_kit = "Join our discord to get a free discord kit!\n~g~discord.gg/gtalife",
	discord_account_not_linked = "~r~You need to link your discord account with FiveM.",
	discord_account_not_guild = "~r~You are not in our discord server.\n~w~Join discord.gg/gtalife",

	already_done_recently = "~r~Try again later, you already did it recently.",
	update_country = "Update country",

	prestige_info = "~b~You reached the maximum level.\n~w~Type /prestige to get info on the prestige leveling system.",
	prestige_not_max_level = "~r~You have not reached the maximum level.",
	max_prestige_reached = "~r~You reached the last prestige.",
	prestige_info_cmd = [[^3Prestige leveling system^7
You are currently prestige ^4%s^7 and level ^5%s^7.

If you reach the maximum level (%s) you can choose to get a prestige and restart your XP progress to return level 0.
Getting a new prestige gives you a special badge and new perks like better loot, new items, more money or a higher inventory maximum weight.
^2If you want to get a prestige and RETURN level 0 type ^1/setprestige^2
]],
	new_prestige = "You unlocked a new prestige!\n~g~You have now %s prestige(s)",
	cant_store_event_veh = "~r~You cant store special vehicles.",

	you_are_no_longer_in_combat = "🛡️ ~b~You are no longer in combat.",
	you_are_in_combat_mode = "🛡️ ~b~You are in combat mode.\nIf you disconnect you will die.",
	you_disconnected_in_combat = "💀 You disconnected in combat mode, you died.",

	not_enough_prestige_points = "~r~You do not have enough prestige points.",
	you_reached_max_prestige_stats_rank = "~r~You reached the maximum rank for this prestige upgrade.",
	new_prestige_stats_upgrade = "You upgraded your ~b~%s~w~\n~g~%s/%s",

	legendary_vehicle_pop = "~r~A legendary vehicle appeared on the map.",

	-- poll one
	poll1_q1 = "What kind of game server would you like to see?",

	poll1_q1_a1 = "Battle Royale",
	poll1_q1_a2 = "Private missions solo or with 1-4 friends (Payday / Heist / Hitman like)",
	poll1_q1_a3 = "Race / Freeroam",
	poll1_q1_a4 = "Murder / Horror game",

	-- poll two
	poll2_q1 = "Are you an English speaker and would you be interested in a GLife RP Server?",

	poll2_q1_a1 = "No",
	poll2_q1_a2 = "Yes",

	combat_mode_container_disabled = "~r~You are in combat.\n~w~You cannot store items.",
	gcoins_wallet_updated = "~g~You GCoins wallet has been updated.\n~w~+%s GCoins",
	not_enough_gcoins = "~r~You do not have enough GCoins.",
	gcoins_something_went_wrong = "~r~Something went wrong.",
	you_bought_with_gcoins = "You bought ~g~%s~w~ for ~b~%s GCoins~w~.",

	equiping_armor = "Equiping armor",

	toggle_mute_player = "Toggle Mute",
	you_muted_this_player = "~b~You muted this player.",
	you_unmuted_this_player = "~b~You unmuted this player.",

	already_purchased = "~r~You have already purchased this item.",
	weapon_camo_preview = "You are previsualizing the weapon base model, some attachments are missing.\n~INPUT_CELLPHONE_CANCEL~ to exit the preview.",

	already_using_a_seringue_booster = "~r~You have already taken a shot of that.",
	seringue_effect_done = "~b~The seryngue booster effect is gone.",
	you_injected_a_seringue_boost = "You have injected a ~b~seryngue shot~w~ in your blood.",

	put_item_permission = "Put items",
	take_item_permission = "Take items",
	put_money_permission = "Put money",
	take_money_permission = "Take money",

	preferred_badge_set = "You have set your ~g~preferred badge~w~.",
	preferred_badge_not_set = "~r~Unable to set your preferred badge.",

	marketplace_received_money_sales = "You received ~g~$%s~w~ from ~b~%s~w~ sale(s).",
	marketplace_no_sales = "~r~You have not sold anything.",
	marketplace_you_paid_for = "You paid ~g~$%s~w~ for ~b~%s~w~.",

	deleted_sell_offer = "~b~You deleted your sell offer.",
	deleted_buy_offer = "~b~You deleted your sell offer.",
	deleted_sell_offers = "~b~You deleted your sell offers.",
	deleted_buy_offers = "~b~You deleted your sell offers.",

	marketplace_offer_does_not_exist = "~r~This offer does not exist.",

	marketplace_create_sell_offer = "You created a sell offer for ~b~%sx %s ~w~for ~g~$%s~w~ per unit.",
	marketplace_create_buy_offer = "You created a buy offer for ~b~%sx %s ~w~for ~g~$%s~w~ per unit.",

	i_want_to_enter_in_my_property = "I want to enter in my property.",
	i_want_to_exit_private_world = "I want to return in the public world.",
	public_world = "Public World",
	private_world = "Private World",

	dailymission_playerkill = "Killed players",
	dailymission_zombiekill = "Killed zombies",
	dailymission_playerheadshotkill = "Player headshots",
	dailymission_zombieheadshotkill = "Zombie headshots",
	dailymission_zombiesurvivorkill = "Killed survivor zombies",
	dailymission_zombiearmoredkill = "Killed armored zombies",
	dailymission_zombiehazmatkill = "Killed  hazmat zombies",
	dailymission_zoombieboomerkill = "Killed boomer zombies",
	dailymission_sellitems = "Items sold",
	dailymission_buyitems = "Items bought",
	dailymission_lootitems = "Items looted",
	dailymission_createselloffer = "Sell offer created",
	dailymission_killtopkillcrew = "Killed players from crew",
	dailymission_killtopkillplayers = "Killed players",
	dailymission_getintolegendaryvehicle = "Vehicles",
	dailymission_killzombiewithweapon = "Zombies killed with weapon",
	dailymission_killplayerwithweapon = "Players killed with weapon",
	dailymission_darkzonesurvivingtime = "Darkzone surviving time",
	dailymission_redzoneplayerkill = "Player kills in redzone",
	dailymission_redzonezombiekill = "Zombie kills in redzone",
	dailymission_darkzoneplayerkill = "Player kills in darkzone",
	dailymission_darkzonezombiekill = "Zombie kills in darkzone",
	dailymission_useitem = "Used items",
	dailymission_playtime = "Play time",
	dailymission_xpharvest = "Harvested XO",
	dailymission_sellofferpurchased = "Sell offers purchased",
	dailymission_sellofferpurchasedbyme = "Sell offers purchased",
	dailymission_tradeitems = "Items traded",
	dailymission_createbuyoffer = "Buy offers created",

	dailymission_completed = "~g~You completed a daily mission!\n~b~+%s XP\n~y~+1 Dungeon Key",

	character_creation_mix_desc = "Select whether if the shape of your face is more influenced by the shape of your father/mother.",
	character_creation_skin_desc = "Select whether if your skin is more influenced by the skin of your father/mother.",

	ff_1 = "Nose width",
	ff_2 = "Nose height",
	ff_3 = "Nose length",
	ff_4 = "Nose drooping",
	ff_5 = "Nose peak drop",
	ff_6 = "Nose twist",
	ff_7 = "Eyebrow height",
	ff_8 = "Eyebrow depth",
	ff_9 = "Cheekbone height",
	ff_10 = "Cheekbone width",
	ff_11 = "Cheek width",
	ff_12 = "Eyes opening",
	ff_13 = "Lip thickness",
	ff_14 = "Jaw width",
	ff_15 = "Jaw back length",
	ff_16 = "Chin lowering",
	ff_17 = "Chin bone length",
	ff_18 = "Chin Width",
	ff_19 = "Chin hole",
	ff_20 = "Neck thickness",

	airdrop_taken_by = "^1%s has taken %s from the airdrop.",

	available_death_effects = "Available death effects",
	available_modes = "Available modes",

	you_changed_your_ped_model = "~g~You successfully changed your ped model.",
	i_want_to_change_my_ped = "I want to change my ped",

	poll4_q1 = "What do you expect from the next season?",
	poll4_q1_a4 = "New world event like airdrops, zone capture etc.",
	poll4_q1_a1 = "More PvE content like dungeons",
	poll4_q1_a2 = "More games like casino / races",
	poll4_q1_a3 = "PvP content",

	poll4_q2 = "Would you like to have more ranked/tournament modes?",
	poll4_q2_a1 = "Yes",
	poll4_q2_a2 = "No",

	poll4_q3 = "Would you like to have snipers in shops?",
	poll4_q3_a1 = "Yes",
	poll4_q3_a2 = "No",

	poll4_q4 = "What do you enjoy the most on Extinction?",
	poll4_q4_a1 = "PvP",
	poll4_q4_a2 = "PvE",
	poll4_q4_a3 = "Trading",

	dungeon_no_more_time = "~r~You have been too slow. The dungeon closed.",
	dungeon_participant_left = "~r~%s left the dungeon.",
	started_dungeon_party = "~b~You created a dungeon room.",
	dungeon_party_no_longer_exists = "~r~This dungeon party no longer exists.",
	dungeon_invitation_expired = "~r~The dungeon party invitation expired.",
	dungeon_join_party = "~g~You joined the dungeon party.",
	dungeon_too_late_for_invitation = "~r~You were too late. You cannot join the dungeon at this state of the game.",
	dungeon_already_invited_this_player = "~r~You have already invited this player.",
	dungeon_invitation_received = "You received an invitation from ~b~%s~w~ to join its dungeon party.\nType ~g~/dungeon join %s~w~ to join the party.",
	dungeon_invitation_sent = "You invited ~g~%s~w~ to your dungeon party.",

	i_want_to_enter_a_dungeon = "I want to enter in a dungeon",
	dungeon_list = "Dungeon list",
	dungeon = "Dungeon",
	dungeons = "Dungeons",
	you_need_x_keys = "You need ~y~%s dungeon keys~w~ to enter the dungeon.",
	time_remaining = "Time remaining",
	you_killed_the_dungeon_boss = "~r~You killed the dungeon boss.",
	dungeon_kill_final_boss = "You are in the final room. Kill the boss to get the treasure.",

	dungeon_died_remaining = "You died, you have ~r~%s~w~ remaining lives.",
	dungeon_died = "~r~You no longer have any remaining lives. You died.",
	dungeon_already_in_party = "~r~You already are in a dungeon party.\n~w~Type /dungeon quit to leave.",
	dungeon_does_not_exist = "~r~This dungeon does not exist.",
	dungeon_ready = "~g~%s~w~ is ready.",
	dungeon_not_ready = "~r~%s~w~ is not ready.",

	not_released_yet = "This is not released yet.",
	feature_only_supporters = "~b~This feature is in beta-testing and only Diamond/Gold supporters can use it now.",
	feature_not_enabled = "~b~This feature is not enabled yet.\n~w~Please wait for the activation later today.",
	dungeon_charid_required = "~r~Please include your friend character id (top-right of its screen) after the command.\nExample: /dungeon invite 1234",

	poll5_q1 = "Would you accept that our anticheat captures cheaters's entire screen if they're suspected of wallhack or aimbots? (It may shows a part of your desktop if the game is in windowed mode but these captures will not be saved and only used by reliable moderators)",
	poll5_q1_a1 = "skip - ignore",
	poll5_q1_a2 = "Yes, I agree to this new method",
	poll5_q1_a3 = "No, I disagree",
	
	-- S4
	redzone_kill_leader_killed = "The ~r~redzone kill leader~w~ was killed.",
	redzone_kill_leader_fled = "The ~r~redzone kill leader~w~ fled.",
	redzone_get_back_kill_leader_before_x = "You are ~r~outside the redzone~w~ get back or you will loose your title in ~r~%s seconds~w~.",
	redzone_kill_leader_new_xp_step = "~r~Redzone XP Multiplier\n~b~+%s%~w~ bonus",
	remaining_lives = "Remaining lives",

	name_tag = "Crew tag",
	redzone_changed = "~r~Red zones moved to a new position.",

	-- Squad
	squad_not_leader = "~r~You are not the leader of your squad.",
	squad_kicked_by_x = "You have been ~r~kicked~w~ from your squad by ~r~%s~w~.",
	squad_you_kicked_x = "You kicked ~r~%s~w~ from your squad.",
	squad_invited_x = "You invited ~r~%s~w~ to your squad.",
	squad_invited_you_x = "~r~%s~w~ invited you to its squad.\nType ~r~/squad join %s~w~ to join the squad.",
	squad_you_set_new_leader = "You set ~r~%s~w~ as the new ~r~leader~w~ of the squad.",
	squad_you_are_new_leader = "~g~You are the new leader of the squad.",
	squad_not_invited = "~r~You have not been invited to the squad.",
	squad_joined_squad = "~g~You joined the squad.",
	squad_left = "~r~You left the squad.",
	squad_already_in = "~r~You are already in a squad.",
	squad_created_x = "You created a new squad. ~b~(%s)",
	squad_x_joined = "~b~%s~w~ joined the squad.",
	squad_leader_deleted = "~r~The leader deleted the squad.",
	write_yes_to_confirm = "Type yes to confirm",
	invite_a_player_write_char_id = "Invite a player. Type its character id",

	-- Help stuff
	press_enter_beginner_guide = "Press ~INPUT_ENTER~ to start the beginner guide.",
	welcome_glife = "Welcome on ~r~GLife Extinction~w~!",
	you_are_playing_server_x_with_x = "You are playing on server ~b~#%s~w~ with ~b~%s players~w~.",
	start_beginner_guide = "Start the beginner guide",
	play_now = "~g~Play now!",
	interact_npc_fast_travel = "Interact with the fast travel NPC",

	-- Tutorial
	tutorial_beginner_end_msg = "~r~Thank you for your time!\n~w~Have fun playing Extinction, if you have any question use the chat or find us on discord.",
	tutorial_beginner_start_msg = "~r~Welcome on GLife Extinction!\n~w~This short guide aims to explain how to begin on this gamemode.",
	tutorial_beginner_camera_01 = "~r~~BLIP_557~ ~r~Main safezone\n~w~This is a safe area where you can shop and store items, but also personalize your equipment and trade with other players.",
	tutorial_beginner_camera_02 = "~BLIP_568~ ~r~Storage chests\n~w~Here you can access your private storage and store your precious items.",
	tutorial_beginner_camera_03 = "~BLIP_567~~BLIP_556~~BLIP_658~ ~r~NPC Shops\n~w~You can buy and sell your items in many shops like the weapon, vehicle or equipment dealer.",
	tutorial_beginner_camera_04 = "~BLIP_84~ ~r~Public bounties\n~w~If you manage to find and kill the target, you will get the associated reward.",
	tutorial_beginner_camera_05 = "~BLIP_176~ ~r~Hostile world\n~w~You will meet zombies and hostile players. They will all want to get you killed, but they are the best way to get XP and great loot.",
	tutorial_beginner_camera_06 = "~BLIP_303~ ~r~World redzones\n~w~There you can find better loot and earn more experiences from your kills.",
	tutorial_beginner_camera_07 = "~BLIP_648~ ~r~Darkzone Island\n~w~Here you cannot save items nor flee easily, but it is the best place to find high-tier loot like MK2 weapons or snipers.",
	tutorial_beginner_camera_08 = "~BLIP_575~ ~r~Loot and exploration opportunities\n~w~You can fight for airdrop crates but also explore and beat dungeon boss.",
	tutorial_beginner_training_01 = "~g~You joined the training room.\n~w~Jump with ~INPUT_JUMP~ when you are ready.",
	tutorial_beginner_training_02 = "~g~Let's use the inventory.\n~w~Press ~%s~ to open your inventory.",
	tutorial_beginner_training_03 = "~g~Equip a weapon.\n~w~Open the inventory and drag a weapon in the shortcut bar.\nPress the corresponding key ~b~1/2/3/4/5/6/7~w~.\n~r~If you do not have any weapon use ~b~/kit newbie.",
	tutorial_beginner_training_04 = "~g~Fill your weapon ammo.\n~w~Equip a gun and put a box of ammo in your shortcut bar. Then press the shortcut key.",
	tutorial_beginner_training_05 = "~g~Finally vehicles.\n~w~You can spawn vehicles just like you equip a weapon. Once spawned, you can store it with ~%s~ while driving it. Press the key to confirm.",
	tutorial_beginner_training_success_01 = "~g~Great job, we can begin now!",
	tutorial_beginner_training_success_02 = "~g~Nice, you got it.\n~w~It is the same process to use all items.",
	tutorial_beginner_training_success_03 = "~g~Nice, you got it.\n~w~It is the same process to use all items.",
	tutorial_beginner_training_success_04 = "~g~Nice, you got it.\n~w~We are done now.",

	-- Darkzone stuff
	contaminated = "contaminated",
	darkzone_boat_leaving_in = "Boat leaving in",
	darkzone_exit = "Exit spot",
	purificator = "Purificator",
	you_entered_the_darkzone = "~r~You entered the darkzone.",
	you_left_the_darkzone = "~r~You left the darkzone.",
	cannot_enter_darkzone_time = "~r~The darkzone is not open yet, wait.",
	darkzone_is_full = "~r~The darkzone is full, please wait.",
	darkzone_exit_allowed = "~r~Boats arrived to exit the darkzone, run if you want to escape.",
	darkzone_close_time = "Closing in",
	darkzone_surviving_since = "Surviving since",
	darkzone_points = "Points",
	darkzone_points_x = "~r~Darkzone points: ~w~+%s",
	darkzone_landing_in_x = "Landing available in ~b~%s minutes~w~.\nIf enough players.",
	darkzone_open_press_context = "The darkzone is open~w~.\nPress ~INPUT_CONTEXT~ to land ~m~on the darkzone~w~.",
	darkzone_outside_warning = "~r~You are outside the darkzone, come back or die.",
	darkzone_close_warning = "~r~The darkzone is closing soon~w~.\nYou should not stay here too long.",
	darkzone_close_damage = "The darkzone closed, the entire area is now contaminated.",
	darkzone_not_enough_points_to_exit = "You need ~r~%sx points~w~ to exit the darkzone.",
	press_e_to_exit_the_darkzone = "Press ~INPUT_CONTEXT~ to exit the darkzone.\n~r~You need x%s darkzone points.",
	use_purificator = "use the purificator",
	darkzone_not_enough_points_to_start_purificator = "You need ~r~%sx points~w~ to start the purificator.",
	darkzone_not_enough_points_to_refill_purificator = "You need ~r~%sx points~w~ to refill the purificator.",
	darkzone_too_far_from_purificator = "~r~You are too far from the purificator.",
	darkzone_cant_remove_while_running_purificator = "~r~You cannot remove items while the purificator is running.",
	darkzone_purificator_running = "~r~You cannot put items while the purificator is running.",
	darkzone_purificator_running_refill = "~r~You cannot refill the machine while the purificator is running.",
	darkzone_put_x_in_purificator = "You put ~r~%s~w~ in the purificator.",
	darkzone_you_took_x_from_purificator = "You took ~r~%s~w~ from the purificator.",
	darkzone_purificator_does_not_need_refill = "You do not need to ~r~refill this purificator~w~.",
	darkzone_refilled_purificator_x = "You used ~r~x%s points~w~ to refill the purificator.",
	darkzone_open = "Darkzone landing are available.\n~r~Find a transporter in any safezone.",
	darkzone_item_clean = "This item is already clean.\n~r~You can only put contaminated items.",
	
	dungeon_cooldown_between = "Please wait ~r~%s minutes~w~ before starting a dungeon again.",
	set_as_default = "Set as default custom for vehicle model",
	car_custom_presets_saved = "Your customization presets for ~g~%s~w~ have been saved.",
	marketplace_you_received_x_x = "You received ~b~%sx ~g~%s~w~.",

	above_level_x_no_longer_possible_loot_safe = "Player above rank %s cannot loot zombies in safezones.",
	preferred_component_desc = "This set will be the default set of all %s weapon you hold.",
	set_as_preferred_component_class = "Set as preferred component set",
	weapon_presets_updated = "You have set the default component presets for your ~g~%s~w~.",

	-- New survey
	poll6_q1 = "Would you like the crew member limit to be set to 25 members? (more competition, smaller groups)",
	poll6_q2 = "Is your main server fine for your ping? (Is your average ping ok?)",
	poll6_q3 = "Are you playing in private worlds?",
	poll6_q4 = "Should headshots be enabled for season 4?",
	
	casino_dungeon_desc = "⚠️ ~r~You may need flashlight on your weapon to see well here.",
	dungeon_destroy_wall_obj = "Destroy the wall blocking your path.",
	dungeon_use_key_obj = "Use the key to open the door.",
	dungeon_kill_zombies_obj = "Kill all zombies.",
	dungeon_kill_zombies_obj_x = "~b~Kill all zombies.~w~\n%s/%s of players have killed their zombies.",
	dungeon_use_key_to_open_door = "Use the key to open the door.",
	dungeon_find_key_obj = "Find a key to open the door in the room.",
	take_key = "take the key",
	open_the_door = "open the door",
	dungeon_quit_notif = "Type ~g~/dungeon quit~w~ to leave the dungeon.",
	dungeon_generator_obj = "Find the generator and get the power back.",
	dungeon_press_generator = "Press ~INPUT_CONTEXT~ to toggle the generator.",
	power_generator = "Power generator",
	dungeon_find_c4_obj = "There are blocks of C4 hidden somewhere, find them.",
	dungeon_use_c4_obj = "Use your C4 to blow up the vault door.",
	dungeon_party_help = "Type ~b~\"/dungeon\"~w~ to manage the dungeon party.",
	press_x_to = "Press %s to %s",

	quest_clean_zone = "Clean the zone: %s",
	quest_clean_zone_desc = "Reach %s and clean the area of zombies.",

	loot_crate_light = "Light Loot Crate",
	loot_crate_medium = "Medium Loot Crate",
	loot_crate_high = "High Loot Crate",
	
	dailymission_killzombieinzoneid = "Zombies killed in the zone",
	dailymission_dungeonbosskilled = "Dungeon boss killed",

	quest_too_far_npc = "~r~You are too far from the quest NPC.",
	quest_already_started_quest = "~r~You have already started this quest.",
	quest_redo_in_x = "~r~You have already done this quest.\n~w~You will be able to redo this quest in ~b~%s",
	quest_max_quests_reached = "~r~You can only accept %s quests.",
	quest_new_accepted = "~g~You accepted a new quest.",
	quest_gave_up = "~r~You gave up this quest.",
	quest_not_completed = "~r~You need to complete all objectives of the quest.",
	quest_already_completed = "~r~You already have completed this quest.",
	quest_all_completed = "~g~You successfully completed all objectives.",
	dungeon_key = "Dungeon key",
	darkzone_cannot_enter_min_levels = "You must be level ~b~%s~w~ to enter the darkzone.",
	darkzone_you_survived_x = "You survived ~r~%s minute(s)~w~ in the darkzone.",
	questmenu_command = "Open the quest menu",
	squadmenu_command = "Open the squad menu",
	airdrop_coming_darkzone = "~r~An airdrop is coming in the darkzone check your map.",
	darkzone_full_crew = "There is already ~r~%s members~w~ of your crew in the darkzone, wait for someone to leave.",

	crew_join_cooldown_x = "You need to wait ~r~%s~w~ before joining this crew.",
	darkzone_not_enough_players_darkzone = "The darkzone will not open.\n~r~Not enough players.",

	dungeon_loot_boss_box = "~g~A chest appeared in the center of the room.",
	drug_antizin_bar = "Antizin effect",
	drug_stamina_bar = "Stamina effect",
	drug_berserker_bar = "Health effect",
}

AddLanguage("en", my_language)
