local my_language = {
    give_vehicle = "Du hast ~b~%s~w~ zu deinem Inventar hinzugefügt.",
    store_vehicle_command = "Lagert das Fahrzeug ein, das du fährst.",
    no_entity_vehicle = "~r~Das Fahrzeug ist zu weit entfernt oder existiert nicht.",
    no_entity_vehicle_id = "~r~Das Fahrzeug besitzt keine ID, daher kannst du es nicht einlagern.",
    store_vehicle = "~b~Du hast dein Fahrzeug eingelagert.",
    teleported_former_position = "~g~Du wurdest zu deiner zuletzt gespeicherten Position teleportiert",
    not_enough_of = "~r~Du hast nicht genug %s.",
    max_storage_chest = "~r~Deine Storage-Box ist voll",
    cant_carry_more_items = "~r~Dein Inventar kann keine weiteren Items aufnehmen, da es voll ist.",
    put_item = "Du hast ~g~x%s~w~ %s~w~ weggelegt.",
    take_item = "Du hast ~g~x%s~w~ %s~w~ genommen.",
    delete_item = "Du hast ~r~x%s~w~ %s~w~ gelöscht.",
    you_equiped_item = "Du hast dein(e) ~g~%s~w~ ausgerüstet.",
    bind_weapon_command = "Taste für den Waffen-Slot %s",
    kevlar_broke = "~r~AHH!~n~~w~ Deine Weste wurde zerstört.",
    inventory_command = "Inventar öffnen/schließen",
    press_enter_to_join = "Drücke ~g~ENTER~w~ um zu spielen.",
    new_character = "Neuer Character",
    survivor = "Überlebender",
    right = "Rechts",
    left = "Links",
    male = "männlich",
    female = "weiblich",
    ped = "Ped",
    name = "Name",
    sex = "Geschlecht",
    title = "Title",
    select_this_character = "Diesen Character auswählen",
    no_entity_zombie = "Der Zombie ist zu weit entfertn oder existiert nicht.",
    you_found = "Du hast ~g~%sx %s~w~ gefunden.",
    you_found_nothing = "Du hast ~g~nichts~w~ gefunden.",
    press_e_to_loot = "Drücke ~b~[E]~w~ um zu looten.",
    full_for_item = "~r~Zu wenig Platz, um das Item einzulagern.",
    put_item_container = "Du hast ~g~x%s~w~ %s~w~ in deinen Container gelegt.",
    take_item_container = "Du hast ~g~x%s~w~ %s~w~ aus deinem Container genommen.",
    not_allowed_here = "~r~Du kannst das hier nicht.",
    cant_store_moving_veh = "~r~Du kannst dein Fahrzeug nicht einlagern, wenn es sich bewegt",
    use_repair_tool = "Benutzt das Repair-Kit.",
    please_get_closer = "~b~Bitte geh näher ran, kein Objekt in der Nähe.",
    you_cancel_action = "~r~Du hast die Aktion abgebrochen.",
    selected_target_message = "Ausgewähltes Ziel:~n~%s~n~~r~Drücke ~b~Y~r~ um abzubrechen, ~n~~r~Drücke ~g~X~r~ um weiterzumachen.",
    target_you = "~b~DU",
    target_screen = "~g~angezeigt",
    take_this_path = "diesen Weg zu geheng",
 
    -- hud
    default_hud = "Standardmäßiges HUD",
    cinema_hud = "Kino-HUD",
    no_hud = "Kein HUD",
 
    -- perms
    kick_member = "Mitglieder Kicken",
    invite_someone = "Spieler einladen",
    edit_member = "Mitglieder bearbeiten",
    edit_rank = "Ränge bearbeiten",
    create_rank = "Ränge erstellen",
    delete_rank = "Ränge löschen",
    edit_structure = "Crew-Informationen bearbeiten",
    edit_permissions = "Rechte bearbeiten",
    permission_level = "Rechtestufe",
    red_delete = "Löschen",
    rank = "Rang",
    red_kick = "Kicken",
    crew_name = "Crewname",
    slogan = "Motto",
    information = "Informationen",
    boss_rank = "Name des Anführerrangs",
    member_rank = "Name des Neulingrangs",
    member = "Mitglied",
 
    permissions_manager = "Rechteverwaltung",
    members_manager = "Mitgliederverwaltung",
    ranks_manager = "Rangverwaltung",
    ranks_list = "Liste der Ränge",
    members_list = "Mitgliederliste",
    create_a_rank = "Einen Rang erstellen",
    invite_someone = "Jemanden einladen",
    stats = "Statistiken",
    total_ranks = "Anzahl der Ränge",
    total_members = "Anzahl der Mitglieder",
    level = "Level",
    actions = "Aktionen",
    crew_manager = "Crewverwaltung",
    you_created_a_new_crew = "Du hast eine neue Crew erstellt: %s",
    you_deleted_your_crew = "Du hast deine Crew gelöscht",
    you_are_not_in_a_crew = "Du bist in keiner Crew",
    you_joined_the_crew = "Du bist einer neuen Crew beigetreten: '%s'",
    kick_failed = "Der Kick ist fehlgeschlagen, Grund: %s",
    already_in_crew = "Du bist bereits in einer Crew",
    no_invitation = "Du hast keine Einladung erhalten.",
    left_crew = "Du hast die Crew verlassen",
    permission_updated = "Die Rechte von <C>~g~%s</C>~w~ wurden aktualisiert.",
    incorrect_name = "~r~Das Namensformat ist nicht erlaubt",
    incorrect_rank_perm = "~r~Fehler\n~w~Der Rangname oder die Rechtestufe ist ungültig.",
    warn_rank_limit = "~r~Du hast das Ranglimit erreicht.",
    create_rank_success = "~g~Erfolgreich\n~w~Du hast einen den Rang <C>~b~%s</C>~w~ mit der Rechtestufe <C>~b~%s</C>~w~ erstellt.",
    crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~Du kannst Mitglieder mit einer höheren Rechtestufe als du nicht bearbeiten.",
    you_sent_an_invitation = "Du hast <C>~g~%s</C>~w~ eingeladen deiner Crew beizutreten.",
    you_received_an_invitation = "Du hast eine Creweinladung erhalten.\n~b~/%s um sie anzunehmen.",
    invitation_expired = "Die Einladung ist abgelaufen",
    crew_kick_success = "Du hast <C>~b~%s</C>~w~ aus deiner Crew gekickt.",
    first_rank_warning = "Der erste Rang ist der 'default' Rang.",
 
    you_updated_this = "Du hast %s zu ~g~<C>%s</C>~w~ geändert.",
    changes_saved_on = "Die Veränderungen an <C>~g~%s</C>~w~ wurden übernommen.",
    yes = "Ja",
    no = "Nein",
    none = "kein",
    character_id = "Character-ID",
    server_id = "Server-ID",
    report = "Melden",
    rename = "Umbenennen",
    trade_with = "Handeln",
 
    please_wait_x_before = "~r~Bitte warte %s Sekunden um das zu tun.",
 
    -- cloth
    take_outfit = "Outfit kaufen",
    wardrobe_options = "Kleiderschrank",
    wardrobe = "Kleiderschrank",
    manual_options = "Optionen",
    manual_mode = "manueller Modus",
    save_outfit = "Dieses outfit speichern",
    variation = "Variante",
    outfits = "Outfits",
    cloth_shop = "Kleidungsladen",
    ped_cloth_shop = "Kleidungsladen für Peds",
    manual_props = "Requisiten",
    manuel = "manuell",
    new_name = "Neuer Name",
    outfit_name = "Outfitname",
    variations_saved = "~g~Erfolgreich.~n~~w~Die Veränderungen an deinem Charakter wurden gespeichert.",
    equipped_new_outfit = "Du hast dein neues Outfit ausgerüstet: ~b~%s",
    warning_limit_outfits = "Du kannst nicht mehr Outfits speichern. ~g~(%s)",
    saved_new_outfit = "Du hast ein Outfit gespeichert: ~b~%s~w~.",
    rename_outfit = "Dein Outift ~b~%s~w~ wurd umbenannt zu ~g~%s~w~.",
    delete_outfit = "Dein Outfit: ~b~%s~w~ wurde gelöscht.",
 
    torso = "Torso",
    props = "Accessoires",
    top = "Oberteil",
    tops = "Oberteile",
    badge = "Abzeichen",
    pants = "Hosen",
    pant = "Hose",
    shoes = "Schuhe",
    bags = "Taschen/Rucksäcke",
    undershirt = "Unterteil",
    neck = "Hals",
    bracelets = "Armbänder",
    montres = "Uhren",
    earrings = "Ohrringe",
    glasses = "Brillen",
    hats = "Hüte",
    graphiques = "Logo",
 
    -- health
    inconscious = "bewusstlos",
    doing_something = "Etwas machen",
    time_before_respawn = "Zeit bis zum Respawn",
    you_died = "~r~Du bist gestorben",
    healing_wounds = "Wunden versorgen",
    already_doing_something = "~r~Du führst bereits eine Aktion aus.",
    you_have_been_healed = "~g~Du hast dich geheilt.",
    you_respawned = "~g~Du bist gerespawnt.",
 
    player_too_far_to_interact = "~r~Der Spieler mit du interargieren willst, ist zu weit entfernt.",
    send_trade_invitation_to = "Du hast eine Handelsanfrage an ~b~%s~w~ gesendet.\n~b~Warte darauf, dass er annimmt.",
    receive_invitation_from = "Du hast eine Handelsanfrage von ~b~%s~w~ erhalten.\n~b~Tippe ~w~/trade accept %s~b~ um zu akzeptieren.",
 
    invalid_command_args = "Ungültige Befehlsinhalte: %s",
    start_trade_command_help = "Eine Handelsanfrage an einen Spieler senden",
    accept_trade_command_help = "Eine Handelsanfrage akzeptieren",
    deny_trade_command_help = "Eine Handelsanfrage ablehnen",
    invalid_invitation = "Die Einladung ist ungültig oder existiert nicht mehr.",
    name_accepted_your_trade_invitation = "~b~%s~w~ hat deine Einladung angenommen.",
    you_accepted_trade_invitation_of_name = "Du hast die Handelsanfrage von %s angenommen",
    name_denied_your_trade_invitation = "~b~%s~w~ hat deine Handelsanfrage abgelehnt.",
    you_denied_trade_invitation_of_name = "Du hast die Handelsanfrage von %s abgelehnt",
    you_already_trading = "Du handelst bereits.",
    other_already_trading = "Der Spieler handelt bereits",
 
    other_player_not_enough_money = "~r~Der Handel ist fehlgeschlagen, der andere Spieler hat nicht genug Geld.",
    you_player_not_enough_money = "~r~Der Handel ist fehlgeschlagen, du hast nicht genug Geld.",
    other_player_not_enough_item = "~r~Der Handel ist fehlgeschlagen, der andere Spieler hat nicht genug Items.",
    you_player_not_enough_item = "~r~Der Handel ist fehlgeschlagen, du hast nicht genug Items.",
    success_trade = "~g~Der Handel war erfolgreich",
    fail_trade_other_player = "~r~Der Handel ist fehlgeschlagen, der andere Spieler hat ihn verlassen.",
    trade_other_full_item = "~r~Der Handel ist fehlgeschlagen, der Spieler hat nicht genug Platz.",
    trade_full_for_item = "~r~Der Handel ist fehlgeschlagen, du hast nicht genug Platz.",
 
    press_e_to_loot_inv = "Drücke ~INPUT_CONTEXT~ um die Tasche zu looten.",
    press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~Drücke~INPUT_CONTEXT~ um mit ~b~%s~HUD_COLOUR_NET_PLAYER27~ ~w~zu reden.",
    press_e_to = "Drücke ~INPUT_CONTEXT~ um ~b~%s~w~.",
    press_e_to_open_catalog = "Drücke ~b~E~w~ um den ~g~Prospekt~w~ anzuschauen.",
    this_person = "diese Person",
    the_shop = "diesem Shop",
    you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~Du bist nicht berechtig dies zu tun.",
 
    no_weapon = "~r~Du hast keine Waffe ausgerüstet.",
    no_need_ammo = "~r~Für diese Waffe brauchst du keine Munition.",
    not_right_ammo = "~r~Dies ist die falsche Munition, du brauchst ~b~%s~w~.",
    you_used_ammo = "Du hast deine ~b~%s~w~ mit ~b~x%s~w~ ~b~%s~w~ geladen.",
 
    choose_a_destination = "Wähle dein ~b~Ziel",
    open_your_chest = "deinen Safecontainer zu öffnen",
    no_enough_money = "~r~Du hast nicht genug Geld.",
    you_paid = "Du hast ~g~$%s~w~ für ~b~%s~w~ bezahlt.",
    you_paid_basket = "Du hast ~g~$%s~w~ für deine Waren bezahlt.",
    you_sell_basket = "Du hast ~g~$%s~w~ für das Verkaufen von ~b~%s~w~ Items erhalten.",
 
    you_repaired_your_vehicle = "~g~Du hast dein Fahrzeug repariert.",
    repairing_your_vehicle = "Repariere das Fahrzeug...",
    wheels_are_fine = "~r~Den Reifen geht es gut.",
    changing_wheel = "Wechsele die Räder...",
    you_repaired_the_wheels = "~g~Du hast die Räder der Fahrzeugs gewechselt.",
 
    front_post_ls = "Los Santos Außenposten",
    front_post_ls_2 = "Los Santos Außenposten 2",
    front_post_bc = "Außenposten Blaine County",
    front_post_bc_2 = "Außenposten Blaine County 2",
    main_post_ls = "Zentrale Los Santos",
    main_post_bc = "Zentrale Blaine County",
    random_zone = "Zufälliger Ort (In der Luft)",
 
    this_item_is_equipped = "~r~Dieses Item ist ausgerüstet, lege es aus der Hand.",
    only_in_safezone = "~r~Dies ist nur innerhalb einer grünen Zone möglich.",
    -- commerce stuff
    feature_gold_only = "Nur ~y~Gold-Spieler~w~ können dies.",
    feature_diamond_only = "Nur ~b~Diamond-Spieler~w~ können dies.",
    you_turned_into = "Du hast dich in ein ~g~%s~w~ verwandelt.",
    wait_between_transformation = "~r~Bitte warte einen Moment, bis du den Morph-Mode wieder verwenden kannst.",
    wait_between = "~r~Bitte warte einen Moment, bis du dies erneut tust.",
    available_morphs = "Verfügbare Morphs ",
    animal_models = "Tiere",
    zombie_models = "Zombies",
    success_update_name = "Du hast deinen Characternamen zu ~b~%s~w~ geändert.",
    success_reset_stats = "~g~Du hast deine Statisken erfolgreich zurückgesetzt.",
 
    -- animals
    boar = "Wildschwein",
    cat = "Katze",
    chop = "Rottweiler (Chop)",
    rottweiler = "Rottweiler",
    cow = "Kuh",
    coyote = "Kojote",
    deer = "Hirsch",
    hen = "Huhn",
    husky = "Husky",
    mtlion = "Löwe",
    pig = "Schwein",
    poodle = "Pudel",
    pug = "Mops",
    rabbit = "Hase",
    rat = "Ratte",
    retriever = "Retriever",
    shepherd = "Schaf",
    westy = "Westy",
 
    player_id = "ID des Spielers",
    bounty = "Kopfgeld",
    reason = "Grund",
    id_player_not_found = "~r~Diese ID kann keinem Spieler zugeordnet werden.",
 
    ammo_dealer = "Munitionshändler",
    misc_dealer = "Equipmenthändler",
    veh_dealer = "Autohändler",
    custom_dealer = "LS Custom",
    gun_dealer = "Waffenähndler",
 
    bounty_created = "Du hast ein Kopfheld in Höhe von ~g~$%s~w~ auf ~b~%s~w~ ausgesetzt.",
    contract_success = "~b~%s~w~ hat sich das Kopfgeld für ~r~%s~w~ geholt.",
    a_contract_on_your_head = "~r~Der Killer hat sich das Kopfgeld geholt, welches auf dich ausgesetzt war..",
    reward_for_contract = "Du hast ein Kopfgeld in Höhe von ~g~$%s~w~ für das Töten von ~b~%s~w~ erhalten.",
 
    hey_can_help_you = "Hey, wie kann ich dir helfen",
    i_want_to_buy_items = "Ich möchte etwas kaufen",
    i_want_to_sell_items = "Ich möchte etwas verkaufen",
 
    press_context_or_jump_to_get_up = "Drücke ~INPUT_CONTEXT~ oder ~INPUT_JUMP~ um ~b~nach oben zu gelangen~w~.",
    server_restart_warning = "Der Server wird gleich neugestartet...",
    auto_restart_in = "Automatischer Serverrestart in %s Sekunden.",
 
    not_allowed_create_character = "Du kannst keinen neuen Character erstellen",
    character_not_yours = "Das ist nicht dein Charakter.",
    character_does_not_exist = "Den Character gibt es nicht oder nicht mehr.",
    loading_character = "Deinen Character laden...",
 
    playtime_is = "~b~Deine Spielzeit auf Extinction\n~w~%s",
    dont_spam = "^1Nicht spammen!",
 
    babygod_warning = "~b~Du hast die grüne Zone verlassen. Du bist für einige Sekunden unverwundbar, finde einen sicheren Ort",
 
    -- Customs
    modifications_classiques = "Klassisches Tuning",
    modifications_custom = "Spezialtuning",
    modifications_benny = "Benny's Tuning",
    paint = "Farbe",
    custom_your_car = "Dein Fahrzeug tunen",
    wheels_modifications = "Reifentuning",
    performances = "Leistung",
    neons = "Neon",
    extra = "Extra",
    klaxon = "Hupe",
    teinte_fenetre = "Fenstertönung",
    phares_xenons = "Xenonlichter",
    modele_plaque = "Kennzeichenart",
    livery = "Innenraum",
    headlight_color = "Frontlichtfarbe",
    wheel_type = "Reifenart",
    primary_wheel_type = "Vordere Felge",
    back_wheel_type = "Hintere Felge",
    wheel_color = "Felgenfarbe",
    tire_smoke = "Reifenqualm",
    custom_color = "Farbe tunen",
    custom_wheel = "Rad tunen",
    custom_back_wheel = "Custom back wheel",
    suspension = "Aufhängung",
    transmission = "Getriebe",
    moteur = "Motor",
    frein = "Bremsen",
    turbo = "Turbo",
    primary_color = "Primärfarbe",
    secondary_color = "Sekünderfarbe",
    interior_color = "Innenraumfarbe",
    dashboard_color = "Armaturenbrettfarbe",
    color_effect = "Color effect",
    left_neon = "Unterboden links",
    right_neon = "Unterboden rechts",
    front_neon = "Unterboden vorn",
    back_neon = "Unterboden hinten",
 
    aileron = "Spoiler",
    pc_front = "Frontstoßstange",
    pc_back = "Heckstoßstange",
    carroserie = "Seitenschweller",
    exhaust = "Auspuff",
    cadre = "Rahmen",
    calandre = "Kühlergrill",
    capot = "Motorhaube",
    gb_left = "Kotflügel links",
    gb_right = "Kotflügel rechts",
    roof = "Dach",
    plate_support = "Kennzeichenhalterung",
    front_plate = "Kennzeichen vorn",
    interior_style = "Design Innenraum",
    figurine = "Figur",
    motif_dashboard = "Design Armaturenbrett",
    cadran = "Instrumentendesign",
    haut_parleur_portes = "Türlautsprecher",
    motif_sieges = "Sitzdesign",
    volant = "Lenkrad",
    levier = "Shalthebel",
    logo_custom = "Logo",
    ice = "ICE",
    haut_parleur_coffre = "Lautsprecher hintere Türen",
    hydrolique = "Hydraulics",
    moteur = "Motor",
    filtres_air = "Luftfilter",
    entretoises = "Abstandhalter",
    arc_couverture = "Krümmer",
    antenne = "Antenne",
    motif_exterieur = "Außendesign",
    reservoir = "Tank",
    window = "Scheiben",
    style = "Style",
    default = "Standard",
    type = "Art",
    normal = "Normal",
    black = "Schwarz",
    black_smoke = "Schwarzer Rauchen",
    simple_smoke = "leichter Rauch",
    stock = "Werksmäßig",
    limo = "Limousine",
    sa_black = "San Andreas schwarz",
    sa_blue = "San Andreas blau",
    sa_white = "San Andreas weiß",
    simple_white = "weiß",
    ny_white = "North Yankton weiß",
    race = "Rennen",
    sport = "Sport",
    stock = "Werksmäßig",
    street = "Straße",
    discount = "Rabatt",
    select_your_car = "Wähle dein Fahrzeug",
    select_car_custom = "Wähle das Fahrzeug, welches du tunen Möchtest. Die Nummer zwischen den Pfeilen ist der Item-Key.",
    loading_vehicle = "Fahrzeug spawnen...",
    invalid_vehicle = "~r~Ungültiges Fahrzeug.",
    invalid_vehicle_please_spawn = "~r~Ungültiges Fahrzeugitem. Bitte spawne es einmalig, bevor du etwas damit machst.",
    free_take_and_validate = "Alles kostenlos! Nimm was du tragen kannst und fahre fort!",
    car_custom_saved = "~g~Deine Tunings wurden gespeichert.",
 
    -- Character creation
    character_creation = "Charactererstellung",
    confirm = "bestätigen",
    start_playing = "Spielen",
    appearance = "Aussehen",
    character_list = "Characterliste",
    face_features = "Gesichtszüge",
    parents = "Eltern",
    parent = "Elternteil",
    mix = "mix",
    skin = "Aussehen",
    desc_mix = "Wähle aus, ob dein Gesicht mehr dem des Vaters oder der Mutter ähnelt.",
    desc_skin = "Wähle aus, ob dein Gesicht mehr dem des Vaters oder der Mutter ähnelt",
    identity = "Name",
    player_name = "Spielername",
    new_character = "neuer Character",
    warning_headblend = "~r~Du hast keine Eltern für deinen Character ausgewählt.",
    warning_overlays = "~r~Du hast keine Haare, Augenbrauen oder Bart ausgewählt.",
    warning_identity = "~r~Achtung.~n~~w~Du hast das Namensfeld nicht ausgefüllt.",
 
    -- kits
    kit_does_not_exist = "~r~Dieses Kit existiert nicht.",
    kit_needs_rank = "Du benötigst den ~r~%s~w~ Rang.",
    wait_before_using_kit = "Bitte warte ~r~%s~w~ bis du dieses Kit wieder nutzen kannst.",
    received_kit = "Du hast dein ~b~%s~w~ Kit erhalten.",
    no_kit = "Du hast kein Kits.",
 
    unable_to_find_booster = "Es konnte kein Booster mit dieser ID gefunden werden.",
    wait_already_player_boost = "Du hast bereits einen aktiven booster. Bitte warte einen Moment, bis du den nächsten verwenden kannst.",
    wait_already_crew_boost = "Es gibt bereits einen aktiven Crewbooster. Bitte warte einen Moment, bis du den nächsten verwenden kannst.",
    wait_already_server_boost = "Es gibt bereits einen aktiven Serverbooster. Bitte warte einen Moment, bis du den nächsten verwenden kannst.",
    booster_activated = "Booster für ~g~%s Minuten~w~ aktiviert! ~b~XP +%s%%",
    server_booster_activated = "~b~%s~w~ aktiviert einen Serverbooster für ~g~%s Minuten~z~! ~b~XP +%s%%",
    crew_booster_activated = "~b~%s~w~ aktiviert einen Crewbooster für ~g~%s Minuten~z~! ~b~XP +%s%%",
    no_booster = "Du hast keine Booster.",
 
    rank_expired = "~r~Dein Supporterrang ist abgelaufen.",
    supporter_role = "~g~Supporterrang:~w~ %s",
    no_rank_warning = "Du hast keinen Supporterrang.\n~r~Wenn du einen gekauft hast, verbinde bitte deinen FiveM Account.",
    no_fivem_id = "Du hast FiveM nicht mit deinem Spiel verknüpft.\n~r~Stelle sicher, dass du einen FiveM Account hast und ihn mit dem Spiel verbunden hast.",
    no_queue_warning = "Du hast kein Paket in der Warteschlange.\n~r~Warte kurz oder versuche /getRank wenn du deinen Rang vermisst.",
    package_sync_success = "~g~Deine Pakete wurden erfolgreich hinzugefügt, viel Spaß!\n~w~hilfreiche befehle: /getRank, /booster",
 
    level_required = "Du benötigst %s.",
    rank_required = "Du benötigst den %s Rang.",
    level_required_2 = "~r~ Du musst Level %s sein.",
 
    updated_deathmessage = "~g~Du hast deine Todesnachricht aktualiseirt.",
    updated_deatheffect = "~g~Du hast deinen Killeffekt aktualisiert.",
    use = "benutzen",
    test = "Test",
 
    -- zombie
    you_bitten = "~r~Du wurdest gebissen.",
    infection_rate = "Infektionsrate: ~r~%s%%",
 
    -- ranks
    thug = "Schläger",
    hustler = "Hustler",
    soldier = "Soldat",
    trigger = "Abzug",
    enforcer = "Vollstrecker",
    facilitator = "Facilitator",
    public_enemy = "Public Enemy",
    shot_caller = "Shot Caller",
    street_boss = "Straßenboss",
    kingpin = "Kingpin",
    -- Tattoo
    tattoo = "Tattoo",
    tattoos = "Tattoos",
    torso = "torso",
    head = "Kopf",
    left_arm = "linker Arm",
    right_arm = "rechter Arm",
    left_leg = "linkes bein",
    right_leg = "rechtes Bein",
    unknown = "unbekannt",
    other = "Andere",
    remove_tattoo = "Alle Tattoos entfernen",
    -- Hairdress
    haircuts = "Frisuren",
    makeup = "Make up",
    face = "Gesicht",
    eyebrows = "Augenbrauen",
    facial_hair = "Gesichtsbehaarung",
    body_hair = "Körperbehaarung",
    barber_shop = "Friseur",
    face_makeup = "Make Up",
    lipstick = "Lippenstift",
    face_foundation = "Gesichtsfoundation",
    skin_blemishes = "Hautunreinheiten",
    skin_ageing = "Hautalterung",
    moles_freckles = "Flecken und Pickel",
    sun_damage = "Hautbeschädigung",
    skin_complexion = "Hautfarbe",
    body_blemishes = "Körperverunstaltungen",
    body_blemishes_2 = "Körperverunstaltungen 2",
    opacity = "Sichtbarkeit",
    variations = "Variationen",
    filter = "Filter",
    eyes_color = "Augenfarbe",
    -- Mask
    masks = "Masken",
    -- Items
    money = "Geldscheine",
    -- Ammo
    ["9mm"] = "9mm",
    ["300_mag"] = ".300 Magnum",
    ["7_62mm"] = "7.62mm",
    ["calibre_12"] = "Kaliber 12",
    ["45_acp"] = ".45 ACP",
    ["5_56mm"] = "5.56mm",
 
    mask = "Maske",
    clean_kit = "Reinigungsset",
    radio = "Radio",
    recyclor = "Recycler",
    medkit = "Verbandskasten",
    kevlar = "Weste",
    gps = "GPS",
    repair_tool = "Reparatur kit",
    engine_veh = "Motor",
    wheel_veh = "Reifen",
    paint_spray = "Tuning Werkstatt",
    spike = "Nagelband",
    bandage = "Bandage",
    gaz_mask = "Gasmaske",
    filter = "Filter",
 
    pickup_spikestrip = "Nagelband aufheben",
    you_dropped_spikestrip = "Du hast ein ~g~Nagelband~w~ platziert.",
    you_pickup_spikestrip = "Du hast ein ~g~Nagelband~w~ aufgehoben.",
 
    you_have_been_killed_by = "Du wurdest durch ~r~%s getötet",
    kill_notif = "~m~getötet",
    you_killed = "Du hast ~r~%s~w~ getötet",
    already_used_reset_only = "~r~Du hast deinen Charakter schon neu gemacht.\n~w~Nur %s~w~ Member können den Charakter mehr als einmal zurücksetzen.",
    already_used_reset_only2 = "~r~Du hast diese Option schon einmal genutzt.\n~w~Nur %s~w~ Member können das mehr als einmal.",
 
    hud_options = "HUD Optionen",
    advanced_hud = "Erweitertes HUD anzeigen",
    players = "Spieler",
    health = "Leben",
    player_menu = "Spieler Menü",
 
    you_are_now_zombie = "~r~Du bist nun ein Zombie.",
 
    my_weapons = "Meine Waffen",
    customize_weapons = "Meine Waffe anpassen",
    weapon_skin = "Farbton",
 
    -- camo
    skin_classic = "Standard",
    skin_green = "Grün",
    skin_yellow = "Gelb",
    skin_pink = "Pink",
    skin_gold = "Gold",
    skin_blue = "Blau",
    skin_orange = "Orange",
 
    -- new
    airdrop_coming = "~r~Ein Airdrop ist im Anflug, wirf einen Blick auf die Map.",
    killed_by_cheater = "~r~Du wurdest durch einen Cheater getötet.\n~w~Wir haben ihn gebannt und dein Tod wurde rückgängig gemacht.",
 
    corrupted_vehicle = "~r~Das Fahrzeug ist beschädigt und wurde in der Vergangenheit dupliziert, es wurde aus deinem Inventar entfernt. Es tut uns leid, wenn dich jemand damit über den Tisch gezogen hat.",
 
    -- Discord
    join_discord_for_kit = "Komm auf unseren Discord um ein kostenloses Discord Kit zu bekommen!\n~g~discord.gg/gtalife",
    discord_account_not_linked = "~r~Du musst deinen Discord Account mit FiveM verknüpfen.",
    discord_account_not_guild = "~r~Du bist nicht im Discord Server.\n~w~ discord.gg/gtalife",
 
    already_done_recently = "~r~Versuche es bitte später noch einmal, du hast es erst kürzlich versucht.",
    update_country = "Land ändern",
 
    prestige_info = "~b~Du hast das maximale Level erreicht.\n~w~schreib /prestige um dir die Informationen über das Prestige Level System anzeigen zu lassen.",
    prestige_not_max_level = "~r~Du hast noch nicht das maximale Level dafür erreicht.",
    max_prestige_reached = "~r~Du hast das letzte Prestige erreicht.",
    prestige_info_cmd = [[^3Prestige Level System^7
Du bist momentan Prestige ^4%s^7 und Level ^5%s^7.
 
Wenn du das maximale Level erreichen solltest (%s) hast du die Möglichkeit, Prestige zu werden und von vorne wieder bei Level 0 anzufangen.
Durch ein neues Prestige bekommst du ein spezielles Abzeichen und neue Perks, wie zum Beispiel besseres Loot, neue Items, mehr Geld oder ein größeres Maximalgewicht deines Inventares.
^2Wenn du Prestige werden willst und wieder von Level 0 anfangen möchtest gib ein ^1/setprestige^2 in den Chat]],
    new_prestige = "Du hast ein neues Prestige freigeschaltet!\n~g~Du bist nun %s Prestige",
    cant_store_event_veh = "~r~Du kannst keine legendären Fahrzeuge einlagern.",
 
    you_are_no_longer_in_combat = "🛡️ ~b~Du bist nicht mehr im combat mode.",
    you_are_in_combat_mode = "🛡️ ~b~Du bist im combat mode.\nWenn du dich ausloggst, stirbst du.",
    you_disconnected_in_combat = "💀 Du hast dich während eines Kampfes ausgeloggt, du bist gestorben.",
 
    not_enough_prestige_points = "~r~Du hast nicht genug Prestige Punkte.",
    you_reached_max_prestige_stats_rank = "~r~Du hast den maximalen Rank für dieses Prestige Upgrade erreicht.",
    new_prestige_stats_upgrade = "Du hast dein ~b~%s~w~\n~g~%s/%s geupgraded",
 
    legendary_vehicle_pop = "~r~Ein legendäres Fahrzeug ist auf der Karte erschienen.",
 
    combat_mode_container_disabled = "~r~Du bist noch im Kampf.\n~w~Du kannst diese Items momentan nicht wegpacken.",
    gcoins_wallet_updated = "~g~Dein GCoins Konto wurde aktualisiert.\n~w~+%s GCoins",
    not_enough_gcoins = "~r~Du hast leider nicht genug GCoins.",
    gcoins_something_went_wrong = "~r~Etwas ist schief gelaufen.",
    you_bought_with_gcoins = "Du hast ~g~%s~w~ für ~b~%s GCoins gekauft~w~.",
 
    equiping_armor = "Weste anziehen",
 
    toggle_mute_player = "Spieler stummen/entstummen",
    you_muted_this_player = "~b~Du hast diesen Spieler gemuted.",
    you_unmuted_this_player = "~b~Du hast diesen Spieler entmuted.",
}
 
AddLanguage("de", my_language)