local my_language = {
	give_vehicle = "Você guardou ~b~%s~w~ no seu inventário.",
	store_vehicle_command = "Guardar o veículo",
	no_entity_vehicle = "~r~O veículo não existe ou está muito longe de você.",
	no_entity_vehicle_id = "~r~Veículo sem identificação, você não pode guarda-lo.",
	store_vehicle = "~b~Você guardou o veículo.",
	teleported_former_position = "~g~Você foi teleportado para a última localização salva.",
	not_enough_of = "~r~Você não possuí %s.",
	max_storage_chest = "~r~O depósito encontra-se cheio.",
	cant_carry_more_items = "~r~Você não pode carregar mais itens (full).",
	put_item = "Você guardou ~g~x%s~w~ %s~w~.",
	take_item = "Você pegou ~g~x%s~w~ %s~w~.",
	delete_item = "Você removeu ~r~x%s~w~ %s~w~.",
	you_equiped_item = "Você equipou seu ~g~%s~w~.",
	bind_weapon_command = "Atalho para slot de arma %s",
	kevlar_broke = "~r~AHH!~n~~w~Seu colete foi destruído.",
	inventory_command = "Abrir/Fechar inventário",
	press_enter_to_join = "Pressione ~g~ENTER~w~ para começar a jogar.",
	new_character = "Novo personagem",
	survivor = "Sobrevivente",
	right = "Direita",
	left = "Esquerda",
	male = "Homem",
	female = "Mulher",
	ped = "Ped",
	name = "Nome",
	sex = "Sexo",
	title = "Titulo",
	select_this_character = "Selecione este personagem",
	no_entity_zombie = "Zumbi não encontrado ou muito longe de você.",
	you_found = "Você encontrou ~g~%sx %s~w~.",
	you_found_nothing = "Você não encontrou ~g~nada~w~.",
	press_e_to_loot = "Aperte ~b~[E]~w~ para saquear",
	full_for_item = "~r~Você não possuí espaço para este item.",
	put_item_container = "Você guardou ~g~x%s~w~ %s~w~ em seu container.",
	take_item_container = "Você retirou ~g~x%s~w~ %s~w~ do seu container.",
	not_allowed_here = "~r~Você não pode fazer isto aqui.",
	cant_store_moving_veh = "~r~Você não pode guardar um véiculo em movimento.",
	use_repair_tool = "usar kit de reparo",
	please_get_closer = "~b~Por favor aproxime-se, entidade não encontrada.",
	you_cancel_action = "~r~Você cancelou esta ação.",
	selected_target_message = "Alvo selecionado:~n~%s~n~~r~Pressione ~b~Y~r~ para cancelar~n~~r~Pressione ~g~X~r~ para continuar.",
	target_you = "~b~VOCÊ",
	target_screen = "~g~Alvo",
	take_this_path = "pegue este caminho",

	-- hud
	default_hud = "HUD Padrão",
	cinema_hud = "HUD Cinemática",
	no_hud = "HUD Desabilitada",

	-- perms
	kick_member = "Expulsar membros",
	invite_someone = "Convidar",
	edit_member = "Editar membros",
	edit_rank = "Editar cargos",
	create_rank = "Criar cargos",
	delete_rank = "Deletar cargos",
	edit_structure = "Editar informações",
	edit_permissions = "Editar permissões",
	permission_level = "Níveis de permissão",
	red_delete = "Deletar",
	rank = "Cargo",
	red_kick = "Expulsar",
	crew_name = "Nome da equipe",
	slogan = "Slogan",
	information = "informação",
	boss_rank = "Nome do cargo chefe",
	member_rank = "Nome do cargo membro",
	member = "Membro",

	permissions_manager = "gerenciar permissões",
	members_manager = "gerenciar membros",
	ranks_manager = "gerenciar cargos",
	ranks_list = "lista de cargos",
	members_list = "lista de membros",
	create_a_rank = "criar um cargo",
	invite_someone = "convidar alguém",
	stats = "Estatísticas",
	total_ranks = "Total de cargos",
	total_members = "Total de membros",
	level = "Nível",
	actions = "ações",
	crew_manager = "gerenciar equipe",
	you_created_a_new_crew = "Você criou a equipe: %s",
	you_deleted_your_crew = "Você deletou sua equipe.",
	you_are_not_in_a_crew = "Você não está em uma equipe",
	you_joined_the_crew = "Você entrou na equipe '%s'",
	kick_failed = "A expulsão falhou, motivo: %s",
	already_in_crew = "Você já esetá em uma equipe",
	no_invitation = "Você não recebeu nenhum convite para equipe.",
	left_crew = "Você saiu de sua equipe.",
	permission_updated = "As permissões de <C>~g~%s</C>~w~ foram atualizadas.",
	incorrect_name = "~r~O formato do nome é inválido",
	incorrect_rank_perm = "~r~ERRO!\n~w~O nome deste cargo ou sua permissão é inválida.",
	warn_rank_limit = "~r~Você atingiu o limite de cargos.",
	create_rank_success = "~g~SUCESSO!\n~w~Você criou o cargo <C>~b~%s</C>~w~ com o nível de permissão <C>~b~%s</C>~w~.",
	crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~Você não pode interagir com um membro com o cargo maior que o seu.",
	you_sent_an_invitation = "Você convidou <C>~g~%s</C>~w~ para se juntar a sua equipe.",
	you_received_an_invitation = "Você recebeu um convite para uma equipe.\n~b~/%s para aceitar.",
	invitation_expired = "O convite expirou",
	crew_kick_success = "Você expulsou <C>~b~%s</C>~w~ de sua equipe.",
	first_rank_warning = "O primeiro cargo é o cargo padrão.",

	you_updated_this = "Você promoveu %s para ~g~<C>%s</C>~w~.",
	changes_saved_on = "As mudanças em <C>~g~%s</C>~w~ foram salvas.",
	yes = "sim",
	no = "não",
	none = "Nenhum",
	character_id = "ID do Personagem",
	server_id = "ID do Servidor",
	report = "Reportar",
	rename = "Renomear",
	trade_with = "Comércio",
	
	please_wait_x_before = "~r~Por favor, aguarde %s segundos antes de fazer isto.",

	-- cloth
	take_outfit = "Comprar este outfit",
	wardrobe_options = "opções do guarda-roupas",
	wardrobe = "guarda-roupas",
	manual_options = "opções manuais",
	manual_mode = "modo manual",
	save_outfit = "salvar este outfit",
	variation = "variação",
	outfits = "outfits",
	cloth_shop = "Loja de Roupas",
	ped_cloth_shop = "Loja de Roupas de Ped",
	manual_props = "adereços manuais",
	manuel = "manual",
	new_name = "Novo nome",
	outfit_name = "Nome do Outfit",
	variations_saved = "~g~Sucesso.~n~~w~As variações de seu personagem foram salvas.",
	equipped_new_outfit = "Você vestiu o outfit: ~b~%s",
	warning_limit_outfits = "Você antigiu o número máximo de outfits. ~g~(%s)",
	saved_new_outfit = "Você salvou um novo outfit: ~b~%s~w~.",
	rename_outfit = "Seu outfit ~b~%s~w~ foi renomeado para ~g~%s~w~.",
	delete_outfit = "Seu outfit: ~b~%s~w~ foi deletado.",

	torso = "Corpo",
	props = "Adereços",
	top = "Jaqueta",
	tops = "Jaquetas",
	badge = "Distintivo",
	pants = "Calças",
	pant = "Calça",
	shoes = "Sapatos",
	bags = "Bolsas",
	undershirt = "camisas",
	neck = "pescoço",
	bracelets = "braceletes",
	montres = "relógicos",
	earrings = "orelhas",
	glasses = "óculos",
	hats = "chapéus",
	graphiques = "decorações",

	-- health
	inconscious = "Inconsciente",
	doing_something = "Fazendo algo",
	time_before_respawn = "Tempo antes do respawn",
	you_died = "~r~Você morreu",
	healing_wounds = "Curando feridas",
	already_doing_something = "~r~Você já está realizando uma ação.",
	you_have_been_healed = "~g~Você foi curado.",
	you_respawned = "~g~Você respawnou.",

	player_too_far_to_interact = "~r~O jogador que você deseja interagir está muito longe.",
	send_trade_invitation_to = "Você enviou um convite de troca para ~b~%s~w~.\n~b~Aguarde até que o jogador aceite.",
	receive_invitation_from = "Você recebeu um convite de troca de ~b~%s~w~.\n~b~Digite ~w~/trade accept %s~b~ para iniciar as trocas.",

	invalid_command_args = "Comando inválido, argumentos: %s",
	start_trade_command_help = "Iniciar trocas com umjogador",
	accept_trade_command_help = "Aceitar um pedido de trocas",
	deny_trade_command_help = "Negar um pedido de trocas",
	invalid_invitation = "O convite de trocas é inválido ou expirou",
	name_accepted_your_trade_invitation = "~b~%s~w~ aceitou seu pedido de trocas",
	you_accepted_trade_invitation_of_name = "Você aceitou o pedido de trocas de %s",
	name_denied_your_trade_invitation = "~b~%s~w~ recusou seu pedido de trocas",
	you_denied_trade_invitation_of_name = "Você recusou o pedido de trocas de %s",
	you_already_trading = "Você já está em uma troca",
	other_already_trading = "O jogador já está em uma troca",

	other_player_not_enough_money = "~r~A troca falhou. O jogador não possuí dinheiro suficiente.",
	you_player_not_enough_money = "~r~A troca falhou. Você não possuí dinheiro suficiente.",
	other_player_not_enough_item = "~r~A troca falhou. O jogador não possuí itens suficientes.",
	you_player_not_enough_item = "~r~A troca falhou. Você não possuí itens suficientes.",
	success_trade = "~g~A troca foi confirmada.",
	fail_trade_other_player = "~r~A troca falhou, o jogador se desconectou.",
	trade_other_full_item = "~r~A troca falhou, o jogador não possuí espaço de inventário suficiente.",
	trade_full_for_item = "~r~A troca falhou, você não possuí espaço de inventário suficiente.",

	press_e_to_loot_inv = "Pressione ~INPUT_CONTEXT~ para saquear o inventário.",
	press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~Pressione ~INPUT_CONTEXT~ para interagir com ~b~%s~HUD_COLOUR_NET_PLAYER27~.",
	press_e_to = "Pressione ~INPUT_CONTEXT~ para ~b~%s~w~.",
	press_e_to_open_catalog = "Pressione ~b~E~w~ para ver o ~g~catálogo~w~.",
	this_person = "esta pessoa",
	the_shop = "esta loja",
	you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~Você não tem permissão para fazer isto.",

	no_weapon = "~r~Você não possuí nenhuma arma equipada.",
	no_need_ammo = "~r~Você não precisa de munição para utilizar esta arma.",
	not_right_ammo = "~r~Você não está utilizando a munição adequada, você precisa de munição ~b~%s~w~.",
	you_used_ammo = "Você carregou sua ~b~%s~w~ com ~b~x%s~w~ de ~b~%s~w~.",

	choose_a_destination = "escolha um ~b~destino",
	open_your_chest = "abrir seu baú",
	no_enough_money = "~r~Você não possuí dinheiro suficiente.",
	you_paid = "Você pagou ~g~$%s~w~ para ~b~%s~w~.",
	you_paid_basket = "Você pagou ~g~$%s~w~ pelo item(s).",
	you_sell_basket = "Você recebeu ~g~$%s~w~ por vender ~b~x%s~w~ item(s).",

	you_repaired_your_vehicle = "~g~Você reparou seu veiculo.",
	repairing_your_vehicle = "Reparando veículo",
	wheels_are_fine = "~r~Os pneus do veículo estão sem problemas.",
	changing_wheel = "Trocando os pneus",
	you_repaired_the_wheels = "~g~Você trocou os pneus do veículo",

	front_post_ls = "Posto Seguro de Los Santos",
	front_post_ls_2 = "Posto Seguro de Los Santos 2",
	front_post_bc = "Posto Seguro de Blaine County",
	front_post_bc_2 = "Posto Seguro de Blaine County 2",
	main_post_ls = "Posto Principal de Los Santos",
	main_post_bc = "Posto Principal de Blaine County",
	random_zone = "Zona aleatória",

	this_item_is_equipped = "~r~Este item está equipado, remova-o de seus atalhos.",
	only_in_safezone = "~r~Você não pode fazer isto fora de uma zona segura.",
	-- commerce stuff
	feature_gold_only = "Esta vantagem é apenas para ~y~membros gold~w~.",
	feature_diamond_only = "Esta vantagem é apenas para ~b~membros diamond~w~.",
	you_turned_into = "Você se transformou em ~g~%s~w~.",
	wait_between_transformation = "~r~Por favor, aguarde antes de utilizar a metaformose novamente.",
	wait_between = "~r~Por favor, aguarde antes de realizar isto novamente.",
	available_morphs = "Formas Disponíveis",
	animal_models = "Animais",
	zombie_models = "Zumbis",
	success_update_name = "Você alterou o nome do seu personagem para ~b~%s~w~.",
	success_reset_stats = "~g~Você resetou sua estatísticas. (O ranking será atualizado mais tarde)",

	-- animals
	boar = "Javali",
	cat = "Gato",
	chop = "Rottweiler (Chop)",
	rottweiler = "Rottweiler",
	cow = "Vaca",
	coyote = "Coyote",
	deer = "Veado",
	hen = "Galinha",
	husky = "Husky",
	mtlion = "Puma",
	pig = "Porco",
	poodle = "Poodle",
	pug = "Pug",
	rabbit = "Coelho",
	rat = "Rato",
	retriever = "Retriever",
	shepherd = "Shepherd",
	westy = "Terrier",

	player_id = "ID do Jogador",
	bounty = "Recompensa",
	reason = "Motivo",
	id_player_not_found = "~r~Nenhum jogador encontrado com este ID.",

	ammo_dealer = "Vendedor de munições",
	misc_dealer = "Loja de equipamentos",
	veh_dealer = "Loja de veículos",
	custom_dealer = "LS Custom",
	gun_dealer = "Loja de armas",

	bounty_created = "Você pagou ~g~$%s~w~ para criar um contrato de recompensa para ~b~%s~w~.",
	contract_success = "A recompensa sob a cabeça de ~r~%s~w~ foi enviada para ~b~%s~w~.",
	a_contract_on_your_head = "~r~Sua cabeça foi colocada sob recompensa. Seu assassino receberá a recompensa por ela",
	reward_for_contract = "Caçador de Recompensas! Você recebeu ~g~$%s~w~ por matar ~b~%s~w~.",

	hey_can_help_you = "Olá, em que posso ajudar?",
	i_want_to_buy_items = "Eu quero comprar itens",
	i_want_to_sell_items = "Eu quero vender itens",

	press_context_or_jump_to_get_up = "Pressione ~INPUT_CONTEXT~ ou ~INPUT_JUMP~ para ~b~levantar-se~w~.",
	server_restart_warning = "O servidor irá reiniciar..",
	auto_restart_in = "Reiniciamento automático em %s segundos.",

	not_allowed_create_character = "Você não pode criar um novo personagem.",
	character_not_yours = "Este personagem não é seu.",
	character_does_not_exist = "Este personagem não existe ou não existe mais.",
	loading_character = "Carregando seu personagem...",

	playtime_is = "~b~Seu tempo de jogo em Extinction:\n~w~%s",
	dont_spam = "^1Não faça spam!",

	babygod_warning = "~b~Você saiu da zona segura, você tem alguns segundos de invencibilidade para encontrar um lugar seguro!",

	-- LS Custom
	modifications_classiques = "Modificações clássicas",
	modifications_custom = "Modificiações especiais",
	modifications_benny = "Modificações da bennys",
	paint = "pintar",
	custom_your_car = "Customizar seu carro",
	wheels_modifications = "Modificações no pneu",
	performances = "Performances",
	neons = "Neons",
	extra = "Extra",
	klaxon = "Busina",
	teinte_fenetre = "Pintura de vidros",
	phares_xenons = "Faróis xenon",
	modele_plaque = "Modelo de placa",
	livery = "Pinturas especiais",
	headlight_color = "Cores de luzes",
	wheel_type = "Tipos de pneu",
	primary_wheel_type = "Pneu primário",
	back_wheel_type = "Pneu traseiro",
	wheel_color = "Cor do pneu",
	tire_smoke = "Fumaça de arrancada",
	custom_color = "Cor customizada",
	custom_wheel = "Pneu customizado",
	custom_back_wheel = "Pneu traseiro customizado",
	suspension = "Suspensão",
	transmission = "Transmissão",
	moteur = "Motor",
	frein = "Freios",
	turbo = "Turbo",
	primary_color = "Cor primária",
	secondary_color = "Cor secundária",
	interior_color = "Cor do interior",
	dashboard_color = "Dashboard color",
	color_effect = "Efeito de cor",
	left_neon = "Neon esquerdo",
	right_neon = "Neon direito",
	front_neon = "Neon primário",
	back_neon = "Neon traseiro",

	aileron = "Spoiler",
	pc_front = "Front bumper",
	pc_back = "Rear bumper",
	carroserie = "Side skirt",
	exhaust = "Exhaust",
	cadre = "Frame",
	calandre = "Grille",
	capot = "Hood",
	gb_left = "Left fender",
	gb_right = "Right fender",
	roof = "Roof",
	plate_support = "Plate holders",
	front_plate = "Front plate",
	interior_style = "Interior style",
	figurine = "Figurine",
	motif_dashboard = "Dashboard style",
	cadran = "Dial design",
	haut_parleur_portes = "Speaker doors",
	motif_sieges = "Seat style",
	volant = "Steering wheel",
	levier = "Shifter leavers",
	logo_custom = "Logo",
	ice = "ICE",
	haut_parleur_coffre = "Speaker back doors",
	hydrolique = "Hydraulics",
	moteur = "Engine",
	filtres_air = "Air filter",
	entretoises = "Spacers",
	arc_couverture = "Arch",
	antenne = "Antenna",
	motif_exterieur = "Exterior style",
	reservoir = "Tank",
	window = "Window",
	style = "Style",
	default = "Default",
	type = "Type",
	normal = "Normal",
	black = "Black",
	black_smoke = "Black smoke",
	simple_smoke = "Simple smoke",
	stock = "Stock",
	limo = "Limousine",
	sa_black = "San Andreas black",
	sa_blue = "San Andreas blue",
	sa_white = "San Andreas white",
	simple_white = "Simple white",
	ny_white = "North Yankton white",
	race = "Corrida",
	sport = "Esportivo",
	stock = "Original",
	street = "Rua",
	discount = "Desconto",
	select_your_car = "Selecione seu veículo",
	select_car_custom = "Select the vehicle you want to customize. The number between arrows is the item key.",
	loading_vehicle = "Creating vehicle",
	invalid_vehicle = "~r~Invalid vehicle entity.",
	invalid_vehicle_please_spawn = "~r~Invalid vehicle item. Please spawn it one time before trying to do anything.",
	free_take_and_validate = "Everything is free. Take what you want and confirm!",
	car_custom_saved = "~g~Modificações do veículo salvas com sucesso.",

	-- Character creation
	character_creation = "Criação de personagem",
	confirm = "confirmar",
	start_playing = "Começar a jogar",
	appearance = "aparência",
	character_list = "lista de personagens",
	face_features = "características do rosto",
	parents = "parentes",
	parent = "parente",
	mix = "mix",
	skin = "pele",
	desc_mix = "Selecione se rosto de seu personagem é baseado na escolha de seu pai / mãe.",
	desc_skin = "Selecione se a pele de seu personagem é baseada na escolha de seu pai / mãe.",
	identity = "identidade",
	player_name = "nome do jogador",
	new_character = "novo personagem",
	warning_headblend = "~r~Você não selecionou seus parentes.",
	warning_overlays = "~r~Você não selecionou cabelos, sombrancelhas ou barba.",
	warning_identity = "~r~Atenção.~n~~w~Você esqueceu de preencher a seção de identidade.",

	-- kits
	kit_does_not_exist = "~r~Este kit não existe",
	kit_needs_rank = "Você não possuí o rank ~r~%s~w~.",
	wait_before_using_kit = "Por favor, aguarde ~r~%s~w~ antes de usar este kit.",
	received_kit = "Você recebeu o kit ~b~%s~w~.",
	no_kit = "Você não possuí nenhum kit.",

	unable_to_find_booster = "Unable to find a booster with this id.",
	wait_already_player_boost = "Please wait a moment before using this booster. There is already one player booster active.",
	wait_already_crew_boost = "Please wait a moment before using this booster. There is already one crew booster active.",
	wait_already_server_boost = "Please wait a moment before using this booster. There is already one server booster active.",
	booster_activated = "Booster activated for ~g~%s minutes~w~! ~b~XP +%s%%",
	server_booster_activated = "~b~%s~w~ activated a server booster for ~g~%s minutes~z~! ~b~XP +%s%%",
	crew_booster_activated = "~b~%s~w~ activated a crew booster for ~g~%s minutes~z~! ~b~XP +%s%%",
	no_booster = "You do not have any booster.",

	rank_expired = "~r~Seu pacote apoiador expirou.",
	supporter_role = "~g~Grupo Apoiador:~w~ %s",
	no_rank_warning = "Você não possuí nenhum grupo apoiador.\n~r~Caso você tenha comprado, vincule sua conta do FiveM.",
	no_fivem_id = "Sua conta do FiveM não foi vinculada no jogo.\n~r~Verifique se você possuí uma conta no FiveM e se ela está vinculada no jogo.",
	no_queue_warning = "Você não possuí nenhum pacote na fila.\n~r~Aguarde um momento ou utilize /getRank se você já comprou seu apoiador.",
	package_sync_success = "~g~Seus pacotes foram sincronizados com sucesso!\n~w~Comandos úteis: /getRank, /booster",

	level_required = "Você precisa ter o nível %s.",
	rank_required = "Você precisa ter o rank %s.",
	level_required_2 = "~r~Você precisa ter o nível %s.",

	updated_deathmessage = "~g~Você atualizou sua mensagem de morte.",
	updated_deatheffect = "~g~Você atualizou seu efeito de morte.",
	use = "Usar",
	test = "Testar",

	-- zombie
	you_bitten = "~r~Você foi mordido.",
	infection_rate = "Nível de Infecção: ~r~%s%%",

	-- ranks
	thug = "Bandido",
	hustler = "Vigarista",
	soldier = "Soldado",
	trigger = "Gatilho",
	enforcer = "Executor",
	facilitator = "Facilitador",
	public_enemy = "Inimigo Público",
	shot_caller = "Mandante",
	street_boss = "Chefe das Ruas",
	kingpin = "Rei do Crime",
	-- Tattoo
	tattoo = "tatuagem",
	tattoos = "tatuagens",
	torso = "corpo",
	head = "cabeça",
	left_arm = "braço esquerdo",
	right_arm = "braço direito",
	left_leg = "perna esquerda",
	right_leg = "perna direita",
	unknown = "desconhecido",
	other = "outras",
	remove_tattoo = "Remover todas as tatuagens",
	-- Hairdress
	haircuts = "Cortes de cabelo",
	makeup = "Maquiagem",
	face = "Rosto",
	eyebrows = "Sombrancelhas",
	facial_hair = "Pelo facial",
	body_hair = "Pelo corporal",
	barber_shop = "Barbearia",
	face_makeup = "Maquiagem facial",
	lipstick = "Batom",
	face_foundation = "Base facial",
	skin_blemishes = "Manchas na pele",
	skin_ageing = "Envelhecimento da pele",
	moles_freckles = "Sardas",
	sun_damage = "Danos na pele",
	skin_complexion = "Complexidade na pele",
	body_blemishes = "Manchas no corpo",
	body_blemishes_2 = "Manchas no corpo 2",
	opacity = "Opacidade",
	variations = "Variações",
	filter = "Filtro",
	eyes_color = "Cores de olho",
	-- Mask
	masks = "Máscaras",
	-- Items
	money = "Dinheiro",
	-- Ammo
	["9mm"] = "9mm",
	["300_mag"] = ".300 Magnum",
	["7_62mm"] = "7.62mm",
	["calibre_12"] = "Calibre 12",
	["45_acp"] = ".45 ACP",
	["5_56mm"] = "5.56mm",
	-- Food
	["fish_1"] = "Largemouth Bass",
	["fish_2"] = "Rainbow Trout",
	["fish_3"] = "Kokanee",
	["fish_4"] = "Arctic Grayling",
	["fish_5"] = "Rock Bass",
	["fish_6"] = "Smallmouth Bass",
	["fish_7"] = "Paddlefish",
	["fish_8"] = "Bull Trout",
	["fish_9"] = "Lake Trout",
	["fish_10"] = "Chinook",
	["fish_11"] = "Pallid Sturgeon",
	["fish_12"] = "Salmon",

	misc_meat = "Carne crua",
	rabbit_meat = "Carne de coelho",
	lion_meat = "Carne de puma",
	rare_plume = "Pluma rara",
	dog_meat = "Carne de cachorro",
	cat_meat = "Carne de gato",
	rare_fish = "Peixe raro",

	mask = "Máscara",
	malette = "Maleta",
	malette_metal = "Maleta metálica",
	ciseaux = "Tesouras",
	clean_kit = "Kit de limpeza",
	fishing_rod = "Vara-de-pesca",
	meuble = "Mobília",
	tissu = "Roupas",
	accessory = "Acessórios",
	radio = "Rádio",
	recyclor = "Reciclador",
	medkit = "Kit Médico",
	kevlar = "Colete Balístico",
	gps = "GPS",
	repair_tool = "Kit de Reparo",
	jvn = "JVN",
	engine_veh = "Motor",
	wheel_veh = "Pneu",
	vetement = "Jaqueta",
	bloc_note = "Bloco de Notas",
	paint_spray = "Spray de pintura",
	spike = "Faixa de Espinhos",
	paracetamol = "Paracetamol",
	bandage = "Bandagem",
	gaz_mask = "Máscara de Gás",
	filter = "Fitlro",
	tattoo_tool = "Ferramenta de tatuagem",
	drug_med = "Droga",
	antizin = "Antizin",

	pickup_spikestrip = "pickup the spike strip",
	you_dropped_spikestrip = "You dropped a ~g~spike strip~w~.",
	you_pickup_spikestrip = "You picked up a ~g~spike strip~w~.",

	you_have_been_killed_by = "Você foi morto ~r~%s",
	kill_notif = "~m~Matou",
	you_killed = "Você matou ~r~%s~w~",
	already_used_reset_only = "~r~Você já resetou seu personagem.\n~w~Apenas apoiadores %s~w~ podem refazer seus personagens mais de uma vez.",
	already_used_reset_only2 = "~r~Você já fez isto.\n~w~Apenas apoiadores %s~w~ podem fazer isto mais de uma vez.",

	hud_options = "Opções de HUD",
	advanced_hud = "Exibir HUD avançada",
	players = "Jogadores",
	health = "Vida",
	player_menu = "Menu de Jogador",

	you_are_now_zombie = "~r~Você agora é um zumbi.",

	my_weapons = "minhas armas",
	customize_weapons = "customizar minha arma",
	weapon_skin = "pintura",

	-- camo
	skin_classic = "Padrão",
	skin_green = "Verde",
	skin_yellow = "Amarelo",
	skin_pink = "Rosa",
	skin_gold = "Ouro",
	skin_blue = "Azul",
	skin_orange = "Laranja",

	-- new
	airdrop_coming = "~r~Um airdrop está chegando, cheque seu mapa.",
	killed_by_cheater = "~r~Você foi morto por um cheater.\n~w~Nós banimos ele e sua morte foi cancelada.",

	corrupted_vehicle = "~r~Este veículo foi comprometido e foi duplicado no passado, ele foi removido do seu inventário. Desculpe caso tenha sido roubado.",

	-- Discord
	join_discord_for_kit = "Entre em nosso discord para receber um kit discord!\n~g~discord.gg/gtalife",
	discord_account_not_linked = "~r~Você precisa vincular sua conta do Discord com o FiveM.",
	discord_account_not_guild = "~r~Você não está no nosso servidor do Discord.\n~w~Join discord.gg/gtalife",

	already_done_recently = "~r~Tente mais tarde, você já fez isto recentemente.",
	update_country = "Atualizar país",

	prestige_info = "~b~Você chegou ao último nível.\n~w~Digite /prestige para receber informações sobre o sistema de prestígio.",
	prestige_not_max_level = "~r~Você ainda não alcançou o nível máximo.",
	max_prestige_reached = "~r~Você chegou ao último prestígio.",
	prestige_info_cmd = [[^3Sistema de Prestígio^7
Você está no prestígio ^4%s^7 e no nível ^5%s^7.

Caso você chegue ao nível (%s) você recebe o prestígio e sua experiência é resetada e volta novamente ao level 0.
Conquistando um novo prestígio você recebe uma insignia especial, novas vantagens como melhores loots, novos itens, mais dinheiro ou um espaço maior em seu inventário
^2Caso você queira prestigiar e RETORNAR ao nível 0 digite ^1/setprestige^2
]],
	new_prestige = "Você desbloqueou um novo prestígio!\n~g~Você agora possuí %s prestígio(s)",
	cant_store_event_veh = "~r~Você não pode guardar veículos especiais.",

	you_are_no_longer_in_combat = "🛡️ ~b~Você não está mais em combate.",
	you_are_in_combat_mode = "🛡️ ~b~Você está em combate.\nCaso desconecte-se você morrerá.",
	you_disconnected_in_combat = "💀 Você desconectou em combate, você morreu.",

	not_enough_prestige_points = "~r~Você não possuí pontos de prestígio suficientes.",
	you_reached_max_prestige_stats_rank = "~r~Você alcançou o nível máximo de prestígio.",
	new_prestige_stats_upgrade = "Você melhorou seu ~b~%s~w~\n~g~%s/%s",

	legendary_vehicle_pop = "~r~Um veículo lendário apareceu no mapa.",

	-- poll one
	poll1_q1 = "O que em nosso servidor você gostaria de ver?",
	poll1_q2 = "Qual atualização você acha que seria uma prioridade para o Extinction?",

	poll1_q1_a1 = "Battle Royale",
	poll1_q1_a2 = "Private missions solo or with 1-4 friends (Payday / Heist / Hitman like)",
	poll1_q1_a3 = "Race",
	poll1_q1_a4 = "Murder / Horror game",

	poll1_q2_a1 = "PvE improve zombies/farm",
	poll1_q2_a2 = "Add new map events",
	poll1_q2_a3 = "Shop/Trade update",
	poll1_q2_a4 = "More RPG stats / improvements",

	combat_mode_container_disabled = "~r~You are in combat.\n~w~You cannot store items.",
	gcoins_wallet_updated = "~g~You GCoins wallet has been updated.\n~w~+%s GCoins",
	not_enough_gcoins = "~r~You do not have enough GCoins.",
	gcoins_something_went_wrong = "~r~Something went wrong.",
	you_bought_with_gcoins = "You bought ~g~%s~w~ for ~b~%s GCoins~w~.",

	equiping_armor = "Equiping armor",
}

AddLanguage("en", my_language)
