local my_language = {
    give_vehicle = "Has agregado ~b~%s~w~ a tu inventario.",
    store_vehicle_command = "Almacene el vehículo que está conduciendo",
    no_entity_vehicle = "~r~El vehículo no existe o está demasiado lejos de ti.",
    no_entity_vehicle_id = "~r~El vehículo no está vinculado a ningun usuario, no puedes almacenarlo.",
    store_vehicle = "~b~Guardaste tu vehiculo.",
    teleported_former_position = "~g~Has sido teletransportado a tu última posición guardada.",
    not_enough_of = "~r~No tienes suficiente %s.",
    max_storage_chest = "~r~La caja de almacenamiento está llena.",
    cant_carry_more_items = "~r~Su inventario no puede almacenar más artículos (Completo).",
    put_item = "Has puesto ~g~x%s~w~ %s~w~.",
    take_item = "Has tomado ~g~x%s~w~ %s~w~.",
    delete_item = "Te quitaste ~r~x%s~w~ %s~w~.",
    you_equiped_item = "Has equipado tu ~g~%s~w~.",
    bind_weapon_command = "Atajo para la ranura del arma %s",
    kevlar_broke = "~r~AHH!~n~~w~Tu armadura se rompió.",
    inventory_command = "Alternar inventario",
    press_enter_to_join = "Presiona ~g~ENTER~w~ para empezar a jugar.",
    new_character = "Nuevo personaje",
    survivor = "Sobreviviente",
    right = "Derecha",
    left = "Izquierda",
    male = "Masculino",
    female = "Femenino",
    ped = "Ped",
    name = "Nombre",
    sex = "Sexo",
    title = "Titulo",
    select_this_character = "Selecciona este personaje",
    no_entity_zombie = "El zombi no existe o está muy lejos de ti.",
    you_found = "Has encontrado ~g~%sx %s~w~.",
    you_found_nothing = "Has encontrado ~g~nada~w~.",
    press_e_to_loot = "Presiona ~b~[E]~w~ para saquear",
    full_for_item = "~r~No hay suficiente espacio para este artículo.",
    put_item_container = "Has puesto ~g~x%s~w~ %s~w~ en tu contenedor.",
    take_item_container = "Has tomado ~g~x%s~w~ %s~w~ de tu contenedor.",
    not_allowed_here = "~r~You are not allowed to do that here.",
    cant_store_moving_veh = "~r~No puedes hacer eso aquí.",
    use_repair_tool = "Usa la herramienta de reparación",
    please_get_closer = "~b~PPor favor, acércate, no hay entidad en el rango.",
    you_cancel_action = "~r~Cancelaste la acción.",
    selected_target_message = "Objetivo seleccionado:~n~%s~n~~r~Presiona ~b~Y~r~ para cancelar~n~~r~Presiona ~g~X~r~ para continuar.",
    target_you = "~b~Tú",
    target_screen = "~g~Desplegada",
    take_this_path = "Toma este camino",
 
    -- hud
    default_hud = "Default HUD",
    cinema_hud = "Cinema HUD",
    no_hud = "No HUD",
 
    -- perms
    kick_member = "Patear miembros",
    invite_someone = "Invitación",
    edit_member = "Editar miembros",
    edit_rank = "Editar rangos",
    create_rank = "Crear rangos",
    delete_rank = "Eliminar rangos",
    edit_structure = "Editar la información de la tripulación",
    edit_permissions = "Permisos de edición",
    permission_level = "Conceder permisos",
    red_delete = "Borrar",
    rank = "Rango",
    red_kick = "Expulsar",
    crew_name = "Nombre de la tripulación",
    slogan = "Frase clave",
    information = "Información",
    boss_rank = "Nombre de rango del jefe",
    member_rank = "Nombre de rango de novato",
    member = "Miembro",
 
    permissions_manager = "Administrador de permisos",
    members_manager = "Administrador de miembros",
    ranks_manager = "Administrador de rangos",
    ranks_list = "Lista de rangos",
    members_list = "Lista de miembros",
    create_a_rank = "Crear un rango",
    invite_someone = "Invitar a alguien",
    stats = "Estadísticas",
    total_ranks = "Rangos totales",
    total_members = "Miembros totales",
    level = "Nivel",
    actions = "Acciones",
    crew_manager = "Jefe de tripulacion",
    you_created_a_new_crew = "Creaste una nueva tripulación: %s",
    you_deleted_your_crew = "Borraste tu tripulación.",
    you_are_not_in_a_crew = "YNo estás en una tripulación",
    you_joined_the_crew = "Te uniste a una nueva Tripulación '%s'",
    kick_failed = "La expulsión fallo, razon: %s",
    already_in_crew = "Ya estás en una tripulación",
    no_invitation = "No has recibido ninguna invitación.",
    left_crew = "Dejaste tu tripulación.",
    permission_updated = "Los permisos de <C>~g~%s</C>~w~  han sido actualizados.",
    incorrect_name = "~r~El formato del nombre es incorrecto",
    incorrect_rank_perm = "~r~Error\n~w~El nombre de rango o el nivel de permiso es inválido.",
    warn_rank_limit = "~r~Alcanzaste el límite de rangos.",
    create_rank_success = "~g~Success\n~w~Creaste un nuevo rango <C>~b~%s</C>~w~ con un nivel de permiso de <C>~b~%s</C>~w~.",
    crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~No puedes interactuar con un miembro que tenga un nivel de permiso superior al tuyo.",
    you_sent_an_invitation = "Usted envió una invitación a <C>~g~%s</C>~w~ para unirse a su tripulación.",
    you_received_an_invitation = "Recibió una invitación para unirse a una tripulación.\n~b~/%s para aceptar.",
    invitation_expired = "La invitación expiró",
    crew_kick_success = "Expulsaste <C>~b~%s</C>~w~ de tu tripulación.",
    first_rank_warning = "El primer rango es el rango 'predeterminado'.",
 
    you_updated_this = "Actualizaste %s to ~g~<C>%s</C>~w~.",
    changes_saved_on = "Los cambios realizados e <C>~g~%s</C>~w~ han sido guardados.",
    yes = "si",
    no = "no",
    none = "Ninguno",
    character_id = "ID del personaje",
    server_id = "ID del servidor",
    report = "Reporte",
    rename = "Cambiar nombre",
    trade_with = "Intercambiar",
    
    please_wait_x_before = "~r~Porfavor espere %s segundos antes de hacer eso.",
 
    -- cloth
    take_outfit = "Comprar este atuendo",
    wardrobe_options = "Opciones de vestuario",
    wardrobe = "guardarropa",
    manual_options = "opciones manuales",
    manual_mode = "modo manual",
    save_outfit = "Guarda este atuendo",
    variation = "variación",
    outfits = "Atuendos",
    cloth_shop = "Tienda de ropa",
    ped_cloth_shop = "Tienda de ropa (ped)",
    manual_props = "accesorios manuales",
    manuel = "manual",
    new_name = "Nuevo nombre",
    outfit_name = "Nombre del atuendo",
    variations_saved = "~g~Éxito.~n~~w~Se han guardado las variaciones de tu personaje..",
    equipped_new_outfit = "Has equipado tu nuevo atuendo: ~b~%s",
    warning_limit_outfits = "Has alcanzado el límite de atuendos guardados. ~g~(%s)",
    saved_new_outfit = "Guardaste un nuevo atuendo: ~b~%s~w~.",
    rename_outfit = "Tu atuendo ~b~%s~w~ ha sido renombrado a ~g~%s~w~.",
    delete_outfit = "Tu atuendo: ~b~%s~w~ ha sido eliminado.",
 
    torso = "Torso",
    props = "Accesorios",
    top = "Arriba",
    tops = "Tops",
    badge = "Insignia",
    pants = "Pantalones",
    pant = "Pantalon",
    shoes = "Zapatos",
    bags = "Bolsas",
    undershirt = "camiseta",
    neck = "cuello",
    bracelets = "pulseras",
    montres = "relojes",
    earrings = "pendientes",
    glasses = "gafas",
    hats = "sombreros",
    graphiques = "decoraciones",
 
    -- health
    inconscious = "Inconsciente",
    doing_something = "Haciendo algo",
    time_before_respawn = "Tiempo antes de reaparecer",
    you_died = "~r~Has muerto.",
    healing_wounds = "Curando heridas",
    already_doing_something = "~r~Ya estás haciendo algo.",
    you_have_been_healed = "~g~Has sido curado.",
    you_respawned = "~g~Reapareciste.",
 
    player_too_far_to_interact = "~r~El jugador con el que quieres interactuar está demasiado lejos de ti.",
    send_trade_invitation_to = "Enviaste una invitación para intercambiar a ~b~%s~w~.\n~b~Espera a que el otro jugador la acepte.",
    receive_invitation_from = "Recibiste una invitación para intercambiar de ~b~%s~w~.\n~b~Escribe ~w~/trade accept %s~b~ para comenzar el intercambio.",
 
    invalid_command_args = "Argumentos de comando no válidos: %s",
    start_trade_command_help = "Iniciar un intercambio con otro jugador",
    accept_trade_command_help = "Aceptar una invitación de intercambio",
    deny_trade_command_help = "Rechazar una invitación de intercambio",
    invalid_invitation = "La invitación no es válida o ya no existe",
    name_accepted_your_trade_invitation = "~b~%s~w~ aceptó su invitación de intercambio",
    you_accepted_trade_invitation_of_name = "Aceptaste la invitación de intercambio de %s",
    name_denied_your_trade_invitation = "~b~%s~w~ negó su invitación de intercambio",
    you_denied_trade_invitation_of_name = "Rechazó la invitación de intercambio %s",
    you_already_trading = "Ya estas intercambiando",
    other_already_trading = "El otro jugador esta intercambiando",
 
    other_player_not_enough_money = "~r~El intercambio falló. El otro jugador no tenía suficiente dinero.",
    you_player_not_enough_money = "~r~El intercambio falló. No tenías suficiente dinero.",
    other_player_not_enough_item = "~r~El intercambio falló. El otro jugador no tenía suficiente de algún ítem.",
    you_player_not_enough_item = "~r~El intercambio falló. No tenias suficiente de algún ítem.",
    success_trade = "~g~El intercambio ha sido confirmado.",
    fail_trade_other_player = "~r~El intercambio falló, el otro jugador se fue.",
    trade_other_full_item = "~r~El intercambio falló, el otro jugador no tiene suficiente almacenamiento.",
    trade_full_for_item = "~r~El intercambio falló, no tienes suficiente almacenamiento.",
 
    press_e_to_loot_inv = "Presiona ~INPUT_CONTEXT~ para saquear el inventario.",
    press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~Presiona ~INPUT_CONTEXT~ para interactuar con ~b~%s~HUD_COLOUR_NET_PLAYER27~.",
    press_e_to = "Presiona ~INPUT_CONTEXT~ para ~b~%s~w~.",
    press_e_to_open_catalog = "Presiona ~b~E~w~ para leer el ~g~catálogo~w~.",
    this_person = "esta persona",
    the_shop = "esta tienda",
    you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~No tiene permiso para hacer eso.",
 
    no_weapon = "~r~No tienes ningún arma equipada.",
    no_need_ammo = "~r~No necesitas usar munición con esta arma.",
    not_right_ammo = "~r~You are not using the right ammo, you need ~b~%s~w~.",
    you_used_ammo = "Cargaste tu ~b~%s~w~ con ~b~x%s~w~ de ~b~%s~w~.",
 
    choose_a_destination = "elige un ~b~destino",
    open_your_chest = "abre tu cofre",
    no_enough_money = "~r~No puedes pagar eso.",
    you_paid = "Pagaste ~g~$%s~w~ por ~b~%s~w~.",
    you_paid_basket = "Pagaste ~g~$%s~w~ por tu cesta.",
    you_sell_basket = "Recibiste ~g~$%s~w~ por vender ~b~x%s~w~ objeto(s).",
 
    you_repaired_your_vehicle = "~g~Reparaste tu vehículo.",
    repairing_your_vehicle = "Reparando tu vehículo",
    wheels_are_fine = "~r~Las ruedas del vehículo ya están bien.",
    changing_wheel = "Cambiando de rueda",
    you_repaired_the_wheels = "~g~Reparaste las ruedas del vehículo.",
 
    front_post_ls = "Parte delantera Los Santos",
    front_post_ls_2 = "Parte delantera Los Santos 2",
    front_post_bc = "Parte delantera Blaine County",
    front_post_bc_2 = "Parte delantera Blaine County 2",
    main_post_ls = "Ciudad Segura Los Santos",
    main_post_bc = "Ciudad Segura Blaine County",
    random_zone = "Zona aleatoria (landing)",
 
    this_item_is_equipped = "~r~Este elemento está equipado, elimínelo de tus atajos.",
    only_in_safezone = "~r~No puedes hacer eso fuera de una zona segura.",
    -- commerce stuff
    feature_gold_only = "Esta función es solo para ~y~Miembros oro~w~.",
    feature_diamond_only = "Esta función es solo para ~b~Miembros diamante~w~.",
    you_turned_into = "Te convertiste en un ~g~%s~w~.",
    wait_between_transformation = "~r~Espere un momento antes de usar el Modo Morph nuevamente.",
    wait_between = "~r~Espere un momento antes de volver a hacerlo.",
    available_morphs = "Morphs disponibles",
    animal_models = "Modelos animales",
    zombie_models = "Modelos zombies",
    success_update_name = "Cambiaste el nombre de tu personaje a ~b~%s~w~.",
    success_reset_stats = "~g~Reiniciaste con éxito tus estadísticas. (Las tablas de clasificación se actualizarán más tarde)",
 
    -- animals
    boar = "Jabalí",
    cat = "Gato",
    chop = "Rottweiler (Chop)",
    rottweiler = "Rottweiler",
    cow = "Vaca",
    coyote = "Coyote",
    deer = "Venado",
    hen = "Gallina",
    husky = "Husky",
    mtlion = "León",
    pig = "Cerdo",
    poodle = "Caniche",
    pug = "Pug",
    rabbit = "Conejo",
    rat = "Rata",
    retriever = "Labrador",
    shepherd = "Pastor",
    westy = "Westy",
 
    player_id = "ID del jugador",
    bounty = "Recompensa",
    reason = "Razon",
    id_player_not_found = "~r~Ningun jugador está vinculado a esta identificación.",
 
    ammo_dealer = "Distribuidor de munición",
    misc_dealer = "Tienda de equipos",
    veh_dealer = "Tienda de vehículos",
    custom_dealer = "LS Custom",
    gun_dealer = "Tienda de armas",
 
    bounty_created = "Pagaste ~g~$%s~w~ para crear un contrato de recompensa en ~b~%s~w~.",
    contract_success = "La recompensa que creaste en ~r~%s~w~ ha sido enviada a ~b~%s~w~.",
    a_contract_on_your_head = "~r~Tenías una recompensa por tu cabeza.Tu asesino recibió la recompensa.",
    reward_for_contract = "¡Cazarrecompensas! ~g~$%s~w~ por matar ~b~%s~w~.",
 
    hey_can_help_you = "Oye, ¿En qué puedo ayudarte?",
    i_want_to_buy_items = "Quiero comprar artículos",
    i_want_to_sell_items = "Quiero vender artículos",
 
    press_context_or_jump_to_get_up = "Presiona ~INPUT_CONTEXT~ o ~INPUT_JUMP~ para ~b~levantarse~w~.",
    server_restart_warning = "El servidor va a reiniciarse...",
    auto_restart_in = "Reinicio automático en %s segundos.",
 
    not_allowed_create_character = "No puedes crear un personaje nuevo.",
    character_not_yours = "Este personaje no es tuyo.",
    character_does_not_exist = "Este personaje no existe o ya no existe.",
    loading_character = "Cargando tu personaje...",
 
    playtime_is = "~b~Tu tiempo de juego en Extinction:\n~w~%s",
    dont_spam = "^1No hagas spam!",
 
    babygod_warning = "~b~Dejaste la zona segura, eres invencible por algún tiempo encuentra un lugar seguro!",
 
    -- LS Custom
    modifications_classiques = "Modificaciones clásicas",
    modifications_custom = "Modificaciones especiales",
    modifications_benny = "Modificaciones de Benny",
    paint = "Pintura",
    custom_your_car = "Personaliza tu coche",
    wheels_modifications = "Modificaciones de ruedas",
    performances = "Performances",
    neons = "Neoes",
    extra = "Extra",
    klaxon = "Claxon",
    teinte_fenetre = "Tinte de ventanas",
    phares_xenons = "Faros de Xenon",
    modele_plaque = "Modelo de placa",
    livery = "Librea",
    headlight_color = "Color de los faros",
    wheel_type = "Tipo de rueda",
    primary_wheel_type = "Tipo de rueda principal",
    back_wheel_type = "Tipo de rueda trasera",
    wheel_color = "Color de rueda",
    tire_smoke = "Humo de llantas",
    custom_color = "Color personalizado",
    custom_wheel = "Rueda personalizada",
    custom_back_wheel = "Rueda trasera personalizada",
    suspension = "Suspensión",
    transmission = "Transmisión",
    moteur = "Motor",
    frein = "Freno",
    turbo = "Turbo",
    primary_color = "Color primario",
    secondary_color = "Color secundario",
    interior_color = "Color interior",
    dashboard_color = "Color del tablero",
    color_effect = "Efecto de color",
    left_neon = "Neón izquierdo",
    right_neon = "Neón derecho",
    front_neon = "Neón frontal",
    back_neon = "Neón trasero",
 
    aileron = "Aleron",
    pc_front = "Parachoques delantero",
    pc_back = "Parachoques trasero",
    carroserie = "Faldón lateral",
    exhaust = "Escape",
    cadre = "Marco",
    calandre = "Rejilla",
    capot = "Capó",
    gb_left = "Guardabarros izquierdo",
    gb_right = "Guardabarros derecho",
    roof = "Techo",
    plate_support = "Portaplacas",
    front_plate = "Placa frontal",
    interior_style = "Estilo interior",
    figurine = "Figurilla",
    motif_dashboard = "Estilo del tablero",
    cadran = "Diseño de dial",
    haut_parleur_portes = "Puertas de altavoces",
    motif_sieges = "Estilo de asiento",
    volant = "Volante",
    levier = "Palancas de cambio",
    logo_custom = "Logo",
    ice = "HIELO",
    haut_parleur_coffre = "Puertas traseras de altavoz",
    hydrolique = "Hidráulica",
    moteur = "Motor",
    filtres_air = "Filtro de aire",
    entretoises = "Espaciadores",
    arc_couverture = "Arco",
    antenne = "Antena",
    motif_exterieur = "Estilo exterior",
    reservoir = "Tanque",
    window = "Ventana",
    style = "Estilo",
    default = "Predeterminado",
    type = "Tipo",
    normal = "Normal",
    black = "Negro",
    black_smoke = "Humo negro",
    simple_smoke = "Humo simple",
    stock = "Stock",
    limo = "Limusina",
    sa_black = "San Andreas negro",
    sa_blue = "San Andreas azul",
    sa_white = "San Andreas blanco",
    simple_white = "Blanco simple",
    ny_white = "North Yankton white",
    race = "Raza",
    sport = "Deporte",
    stock = "Stock",
    street = "Calle",
    discount = "Descuento",
    select_your_car = "Seleccione su coche",
    select_car_custom = "Seleccione el vehículo que desea personalizar. El número entre flechas es la clave del artículo.",
    loading_vehicle = "Creando vehículo",
    invalid_vehicle = "~r~Entidad de vehículo no válida.",
    invalid_vehicle_please_spawn = "~r~Elemento de vehículo no válido. Por favor, generelo una vez antes de intentar hacer algo.",
    free_take_and_validate = "Todo es libre. Toma lo que quieras y confirma!",
    car_custom_saved = "~g~Las modificaciones de tu coche han sido guardadas.",
 
    -- Character creation
    character_creation = "Creación de personajes",
    confirm = "confirmar",
    start_playing = "Empieza a jugar",
    appearance = "apariencia",
    character_list = "lista de personajes",
    face_features = "rasgos faciales",
    parents = "padres",
    parent = "padre",
    mix = "mezclar",
    skin = "piel",
    desc_mix = "Selecciona si la forma de tu rostro está más influenciada por tu padre / madre.",
    desc_skin = "Selecciona si tu piel está más influenciada por tu padre / madre.",
    identity = "identidad",
    player_name = "nombre del jugador",
    new_character = "nuevo personaje",
    warning_headblend = "~r~No seleccionaste pelos, cejas o barba.",
    warning_overlays = "~r~You have not selected hairs, eyebrows or beard.",
    warning_identity = "~r~Advertencia.~n~~w~Olvidaste llenar la pestaña de identidad.",
 
    -- kits
    kit_does_not_exist = "~r~Este kit no existe.",
    kit_needs_rank = "No tienes el ~r~%s~w~ rango.",
    wait_before_using_kit = "Porfavor espere ~r~%s~w~ antes de usar este kit.",
    received_kit = "Recibiste tu kit ~b~%s~w~.",
    no_kit = "No tienes ningún kit.",
 
    unable_to_find_booster = "No se pudo encontrar un potenciador con esta id.",
    wait_already_player_boost = "Por favor, espere un momento antes de usar este potenciador. Ya hay un potenciador de jugador activo.",
    wait_already_crew_boost = "Espere un momento antes de usar este potenciador. Ya hay un potenciador de tripulación activo..",
    wait_already_server_boost = "Espere un momento antes de usar este potenciador. Ya hay un potenciador de servidor activo.",
    booster_activated = "Potenciador activado durante ~g~%s minutos~w~! ~b~XP +%s%%",
    server_booster_activated = "~b~%s~w~ activó un potenciador del servidor durante ~g~%s minutos~z~! ~b~XP +%s%%",
    crew_booster_activated = "~b~%s~w~ activó un potenciador de tripulación durante ~g~%s minutos~z~! ~b~XP +%s%%",
    no_booster = "No tienes ningún potenciador.",
 
    rank_expired = "~r~Tu rol de colaborador expiró.",
    supporter_role = "~g~Rol de colaborador:~w~ %s",
    no_rank_warning = "No tienes ningún rol de colaborado.\n~r~Si compraste algo, vincula tu cuenta de fivem.",
    no_fivem_id = "Tu FiveM no está vinculado con el juego.\n~r~VVerifica que tienes una cuenta FiveM y que está vinculada al juego.",
    no_queue_warning = "No tienes ningún paquete en cola.\n~r~Espera un momento o prueba /getRank si estás buscando tu rango.",
    package_sync_success = "~g~YSus paquetes se han sincronizado correctamente, ¡disfrútelo!\n~w~Comandos útiles: /getRank, /booster",
 
    level_required = "Necesitas ser nivel %s.",
    rank_required = "Necesitas tener el rango %s rank.",
    level_required_2 = "~r~Necesitas ser nivel %s.",
 
    updated_deathmessage = "~g~Actualizaste tu mensaje de muerte.",
    updated_deatheffect = "~g~Actualizaste tu efecto de muerte.",
    use = "Usar",
    test = "Prueba",
 
    -- zombie
    you_bitten = "~r~Te han mordido.",
    infection_rate = "Tasa de infección: ~r~%s%%",
 
    -- ranks
    thug = "Matón",
    hustler = "Hustler",
    soldier = "Soldado",
    trigger = "Trigger",
    enforcer = "Enforcer",
    facilitator = "Facilitador",
    public_enemy = "Enemigo publico",
    shot_caller = "Llamador de tiro",
    street_boss = "Jefe de la calle",
    kingpin = "Kingpin",
    -- Tattoo
    tattoo = "tatuaje",
    tattoos = "tatuajes",
    torso = "torso",
    head = "cabeza",
    left_arm = "brazo izquierdo",
    right_arm = "brazo derecho",
    left_leg = "pierna izquierda",
    right_leg = "pierna derecha",
    unknown = "desconocido",
    other = "otro",
    remove_tattoo = "Eliminar todos los tatuajes",
    -- Hairdress
    haircuts = "Cortes de pelo",
    makeup = "Maquillaje",
    face = "Cara",
    eyebrows = "Cejas",
    facial_hair = "Vello facial",
    body_hair = "Vello corporal",
    barber_shop = "Peluquería",
    face_makeup = "Maquillaje facial",
    lipstick = "Lápiz labial",
    face_foundation = "Base de maquillaje facial",
    skin_blemishes = "Manchas de la piel",
    skin_ageing = "Envejecimiento de la piel",
    moles_freckles = "Lunares y pecas",
    sun_damage = "Daño en la piel",
    skin_complexion = "Complexión de la piel",
    body_blemishes = "Manchas corporales",
    body_blemishes_2 = "Manchas corporales 2",
    opacity = "Alfa",
    variations = "Variaciones",
    filter = "Filtro",
    eyes_color = "Color de ojos",
    -- Mask
    masks = "Máscaras",
    -- Items
    money = "Dinero",
    -- Ammo
    ["9mm"] = "9mm",
    ["300_mag"] = ".300 Magnum",
    ["7_62mm"] = "7.62mm",
    ["calibre_12"] = "Calibre 12",
    ["45_acp"] = ".45 ACP",
    ["5_56mm"] = "5.56mm",
    -- Food
    ["fish_1"] = "Lobina negra",
    ["fish_2"] = "RTrucha arcoiris",
    ["fish_3"] = "Kokanee",
    ["fish_4"] = "Tímalo ártico",
    ["fish_5"] = "Rock Bass",
    ["fish_6"] = "Lobina de boca chica",
    ["fish_7"] = "Pez espátula",
    ["fish_8"] = "Trucha toro",
    ["fish_9"] = "Trucha de lago",
    ["fish_10"] = "Chinook",
    ["fish_11"] = "Esturión pálido",
    ["fish_12"] = "Salmón",
 
    misc_meat = "Carne cruda",
    rabbit_meat = "Conejo crudo",
    lion_meat = "León crudo",
    rare_plume = "Pluma rara",
    dog_meat = "Perro crudo",
    cat_meat = "Gato crudo",
    rare_fish = "Pez raro",
 
    mask = "Máscara",
    malette = "Maleta",
    malette_metal = "Maleta de metal",
    ciseaux = "Tijeras",
    clean_kit = "Kit de limpieza",
    fishing_rod = "Caña de pescar",
    meuble = "Mobiliario",
    tissu = "Paño",
    accessory = "Accesorio",
    radio = "Radio",
    recyclor = "Reciclador",
    medkit = "Medkit",
    kevlar = "Kevlar",
    gps = "GPS",
    repair_tool = "Kit de reparación",
    jvn = "JVN",
    engine_veh = "Motor",
    wheel_veh = "Rueda",
    vetement = "Arriba",
    bloc_note = "Bloc de notas",
    paint_spray = "Pintura en aerosol",
    spike = "Tira de púas",
    paracetamol = "Paracetamol",
    bandage = "Vendaje",
    gaz_mask = "Máscara de gas",
    filter = "Filtro",
    tattoo_tool = "Herramienta de tatuaje",
    drug_med = "Droga",
    antizin = "Antizin",
 
    pickup_spikestrip = "recoge la tira de púas",
    you_dropped_spikestrip = "Dejaste caer una ~g~tira de púas~w~.",
    you_pickup_spikestrip = "Recogiste una ~g~tira de púas~w~.",
 
    you_have_been_killed_by = "Te ha matado ~r~%s",
    kill_notif = "~m~Muerto",
    you_killed = "Mataste a ~r~%s~w~",
    already_used_reset_only = "~r~Ya has reiniciado tu personaje.\n~w~Solo %s~w~ miembros pueden rehacer su personaje más de una vez.",
 
    hud_options = "Opciones de HUD",
    advanced_hud = "Mostrar HUD avanzado",
    players = "Jugadores",
    health = "Salud",
    player_menu = "Menú del jugador",
 
    you_are_now_zombie = "~r~Ahora eres un zombie.",
 
    my_weapons = "mis armas",
    customize_weapons = "personalizar mi arma",
    weapon_skin = "Tinte",
 
    -- camo
    skin_classic = "Predeterminado",
    skin_green = "Verde",
    skin_yellow = "Amarillo",
    skin_pink = "Rosa",
    skin_gold = "Oro",
    skin_blue = "Azul",
    skin_orange = "Naranj",
 
    -- new
    airdrop_coming = "~r~Se acerca un lanzamiento aéreo revisa tu mapa.",
    killed_by_cheater = "~r~Te ha matado un tramposo.\n~w~Lo baneamos y tu muerte ha sido cancelada.",
}
 
AddLanguage("es", my_language)
