local my_language = {
	give_vehicle = "شما اظافه کردید~b~%s~w~ داخل فهرست خود.",
	store_vehicle_command = "وسیله نقلیه ای را که در حال رانندگی آن هستید ذخیره کنید",
	no_entity_vehicle = "~r~وسیله نقلیه وجود ندارد یا از شما خیلی دور است.",
	no_entity_vehicle_id = "~r~وسیله نقلیه به هیچ شناسه ای متصل نیست ، شما نمی توانید آن را ذخیره کنید.",
	store_vehicle = "~b~شما ماشین خود را ذخیره کردید.",
	teleported_former_position = "~g~شما تلپورت شدید به اخرین موقعیت ذخیره شده خود.",
	not_enough_of = "~r~شما به اندازه کافی ندارید%s.",
	max_storage_chest = "~r~جعبه ذخیره سازی پر است.",
	cant_carry_more_items = "~r~فهرست شما نمی تواند موارد بیشتری را ذخیره کند(پر است).",
	put_item = "شما گذاشتید~g~x%s~w~ %s~w~.",
	take_item = "شما برداشتید~g~x%s~w~ %s~w~.",
	delete_item = "شما حذف کردید~r~x%s~w~ %s~w~.",
	you_equiped_item = "شما مجهز کردید~g~%s~w~.",
	bind_weapon_command = "میانبر برای اسلات اسلحه%s",
	kevlar_broke = "~r~نههه!~n~~w~زره شما شکست.",
	inventory_command = "تغییر موجودی",
	press_enter_to_join = "دکمه ~g~ENTER~w~ را فشار بدبد برای بازی کردن.",
	new_character = "شخصیت جدید",
	survivor = "بازمانده",
	right = "راست",
	left = "چپ",
	male = "مرد",
	female = "زن",
	ped = "پد",
	name = "اسم",
	sex = "جنسیت",
	title = "عتوان",
	select_this_character = "این شخصیت را انتخاب کنید",
	no_entity_zombie = "زامبی وجود ندارد یا خیلی از شما دور است.",
	you_found = "شما پیدا کردید ~g~%sx %s~w~.",
	you_found_nothing = "شما چیزی ~g~پیدا نکردید~w~.",
	press_e_to_loot = "دکمه ~b~[E]~w~ را نگه دارید برای گشتن ",
	full_for_item = "~r~فضای کافی برای این مورد وجود ندارد.",
	put_item_container = "شما گذاشتید ~g~x%s~w~ %s~w~ داخل فضای امن.",
	take_item_container = "شما برداشتیذ ~g~x%s~w~ %s~w~ از داخل فضای امن.",
	not_allowed_here = "~r~در اینجا مجاز به انجام این کار نیستید.",
	cant_store_moving_veh = "~r~شما نمی توانید وسیله نقلیه در حال حرکت را ذخیره کنید.",
	use_repair_tool = "از ابزار تعمیر استفاده کنید",
	please_get_closer = "~b~لطفاً نزدیکتر شوید ، هیچ موجودی در محدوده نیست.",
	you_cancel_action = "~r~شما اقدام را لغو کردید.",
	selected_target_message = "هدف انتخاب شده:~n~%s~n~~r~دکمه ~b~Y~r~ لغو~n~~r~دکمه ~g~X~r~ ادامه.",
	target_you = "~b~شما",
	target_screen = "~g~نمایش داده",
	take_this_path = "این راه را طی کنید",

	-- hud
	default_hud = "HUD پیش فرض",
	cinema_hud = "سینما HUD",
	no_hud = "بدون HUD",

	-- perms
	kick_member = "بیرون انداختن اعضا",
	invite_someone = "دعوت",
	edit_member = "ویرایش اعضا",
	edit_rank = "ویرایش رنک ها",
	create_rank = "ساخت رنک",
	delete_rank = "خذف رنکها",
	edit_structure = "ویرایش اعطلاعات گروه",
	edit_permissions = "ویرایش دسترسی ها",
	permission_level = "دادن مجوز",
	red_delete = "پاک کردن",
	rank = "رنک",
	red_kick = "حذف",
	crew_name = "اسم گروه",
	slogan = "عبارتی",
	information = "اطلاعات",
	boss_rank = "نام رنک رئیس",
	member_rank = "نام رنک تازه وارد",
	member = "اعضا",

	permissions_manager = "مدیریت دسترسی ها",
	members_manager = "مدیریت اعضا",
	ranks_manager = "مدیریت رنک ها",
	ranks_list = "لیست رنک ها",
	members_list = "لیست اعضا",
	create_a_rank = "ساخت رنک جدید",
	invite_someone = "دعوت کردن",
	stats = "آمار",
	total_ranks = "تعداد رتبه",
	total_members = "تعداد اعضا",
	level = "مرحله",
	actions = "اقدامات",
	crew_manager = "مدیر گروه",
	you_created_a_new_crew = "شما یک گروه جدید ساختیذ: %s",
	you_deleted_your_crew = "شما گروه خود را پاک کردید.",
	you_are_not_in_a_crew = "شما داخل گروه نیستید",
	you_joined_the_crew = "شما وارد گروه شدید '%s'",
	kick_failed = "حذف موفق نیود, به دلل: %s",
	already_in_crew = "شما در حال حاضر در یک گروه هستید",
	no_invitation = "شما هیچ دعوت نامه ای دریافت نکرده اید.",
	left_crew = "شما از گروه رفتید.",
	permission_updated = "مجوزهای <C>~g~%s</C>~w~ به روز شده اند.",
	incorrect_name = "~r~قالب نام نادرست است",
	incorrect_rank_perm = "~r~خطا\n~w~نام رتبه یا سطح اجازه نامعتبر است.",
	warn_rank_limit = "~r~شما به حد مجاز رسیده اید.",
	create_rank_success = "~g~موفقیت\n~w~شما رنک جدید ساختید <C>~b~%s</C>~w~ با سطح مجاز <C>~b~%s</C>~w~.",
	crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~شما نمیتوانید با عضوی که رنکش از شما بالاتر است تعامل داشته باشید.",
	you_sent_an_invitation = "شما دعوت نامه فرستادید برای <C>~g~%s</C>~w~ تا عضو گروه شود.",
	you_received_an_invitation = "شما دعوت نامه دریافت کردید برای عضو شدن در گروه.\n~b~/%s برای قبول کردن.",
	invitation_expired = "دعوتنامه منقضی شد",
	crew_kick_success = "شما انداختید بیرون <C>~b~%s</C>~w~ از داخل گروه.",
	first_rank_warning = "بالا ترین رنک 'پیش فرض' رنک.",

	you_updated_this = "شما به روز کردید %s برای ~g~<C>%s</C>~w~.",
	changes_saved_on = "تغییرات ایجاد شده در <C>~g~%s</C>~w~ ذخیره شد.",
	yes = "اره",
	no = "ته",
	none = "هیچ",
	character_id = "شناسه شخصیت",
	server_id = "شناسه سرور",
	report = "گزارش",
	rename = "تغییر نام",
	trade_with = "تجارت",

	please_wait_x_before = "~r~لطفا صبر کنید %s 1ثانیه قبل از انجام آن.",

	-- cloth
	take_outfit = "این لباس را بخرید",
	wardrobe_options = "گزینه های کمد لباس",
	wardrobe = "كمد لباس",
	manual_options = "گزینه های دستی",
	manual_mode = "حالت دستی",
	save_outfit = "این لباس را ذخیره کنید",
	variation = "تغییر",
	outfits = "لیاس ها",
	cloth_shop = "بیاس فروشی",
	ped_cloth_shop = "بیاس فروشی پد",
	manual_props = "لوازم جانبی دستی",
	manuel = "دستی",
	new_name = "نام جدید",
	outfit_name = "نام لباس",
	variations_saved = "~g~با موفقیت.~n~~w~تغییرات شخصیت شما ذخیره شده است.",
	equipped_new_outfit = "شما لباس جدید خود را مجهز کردید: ~b~%s",
	warning_limit_outfits = "شما به حداکثر لباسهای ذخیره شده رسیدید. ~g~(%s)",
	saved_new_outfit = "شما یک لباس جدید ذخیره کردید: ~b~%s~w~.",
	rename_outfit = "لباس شما ~b~%s~w~ تغییر نام داده است به ~g~%s~w~.",
	delete_outfit = "لباس شما: ~b~%s~w~ حذف شده است.",

	torso = "بدن",
	props = "لوازم جانبی",
	top = "بالا تنه",
	tops = "بالا تنه ها",
	badge = "نشان",
	pants = "شلوارها",
	pant = "شلوار",
	shoes = "کفش ها",
	bags = "کیف ها",
	undershirt = "زیر لباس",
	neck = "گردن",
	bracelets = "دستبند ",
	montres = "ساعت",
	earrings = "گوشواره",
	glasses = "عینک",
	hats = "کلاه",
	graphiques = "لوازم تزئینی",

	-- health
	inconscious = "بیهوش",
	doing_something = "انجام کاری",
	time_before_respawn = "زمان قبل از احیا",
	you_died = "~r~شما مردید.",
	healing_wounds = "التیام زخم ها",
	already_doing_something = "~r~شما در حال انجام کاری هستید.",
	you_have_been_healed = "~g~شما خوب شدید.",
	you_respawned = "~g~شما احیا شدید.",

	player_too_far_to_interact = "~r~بازیکنی که می خواهید با او تعامل داشته باشید خیلی از شما دور است.",
	send_trade_invitation_to = "شما دعوت نامه ای برای مبادله با آن ارسال کرده اید ~b~%s~w~.\n~b~منتظر باشید تا بازیکن دیگر آن را بپذیرد.",
	receive_invitation_from = "شما دعوت نامه ای برای مبادله از آن دریافت کردید ~b~%s~w~.\n~b~تایپ کنید ~w~/trade accept %s~b~ برای شروع تجارت.",

	invalid_command_args = "آرگومان های دستور نامعتبر است: %s",
	start_trade_command_help = "تجارت را با یک بازیکن دیگر شروع کنید",
	accept_trade_command_help = "دعوت نامه تجاری را بپذیرید",
	deny_trade_command_help = "دعوت نامه تجاری را رد کنید",
	invalid_invitation = "دعوت نامه نامعتبر است یا دیگر وجود ندارد",
	name_accepted_your_trade_invitation = "~b~%s~w~ دعوتنامه تجاری شما را پذیرفت",
	you_accepted_trade_invitation_of_name = "شما دعوت نامه تجارت را پذیرفتید %s",
	name_denied_your_trade_invitation = "~b~%s~w~ دعوت تجاری شما را رد کرد",
	you_denied_trade_invitation_of_name = "شما دعوت تجارت را رد کردید %s",
	you_already_trading = "شما در حال تجارت هستید",
	other_already_trading = "بازیکن دیگر در حال تجارت است",

	other_player_not_enough_money = "~r~تجارت شکست خورد. بازیکن دیگر پول کافی نداشت.",
	you_player_not_enough_money = "~r~تجارت شکست خورد. پول کافی نداشتید.",
	other_player_not_enough_item = "~r~تجارت شکست خورد. بازیکن دیگر به اندازه کافی مورد نداشت.",
	you_player_not_enough_item = "~r~تجارت شکست خورد. مقدارموردی به اندازه کافی ندارید.",
	success_trade = "~g~تجارت تأیید شده است.",
	fail_trade_other_player = "~r~تجارت شکست خورد, بازیکن دیگر رفت.",
	trade_other_full_item = "~r~تجارت انجام نشد ، بازیکن دیگر فضای ذخیره سازی کافی ندارد.",
	trade_full_for_item = "~r~تجارت انجام نشد ، فضای ذخیره سازی کافی ندارید.",

	press_e_to_loot_inv = "دکمه قشار دهید ~INPUT_CONTEXT~ تا موجود را غارت کنید.",
	press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~دکمه قشار دهید ~INPUT_CONTEXT~ برای تعامل با ~b~%s~HUD_COLOUR_NET_PLAYER27~.",
	press_e_to = "دکمه قشار دهید ~INPUT_CONTEXT~ یرای ~b~%s~w~.",
	press_e_to_open_catalog = "دکمه قشار دهید ~b~E~w~ برای خواندن ~g~catalog~w~.",
	this_person = "این فرد",
	the_shop = "این مغازه",
	you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~شما مجاز به انجام این کار نیستید.",

	no_weapon = "~r~شما هیچ سلاح مجهزی ندارید.",
	no_need_ammo = "~r~با این سلاح نیازی به استفاده از هیچ مهماتی ندارید.",
	not_right_ammo = "~r~شما از مهمات مناسب استفاده نمی کنید ، به این نیاز دارید ~b~%s~w~.",
	you_used_ammo = "شما برگذاری کردید ~b~%s~w~ با ~b~x%s~w~ of ~b~%s~w~.",

	choose_a_destination = "انتخاب کن ~b~مقصد مورد نظر را",
	open_your_chest = "جعبه خود را باز کنید",
	no_enough_money = "~r~شما توانایی پرداخت چنین هزینه ای را ندارید.",
	you_paid = "شما پرداخت کردید ~g~$%s~w~ برای ~b~%s~w~.",
	you_paid_basket = "شما پرداخت کردید ~g~$%s~w~ برای سبد شما.",
	you_sell_basket = "دریافت کردید ~g~$%s~w~ برای فروش ~b~x%s~w~ وسیله ها.",

	you_repaired_your_vehicle = "~g~شما وسیله نقلیه خود را تعمیر کردید.",
	repairing_your_vehicle = "وسیبه نقلیه خوذ را تعمیر کنید",
	wheels_are_fine = "~r~چرخ های خودرو از قبل خوب هستند.",
	changing_wheel = "تغییر چرخ",
	you_repaired_the_wheels = "~g~شما چرخ های وسیله نقلیه را تعمیر کردید.",

	front_post_ls = "پست جلو Los Santos",
	front_post_ls_2 = "پست جلو Los Santos 2",
	front_post_bc = "پست جلو Blaine County",
	front_post_bc_2 = "پست جلو Blaine County 2",
	main_post_ls = "شهر امن Los Santos",
	main_post_bc = "شهر امن Blaine County",
	random_zone = "منطقه تصادفی (فرود آمدن)",

	this_item_is_equipped = "~r~این مورد مجهز است ، آن را از میانبرهای خود حذف کنید.",
	only_in_safezone = "~r~نمی توانید این کار را در خارج از منطقه امن انجام دهید.",
	-- commerce stuff
	feature_gold_only = "این ویژگی فقط برای ~y~اعضای طلایی است~w~.",
	feature_diamond_only = "این ویژگی فقط برای ~b~برای اعضای دایمند است~w~.",
	you_turned_into = "شما تبدیل به یک ~g~%s~w~.",
	wait_between_transformation = "~r~لطفاً قبل از استفاده  میجدد از حالت تغییرشکل ، لحظه ای صبر کنید.",
	wait_between = "~r~لطفاً قبل از انجام دوباره آن لحظه ای صبر کنید.",
	available_morphs = "شکل های موجود",
	animal_models = "مدل های حیوانات",
	zombie_models = "مدل های زامبی",
	success_update_name = "شما نام شخصیت خود را تغییر دادید یه ~b~%s~w~.",
	success_reset_stats = "~g~شما با موفقیت آمار خود را تنظیم کردید. (رهبران بعداً به روز می شوند)",

	-- animals
	boar = "گراز",
	cat = "گربه",
	chop = "روتوایلر (سگ)",
	rottweiler = "روتوایلر",
	cow = "گاو",
	coyote = "گرگ صحرایی",
	deer = "گوزن",
	hen = "مرغ",
	husky = "هاسکی",
	mtlion = "شیر",
	pig = "خوک",
	poodle = "پودل",
	pug = "پاگ",
	rabbit = "خرگوش",
	rat = "موش",
	retriever = "رتریور",
	shepherd = "شپرد",
	westy = "وستی",

	player_id = "شناسه بازیکن",
	bounty = "جایزه",
	reason = "دلیل",
	id_player_not_found = "~r~هیچ بازیکنی به این شناسه متصل نیست.",

	ammo_dealer = "فروشنده مهمات",
	misc_dealer = "فروشگاه تجهیزات",
	veh_dealer = "فروشگاه وسایل نقلیه",
	custom_dealer = "LS سفارشی",
	gun_dealer = "اسلحه فروشی",

	bounty_created = "شما پرداخت کردید ~g~$%s~w~ برای ایجاد یک قرارداد فضل در ~b~%s~w~.",
	contract_success = "امتیازاتی که در آن ایجاد کردید ~r~%s~w~ ارسال شده است به ~b~%s~w~.",
	a_contract_on_your_head = "~r~برای سرت جایزه گذاشته شده است. قاتل شما جایزه را دریافت میکند.",
	reward_for_contract = "جایزه بگیر! جایزه گرفتی ~g~$%s~w~ برای کشتن ~b~%s~w~.",

	hey_can_help_you = "سلام ، چگونه می توانم به شما کمک کنم?",
	i_want_to_buy_items = "می خواهم وسایلی بخرم",
	i_want_to_sell_items = "می خواهم وسایلم را بفروشم",

	press_context_or_jump_to_get_up = "دکمه یزنید ~INPUT_CONTEXT~ یا ~INPUT_JUMP~ برای ~b~یرو بالا~w~.",
	server_restart_warning = "سرور در حال راه اندازی مجدد است..",
	auto_restart_in = "راه اندازی مجدد خودکار در %s ثانیه.",

	not_allowed_create_character = "شما مجاز به ایجاد یک شخصیت جدید نیستید.",
	character_not_yours = "این شخصیت از آن شما نیست.",
	character_does_not_exist = "این شخصیت وجود ندارد یا دیگر وجود ندارد.",
	loading_character = "بارگیری شخصیت شما...",

	playtime_is = "~b~زمان بازی شما در Extinction:\n~w~%s",
	dont_spam = "^1پشت سر هم تایپ نکنید!",

	babygod_warning = "~b~شما منطقه امن را ترک کردید ، برای مدتی شکست ناپذیر هستید یک مکان امن پیدا می کنید!",

	-- LS Custom
	modifications_classiques = "تغییرات کلاسیک",
	modifications_custom = "اصلاحات ویژه",
	modifications_benny = "تغییرات بنی",
	paint = "رنگ کردن",
	custom_your_car = "اتومبیل خود را سفارشی کنید",
	wheels_modifications = "اصلاح چرخ ها",
	performances = "اجراها",
	neons = "نئون ها",
	extra = "اضافی",
	klaxon = "بوغ",
	teinte_fenetre = "رنگ ششیه ها",
	phares_xenons = "Xenon چراغهای جلو",
	modele_plaque = "مدل صفحه",
	livery = "لیوری",
	headlight_color = "رنگ چراغهای جلو",
	wheel_type = "نوع چرخ",
	primary_wheel_type = "نوع چرخ اولیه",
	back_wheel_type = "نوع چرخ عقب",
	wheel_color = "رنگ چرخ",
	tire_smoke = "دود لاستیک",
	custom_color = "رنگ سفارشی",
	custom_wheel = "چرخ سفارشی",
	custom_back_wheel = "چرخ عقب سفارشی",
	suspension = "تعلیق",
	transmission = "ترنزمیشن",
	moteur = "موتور",
	frein = "ترمز",
	turbo = "توربو",
	primary_color = "رنگ اصلی",
	secondary_color = "رنگ ثانویه",
	interior_color = "رنگ داخلی",
	dashboard_color = "رنگ داشبورد",
	color_effect = "جلوه رنگ",
	left_neon = "نئون چپ",
	right_neon = "نئون راست",
	front_neon = "نئون جلو",
	back_neon = "نئون عقب",
	aileron = "اسپیلر",
	pc_front = "سپر جلو",
	pc_back = "سپرعقب",
	carroserie = "کتاره ها",
	exhaust = "اگزوز",
	cadre = "قاب",
	calandre = "جلو پنجره",
	capot = "کاپوت ماشین",
	gb_left = "گلگیر چپ",
	gb_right = "گلگیر راست",
	roof = "سقف",
	plate_support = "جا پلاک",
	front_plate = "پلاک جلو",
	interior_style = "سبک داخلی",
	figurine = "مجسمه",
	motif_dashboard = "سبک داشبورد",
	cadran = "طراحی شماره گیری",
	haut_parleur_portes = "درهای بلندگو",
	motif_sieges = "سبک صندلی",
	volant = "فرمان",
	levier = "ترک شیفت",
	logo_custom = "لوگو",
	ice = "یخ",
	haut_parleur_coffre = "در پشت بلندگو",
	hydrolique = "هیدرولیک",
	moteur = "موتور",
	filtres_air = "فیلتر هوا",
	entretoises = "فاصله ها",
	arc_couverture = "قوس",
	antenne = "آنتن",
	motif_exterieur = "سبک بیرونی",
	reservoir = "مخزن",
	window = "پنجره",
	style = "سبک",
	default = "پیشفرض",
	type = "توع",
	normal = "معمولی",
	black = "مشکی",
	black_smoke = "دود سیاه",
	simple_smoke = "دود معمولی",
	stock = "موجودی",
	limo = "لیموزین",
	sa_black = "San Andreas مشکی",
	sa_blue = "San Andreas آبی",
	sa_white = "San Andreas سفید",
	simple_white = "سفید ساده",
	ny_white = "North Yankton سفید",
	race = "مسابقه ای",
	sport = "اسپرت",
	stock = "موجودی",
	street = "خیابون",
	discount = "تخفیف",
	select_your_car = "ماشین خود را انتخاب کنید",
	select_car_custom = "وسیله نقلیه ای را که می خواهید سفارشی کنید انتخاب کنید. شماره بین پیکان ها کلید مورد نظر است.",
	loading_vehicle = "ایجاد وسیله نقلیه",
	invalid_vehicle = "~r~موجودیت وسیله نقلیه نامعتبر است.",
	invalid_vehicle_please_spawn = "~r~مورد وسیله نقلیه نامعتبر است. قبل از اینکه بخواهید کاری انجام دهید ، یک بار دیگر آن را ریسپان کنید.",
	free_take_and_validate = "همه چیز رایگان است آنچه می خواهید بگیرید و تأیید کنید!",
	car_custom_saved = "~g~تغییرات ماشین ذخیره شد.",

	-- Character creation
	character_creation = "شخصیت سازی",
	confirm = "تایید",
	start_playing = "شروع به بازی کنید",
	appearance = "ظاهر",
	character_list = "لیست کاراکترها",
	face_features = "ویژگی های چهره",
	parents = "والدین",
	parent = "والدین",
	mix = "مخلوط",
	skin = "پوست",
	desc_mix = "اگر شکل صورت شما بیشتر تحت تأثیر پدرتان است ، انتخاب کنید / مادر.",
	desc_skin = "اگر پوست شما بیشتر تحت تأثیر پدر قرار گرفته است ، انتخاب کنید / مادر.",
	identity = "هویت",
	player_name = "نام بازیکن",
	new_character = "شخصیت جدید",
	warning_headblend = "~r~شما والدین شخصیت خود را انتخاب نکرده اید.",
	warning_overlays = "~r~شما مو ، ابرو یا ریش را انتخاب نکرده اید.",
	warning_identity = "~r~هشدار.~n~~w~You فراموش کردید که برگه هویت را پر کنید.",

	-- kits
	kit_does_not_exist = "~r~این کیت وجود ندارد.",
	kit_needs_rank = "شما ندارید ~r~%s~w~ مرتبه.",
	wait_before_using_kit = "لطفا صبر کنید ~r~%s~w~ قبل از استفاده از این کیت.",
	received_kit = "کیت خود را تحویل گرفتید ~b~%s~w~.",
	no_kit = "شما هیچ کیتی ندارید.",

	unable_to_find_booster = "با این شناسه نمی توان یک تقویت کننده پیدا کرد.",
	wait_already_player_boost = "لطفاً قبل از استفاده از این تقویت کننده لحظه ای صبر کنید. در حال حاضر یک تقویت کننده پخش فعال است.",
	wait_already_crew_boost = "لطفاً قبل از استفاده از این تقویت کننده لحظه ای صبر کنید. در حال حاضر یک تقویت کننده خدمه فعال است.",
	wait_already_server_boost = "لطفاً قبل از استفاده از این تقویت کننده لحظه ای صبر کنید. در حال حاضر یک تقویت کننده سرور فعال است.",
	booster_activated = "تقویت کننده فعال شده است برای ~g~%s دقیقه~w~! ~b~XP +%s%%",
	server_booster_activated = "~b~%s~w~ تقویت کننده سرور فعال شده است برای ~g~%s دقیقه~z~! ~b~XP +%s%%",
	crew_booster_activated = "~b~%s~w~ تقویت کننده گروه فعال شده است برای ~g~%s دقیقه~z~! ~b~XP +%s%%",
	no_booster = "شما هیچ تقویت کننده ای ندارید.",

	rank_expired = "~r~نقش حامی شما منقضی شد.",
	supporter_role = "~g~نقش حامی:~w~ %s",
	no_rank_warning = "شما هیچ نقش حامی ندارید.\n~r~اگر چیزی خریداری کرده اید به حساب یوام خود پیوتد دهید.",
	no_fivem_id = "فایوام شما به بازی لینک نیست.\n~r~تأیید کنید که یک حساب FiveM دارید و این حساب به بازی مرتبط است.",
	no_queue_warning = "شما هیچ بسته ای در صف ندارید.\n~r~اگر به دنبال رتبه خود هستید لحظه ای صبر کنید یا /getRank را امتحان کنید.",
	package_sync_success = "~g~بسته های شما به درستی همگام سازی شده اند ، لذت ببرید!\n~w~دستورات مفید: /getRank, /booster",

	level_required = "سطح شما باید %s.",
	rank_required = "شما باید داشته باشید %s rank.",
	level_required_2 = "~r~سطح شما باید %s.",

	updated_deathmessage = "~g~پیام مرگ خود را به روز کردید.",
	updated_deatheffect = "~g~شما افکت کشتن خود را به روز کردید.",
	use = "استفاده",
	test = "تست",

	-- zombie
	you_bitten = "~r~شما گاز گرفته شده اید.",
	infection_rate = "میزان عفونت: ~r~%s%%",

	-- ranks
	thug = "اراذل",
	hustler = "هوستلر",
	soldier = "سرباز",
	trigger = "تریگر",
	enforcer = "مجری",
	facilitator = "تسهیل کننده",
	public_enemy = "دشمن عمومی",
	shot_caller = "خبرجین",
	street_boss = "رئیس خیابان",
	kingpin = "کینگ پین",
	-- Tattoo
	tattoo = "خال کوبی",
	tattoos = "خال کوبی ها",
	torso = "بالا تنه",
	head = "سر",
	left_arm = "دست چپ",
	right_arm = "دست راست",
	left_leg = "پای چپ",
	right_leg = "پای راست",
	unknown = "ناشناخته",
	other = "دیگر",
	remove_tattoo = "همه خال کوبی ها را بردارید",
	-- Hairdress
	haircuts = "کوتاهی مو",
	makeup = "آرایش",
	face = "صورت",
	eyebrows = "ابرو",
	facial_hair = "موی صورت",
	body_hair = "موی بدن",
	barber_shop = "آرایشگاه",
	face_makeup = "آرایش صورت",
	lipstick = "رژ لب",
	face_foundation = "زیرسازی صورت",
	skin_blemishes = "لکه های پوستی",
	skin_ageing = "پیری پوست",
	moles_freckles = "کک و مک",
	sun_damage = "آسیب به پوست",
	skin_complexion = "ظاهر پوست",
	body_blemishes = "لکه های بدن",
	body_blemishes_2 = "لکه های بدن 2",
	opacity = "آلفا",
	variations = "تغییرات",
	filter = "فیلتر",
	eyes_color = "رنگ چشم",
	-- Mask
	masks = "ماسک",
	-- Items
	money = "پول",
	-- Ammo
	["9mm"] = "9مم",
	["300_mag"] = ".300 Magnum",
	["7_62mm"] = "7.62مم",
	["calibre_12"] = "Calibre 12",
	["45_acp"] = ".45 ACP",
	["5_56mm"] = "5.56مم",
	-- Food
	["fish_1"] = "لارگموث باس",
	["fish_2"] = "رنگین کمان",
	["fish_3"] = "کوکانی",
	["fish_4"] = "خاکستری قطبی",
	["fish_5"] = "راک باس",
	["fish_6"] = "باس",
	["fish_7"] = "پارو ماهی",
	["fish_8"] = "ماهی قزل آلا",
	["fish_9"] = "قزل آلای دریاچه",
	["fish_10"] = "چینوک",
	["fish_11"] = "پالید",
	["fish_12"] = "سالمون",

	misc_meat = "گوشت خام",
	rabbit_meat = "خرگوش خام",
	lion_meat = "شیر خام",
	rare_plume = "پر نادر",
	dog_meat = "سگ خام",
	cat_meat = "گربه خام",
	rare_fish = "ماهی نادر",

	mask = "ماسک",
	malette = "چمدان",
	malette_metal = "چمدان فلزی",
	ciseaux = "قیچی",
	clean_kit = "کیت تمیز",
	fishing_rod = "قلاب ماهی گیری",
	meuble = "مبلمان",
	tissu = "پارچه",
	accessory = "لوازم جانبی",
	radio = "رادیو",
	recyclor = "بازیافت",
	medkit = "مدکیت",
	kevlar = "جلیقه",
	gps = "ردیاب",
	repair_tool = "کیت تعمییر",
	jvn = "چی وی ان",
	engine_veh = "موتور",
	wheel_veh = "چرخ",
	vetement = "بالا",
	bloc_note = "دفترچه یادداشت",
	paint_spray = "اسپری رنگ",
	spike = "نوار سنبله",
	paracetamol = "پاراستامول",
	bandage = "بانداژ",
	gaz_mask = "ماسک گاز",
	filter = "فیلتر",
	tattoo_tool = "ابزار تاتوl",
	drug_med = "دارو",
	antizin = "آنتی آنزین",

	pickup_spikestrip = "نوار سنبله را بردارید",
	you_dropped_spikestrip = "شما یک ~g~نوار سنبله انذاختید~w~.",
	you_pickup_spikestrip = "شما یک ~g~نوار سنبله انداختید~w~.",

	you_have_been_killed_by = "شما به قتل رسیدید توسط ~r~%s",
	kill_notif = "~m~کشته شده",
	you_killed = "شما کشتید ~r~%s~w~",
	already_used_reset_only = "~r~شما در حال حاضر شخصیت خود را تنظیم مجدد کرده اید.\n~w~فقط %s~w~ اعضا می توانند شخصیت خود را بیش از یک بار تکرار کنند.",

	hud_options = "HUD تنضیمات",
	advanced_hud = "نمایش پیشرفته HUD",
	players = "بازیکن ها",
	health = "سلامتی",
	player_menu = "منوی بازیکن",

	you_are_now_zombie = "~r~شما اکنون یک زامبی هستید.",

	my_weapons = "اسلحه های من",
	customize_weapons = "سلاح من را سفارشی کن",
	weapon_skin = "رنگ",

	-- camo
	skin_classic = "پیشفرض",
	skin_green = "سبز",
	skin_yellow = "زرد",
	skin_pink = "صورتی",
	skin_gold = "ظلایی",
	skin_blue = "ابی",
	skin_orange = "نارنجی",

	-- new
	airdrop_coming = "~r~ایر دراپ درحال امدن است نضشه خود را بررسی کنید.",
	killed_by_cheater = "~r~شما توسط یک متقلب کشته شده اید.\n~w~ما او را تحریم کردیم و مرگ شما لغو شده است.",
}

AddLanguage("fa", persian)
