local my_language = {
	give_vehicle = "Vous avez ajouté ~b~%s~w~ à votre inventaire",
	store_vehicle_command = "Ranger le véhicule que vous conduisez",
	no_entity_vehicle = "~r~Le véhicule est introuvable ou est trop loin de vous.",
	no_entity_vehicle_id = "~r~Le véhicule n'est lié à aucune ID, vous ne pouvez pas le ranger.",
	store_vehicle = "~b~Vous avez rangé votre véhicule.",
	teleported_former_position = "~g~Vous avez été replacé à votre ancienne position.",
	not_enough_of = "~r~Vous n'avez pas assez de %s.",
	max_storage_chest = "~r~Le coffre est plein.",
	cant_carry_more_items = "~r~Vous ne pouvez pas porter d'objets en plus.",
	put_item = "Vous avez déposé ~g~x%s~w~ %s~w~.",
	take_item = "Vous avez pris ~g~x%s~w~ %s~w~.",
	delete_item = "Vous avez supprimé ~r~x%s~w~ ~%s~~w~.",
	you_equiped_item = "Vous avez équipé votre ~g~%s~w~.",
	bind_weapon_command = "Raccourci pour le slot arme %s",
	kevlar_broke = "~r~AHH!~n~~w~Votre kevlar s'est brisé.",
	inventory_command = "Ouvrir/Fermer l'inventaire",
	press_enter_to_join = "Appuyez sur ~g~ENTRER~w~ pour commencer à jouer.",
	new_character = "Nouveau personnage",
	survivor = "Survivant",
	right = "Droite",
	left = "Gauche",
	male = "Homme",
	female = "Femme",
	ped = "Ped",
	name = "Nom",
	sex = "Sexe",
	title = "Titre",
	select_this_character = "Sélectionner ce personnage",
	no_entity_zombie = "Le zombie est introuvable ou est trop loin de vous.",
	you_found = "Vous avez trouvé ~g~%sx %s~w~.",
	you_found_nothing = "Vous n'avez ~g~rien trouvé~w~.",
	press_e_to_loot = "Appuie sur ~b~[E]~w~ pour fouiller",
	full_for_item = "Il n'y a pas assez de place pour cet item.",
	put_item_container = "Vous avez déposé ~g~x%s~w~ %s~w~ de votre conteneur.",
	take_item_container = "Vous avez pris ~g~x%s~w~ %s~w~ de votre conteneur.",
	not_allowed_here = "~r~Vous n'avez pas le droit de faire ça ici.",
	cant_store_moving_veh = "~r~Vous ne pouvez pas ranger un véhicule qui bouge.",
	use_repair_tool = "utiliser l'outil de réparation",
	please_get_closer = "~b~Rapprochez-vous, aucune entité autour.",
	you_cancel_action = "~r~Vous avez annulé l'interaction.",
	selected_target_message = "Cible séléctionnée:~n~%s~n~~r~Appuyer sur ~b~Y~r~ pour annuler~n~~r~Appuyer sur ~g~X~r~ pour valider.",
	target_you = "~b~VOUS",
	target_screen = "~g~Affichée sur votre écran",
	take_this_path = "prendre ce chemin",

	-- hud
	default_hud = "HUD par défaut",
	cinema_hud = "HUD cinéma",
	no_hud = "Pas de HUD",

	-- perms
	kick_member = "Exclure un membre",
	invite_someone = "Inviter quelqu'un",
	edit_member = "Editer un membre",
	edit_rank = "Editer un rang",
	create_rank = "Créer un rang",
	delete_rank = "Supprimer un rang",
	edit_structure = "Editer la structure",
	edit_permissions = "Editer les permissions",
	permission_level = "Niveau de permission",
	red_delete = "~HUD_COLOUR_REDLIGHT~Supprimer",
	rank = "Rang",
	red_kick = "~HUD_COLOUR_REDLIGHT~Exclure",
	crew_name = "Nom du crew",
	slogan = "Devise",
	information = "information",

	boss_rank = "Nom du rang chef",
	member_rank = "Nom du rang membre",
	member = "Membre",

	permissions_manager = "gestion des permissions",
	members_manager = "gestion des membres",
	ranks_manager = "gestion des rangs",
	ranks_list = "liste des rangs",
	members_list = "liste des membres",
	create_a_rank = "Créer un rang",
	invite_someone = "Recruter quelqu'un",
	stats = "Statistiques",
	total_ranks = "Total des rangs",
	total_members = "Total des membres",
	level = "Level",
	information = "information",
	actions = "actions",
	crew_manager = "gestion crew",
	you_created_a_new_crew = "Vous avez crée un nouveau crew: %s",
	you_deleted_your_crew = "Vous avez supprimé votre crew.",
	you_are_not_in_a_crew = "Vous n'êtes pas dans un crew.",
	you_joined_the_crew = "Vous avez rejoint un nouveau crew '%s'",
	kick_failed = "L'exclusion a échoué, raison: %s",
	already_in_crew = "Vous êtes déjà dans un crew.",
	no_invitation = "Vous n'avez reçu aucune invitation.",
	left_crew = "Vous avez quitté le crew.",
	permission_updated = "Les permissions de <C>~g~%s</C>~w~ ont été mises à jour.",
	incorrect_name = "~r~Le format du nom est incorrect.",
	incorrect_rank_perm = "~r~Incorrect\n~w~Le nom du grade ou le niveau de permission est incorrect.",
	warn_rank_limit = "~r~Vous avez atteint la limite de rangs.",
	create_rank_success = "~g~Validation\n~w~Vous avez créé un nouveau grade <C>~b~%s</C>~w~ avec un grant de <C>~b~%s</C>~w~.",
	crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~Vous ne pouvez pas modifier un membre qui dispose d'un niveau de permission supérieur au votre.",
	you_sent_an_invitation = "Vous avez envoyé une invitation à <C>~g~%s</C>~w~ pour rejoindre votre crew.",
	you_received_an_invitation = "Vous avez été invité à rejoindre un crew.\n~b~/%s pour accepter.",
	invitation_expired = "L'invitation a expiré.",
	crew_kick_success = "Vous avez exclu <C>~b~%s</C>~w~ de votre crew.",
	first_rank_warning = "Le premier rang sera toujours le rang par défaut.",

	you_updated_this = "Vous avez mis à jour %s pour ~g~<C>%s</C>~w~.",
	changes_saved_on = "Les changements effectués sur <C>~g~%s</C>~w~ ont été appliqués.",
	yes = "oui",
	no = "non",
	none = "Aucun",
	character_id = "ID personnage",
	report = "Signaler",
	rename = "Renommer",
	trade_with = "Troc",

	please_wait_x_before = "~r~Patientez %s secondes avant d'effectuer cette action.",

	-- cloth
	take_outfit = "Acheter cette tenue",
	wardrobe_options = "option garde robe",
	wardrobe = "garge robe",
	manual_options = "choix manuel",
	manual_mode = "mode manuel",
	save_outfit = "Sauvegarder cette tenue",
	variation = "variation",
	outfits = "tenues",
	cloth_shop = "magasin",
	ped_cloth_shop = "magasin ped",
	manual_props = "props manuel",
	manuel = "manuel",
	new_name = "Nouveau nom",
	outfit_name = "Nom de la tenue",
	variations_saved = "~g~Validé.~n~~w~Les variations de votre personnage ont été sauvegardées.",
	equipped_new_outfit = "Vous avez équippé votre nouvelle tenue: ~b~%s",
	warning_limit_outfits = "Vous avez atteint la limite de tenues sauvegardées. ~g~(%s)",
	saved_new_outfit = "Vous avez sauvegardée une nouvelle tenue: ~b~%s~w~.",
	rename_outfit = "Votre tenue ~b~%s~w~ a été renommée: ~g~%s~w~.",
	delete_outfit = "Votre tenue: ~b~%s~w~ a été supprimée.",

	torso = "Torse",
	props = "Accessoires",
	top = "Haut",
	tops = "Hauts",
	badge = "Badge",
	pants = "Pantalons",
	pant = "Pantalon",
	shoes = "Chaussures",
	bags = "Sacs",
	undershirt = "sous-haut",
	neck = "cou",
	bracelets = "bracelets",
	montres = "montres",
	earrings = "boucles oreilles",
	glasses = "lunettes",
	hats = "chapeaux",
	graphiques = "graphiques",

	-- health
	inconscious = "Inconscient",
	doing_something = "Action en cours",
	time_before_respawn = "Temps avant la ré-apparition",
	you_died = "~r~Vous avez été tué.",
	healing_wounds = "Soin de vos blessures",
	already_doing_something = "~r~Vous êtes déjà entrain de réaliser quelque chose.",
	you_have_been_healed = "~g~Vous avez été soigné.",
	you_respawned = "~g~Vous avez respawn.",

	press_e_to_loot_inv = "Appuyez sur ~INPUT_CONTEXT~ pour fouiller l'inventaire.",
	press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~Appuyez sur ~INPUT_CONTEXT~ pour intéragir avec ~b~%s~HUD_COLOUR_NET_PLAYER27~.",
	press_e_to = "~HUD_COLOUR_NET_PLAYER27~Appuyez sur ~INPUT_CONTEXT~ pour %s~HUD_COLOUR_NET_PLAYER27~.",
	press_e_to_open_catalog = "Appuyez sur ~b~E~w~ pour lire le ~g~catalogue~w~.",
	this_person = "cet individu",
	the_shop = "ce magasin",

	you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~Vous n'avez pas l'autorisation de faire cela.",

	no_weapon = "~r~Vous n'avez aucune arme équipée.",
	no_need_ammo = "~r~Vous n'avez pas besoin de munition pour cette arme.",
	not_right_ammo = "~r~Vous n'utilisez pas les bonnes munitions, vous avez besoin de ~b~%s~w~.",
	you_used_ammo = "Vous avez chargé votre ~b~%s~w~ avec ~b~x%s~w~ de ~b~%s~w~.",

	choose_a_destination = "choisir une ~b~destination",
	press_to_open_your_chest = "ouvrir le coffre",
	no_enough_money = "~r~Vous n'avez pas assez d'argent.",
	you_paid = "Vous avez payé ~g~$%s~w~ pour ~b~%s~w~.",
	you_paid_basket = "Vous avez payé ~g~$%s~w~ pour votre panier.",
	you_sell_basket = "Vous avez reçu ~g~$%s~w~ pour avoir vendu ~b~x%s~w~ objet(s).",

	you_repaired_your_vehicle = "~g~Vous avez terminé de réparer le véhicule.",
	repairing_your_vehicle = "Réparation en cours",
	wheels_are_fine = "~r~Les roues du véhicule sont déjà réparées.",
	changing_wheel = "Changement de la roue",
	you_repaired_the_wheels = "~g~Vous avez réparé les roues du véhicules.",

	front_post_ls = "Avant-poste Los Santos",
	front_post_ls_2 = "Avant-poste Los Santos 2",
	front_post_bc = "Avant-poste Blaine County",
	front_post_bc_2 = "Avant-poste Blaine County 2",
	main_post_ls = "Zone sécurisée Los Santos",
	main_post_bc = "Zone sécurisée Blaine County",
	random_zone = "Zone random (parachute)",

	this_item_is_equipped = "~r~Cet item est équipé, supprimez l'item de vos raccourcis.",
	only_in_safezone = "~g~Vous ne pouvez pas faire cela en dehors de la safe-zone.",
	-- Commerce
	feature_gold_only = "Cette fonctionnalité est réservée aux ~y~membres gold~w~.",
	feature_diamond_only = "Cette fonctionnalité est réservé aux ~b~membres diamond~w~.",
	you_turned_into = "Vous vous êtes transformé en ~g~%s~w~.",
	wait_between_transformation = "~r~Veuillez patienter un moment avant d'utiliser le MorphMod de nouveau.",
	wait_between = "~r~Veuillez patienter un moment avant de réaliser cette action.",
	available_morphs = "Transformations disponible",
	animal_models = "Models d'animaux",
	zombie_models = "Models de zombie",
	success_update_name = "Vous avez changé le nom de votre personnage pour ~b~%s~w~.",
	success_reset_stats = "~g~Vous avez réinitialisé vos statistiques. (Les classements seront mis à jour plus tard)",

	level_required = "Vous devez être level %s",
	rank_required = "Vous devez avoir le rang %s.",
	level_required_2 = "~r~Vous devez être level %s.",

	updated_deathmessage = "~g~Vous avez mis à jour votre message de mort.",
	updated_deatheffect = "~g~Vous avez mis à jour votre effet de kill.",
	use = "Utiliser",
	test = "Tester",

	-- kits
	kit_does_not_exist = "~r~Ce kit n'existe pas.",
	kit_needs_rank = "Vous devez avoir le rang ~r~%s~w~ pour ce kit.",
	wait_before_using_kit = "Veuillez patienter ~r~%s~w~ avant d'utiliser ce kit.",
	received_kit = "Vous avez reçu votre kit ~b~%s~w~.",
	no_kit = "Vous n'avez aucun kit.",

	unable_to_find_booster = "Impossible de trouver un booster avec cette id.",
	wait_already_player_boost = "Veuillez patienter avant d'utiliser votre booster. Il y a déjà un booster joueur actif.",
	wait_already_crew_boost = "Veuillez patienter avant d'utiliser votre booster. Il y a déjà un booster crew actif.",
	wait_already_server_boost = "Veuillez patienter avant d'utiliser votre booster. Il y a déjà un booster serveur actif.",
	booster_activated = "Booster activé pour ~g~%s minutes~w~! ~b~XP +%s%%",
	server_booster_activated = "~b~%s~w~ a activé un booster serveur pour ~g~%s minutes~z~! ~b~XP +%s%%",
	crew_booster_activated = "~b~%s~w~ a activé un booster de crew pour ~g~%s minutes~z~! ~b~XP +%s%%",
	no_booster = "Vous n'avez aucun booster.",
	
	rank_expired = "~r~Votre rang boutique a expiré.",
	supporter_role = "~g~Rang boutique:~w~ %s",
	no_rank_warning = "Vous n'avez aucun rôle boutique.\n~r~Si vous avez acheté quelque chose, liez votre compte FiveM au jeu.",
	no_fivem_id = "Votre compte FiveM n'est pas lié.\n~r~Vérifiez que vous avez un compte FiveM et qu'il est lié au jeu.",
	no_queue_warning = "Vous n'avez aucun package en attente.\n~r~Patientez un moment ou essayez /getRank si vous souhaitez avoir votre rang.",
	package_sync_success = "~g~Vos packages ont été synchronisés, enjoy!\n~w~Commandes utiles: /getRank, /booster",

	-- animals
	boar = "Sanglier",
	cat = "Chat",
	chop = "Rottweiler (Chop)",
	rottweiler = "Rottweiler",
	cow = "Vache",
	coyote = "Coyote",
	deer = "Biche",
	hen = "Poule",
	husky = "Husky",
	mtlion = "Lion",
	pig = "Cochon",
	poodle = "Poodle",
	pug = "Bulldog",
	rabbit = "Lapin",
	rat = "Rat",
	retriever = "Labrador",
	shepherd = "Chien",
	westy = "Caniche",

	player_id = "ID du joueur",
	bounty = "Prime",
	reason = "Raison",
	id_player_not_found = "~r~Aucune joueur n'est lié à cet id.",

	ammo_dealer = "Vendeur de munitions",
	misc_dealer = "Vendeur d'équipements",
	veh_dealer = "Vendeur de véhicules",
	custom_dealer = "LS Custom",
	gun_dealer = "Vendeur d'armes",

	bounty_created = "Vous avez payé ~g~$%s~w~ pour créer un contrat sur la tête de ~b~%s~w~.",
	contract_success = "La prime que vous avez déposé sur ~r~%s~w~ a été récupérée par ~b~%s~w~.",
	a_contract_on_your_head = "~r~Il y avait une prime sur votre tête. Votre tueur a reçu la prime.",
	reward_for_contract = "Chasseur de prime! Vous avez été récompensé de ~g~$%s~w~ pour la mort de ~b~%s~w~.",
	
	hey_can_help_you = "Hey, comment puis-je vous aider?",
	i_want_to_buy_items = "Je souhaite acheter des items",
	i_want_to_sell_items = "Je souhaite vendre des items",

	press_context_or_jump_to_get_up = "Appuyez sur ~INPUT_CONTEXT~ ou ~INPUT_JUMP~ pour ~b~vous relever~w~.",
	server_restart_warning = "Le serveur va redémarrer..",
	auto_restart_in = "Restart automatique du serveur dans %s secondes.",

	not_allowed_create_character = "Vous n'avez pas eu l'autorisation de créer un autre personnage.",
	character_not_yours = "Ce personnage ne vous appartient pas.",
	character_does_not_exist = "Ce personnage n'existe pas ou plus.",
	loading_character = "Changement du personnage en cours...",

	playtime_is = "~b~Votre temps de jeu sur Extinction:\n~w~%s",
	dont_spam = "^1Ne spammez pas!",

	babygod_warning = "~b~Vous avez quitté la zone sécurisée, vous êtes invincible pour un moment trouvez un lieu sûr!",

	-- Character creation
	character_creation = "Création de personnage",
	confirm = "confirmer",
	start_playing = "Commencer à jouer",
	appearance = "apparence",
	character_list = "liste des personnages",
	face_features = "traits du visage",
	parents = "parents",
	parent = "parent",
	mix = "ressemblance",
	skin = "peau",
	desc_mix = "Sélectionnez si la forme de votre visage est plus influencée par celle de votre père / mère.",
	desc_skin = "Sélectionnez si votre peau est plus influencée par celle de votre père / mère.",
	identity = "identité",
	player_name = "Nom du joueur",
	new_character = "nouveau personnage",
	warning_headblend = "~r~Vous n'avez pas renseigné l'héritage de votre personnage.",
	warning_overlays = "~r~Vous n'avez pas mis de sourcils/barbes/etc...",
	warning_identity = "~r~Attention.~n~~w~Vous n'avez pas correctement indiqué le nom RP de votre personnage.",

	-- zombie
	you_bitten = "~r~Vous avez été mordu.",
	infection_rate = "Taux d'infection: ~r~%s%",

	-- ranks
	thug = "Racaille",
	hustler = "Escroc",
	soldier = "Soldat",
	trigger = "Gâchette",
	enforcer = "Homme de main",
	facilitator = "Conseiller",
	public_enemy = "Ennemi public",
	shot_caller = "Gros bonnet",
	street_boss = "Gros caïd",
	kingpin = "Parrain",

	tattoo = "tatouage",
	tattoos = "tatouages",
	torso = "Torse",
	head = "Tête",
	left_arm = "Bras gauche",
	right_arm = "Bras droit",
	left_leg = "Jambe gauche",
	right_leg = "Jambe droite",
	unknown = "Inconnu",
	other = "Autre",
	remove_tattoo = "Enlever tous les tatouages",
	-- Hairdress
	haircuts = "Coiffures",
	makeup = "Maquillage",
	face = "Visage",
	eyebrows = "Sourcils",
	facial_hair = "Pilosité faciale",
	body_hair = "Pilosité torse",
	barber_shop = "Salon de coiffure",
	face_makeup = "Maquillage visage",
	lipstick = "Rouge à lèvres",
	face_foundation = "Fond de teint",
	skin_blemishes = "Problème de peau",
	skin_ageing = "Rides",
	moles_freckles = "Tâches et boutons",
	sun_damage = "Dégâts peau",
	skin_complexion = "Complexité de la peau",
	body_blemishes = "Tâche corps",
	body_blemishes_2 = "Tâche corps 2",
	opacity = "Opacité",
	variations = "Variations",
	filter = "Filtre",
	eyes_color = "Couleur des yeux",
	-- Mask
	masks = "Masques",
	-- Items
	money = "Argent",
	-- Ammo
	["9mm"] = "9mm",
	["300_mag"] = ".300 Magnum",
	["7_62mm"] = "7.62mm",
	["calibre_12"] = "Calibre 12",
	["45_acp"] = ".45 ACP",
	["5_56mm"] = "5.56mm",
	-- Food
	["fish_1"] = "Grande bouche",
	["fish_2"] = "Truie arc-en-ciel",
	["fish_3"] = "Kokanee",
	["fish_4"] = "Omble de l'arctique",
	["fish_5"] = "Perche rock",
	["fish_6"] = "Petite bouche",
	["fish_7"] = "Spatules",
	["fish_8"] = "Truite bull",
	["fish_9"] = "Truite de lac",
	["fish_10"] = "Chinook",
	["fish_11"] = "Esturgeon pâle",
	["fish_12"] = "Saumon",

	misc_meat = "Viande crue",
	rabbit_meat = "Lapin cru",
	lion_meat = "Lion cru",
	rare_plume = "Plume rare",
	dog_meat = "Chien cru",
	cat_meat = "Chat cru",
	rare_fish = "Poisson rare",

	mask = "Masque",
	malette = "Malette",
	malette_metal = "Malette en métal",
	outfit = "Tenue",
	ciseaux = "Ciseaux",
	clean_kit = "Kit de lavage",
	fishing_rod = "Canne à pêche",
	meuble = "Meuble",
	tissu = "Tissu",
	accessory = "Accessoire",
	radio = "Radio",
	recyclor = "Recycleur",
	medkit = "Trousse de soin",
	kevlar = "Kevlar",
	gps = "GPS",
	repair_tool = "Trousse à outils",
	jvn = "JVN",
	engine_veh = "Moteur",
	bag = "Sac",
	wheel_veh = "Roue de secours",
	vetement = "Vêtement",
	bloc_note = "Bloc-note",
	paint_spray = "Bombe de peinture",
	spike = "Herse",
	paracetamol = "Paracétamol",
	bandage = "Bandage",
	gaz_mask = "Masque à gaz",
	filter = "Filtre",
	tattoo_tool = "Outil tatouage",
	drug_med = "Médicament",
	antizin = "Antizin",

	pickup_spikestrip = "ramasser la herse",
	you_dropped_spikestrip = "Vous avez posé une ~g~herse~w~ au sol.",
	you_pickup_spikestrip = "Vous avez récupéré votre ~g~herse~w~ au sol.",

	you_have_been_killed_by = "Vous avez été tué par ~r~%s",
	kill_notif = "~m~Tué",
	you_killed = "Vous avez tué ~r~%s~w~",
	already_used_reset_only = "~r~Vous avez déjà réinitialisé votre personnage.\n~w~Seulement les membres %s~w~ peuvent refaire leur personnage plus d'une fois.",
	already_used_reset_only2 = "~r~Vous avez déjà fait cela.\n~w~Seulement les membres %s~w~ peuvent le faire plus d'une fois.",

	hud_options = "Options du HUD",
	advanced_hud = "Afficher le HUD avancé",
	players = "Joueurs",
	health = "Santé",
	player_menu = "Menu joueur",

	you_are_now_zombie = "~r~Vous êtes désormais un zombie.",

	my_weapons = "mes armes",
	customize_weapons = "customisation de mon arme",
	weapon_skin = "Camouflage",

	-- camo
	skin_classic = "Classique",
	skin_green = "Vert",
	skin_yellow = "Jaune",
	skin_pink = "Rose",
	skin_gold = "Or",
	skin_blue = "Bleu",
	skin_orange = "Orange",

	weapon_dagger = "Dague",

	-- new
	airdrop_coming = "~r~Un larguage est en chemin regardez votre map.",
	killed_by_cheater = "~r~Vous avez été tué par un cheater.\n~w~Nous l'avons banni et votre mort a été annulée.",

	corrupted_vehicle = "~r~Ce véhicule est corrompu et a été dupliqué par le passé, il a été supprimé de votre inventaire. Désolé si vous avez été arnaqué.",

	-- Discord
	join_discord_for_kit = "Rejoingez notre discord pour un kit gratuit!\n~g~discord.gg/gtalife",
	discord_account_not_linked = "~r~Vous devez lier votre compte discord avec FiveM.",
	discord_account_not_guild = "~r~Vous n'êtes pas sur notre serveur discord.\n~w~Rejoignez discord.gg/gtalife",

	already_done_recently = "~r~Réessayez plus tard, vous l'avez déjà fait aujourd'hui.",
	update_country = "Mettre à jour le pays",

	prestige_info = "~b~Vous avez atteint le niveau maximum.\n~w~Tapez /prestige pour avoir des infos sur le système de prestige.",
	prestige_not_max_level = "~r~Vous n'avez pas atteint le niveau maximum.",
	max_prestige_reached = "~r~Vous avez atteint le dernier prestige.",
	prestige_info_cmd = [[^3Système de prestige^7
Vous êtes actuellement prestige ^4%s^7 et niveau ^5%s^7.

Si vous atteignez le niveau maximum (%s), vous pouvez choisir d'obtenir un prestige et de recommencer votre progression XP pour revenir au niveau 0.
L'obtention d'un nouveau prestige vous donne un badge spécial et de nouveaux avantages comme du meilleur loot, des nouveaux items, plus d'argent ou un poids maximum d'inventaire plus élevé.
^2Si vous voulez obtenir un prestige et RECOMMENCER level 0 tapez ^1/setprestige^2
]],
	new_prestige = "Vous avez débloqué un nouveau prestige!\n~g~Vous êtes désormais prestige %s.",
	cant_store_event_veh = "~r~Vous ne pouvez pas ranger les véhicules spéciaux.",

	you_are_no_longer_in_combat = "🛡️ ~b~Vous n'êtes plus en combat.",
	you_are_in_combat_mode = "🛡️ ~b~Vous êtes en combat.\nSi vous déconnectez vous mourrez.",
	you_disconnected_in_combat = "💀 Vous avez déconnecté en combat, vous êtes mort.",

	not_enough_prestige_points = "~r~Vous n'avez pas suffisamment de point de prestige.",
	you_reached_max_prestige_stats_rank = "~r~Vous avez atteint le niveau maximum pour cette amélioration.",
	new_prestige_stats_upgrade = "Vous avez amélioré votre ~b~%s~w~\n~g~%s/%s",

	legendary_vehicle_pop = "~r~Un véhicule légendaire est apparu sur la carte.",

	-- poll one
	poll1_q1 = "Quel genre de serveur souhaiteriez-vous voir?",
	poll1_q2 = "Quelle mise à jour souhaiteriez-vous prioriser sur Extinction?",

	poll1_q1_a1 = "Battle Royale",
	poll1_q1_a2 = "Mission privée solo ou avec 1-4 amis (comme Payday / Heist / Hitman)",
	poll1_q1_a3 = "Course",
	poll1_q1_a4 = "Murder / Horreur",

	poll1_q2_a1 = "PvE améliorer les zombies/farm",
	poll1_q2_a2 = "Ajouter des évènements sur la map",
	poll1_q2_a3 = "Shop/Troc MAJ",
	poll1_q2_a4 = "Plus de stats RPG / améliorations",

	-- new
	combat_mode_container_disabled = "~r~Vous êtes en combat.\n~w~Vous ne pouvez pas ranger d'objet.",
	gcoins_wallet_updated = "~g~Vos GCoins ont été mis à jour.\n~w~+%s GCoins",
	not_enough_gcoins = "~r~Vous n'avez pas suffisamment de GCoins.",
	gcoins_something_went_wrong = "~r~Something went wrong.",
	you_bought_with_gcoins = "Vous avez acheté ~g~%s~w~ pour ~b~%s GCoins~w~.",
}

AddLanguage("fr", my_language)
