local my_language = {
    give_vehicle = "~b~%s~w~ 차량이 이벤토리에 추가되었습니다",
    store_vehicle_command = "차량을 멈추고 K 키를눌러 인벤토리에 넣으세요",
    no_entity_vehicle = "~r~차량이 존재하지 않거나 멀리 떨어져 있습니다..",
    no_entity_vehicle_id = "~r~차량은 어떤 ID에도 바인딩되어 있지 않으므로 저장할 수 없습니다.",
    store_vehicle = "~b~차량을 인벤토리에 넣었습니다.",
    teleported_former_position = "~g~최근에 저장된 위치로 순간 이동되었습니다.",
    not_enough_of = "~r~당신은 충분하지 않습니다 %s.",
    max_storage_chest = "~r~보관함이 가득 찼습니다.",
    cant_carry_more_items = "~r~인벤토리에 더 많은 아이템을 저장할 수 없습니다 (꽉참).",
    put_item = "아이템을획득했습니다. ~g~x%s~w~ %s~w~.",
    take_item = "아이템을줬습니다. ~g~x%s~w~ %s~w~.",
    delete_item = "아이템을 제거하였습니다. ~r~x%s~w~ %s~w~.",
    you_equiped_item = "장비를 장착했습니다. ~g~%s~w~.",
    bind_weapon_command = "무기 슬롯 단축키 %s",
    kevlar_broke = "~r~하하하!~n~~w~당신의방탄복이 파손됬습니다.",
    inventory_command = "인벤토리 전환",
    press_enter_to_join = "~g~ENTER~w~키를눌러 플레이하세요.",
    new_character = "캐릭터 생성",
    survivor = "유전자",
    right = "오른족",
    left = "왼쪽",
    male = "남자",
    female = "여자",
    ped = "기본NPC",
    name = "이름",
    sex = "성별",
    title = "제목",
    select_this_character = "이 캐릭터 선택",
    no_entity_zombie = "좀비가 존재하지 않거나 너무 멀리 떨어져 있습니다..",
    you_found = "찾았습니다 ~g~%sx %s~w~.",
    you_found_nothing = "못찾았습니다.~g~아무것도.~w~.",
    press_e_to_loot = "~b~[E]~w~키를눌러 주우세요",
    full_for_item = "~r~이 아이템을 위한 공간이 충분하지 않습니다.",
    put_item_container = "~g~x%s~w~ %s~w~ 안전보관함에 넣습니다.",
    take_item_container = "~g~x%s~w~ %s~w~ 안전보관함에서 꺼냅니다.",
    not_allowed_here = "~r~여기서는 할 수 없습니다.",
    cant_store_moving_veh = "~r~움직이는 차량은 보관할 수 없습니다.",
    use_repair_tool = "수리 도구 사용",
    please_get_closer = "~b~가까이 다가 가세요, 범위 안에 없습니다.",
    you_cancel_action = "~r~행동을 취소했습니다..",
    selected_target_message = "선택한 대상:~n~%s~n~~r~누르세요 ~b~Y~r~취소하려면~n~~r~누르세요~g~X~r~계속하려면",
    target_you = "~b~당신",
    target_screen = "~g~표시",
    take_this_path = "이 길을 택하세요.",
 
    -- hud
    default_hud = "기본 HUD",
    cinema_hud = "영화모드 HUD",
    no_hud = "HUD 없음",
 
    -- perms
    kick_member = "멤버 강퇴",
    invite_someone = "멤버 초대",
    edit_member = "멤버 수정",
    edit_rank = "랭크 수정",
    create_rank = "랭크 생성",
    delete_rank = "랭크 제거",
    edit_structure = "크루 설명 수정",
    edit_permissions = "권한 수정",
    permission_level = "권한 부여",
    red_delete = "삭제",
    rank = "랭크",
    red_kick = "킥",
    crew_name = "크루 이름",
    slogan = "Catchphrase",
    information = "정보",
    boss_rank = "보스 랭크 이름",
    member_rank = "뉴비 랭크 이름",
    member = "멤버",
 
    permissions_manager = "권한 관리자",
    members_manager = "회원 관리자",
    ranks_manager = "계급 관리자",
    ranks_list = "순위 목록",
    members_list = "회원 목록",
    create_a_rank = "계급을 만들다",
    invite_someone = "누군가를 초대하다",
    stats = "통계",
    total_ranks = "순위표시",
    total_members = "멤버표시",
    level = "레벨",
    actions = "행동",
    crew_manager = "멤버 관리자",
    you_created_a_new_crew = "새로운 크루를 만들었습니다.: %s",
    you_deleted_your_crew = "크루를 삭제했습니다.",
    you_are_not_in_a_crew = "당신은 크루원이 아닙니다",
    you_joined_the_crew = "새로운 크루에 합류했습니다. '%s'",
    kick_failed = "크루 강퇴실패 사유: %s",
    already_in_crew = "당신은 이미 크루원입니다",
    no_invitation = "초대장을받지 못했습니다.",
    left_crew = "크루를 떠났습니다.",
    permission_updated = "<C>~g~의%s</C>~w~권한이 업데이트됬습니다..",
    incorrect_name = "~r~이름 형식이 올바르지 않습니다.",
    incorrect_rank_perm = "~r~에러\n~w~순위 이름 또는 권한 수준이 잘못되었습니다..",
    warn_rank_limit = "~r~등급 제한에 도달했습니다..",
    create_rank_success = "~g~성공\n~w~새 순위를 만들었습니다. <C>~b~%s</C>~w~권한 수준으로<C>~b~%s</C>~w~.",
    crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~자신보다 높은 권한 수준을 가진 구성원과 상호 작용할 수 없습니다..",
    you_sent_an_invitation = "<C>~g~을%s</C>~w~ 크루원에 합류하도록 초대장을 보냈습니다..",
    you_received_an_invitation = "크루원 가입 초대를 받았습니다..\n~b~/%s 수락하세요",
    invitation_expired = "초대가 만료되었습니다.",
    crew_kick_success = "<C>~b~를%s</C>~w~ 크루원에게서 강퇴하엿습니다.",
    first_rank_warning = "첫 번째 순위는 '기본'순위입니다.",
 
    you_updated_this = "다음으로 업데이트했습니다. %s 을 ~g~<C>%s</C>~w~.",
    changes_saved_on = "변경 사항 <C>~g~%s</C>~w~ 저장되었습니다.",
    yes = "네",
    no = "아니요",
    none = "없음",
    character_id = "캐릭터 아이디",
    server_id = "서버 아이디",
    report = "신고",
    rename = "이름수정",
    trade_with = "거래",
    
    please_wait_x_before = "~r~이 행동을하기전에 %s 초를 기다리세요.",
 
    -- cloth
    take_outfit = "이 의상 구매",
    wardrobe_options = "옷장 옵션",
    wardrobe = "옷장",
    manual_options = "수동 옵션",
    manual_mode = "수동 모드",
    save_outfit = "복장 저장",
    variation = "변화",
    outfits = "의상",
    cloth_shop = "옷가게",
    ped_cloth_shop = "NPC 스킨",
    manual_props = "수동 소품",
    manuel = "수동",
    new_name = "새로운이름",
    outfit_name = "옷 이름",
    variations_saved = "~g~성공~n~~w~캐릭터 옷이 저장되었습니다.",
    equipped_new_outfit = "새 옷을 입혔습니다.: ~b~%s",
    warning_limit_outfits = "저장된 의상 한도에 도달했습니다.. ~g~(%s)",
    saved_new_outfit = "새 옷을 저장했습니다: ~b~%s~w~.",
    rename_outfit = "당신의 의상 ~b~%s~w~ 이름이 변경되었습니다 to ~g~%s~w~.",
    delete_outfit = "당신의 의상: ~b~%s~w~ 삭제되었습니다.",
 
    torso = "몸통",
    props = "소품",
    top = "상의",
    tops = "상의들",
    badge = "뱃지",
    pants = "바지들",
    pant = "바지",
    shoes = "신발",
    bags = "가방",
    undershirt = "안쪽상의",
    neck = "목",
    bracelets = "팔찌",
    montres = "시계",
    earrings = "귀걸이",
    glasses = "안경",
    hats = "모자",
    graphiques = "장식물",
 
    -- health
    inconscious = "무의식",
    doing_something = "하고 있는중",
    time_before_respawn = "리스폰 전 시간",
    you_died = "~r~사망하였습니다.",
    healing_wounds = "상처 치유",
    already_doing_something = "~r~당신은 이미 뭔가를하고 있습니다.",
    you_have_been_healed = "~g~당신은 치유되었습니다.",
    you_respawned = "~g~당신은 부활했습니다.",
 
    player_too_far_to_interact = "~r~상호 작용하려는 플레이어가 너무 멀리 있습니다..",
    send_trade_invitation_to = "교환 초대를 보냈습니다. ~b~%s~w~.\n~b~다른 플레이어가 수락 할 때까지 기다립니다..",
    receive_invitation_from = "교환 초대를 받았습니다. ~b~%s~w~.\n~b~Type ~w~/trade accept %s~b~를 채팅으로 치신후 거래를하세요.",
 
    invalid_command_args = "잘못된 명령어: %s",
    start_trade_command_help = "다른 플레이어와 거래 시작",
    accept_trade_command_help = "거래 초대 수락",
    deny_trade_command_help = "거래 초대 거부",
    invalid_invitation = "초대가 유효하지 않거나 더 이상 존재하지 않습니다.",
    name_accepted_your_trade_invitation = "~b~%s~w~ 거래 초대를 수락했습니다",
    you_accepted_trade_invitation_of_name = "거래 초대를 수락했습니다. %s",
    name_denied_your_trade_invitation = "~b~%s~w~ 거래초대를 거부했습니다",
    you_denied_trade_invitation_of_name = "거래 초대를 거부했습니다. %s",
    you_already_trading = "당신은 이미 거래하고 있습니다",
    other_already_trading = "다른 플레이어는 이미 거래 중입니다.",
 
    other_player_not_enough_money = "~r~거래가 실패했습니다. 다른 플레이어는 돈이 충분하지 않았습니다..",
    you_player_not_enough_money = "~r~거래가 실패했습니다. 돈이 충분하지 않았습니다.",
    other_player_not_enough_item = "~r~거래가 실패했습니다. 다른 플레이어는 일부 항목이 충분하지 않았습니다..",
    you_player_not_enough_item = "~r~거래가 실패했습니다. 일부 항목이 충분하지 않았습니다.",
    success_trade = "~g~거래가 확인되었습니다.",
    fail_trade_other_player = "~r~거래는 실패했고 다른 플레이어는 떠났습니다.",
    trade_other_full_item = "~r~거래 실패, 다른 플레이어의 저장 공간 부족.",
    trade_full_for_item = "~r~거래가 실패했습니다. 저장 공간이 충분하지 않습니다..",
 
    press_e_to_loot_inv = "~INPUT_CONTEXT~ 키를 눌러 인벤토리를 여세요",
    press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~키를눌러 ~INPUT_CONTEXT~ 상호 작용하세요 ~b~%s~HUD_COLOUR_NET_PLAYER27~.",
    press_e_to = "~INPUT_CONTEXT~ 키를누르세요~b~%s~w~.",
    press_e_to_open_catalog = "~b~E~w~ 키를눌러이용하세요 ~g~옷가게~w~.",
    this_person = "사람",
    the_shop = "상점",
    you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~당신은 그렇게 할 수 없습니다.",
 
    no_weapon = "~r~장비 한 무기가 없습니다.",
    no_need_ammo = "~r~이 무기에는 탄약을 사용할 필요가 없습니다..",
    not_right_ammo = "~r~올바른 탄약을 사용하고 있지 않습니다. ~b~%s~w~.",
    you_used_ammo = "장전하였습니다. ~b~%s~w~ 를 ~b~x%s~w~ 함께 ~b~%s~w~.",
 
    choose_a_destination = "~b~목적지~w~를 설정하세요",
    open_your_chest = "인벤토를 여세요",
    no_enough_money = "~r~당신은 그것을 감당할 수 없습니다.",
    you_paid = "You paid ~g~$%s~w~ for ~b~%s~w~.",
    you_paid_basket = "지불하셨습니다.~g~$%s~w~ 장바구니에 담긴.",
    you_sell_basket = "받앗습니다. ~g~$%s~w~ 판매한 ~b~x%s~w~ 아이템.",
 
    you_repaired_your_vehicle = "~g~차량을 수리했습니다.",
    repairing_your_vehicle = "차량 수리",
    wheels_are_fine = "~r~차량 바퀴는 이미 괜찮아.",
    changing_wheel = "휠 변경",
    you_repaired_the_wheels = "~g~차량의 바퀴를 수리했습니다.",
 
    front_post_ls = "로스산토스 시티1",
    front_post_ls_2 = "로스산토스 시티 2",
    front_post_bc = "블레인카운티 시티1",
    front_post_bc_2 = "블레인카운티 시티 2",
    main_post_ls = "세이프시티 로스산토스",
    main_post_bc = "세이프시티 블레인카운티",
    random_zone = "랜덤 존 (착륙)",
 
    this_item_is_equipped = "~r~이 항목은 장착되어 있습니다. 바로 가기에서 제거하십시오..",
    only_in_safezone = "~r~안전 지대 밖에서는 그렇게 할 수 없습니다.",
    -- commerce stuff
    feature_gold_only = "이기능은 ~y~골드멤버~w~전용입니다..",
    feature_diamond_only = "이기닝은 ~b~다이아몬드 멤버~w~전용입니다..",
    you_turned_into = "바뀌었습니다. ~g~%s~w~.",
    wait_between_transformation = "~r~모프 모드를 다시 사용하기 전에 잠시 기다려주십시오.",
    wait_between = "~r~다시하기 전에 잠시 기다려주십시오.",
    available_morphs = "사용 가능한 변경해",
    animal_models = "동물 모델",
    zombie_models = "좀비 모델",
    success_update_name = "캐릭터 이름을 다음과 같이 변경했습니다. ~b~%s~w~.",
    success_reset_stats = "~g~통계를 성공적으로 재설정했습니다. (리더 보드는 추후 업데이트 될 예정입니다.)",
 
    -- animals
     boar = "멧돼지",
     cat = "고양이",
     chop = "로트와일러 (촙)",
     rottweiler = "로트와일러",
     cow = "소",
     coyote = "코요테",
     deer = "사슴",
     hen = "닭",
     husky = "허스키",
     mtlion = "사자",
     pig = "돼지",
     poodle = "푸들",
     pug = "퍼그",
     rabbit = "토끼",
     rat = "쥐",
     retriever = "리트리버",
     shepherd = "양치기",
     westy = "삽살개",
 
    player_id = "플레이어의 ID",
    bounty = "현상금",
    reason = "사유",
    id_player_not_found = "~r~이 ID에 연결된 플레이어가 없습니다..",
 
    ammo_dealer = "총알 상점",
    misc_dealer = "장비 상점",
    veh_dealer = "차량 상점",
    custom_dealer = "LS Custom(튜닝샵)",
    gun_dealer = "총기 상점",
 
    bounty_created = "금액을지불하여 ~g~$%s~w~ 바운티 계약을 생성했습니다. ~b~%s~w~.",
    contract_success = "생성 한 현상금 ~r~%s~w~ 로 보냈습니다 ~b~%s~w~.",
    a_contract_on_your_head = "~r~당신은 당신의 머리에 현상금을 가졌습니다. 범인이 현상금을 받았습니다.",
    reward_for_contract = "현상금 사냥꾼! 살인에 대해 ~g~$%s~w~ 보상을받았습니다. ~b~%s~w~.",
 
    hey_can_help_you = "어떻게 도와 드릴까요?",
    i_want_to_buy_items = "아이템을 사고 싶다",
    i_want_to_sell_items = "아이템을 판매하고 싶다",
 
    press_context_or_jump_to_get_up = "~INPUT_CONTEXT~ 키를눌러 ~INPUT_JUMP~ ~b~일어나세요~w~.",
    server_restart_warning = "서버가 다시 시작됩니다..",
    auto_restart_in = "자동서버재시작까지 %s 초.",
 
    not_allowed_create_character = "새 캐릭터를 만들 수 없습니다..",
    character_not_yours = "이 캐릭터는 당신 것이 아닙니다.",
    character_does_not_exist = "이 캐릭터는 존재하지 않거나 더 이상 존재하지 않습니다..",
    loading_character = "당신의 캐릭터 로딩중...",
 
    playtime_is = "~b~Extinction 에서의 플레이 시간:\n~w~%s",
    dont_spam = "^1스팸하지 마십시오!",
 
    babygod_warning = "~b~당신은 안전 지대를 떠났습니다, 잠시동안 무적이작용되니 안전한곳을 찾아떠나세요",
 
    -- Customs
    modifications_classiques = "일반 튜닝",
    modifications_custom = "퍼포먼스 튜닝",
    modifications_benny = "베니스 커스텀튜닝",
    paint = "차량색상",
    custom_your_car = "차량튜닝",
    wheels_modifications = "휠 개조",
    performances = "엔진성능개조",
    neons = "네온",
    extra = "기타장치",
    klaxon = "경적소리",
    teinte_fenetre = "창문 선팅",
    phares_xenons = "제논 헤드라이트",
    modele_plaque = "번호판",
    livery = "차량스킨",
    headlight_color = "헤드라이트 색상",
    wheel_type = "휠 타입",
    primary_wheel_type = "앞바퀴 휠타입",
    back_wheel_type = "뒷바퀴 휠타입",
    wheel_color = "휠 색상",
    tire_smoke = "타이어 연기",
    custom_color = "커스텀 컬러",
    custom_wheel = "커스텀 휠",
    custom_back_wheel = "커스텀 뒤쪽 휠",
    suspension = "서스펜션",
    transmission = "트랜스 미션",
    moteur = "엔진",
    frein = "브레이크",
    turbo = "터보",
    primary_color = "첫번쨰 색상",
    secondary_color = "두번쨰 색상",
    interior_color = "인테리어 색상",
    dashboard_color = "대쉬보드 색상",
    color_effect = "컬러 효과",
    left_neon = "왼쪽 네온",
    right_neon = "오른쪽 네온",
    front_neon = "앞쪽 네온",
    back_neon = "뒤쪽 네온",
 
    aileron = "스포일러",
    pc_front = "앞 범퍼",
    pc_back = "뒷 범퍼",
    carroserie = "사이드 스커트",
    exhaust = "배기구",
    cadre = "차대(프레임)",
    calandre = "그릴",
    capot = "후드",
    gb_left = "왼쪽 휀다",
    gb_right = "오른쪽 휀다",
    roof = "지붕",
    plate_support = "번호판 거치대",
    front_plate = "앞 번호판",
    interior_style = "인테리어 스타일",
    figurine = "장식품",
    motif_dashboard = "대시보드 스타일",
    cadran = "다이얼 디자인",
    haut_parleur_portes = "앞문 스피커 튜닝",
    motif_sieges = "시트 스타일",
    volant = "핸들",
    levier = "기어 손잡이",
    logo_custom = "로고",
    ice = "아이스",
    haut_parleur_coffre = "뒷문 스피커튜닝",
    hydrolique = "에어서스펜션",
    moteur = "엔진",
    filtres_air = "에어필터",
    entretoises = "스페이서",
    arc_couverture = "아치",
    antenne = "안테나",
    motif_exterieur = "외장 스타일",
    reservoir = "기름탱크",
    window = "창문",
    style = "스타일",
    default = "기본",
    type = "타입",
    normal = "노말",
    black = "블랙",
    black_smoke = "블랙 스모크",
    simple_smoke = "심플 스모크",
    stock = "순전",
    limo = "진한선팅",
    sa_black = "산 안드레스 블랙",
    sa_blue = "산 안드레스 블루",
    sa_white = "산 안드레스 화이트",
    simple_white = "심플 화이트",
    ny_white = "노스 양크턴 화이트",
    race = "레이싱",
    sport = "스포츠",
    stock = "순정",
    street = "스트릿",
    discount = "할인",
    select_your_car = "차량을선택하세요",
    select_car_custom = "원하는 차량을 선택하세요. 방향키로 선택",
    loading_vehicle = "차량 생성중",
    invalid_vehicle = "~r~잘못된 차량 입니다.",
    invalid_vehicle_please_spawn = "~r~차량 항목이 잘못되었습니다. 무엇이든하기 전에 한 번 생성하십시오.",
    free_take_and_validate = "모든 것이 무료입니다. 원하는 것을 취하고 확인하십시오!",
    car_custom_saved = "~g~자동차 수정 사항이 저장되었습니다.",
 
    -- Character creation
    character_creation = "캐릭터 생성",
    confirm = "확인",
    start_playing = "플레이 시작",
    appearance = "외관",
    character_list = "캐릭터 목록",
    face_features = "얼굴 특징",
    parents = "부모님",
    parent = "부모",
    mix = "믹스",
    skin = "스킨",
    desc_mix = "얼굴 모양이 아버지 / 어머니의 영향을 더 많이받는 경우 선택하세요..",
    desc_skin = "피부가 아버지 / 어머니의 영향을 더 많이 받는지 선택하십시오..",
    identity = "정체",
    player_name = "플레이할닉네임",
    new_character = "새 캐릭터",
    warning_headblend = "~r~캐릭터의 부모를 선택하지 않았습니다..",
    warning_overlays = "~r~머리카락, 눈썹 또는 수염을 선택하지 않았습니다..",
    warning_identity = "~r~경고!.~n~~w~ID 탭을 채우는 것을 잊었습니다..",
 
    -- kits
    kit_does_not_exist = "~r~이 키트는 존재하지 않습니다.",
    kit_needs_rank = "랭크가 부족합니다. ~r~%s~w~ 랭크.",
    wait_before_using_kit = "이 키트를 사용하기전에 잠시만 기다리세요 ~r~%s~w~ ",
    received_kit = "키트를 받았습니다. ~b~%s~w~.",
    no_kit = "키트가 없습니다.",
 
    unable_to_find_booster = "이 ID로 부스터를 찾을 수 없습니다..",
    wait_already_player_boost = "이 부스터를 사용하기 전에 잠시 기다려주십시오. 이미 하나의 플레이어 부스터가 활성화되었습니다..",
    wait_already_crew_boost = "이 부스터를 사용하기 전에 잠시 기다려주십시오. 이미 하나의 크루 부스터가 활성화되어 있습니다..",
    wait_already_server_boost = "이 부스터를 사용하기 전에 잠시 기다려주십시오. 이미 하나의 서버 부스터가 활성화되어 있습니다..",
    booster_activated = "부스터가 사용되었습니다. ~g~%s 분~w~! ~b~XP +%s%%",
    server_booster_activated = "~b~%s~w~ 서버 부스터가 사용되었습니다. ~g~%s 분~z~! ~b~XP +%s%%",
    crew_booster_activated = "~b~%s~w~ 크루 부스터가 사용되었습니다. ~g~%s 분~z~! ~b~XP +%s%%",
    no_booster = "부스터가 없습니다.",
 
    rank_expired = "~r~후원자 역할이 만료되었습니다..",
    supporter_role = "~g~후원자 역할:~w~ %s",
    no_rank_warning = "서포터 역할이 없습니다.\n~r~구입한경우 fivem 계정을 연동시키세요",
    no_fivem_id = "FiveM은 게임과 연결되어 있지 않습니다..\n~r~FiveM 계정이 있고 게임에 연결되어 있는지 확인하십시오..",
    no_queue_warning = "대기열에 패키지가 없습니다..\n~r~순위를 찾고 있다면 잠시 기다리거나 /getrank를 시도하십시오..",
    package_sync_success = "~g~패키지가 올바르게 동기화되었습니다.!\n~w~사용가능한 명령어 : /getrank, /booster",
 
    level_required = "%s 랭크가 필요합니다.",
    rank_required = "%s 랭크가 필요합니다.",
    level_required_2 = "~r~%s 랭크가 필요합니다.",
 
    updated_deathmessage = "~g~사망 메시지를 업데이트했습니다..",
    updated_deatheffect = "~g~처치 효과를 업데이트했습니다.",
    use = "사용",
    test = "테스트",
 
    -- zombie
    you_bitten = "~r~당신은 물렸습니다!",
    infection_rate = "감염률: ~r~%s%%",
 
    -- ranks
    thug = "양아치",
    hustler = "깡패",
    soldier = "퇴역군인",
    trigger = "총잡이",
    enforcer = "정의수호자",
    facilitator = "진행자",
    public_enemy = "공공의적",
    shot_caller = "미친놈",
    street_boss = "거리의보스",
    kingpin = "왕중의왕",
    -- Tattoo
     tattoo = "문신",
     tattoos  = "문신",
     torso = "몸통",
     head = "머리",
     left_arm = "왼쪽 팔",
     right_arm = "오른쪽 팔",
     left_leg = "왼쪽 다리",
     right_leg = "오른쪽 다리",
     unknown = "알 수 없음",
     other = "기타",
     remove_tattoo = "모든 문신 제거",
    -- Hairdress
     haircuts = "머리",
     makeup = "메이크업",
     face = "얼굴",
     eyebrows = "눈썹",
     facial_hair = "얼굴 털",
     body_hair = "바디 헤어",
     barber_shop = "이발소",
     face_makeup = "얼굴 메이크업",
     lipstick = "립스틱",
     face_foundation = "얼굴 파운데이션",
     skin_blemishes = "피부 결점",
     skin_ageing = "피부 노화",
     moles_freckles = "두더지 및 주근깨",
     sun_damage = "피부 손상",
     skin_complexion = "피부 안색",
     body_blemishes = "신체 결점",
     body_blemishes_2 = "신체 결점 2",
     opacity = "알파",
     variations = "변형",
     filter = "필터",
     eyes_color = "눈 색깔",
    -- Mask
    masks = "마스크",
    -- Items
    money = "현금",
    -- Ammo
    ["9mm"] = "9mm(기관단총탄)",
    ["300_mag"] = ".300 Magnum(저격탄)",
    ["7_62mm"] = "7.62mm(소총탄)",
    ["calibre_12"] = "Calibre 12(샷건탄)",
    ["45_acp"] = ".45 ACP(권총탄)",
    ["5_56mm"] = "5.56mm(소총탄)",
 
    mask = "마스크",
    clean_kit = "청소 키트",
    radio = "라디오",
    recyclor = "재활용",
    medkit = "치료킷",
    kevlar = "방탄복",
    gps = "GPS",
    repair_tool = "수리킷",
    engine_veh = "엔진",
    wheel_veh = "휠",
    paint_spray = "페인트 스프레이",
    spike = "스파이크 트랩",
    bandage = "붕대",
    gaz_mask = "가스 마스크",
    filter = "필터",
 
    pickup_spikestrip = "스파이크 트랩 들기",
    you_dropped_spikestrip = "설치하였습니다. ~g~스파이크 트랩~w~.",
    you_pickup_spikestrip = "회수하였습니다. ~g~스파이크 트랩~w~.",
 
    you_have_been_killed_by = "사살 하였습니다. ~r~%s (%s)",
    kill_notif = "~m~사살",
    you_killed = "사살하였습니다. ~r~%s~w~",
    already_used_reset_only = "~r~이미 캐릭터를 재설정했습니다\n~~w~%s~w~ 멤버 만 캐릭터를 한 번 이상 다시 실행할 수 있습니다.",
    already_used_reset_only2 = "~r~이미 캐릭터를 재설정했습니다.\n~w~%s~w~ 멤버 만 캐릭터를 한 번 이상 다시 실행할 수 있습니다.",
 
    hud_options = "HUD 옵션",
    advanced_hud = "고급 HUD 표시",
    players = "유저들",
    health = "체력",
    player_menu = "유저 메뉴",
 
    you_are_now_zombie = "~r~당신은 이제 좀비입니다.",
 
    my_weapons = "내 무기",
    customize_weapons = "내 무기를 꾸미세요",
    weapon_skin = "색상",
 
    -- camo
    skin_classic = "기본",
    skin_green = "초록",
    skin_yellow = "노랑ㅇ",
    skin_pink = "핑크",
    skin_gold = "골드",
    skin_blue = "블루",
    skin_orange = "오렌지",
 
    -- new
    airdrop_coming = "~r~에어 드랍이오고 있습니다지도를 확인하세요!",
    killed_by_cheater = "~r~당신은 핵쟁이에게 살해당했습니다.\n~w~우리는 그를 밴처리 시켰고 당신의 사망은 취소되었습니다.",
 
    corrupted_vehicle = "~r~이 전차는 손상되어 과거에 복제되었으며 인벤토리에서 제거되었습니다. 사기를 당했다면 죄송합니다.",
 
    -- Discord
    join_discord_for_kit = "디스코드에 가입하여 무료 디스코드 키트를 받으세요!\n~g~discord.gg/gtalife",
    discord_account_not_linked = "~r~디스코드 계정을 FiveM과 연결해야합니다..",
    discord_account_not_guild = "~r~당신은 우리의 디스코드 서버에 없습니다r.\n~w~discord.gg/gtalife",
 
    already_done_recently = "~r~나중에 다시 시도하세요. 이미 최근에하셨습니다.",
    update_country = "국가 업데이트",
 
    prestige_info = "~b~ 최고레벨에 도달했습니다. \n~w~프레시티지 레벨시스템을 확인하려면 /prestige 를 사용하세요 ",
    prestige_not_max_level = "~r~최대 레벨에 도달하지 않았습니다..",
    max_prestige_reached = "~r~당신은 마지막 명성에 도달했습니다.",
    prestige_info_cmd = [[^3프레스티지 레벨링 시스템^7
현재 명성 ^4%s^7이고 레벨^5%s^7입니다.
 
최대 레벨 (%s)에 도달하면 명성을 얻고 XP 진행을 다시 시작하여 레벨 0으로 돌아갈 수 있습니다.
새로운 명성을 얻으면 더 나은 전리품, 새 아이템, 더 많은 돈 또는 더 높은 인벤토리 최대 무게와 같은 특별한 배지와 새로운 특전이 주어집니다.
^2프레스티지와 RETURN 레벨 0을 얻고 싶다면 ^1/setprestige^2


]], 
    new_prestige = "새로운 명성을 얻었습니다.!\n~g~%s 명성",
    cant_store_event_veh = "~r~특수 차량을 보관할 수 없습니다..",
 
    you_are_no_longer_in_combat = "🛡️ ~b~더 이상 전투 중이 아닙니다..",
    you_are_in_combat_mode = "🛡️ ~b~전투중 입니다.\n연결을 끊으면 죽습니다..",
    you_disconnected_in_combat = "💀 전투중 연결을 끊고 죽었습니다.",
 
    not_enough_prestige_points = "~r~명성 포인트가 충분하지 않습니다.",
    you_reached_max_prestige_stats_rank = "~r~이 명성 업그레이드의 최대 등급에 도달했습니다..",
    new_prestige_stats_upgrade = "당신의 업그레이드 ~b~%s~w~\n~g~%s/%s",
 
    legendary_vehicle_pop = "~r~전설적인 차량이지도에 나타났습니다.",
 
    combat_mode_container_disabled = "~r~전투 중입니다.\n~w~아이템을 저장할 수 없습니다..",
    gcoins_wallet_updated = "~g~GCoins 지갑이 업데이트 되었습니다.\n~w~+%s GCoins",
    not_enough_gcoins = "~r~GCoin이 충분하지 않습니다..",
    gcoins_something_went_wrong = "~r~문제가 발생했습니다.",
    you_bought_with_gcoins = "~g~%s~w~를~b~%s GCoins에 구매하셨습니다.~w~.",
 
    equiping_armor = "방탄복 착용",
 
    toggle_mute_player = "음소거 전환",
    you_muted_this_player = "~b~이 플레이어를 음소거했습니다..",
    you_unmuted_this_player = "~b~이 플레이어의 음소거를 해제했습니다.",
}
 
AddLanguage("ko", my_language)