local my_language = {
	give_vehicle = "Adicionaste um ~b~%s~w~ ao teu inventário.",
	store_vehicle_command = "Guardar o veículo que conduz",
	no_entity_vehicle = "~r~O veículo não existe ou está demasiado longe de ti.",
	no_entity_vehicle_id = "~r~O veículo não está ligado a nenhuma identificação, não se pode guardá-lo.",
	store_vehicle = "~b~Guardaste o teu veículo.",
	teleported_former_position = "~g~Foste teleportado para a tua última posição guardada.",
	not_enough_of = "~r~Não tens %s suficiente.",
	max_storage_chest = "~r~A caixa de armazenamento está cheia.",
	cant_carry_more_items = "~r~O teu inventário não pode armazenar mais artigos (full).",
	put_item = "Depositaste ~g~x%s~w~ %s~w~.",
	take_item = "Retiraste ~g~x%s~w~ %s~w~.",
	delete_item = "Eliminaste ~r~x%s~w~ %s~w~.",
	you_equiped_item = "Equipaste ~g~%s~w~.",
	press_enter_to_join = "Aperta ~g~ENTER~w~ para começar a jogar.",
	right = "Certo",
	left = "Esquerda",
	male = "Homem",
	female = "Feminino",
	ped = "Ped",
	name = "Nome",
	sex = "Sexo",
	title = "Título",
	no_entity_zombie = "O zombie não existe ou está demasiado longe de ti.",
	you_found = "Encontraste ~g~%sx %s~w~.",
	you_found_nothing = "Não encontraste ~g~nada~w~.",
	press_e_to_loot = "Aperta ~b~[E]~w~ para pilhar",
	full_for_item = "~r~Não há espaço suficiente para este artigo.",
	put_item_container = "Depositaste ~g~x%s~w~ %s~w~ no contentor.",
	take_item_container = "Retiraste ~g~x%s~w~ %s~w~ do contentor.",
	not_allowed_here = "~r~Não estás autorizado a fazer isso aqui.",
	cant_store_moving_veh = "~r~Não se pode armazenar um veículo em movimento.",

	yes = "sim",
	no = "não",
	none = "Nenhum",
	character_id = "Character ID",
	server_id = "Server ID",
	report = "Relatório",
	rename = "Renomear",
	trade_with = "Comércio",

	torso = "Torso",
	props = "Adereços",
	top = "Top",
	tops = "Tops",
	badge = "Badge",
	pants = "Pants",
	pant = "Pant",
	shoes = "Sapatos",
	bags = "Sacos",
	undershirt = "undershirt",
	neck = "neck",
	bracelets = "braceletes",
	montres = "relógios",
	earrings = "brincos",
	glasses = "óculos",
	hats = "chapéus",
	graphiques = "decorations",

	players = "Jogadores",
	weapon_katana = "Katana",
}

AddLanguage("pt", my_language)
