local my_language = {
	give_vehicle = "Você adicionou um ~b~%s~w~ ao seu inventário.",
	store_vehicle_command = "Guardar o veículo que está a conduzir",
	no_entity_vehicle = "~r~O veículo não existe ou está demasiado longe de si.",
	no_entity_vehicle_id = "~r~O veículo não está ligado a nenhuma identificação, não é possível guardá-lo.",
	store_vehicle = "~b~Você guardou seu carro",
	teleported_former_position = "~g~Foi teleportado para a sua última posição guardada.",
	not_enough_of = "~r~Não tem %s suficientes.",
	max_storage_chest = "~r~A caixa de armazenamento está cheia.",
	cant_carry_more_items = "~r~O seu inventário não pode armazenar mais artigos (full).",
	put_item = "Depositou ~g~x%s~w~ %s~w~.",
	take_item = "Retirou ~g~x%s~w~ %s~w~.",
	delete_item = "Eliminou ~r~x%s~w~ %s~w~.",
	you_equiped_item = "Equipou ~g~%s~w~.",
	press_enter_to_join = "Aperte ~g~ENTER~w~ para começar a jogar.",
	right = "Certo",
	left = "Esquerda",
	male = "Homem",
	female = "Feminino",
	ped = "Ped",
	name = "Nome",
	sex = "Sexo",
	title = "Título",
	no_entity_zombie = "O zombie não existe ou está demasiado longe de si.",
	you_found = "Encontrou ~g~%sx %s~w~.",
	you_found_nothing = " Não encontrou ~g~nada~w~.",
	press_e_to_loot = "Aperte ~b~[E]~w~ para lootear",
	full_for_item = "~r~Não há espaço suficiente para este artigo.",
	put_item_container = "Depositou ~g~x%s~w~ %s~w~ no seu contentor.",
	take_item_container = "Retirou ~g~x%s~w~ %s~w~ do seu contentor.",
	not_allowed_here = "~r~Você não está autorizado a fazer isso aqui.",
	cant_store_moving_veh = "~r~Não se pode armazenar um veículo em movimento.",

	yes = "sim",
	no = "não",
	none = "Nenhum",
	character_id = "Character ID",
	server_id = "Server ID",
	report = "Relatório",
	rename = "Renomear",
	trade_with = "Comércio",

	torso = "Torso",
	props = "Adereços",
	top = "Top",
	tops = "Tops",
	badge = "Badge",
	pants = "Pants",
	pant = "Pant",
	shoes = "Sapatos",
	bags = "Sacos",
	undershirt = "undershirt",
	neck = "neck",
	bracelets = "braceletes",
	montres = "relógios",
	earrings = "brincos",
	glasses = "óculos",
	hats = "chapéus",
	graphiques = "decorations",

	players = "Jogadores",
	weapon_katana = "Katana",
}

AddLanguage("pt", my_language)
