-- Put your Lua here
local my_language = {
	give_vehicle = "du lade till ~b~%s~w~ i ditt förråd.",
	store_vehicle_command = "Förvara fordonet du kör",
	no_entity_vehicle = "~r~Fordonet finns inte eller är för långt från dig.",
	no_entity_vehicle_id = "~r~Fordonet är inte bundet till något ID, du kan inte förvara det.",
	store_vehicle = "~b~Du förvarade ditt fordon.",
	teleported_former_position = "~g~Du har teleporterats till din senast sparade position.",
	not_enough_of = "~r~Du har inte tillräckligt %s.",
	max_storage_chest = "~r~Förvaringsboxen är full.",
	cant_carry_more_items = "~r~Ditt förråd kan inte lagra fler artiklar (hela).",
	put_item = "Du lägger in ~g~x%s~w~ %s~w~.",
	take_item = "Du tog ut ~g~x%s~w~ %s~w~.",
	delete_item = "Du tog bort ~r~x%s~w~ %s~w~.",
	you_equiped_item = "Du har utrustat din ~g~%s~w~.",
	bind_weapon_command = "Genväg för vapenspår %s",
	kevlar_broke = "~r~AHH!~n~~w~Din rustning har brutits.",
	inventory_command = "växla till förrådet",
	press_enter_to_join = "Tryck på ~g~ENTER~w~ för att börja spela.",
	new_character = "Ny karaktär",
	survivor = "Överlevande",
	right = "Höger",
	left = "Vänster",
	male = "Man",
	female = "Kvinna",
	ped = "Ped",
	name = "Namn",
	sex = "Sex",
	title = "Titel",
	select_this_character = "Välj denna karaktär",
	no_entity_zombie = "Zombien finns inte eller är för långt från dig.",
	you_found = "Du hittade ~g~%sx %s~w~.",
	you_found_nothing = "Du hittade ~g~nothing~w~.",
	press_e_to_loot = "Tryck på ~b~[E]~w~ för att plundra",
	full_for_item = "~r~Det finns inte tillräckligt med utrymme för denna artikel.",
	put_item_container = "Du lägger ~g~x%s~w~ %s~w~ i din behållare.",
	take_item_container = "Du tog ~g~x%s~w~ %s~w~ från din behållare.",
	not_allowed_here = "~r~Du får inte göra det här.",
	cant_store_moving_veh = "~r~Du kan inte förvara ett fordon i rörelse.",
	use_repair_tool = "använd reparationsverktyget",
	please_get_closer = "~b~Kom närmare, ingen enhet inom räckhåll.",
	you_cancel_action = "~r~Du avbröt åtgärden.",
	selected_target_message = "Markerat mål:~n~%s~n~~r~Tryck ~b~Y~r~ för att avbryta~n~~r~Tryck ~g~X~r~ för att fortsätta.",
	target_you = "~b~Du",
	target_screen = "~g~Visas",
	take_this_path = "ta denna väg",

	-- hud
	default_hud = "Default HUD",
	cinema_hud = "Cinema HUD",
	no_hud = "No HUD",

	-- perms
	kick_member = "Sparka medlemmar",
	invite_someone = "Inbjudan",
	edit_member = "Redigera medlemmar",
	edit_rank = "Redigera rangordningar",
	create_rank = "Skapa rangordningar",
	delete_rank = "Ta bort rangordningar",
	edit_structure = "Redigera grupp info",
	edit_permissions = "Redigera behörigheter",
	permission_level = "behörighetsnivån",
	red_delete = "Radera",
	rank = "Rangordning",
	red_kick = "Sparka",
	crew_name = "Grupp namn",
	slogan = "Catchphrase",
	information = "information",
	boss_rank = "Chefens rankningsnamn",
	member_rank = "Nybörjarens rangnamn",
	member = "Medlem",

	permissions_manager = "behörighetshanteraren",
	members_manager = "medlemmar chef",
	ranks_manager = "rankar chef",
	ranks_list = "rangordning listan",
	members_list = "medlemslista",
	create_a_rank = "skapa en rang",
	invite_someone = "bjuda in någon",
	stats = "Statistik",
	total_ranks = "Rangantal",
	total_members = "Medlemsantal",
	level = "Nivå",
	actions = "åtgärdslista",
	crew_manager = "gruppchef",
	you_created_a_new_crew = "Du skapade ett nytt grupp: %s",
	you_deleted_your_crew = "Du raderade din grupp.",
	you_are_not_in_a_crew = "Du är inte i en grupp",
	you_joined_the_crew = "Du gick med i en ny grupp '%s'",
	kick_failed = "Sparken misslyckades, anledning: %s",
	already_in_crew = "Du är redan i en grupp",
	no_invitation = "Du har inte fått någon inbjudan.",
	left_gcrew = "Du lämnade din grupp.",
	permission_updated = "Behörigheterna för <C>~g~%s</C>~w~ har uppdaterats.",
	incorrect_name = "~r~Namnformatet är felaktigt",
	incorrect_rank_perm = "~r~Error\n~w~Rangnamnet eller behörighetsnivån är ogiltig.",
	warn_rank_limit = "~r~Du nådde rankgränsen.",
	create_rank_success = "~g~Success\n~w~Du skapade en ny rang <C>~b~%s</C>~w~ med en behörighetsnivå på <C>~b~%s</C>~w~.",
	crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~Du kan inte interagera med en medlem som har en behörighetsnivå över din.",
	you_sent_an_invitation = "Du skickade en inbjudan till <C>~g~%s</C>~w~ för att gå med i din grupp.",
	you_received_an_invitation = "Du fick en inbjudan att gå med i en grupp.\n~b~/%s att acceptera.",
	invitation_expired = "Inbjudan gick ut",
	crew_kick_success = "Du sparkade <C>~b~%s</C>~w~ från din grupp.",
	first_rank_warning = "Den första rankningen är 'standard'.",

	you_updated_this = "Du uppdaterade %s till ~g~<C>%s</C>~w~.",
	changes_saved_on = "Ändringarna gjorda på  <C>~g~%s</C>~w~ har sparats.",
	yes = "ja",
	no = "nä",
	none = "Ingen",
	character_id = "Karaktär ID",
	server_id = "Server ID",
	report = "Rapportera",
	rename = "Byt namn",
	trade_with = "Handel",

	please_wait_x_before = "~r~Vänta %s sekunder innan du gör det.",

	-- cloth
	take_outfit = "Köp denna outfit",
	wardrobe_options = "alternativ för garderob",
	wardrobe = "garderob",
	manual_options = "manuella alternativ",
	manual_mode = "manuellt läge",
	save_outfit = "Spara denna outfit",
	variation = "variation",
	outfits = "outfits",
	cloth_shop = "Klädaffär",
	ped_cloth_shop = "Ped klädaffär",
	manual_props = "manuella rekvisita",
	manuel = "manuell",
	new_name = "Nytt namn",
	outfit_name = "Outfitnamn",
	variations_saved = "~g~Lyckades.~n~~w~Dina karaktärsvariationer har sparats.",
	equipped_new_outfit = "Du utrustade din nya outfit: ~b~%s",
	warning_limit_outfits = "Du har nått gränsen för sparade kläder. ~g~(%s)",
	saved_new_outfit = "Du sparade en ny outfit: ~b~%s~w~.",
	rename_outfit = "Din outfit ~b~%s~w~ har bytt namn till ~g~%s~w~.",
	delete_outfit = "Din outfit: ~b~%s~w~ har tagits bort.",

	torso = "Överkropp",
	props = "Rekvisita",
	top = "Topp",
	tops = "Tops",
	badge = "Badge",
	pants = "Byxor",
	pant = "Pant",
	shoes = "Skor",
	bags = "Väskor",
	undershirt = "undertröja",
	neck = "neck",
	bracelets = "armband",
	montres = "klockor",
	earrings = "örhängen",
	glasses = "glasögon",
	hats = "hattar",
	graphiques = "dekorationer",

	-- health
	inconscious = "Medvetslös",
	doing_something = "Gör något",
	time_before_respawn = "Tid innan du återuppstår",
	you_died = "~r~Du dog.",
	healing_wounds = "Läker sår",
	already_doing_something = "~r~Du gör redan något.",
	you_have_been_healed = "~g~Du har botats.",
	you_respawned = "~g~Du återuppstod.",

	player_too_far_to_interact = "~r~Spelaren du vill interagera med är för långt ifrån dig.",
	send_trade_invitation_to = "Du skickade en inbjudan att byta till ~b~%s~w~.\n~b~Vänta tills den andra spelaren accepterar den.",
	receive_invitation_from = "Du fick en inbjudan att byta från ~b~%s~w~.\n~b~Skriv ~w~/trade accept %s~b~ för att starta handeln.",

	invalid_command_args = "Ogiltiga kommandoargument: %s",
	start_trade_command_help = "Starta en handel med en annan spelare",
	accept_trade_command_help = "Acceptera en handelsinbjudan",
	deny_trade_command_help = "Neka en handelsinbjudan",
	invalid_invitation = "Inbjudan är ogiltig eller finns inte längre",
	name_accepted_your_trade_invitation = "~b~%s~w~ accepterade din handelsinbjudan",
	you_accepted_trade_invitation_of_name = "Du accepterade %s handelsinbjudan",
	name_denied_your_trade_invitation = "~b~%s~w~ nekade din handelsinbjudan",
	you_denied_trade_invitation_of_name = "Du nekade %s handelsinbjudan",
	you_already_trading = "Du handlar redan",
	other_already_trading = "Den andra spelaren handlar redan",

	other_player_not_enough_money = "~r~Transaktionen misslyckades. Den andra spelaren hade inte tillräckligt med pengar.",
	you_player_not_enough_money = "~r~Handeln misslyckades. Du hade inte tillräckligt med pengar.",
	other_player_not_enough_item = "~r~Transaktionen misslyckades. Den andra spelaren hade inte tillräckligt med något objekt.",
	you_player_not_enough_item = "~r~Handeln misslyckades. Du hade inte tillräckligt med något objekt.",
	success_trade = "~g~Handeln har bekräftats.",
	fail_trade_other_player = "~r~Transaktionen misslyckades, den andra spelaren lämnade.",
	trade_other_full_item = "~r~Transaktionen misslyckades, den andra spelaren har inte tillräckligt med utrymme.",
	trade_full_for_item = "~r~Transaktionen misslyckades, du har inte tillräckligt med utrymme.",

	press_e_to_loot_inv = "Tryck på ~INPUT_CONTEXT~ för att plundra lager.",
	press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~Tryck på ~INPUT_CONTEXT~ för att interagera med ~b~%s~HUD_COLOUR_NET_PLAYER27~.",
	press_e_to = "Tryck ~INPUT_CONTEXT~ till ~b~%s~w~.",
	press_e_to_open_catalog = "Tryck  ~b~E~w~ för att läsa ~g~katalog~w~.",
	this_person = "den här personen",
	the_shop = "denna butik",
	you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~Du får inte göra det.",

	no_weapon = "~r~Du har inget utrustat vapen.",
	no_need_ammo = "~r~Du behöver inte använda någon ammunition med detta vapen.",
	not_right_ammo = "~r~Du använder inte rätt ammunition, du behöver ~b~%s~w~.",
	you_used_ammo = "Du laddade din ~b~%s~w~ med ~b~x%s~w~ av ~b~%s~w~.",

	choose_a_destination = "välj en ~b~destination",
	open_your_chest = "Öppna din låda",
	no_enough_money = "~r~Du har inte råd med det.",
	you_paid = "Du betalade ~g~$%s~w~ för ~b~%s~w~.",
	you_paid_basket = "Du betalade ~g~$%s~w~ för din korg.",
	you_sell_basket = "Du fick ~g~$%s~w~ för att sälja ~b~x%s~w~ artikel (er).",

	you_repaired_your_vehicle = "~g~Du reparerade ditt fordon.",
	repairing_your_vehicle = "Reparera ditt fordon",
	wheels_are_fine = "~r~Fordonshjulen är hela.",
	changing_wheel = "Byta hjul",
	you_repaired_the_wheels = "~g~Du reparerade fordonets hjul.",

	front_post_ls = "Front post Los Santos",
	front_post_ls_2 = "Front post Los Santos 2",
	front_post_bc = "Front post Blaine County",
	front_post_bc_2 = "Front post Blaine County 2",
	main_post_ls = "Safe City Los Santos",
	main_post_bc = "Safe City Blaine County",
	random_zone = "Slumpmässig zon (landning)",

	this_item_is_equipped = "~r~Denna artikel är utrustad, ta bort den från dina genvägar.",
	only_in_safezone = "~r~Du kan inte göra det utanför en säker zon.",
	-- commerce stuff
	feature_gold_only = "Denna funktion är endast för ~y~guld medlemmar~w~.",
	feature_diamond_only = "Denna funktion är endast för ~b~diamant medlemmar~w~.",
	you_turned_into = "Du blev till en ~g~%s~w~.",
	wait_between_transformation = "~r~Vänta en stund innan du använder Morph Mode igen.",
	wait_between = "~r~Vänta en stund innan du gör det igen.",
	available_morphs = "Tillgängliga morfer",
	animal_models = "Djur modeller",
	zombie_models = "Zombie modeller",
	success_update_name = "Du ändrade karaktärens namn till ~b~%s~w~.",
	success_reset_stats = "~g~Du lyckades återställa din statistik. (Leaderboards uppdateras senare",

	-- animals
	boar = "vildsvin",
	cat = "Cat",
	chop = "Rottweiler (Chop)",
	rottweiler = "Rottweiler",
	cow = "Ko",
	coyote = "Prärievarg",
	deer = "rådjur",
	hen = "höna",
	husky = "Husky",
	mtlion = "Lejon",
	pig = "Gris",
	poodle = "Pudel",
	pug = "Mops",
	rabbit = "Kanin",
	rat = "Råtta",
	retriever = "Retriever",
	shepherd = "Shepherd",
	westy = "Westy",

	player_id = "Spelarens ID",
	bounty = "prisavtal",
	reason = "Anledning",
	id_player_not_found = "~r~Ingen spelare är bunden till detta id.",

	ammo_dealer = "Ammo återförsäljare",
	misc_dealer = "Utrustnings butik",
	veh_dealer = "Fordons butik",
	custom_dealer = "LS Custom",
	gun_dealer = "Vapen affär",

	bounty_created = "Du betalade ~g~$%s~w~ för att skapa ett prisavtal på ~b~%s~w~.",
	contract_success = "Prisavtal du skapade på ~r~%s~w~ har skickats till ~b~%s~w~.",
	a_contract_on_your_head = "~r~Du hade en prisavtal på ditt huvud. Din mördare fick prisavtalet.",
	reward_for_contract = "Prisavtals Jägare! Du belönades ~g~$%s~w~ för att ha dödat ~b~%s~w~.",

	hey_can_help_you = "Hej, hur kan jag hjälpa dig?",
	i_want_to_buy_items = "Jag vill köpa saker",
	i_want_to_sell_items = "Jag vill sälja varor",

	press_context_or_jump_to_get_up = "Tryck ~INPUT_CONTEXT~ eller ~INPUT_JUMP~ för att ~b~stå upp~w~.",
	server_restart_warning = "Servern kommer att starta om ..",
	auto_restart_in = "Automatisk omstart på %s sekunder.",

	not_allowed_create_character = "Du får inte skapa en ny karaktär.",
	character_not_yours = "Den här karaktären är inte din.",
	character_does_not_exist = "Denna karaktär finns inte eller finns inte längre.",
	loading_character = "Läser in din karaktär ...",

	playtime_is = "~b~Din speltid på Extinction:\n~w~%s",
	dont_spam = "^1Spamma inte!",

	babygod_warning = "~b~Du lämnade säkerhetszonen, du är oövervinnlig under en tid att hitta en säker plats!",

	-- LS Custom
	modifications_classiques = "Klassiska modifieringar",
	modifications_custom = "Special modifications",
	modifications_benny = "Benny's modifieringar",
	paint = "måla om din fordon",
	custom_your_car = "Anpassa din bil",
	wheels_modifications = "Modifieringar av hjul",
	performances = "Föreställningar",
	neons = "Neon",
	extra = "Extra",
	klaxon = "Horn",
	teinte_fenetre = "fönster nyans",
	phares_xenons = "Xenon strålkastare",
	modele_plaque = "Registeringsskylt model",
	livery = "Livery",
	headlight_color = "Strålkastar färg",
	wheel_type = "Hjultyp",
	primary_wheel_type = "Primär hjultyp",
	back_wheel_type = "Bakhjulstyp",
	wheel_color = "Hjulfärg",
	tire_smoke = "Däckrök",
	custom_color = "Anpassad färg",
	custom_wheel = "Anpassat hjul",
	custom_back_wheel = "Anpassat bakhjul",
	suspension = "Fjädring",
	transmission = "Växellåda",
	moteur = "Motor",
	frein = "Bromsar",
	turbo = "Turbo",
	primary_color = "Primär färg",
	secondary_color = "Sekundär färg",
	interior_color = "Interiörfärg",
	dashboard_color = "instrumentbräda färg",
	color_effect = "Färgeffekt",
	left_neon = "Vänster neon",
	right_neon = "Höger neon",
	front_neon = "Främre neon",
	back_neon = "Bak neon",

	aileron = "Spoiler",
	pc_front = "Främre stötfångare",
	pc_back = "Rear bumper",
	carroserie = "Sidokjol",
	exhaust = "Avgasrör",
	cadre = "Ram",
	calandre = "Grill",
	capot = "motorhuv",
	gb_left = "Vänster skärm",
	gb_right = "Höger skärm",
	roof = "Tak",
	plate_support = "registreringsskylthållare",
	front_plate = "Främre registeringskylt",
	interior_style = "Interior stil",
	figurine = "Statyett",
	motif_dashboard = "instrumentbräda stil",
	cadran = "urtavla design",
	haut_parleur_portes = "Högtalare för dörrar",
	motif_sieges = "Sätes stil",
	volant = "Ratt",
	levier = "Växelsparkar",
	logo_custom = "Logotyp",
	ice = "Is",
	haut_parleur_coffre = "högtalare för Bakdörrar",
	hydrolique = "Hydraulik",
	moteur = "Motor",
	filtres_air = "Luftfilter",
	entretoises = "distanser",
	arc_couverture = "Båge",
	antenne = "Antenn",
	motif_exterieur = "Exteriör stil",
	reservoir = "Tank",
	window = "Fönster",
	style = "Stil",
	default = "Standard",
	type = "Typ",
	normal = "Normal",
	black = "svart",
	black_smoke = "Svart rök",
	simple_smoke = "Simple smole",
	stock = "Lager",
	limo = "Limousine",
	sa_black = "San Andreas svart",
	sa_blue = "San Andreas blå",
	sa_white = "San Andreas vit",
	simple_white = "Enkel vit",
	ny_white = "North Yankton vit",
	race = "Race",
	sport = "Sport",
	stock = "Stock",
	street = "Street",
	discount = "Rabatt",
	select_your_car = "Välj din bil",
	select_car_custom = "Välj det fordon du vill anpassa. Siffran mellan pilarna är artikelnyckeln.",
	loading_vehicle = "Skapa fordon",
	invalid_vehicle = "~r~Ogiltig fordonsenhet.",
	invalid_vehicle_please_spawn = "~r~Ogiltig fordonsartikel. Spanna den en gång innan du försöker göra någonting.",
	free_take_and_validate = "Allt är gratis. Ta vad du vill och bekräfta!",
	car_custom_saved = "~g~Dina biländringar har sparats..",

	-- Character creation
	character_creation = "Karaktärsskapande",
	confirm = "bekräfta",
	start_playing = "Börja spela",
	appearance = "utseende",
	character_list = "Karaktärs lista",
	face_features = "ansiktsfunktioner",
	parents = "föräldrar",
	parent = "förälder",
	mix = "mix",
	skin = "skin",
	desc_mix = "Välj om ditt ansikts form påverkas mer av din far eller mamma.",
	desc_skin = "Välj om din hud påverkas mer av din far eller mamma.",
	identity = "identitet",
	player_name = "spelarnamn",
	new_character = "ny karaktär",
	warning_headblend = "~r~Du har inte valt din karaktärs föräldrar.",
	warning_overlays = "~r~Du har inte valt hår, ögonbryn eller skägg.",
	warning_identity = "~r~Varning.~n~~w~Du glömde att fylla i identitets fliken.",

	-- kits
	kit_does_not_exist = "~r~Detta kit finns inte.",
	kit_needs_rank = "Du har inte ~r~%s~w~ rang.",
	wait_before_using_kit = "Vänta ~r~%s~w~ innan du använder detta kit.",
	received_kit = "Du fick ditt kit ~b~%s~w~.",
	no_kit = "Du har inget kit.",

	unable_to_find_booster = "Det går inte att hitta en booster med detta id.",---
	wait_already_player_boost = "Vänta en stund innan du använder den här booster. Det finns redan en spelarbooster aktiv.",
	wait_already_crew_boost = "Vänta en stund innan du använder denna booster. Det finns redan en gruppbooster aktiv.",
	wait_already_server_boost = "Vänta en stund innan du använder denna booster. Det finns redan en serverbooster aktiv.",
	booster_activated = "Booster aktiverad under ~g~%s minuter~w~! ~b~XP +%s%%",
	server_booster_activated = "~b~%s~w~ aktiverade en serverbooster under ~g~%s minuter~z~! ~b~XP +%s%%",
	crew_booster_activated = "~b~%s~w~ aktiverade en gruppbooster i ~g~%s minuter~z~! ~b~XP +%s%%",
	no_booster = "Du har ingen booster.",

	rank_expired = "~r~Din supporterroll löpte ut.",
	supporter_role = "~g~Supporterroll:~w~ %s",
	no_rank_warning = "Du har ingen supporterroll.\n~r~Om du har köpt något länka ditt FiveM konto.",
	no_fivem_id = "Din FiveM är inte länkad till spelet.\n~r~Kontrollera att du har ett FiveM konto och att det är länkat till spelet.",
	no_queue_warning = "Du har inget paket i kö.\n~r~Vänta ett ögonblick eller försök / getRank om du letar efter din rang.",
	package_sync_success = "~g~Dina paket har synkroniserats korrekt, njut\n~w~Användbara kommandon: /getRank, /booster",

	level_required = "Du måste vara nivå %s.",
	rank_required = "Du måste ha %s rang.",
	level_required_2 = "~r~Du måste vara nivå %s.",

	updated_deathmessage = "~g~Du uppdaterade ditt dödsmeddelande.",
	updated_deatheffect = "~g~Du uppdaterade din dödseffekt.",
	use = "Använd",
	test = "Testa",

	-- zombie
	you_bitten = "~r~Du har blivit biten.",
	infection_rate = "Infektionsgrad: ~r~%s%%",

	-- ranks
	thug = "Gangster",
	hustler = "Hustler",
	soldier = "Soldat",
	trigger = "Trigger",
	enforcer = "Enforcer",
	facilitator = "Handledare",
	public_enemy = "Offentlig fiende",
	shot_caller = "Shot Caller",
	street_boss = "Gatu kung",
	kingpin = "Kingpin",
	-- Tattoo
	tattoo = "tatuering",
	tattoos = "tatueringar",
	torso = "överkropp",
	head = "huvud",
	left_arm = "vänster  arm",
	right_arm = "höger  arm",
	left_leg = "vänster  ben",
	right_leg = "höger  ben",
	unknown = "okänt",
	other = "annat",
	remove_tattoo = "Ta bort alla tatueringar",
	-- Hairdress
	haircuts = "hårklippningar",
    makeup = "Smink",
    face = "Ansikte",
    eyebrows = "Ögonbryn",
    facial_hair = "Ansiktshår",
    body_hair = "Kroppshår",
    barber_shop = "Frisörbutik",
    face_makeup = "Ansikts Smink",
    lipstick = "läppstift",
    face_foundation = "Ansikts foundation",
    skin_blemishes = "Hudfläckar",
    skin_ageing = "Hudåldring",
    moles_freckles = "Leverfläck och fräknar",
    sun_damage = "Hudskador",
    skin_complexion = "Hudfärg",
    body_blemishes = "Kroppsfel",
    body_blemishes_2 = "Kroppsfel 2",
    opacitet = "Alpha",
    variationer = "Variationer",
    filter = "Filter",
    eyes_color = "Ögonfärg",

 -- Mask
    masks = "Mask",

  -- Föremål
    money = "Pengar",

  -- Ammunition
    ["9mm"] = "9mm",
    ["300_mag"] = ".300 Magnum",
    ["7_62mm"] = "7.62mm",
    ["calibre_12"] = "Kalibre 12",
    ["45_acp"] = ".45 ACP",
    ["5_56mm"] = "5.56mm",

 -- Mat
    ["fish_1"] = "Öringabborre",
    ["fish_2"] = "Regnbågsöring",
    ["fish_3"] = "Lax",
    ["fish_4"] = "Arktisk harr",
    ["fish_5"] = "Klippabborre",
    ["fish_6"] = "Svartabborre",
    ["fish_7"] = "Skedstörar",
    ["fish_8"] = "Tjurröding",
    ["fish_9"] = "Kanadaröding",
    ["fish_10"] = "Kungslax",
    ["fish_11"] = "Pallidstör",
    ["fish_12"] = "Atlantlax",

    misc_meat = "Rå Kött",
    rabbit_meat = "Rå Kanin",
    lion_meat = "Rå Lejon",
    rare_plume = "Sällsynt fjäder",
    dog_meat = "Rå Hund",
    cat_meat = "Rå Katt",
    rare_fish = "Sällsynt fisk",

	mask = "Mask",
    malette = "Resväska",
    malette_metal = "Resväska av metall",
    ciseaux = "Sax",
    clean_kit = "Rengörnings kit",
    fishing_rod = "Fiskespö",
    meuble = "Möbler",
    tissu = "tyg",
    accessory = "Tillbehör",
    radio = "Radio",
    recyclor = "Återvining",
    medkit = "Första Hjälpen",
    kevlar = "Skottsäker Väst",
    gps = "GPS",
    repair_tool = "Reparationssats",
    jvn = "JVN",
    engine_veh = "Motor",
    wheel_veh = "Hjul",
    vetement = "Toppblock",
    bloc_note = "Anteckningsblock",
    paint_spray = "Lackering",
    spike = "Spika",
    paracetamol = "Paracetamol",
    bandage = "Bandage",
    gaz_mask = "Gasmask",
    filter = "Filter",
    tattoo_tool = "Tattoo verktyg",
    drug_med = "Drog",
    antizin = "Antizin",

    pickup_spikestrip = "plocka upp spikmatta",
    you_dropped_spikestrip = "Du tappade en ~ g ~ spikmatta ~ w ~.",
    you_pickup_spikestrip = "Du plockade upp en ~ g ~ spikmatta ~ w ~.",

    you_have_been_killed_by = "Du har dödats av ~r~%s",
    kill_notif = "~m~ Dödad",
    you_killed = "Du dödade ~r~%s~w~",
    already_used_reset_only = "~r~ Du har redan återställt din karaktär. \n~w~Endast %s~w~ medlemmar kan göra om sin karaktär mer än en gång.",
    hud_options = "HUD-alternativ",
    advanced_hud = "Visa avancerad HUD",
    players = "Spelare",
    healtha = "Hälsa",
    player_menu = "Spelarmeny",

    you_are_now_zombie = "~r~ Du är nu en zombie.",

    my_weapons = "mina vapen",
    customize_weapons = "anpassa mitt vapen",
    weapon_skin = "nyans",

    -- kamouflage
    skin_classic = "Standard",
    skin_green = "Grön",
    skin_yellow = "gul",
    skin_pink = "Rosa",
    skin_gold = "Guld",
    skin_blue = "Blå",
    skin_orange = "Orange",

    -- nytt
    airdrop_coming = "~r~ En airdrop kommer kontrollera din karta.",
    kill_by_cheater = "~r~ Du har dödats av en fuskare. \n~w~Vi Bannad honom och din död har avbrutits.",
}

AddLanguage("sv", my_language)
