--SIMPLIFIED CHINESE TRANSLATION BY TITANSIX (Josh B.) for EXTINCTION FIVEM MODIFICATION. ANY UNAUTHORIZED USE IS DISALLOWED. DO NOT REMOVE THIS TAG.

local my_language = {
	give_vehicle = "您添加~b~%s~w~到您的库存",
	store_vehicle_command = "将车辆存放",
	no_entity_vehicle = "~r~车辆不存在或车辆离您太远.",
	no_entity_vehicle_id = "~r~车辆未连接到ID号。 您无法将其存储.",
	store_vehicle = "~b~你把车存放了.",
	teleported_former_position = "~g~您已被传送到最后一个已知的位置.",
	not_enough_of = "~r~你没有足够的 %s.",
	max_storage_chest = "~r~收纳箱已满.",
	cant_carry_more_items = "~r~您的库存无法存储更多物品.",
	put_item = "你把 ~g~x%s~w~ %s~w~.",
	take_item = "你拿了 ~g~x%s~w~ %s~w~.",
	delete_item = "您删除了 ~r~x%s~w~ %s~w~.",
	you_equiped_item = "您的~g~%s~w~已配备.",
	bind_weapon_command = "武器槽快捷方式 %s",
	kevlar_broke = "~r~啊!~n~~w~ 您的防弹衣坏了.",
	inventory_command = "切换库存",
	press_enter_to_join = "按~g~ENTER~w~开始玩游戏.",
	new_character = "新角色",
	survivor = "幸存者",
	right = "对",
	left = "左",
	male = "男男",
	female = "女",
	ped = "Ped",
	name = "名称",
	sex = "性别",
	title = "标题",
	select_this_character = "选择这个角色",
	no_entity_zombie = "找不到僵尸还是离你太远.",
	you_found = "你发现了 ~g~%sx %s~w~.",
	you_found_nothing = "你发现了 ~g~没有~w~.",
	press_e_to_loot = "按~b~[E]~w~下寻找物品",
	full_for_item = "~r~没有足够的空间",
	put_item_container = "你把~g~x%s~w~ %s~w~放入容器中",
	take_item_container = "你拿~g~x%s~w~ %s~w~放入容器中.",
	not_allowed_here = "~r~您不可以在这里这样做.",
	cant_store_moving_veh = "~r~您无法保存您的车辆，它是移动.",
	use_repair_tool = "使用维修工具",
	please_get_closer = "~b~请靠近一点。 附近没有东西.",
	you_cancel_action = "~r~您已取消操作.",
	selected_target_message = "选择的目标：~n~%s~n~~r~按 b~Y~r~ 取消~n~~r~按. ~g~X~r~ 继续.",
	target_you = "~b~你",
	target_screen = "~g~显示",
	take_this_path = "走这条路",

	-- hud
	default_hud = "默认HUD",
	cinema_hud = "电影HUD",
	no_hud = "没有HUD",

	-- perms
	kick_member = "删除成员",
	invite_someone = "请帖",
	edit_member = "编辑成员",
	edit_rank = "编辑等级",
	create_rank = "创造等级",
	delete_rank = "删除等级",
	edit_structure = "编辑机组人员信息",
	edit_permissions = "编辑权限",
	permission_level = "授予权限",
	red_delete = "删除",
	rank = "等级",
	red_kick = "删除",
	crew_name = "人员名称",
	slogan = "口号",
	information = "信息",
	boss_rank = "老板职称",
	member_rank = "新会员等级职称",
	member = "会员",

	permissions_manager = "权限管理员",
	members_manager = "会员经理",
	ranks_manager = "职级经理",
	ranks_list = "职级清单",
	members_list = "会员名单",
	create_a_rank = "建立等级",
	invite_someone = "邀请某人",
	stats = "统计",
	total_ranks = "职级数",
	total_members = "会员人数",
	level = "级",
	actions = "actions",
	crew_manager = "行动",
	you_created_a_new_crew = "您创建了一个新团队 %s",
	you_deleted_your_crew = "您删除了您的团队.",
	you_are_not_in_a_crew = "您不在团队中",
	you_joined_the_crew = "您加入了新的团队 '%s'",
	kick_failed = "删除成员失败，原因: %s",
	already_in_crew = "您已经在团队中",
	no_invitation = "您尚未收到任何邀请.",
	left_crew = "你离开了你的团队.",
	permission_updated = " <C>~g~%s</C>~w~ 的权限已更新.",
	incorrect_name = "~r~名称格式不正确",
	incorrect_rank_perm = "~r~错误\n~w~级别名称或权限级别无效.",
	warn_rank_limit = "~r~您已达到等级别限制.",
	create_rank_success = "~g~Success\n~w~您创建了一个新等级 <C>~b~%s</C>~w~ . 许可级别为 <C>~b~%s</C>~w~.",
	crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~您无法与权限级别高于您的成员互动.",
	you_sent_an_invitation = "您已发送邀请给<C>~g~%s</C>~w~加入你的团队 <C>~g~%s</C>~w~ .",
	you_received_an_invitation = "您收到了加入机组的邀请. \n~b~/%s 接受.",
	invitation_expired = "邀请已过期",
	crew_kick_success = "您已从团队中删除<C>~b~%s</C>~w~ .",
	first_rank_warning = "第一等级是“默认”等级.",

	you_updated_this = "您更新了 %s to ~g~<C>%s</C>~w~.",
	changes_saved_on = " <C>~g~%s</C>~w~ 的更改已保存.",
	yes = "是",
	no = "不",
	none = "没有",
	character_id = "角色ID",
	server_id = "服务器ID",
	report = "报告",
	rename = "改名",
	trade_with = "贸易方式",
	
	please_wait_x_before = "~r~请等待 %s 秒后再执行此操作.",

	-- cloth
	take_outfit = "买这套衣服",
	wardrobe_options = "衣柜选项s",
	wardrobe = "衣柜",
	manual_options = "手动选项",
	manual_mode = "手动模式",
	save_outfit = "保存这件衣服",
	variation = "变异",
	outfits = "服装",
	cloth_shop = "服装店",
	ped_cloth_shop = "Ped 服装店",
	manual_props = "手工道具",
	manuel = "手工",
	new_name = "新名字",
	outfit_name = "服装名称",
	variations_saved = "~g~成功.~n~~w~您的角色变化已保存.",
	equipped_new_outfit = "您已装备好新衣服： ~b~%s",
	warning_limit_outfits = "您达到了已保存服装的限制。 ~g~(%s)",
	saved_new_outfit = "您保存了一套新衣服 ~b~%s~w~.",
	rename_outfit = "您的服装 ~b~%s~w~ 已重命名为.",
	delete_outfit = "您的服装： ~b~%s~w~ 已删除.",

	torso = "躯干",
	props = "道具",
	top = "衬衫",
	tops = "衬衫",
	badge = "徽章",
	pants = "裤子",
	pant = "裤子",
	shoes = "鞋类",
	bags = "包袋",
	undershirt = "汗衫",
	neck = "颈部",
	bracelets = "手链",
	montres = "手表",
	earrings = "耳环",
	glasses = "眼镜",
	hats = "帽子",
	graphiques = "装饰物",

	-- health
	inconscious = "无意识",
	doing_something = "做某事",
	time_before_respawn = "重生之前的时间",
	you_died = "~r~你死了.",
	healing_wounds = "伤口愈合",
	already_doing_something = "~r~你已经在做某事.",
	you_have_been_healed = "~g~你被治愈了.",
	you_respawned = "~g~你重生了.",

	player_too_far_to_interact = "~r~您想与之互动的玩家离您太远.",
	send_trade_invitation_to = "您已发送邀请来交换 ~b~%s~w~.\n~b~等待其他玩家接受  ~b~%s~w~.\n~b~",
	receive_invitation_from = " 您收到了来自~b~%s~w~.\n~b~的交换邀请。 类型 ~w~/trade 接受 %s~b~ 开始交易.",

	invalid_command_args = "无效的命令参数 %s",
	start_trade_command_help = "与其他玩家开始交易",
	accept_trade_command_help = "接受贸易邀请",
	deny_trade_command_help = "拒绝贸易邀请",
	invalid_invitation = "邀请无效或不再存在",
	name_accepted_your_trade_invitation = "~b~%s~w~ 接受了您的贸易邀请",
	you_accepted_trade_invitation_of_name = "您所接受的贸易邀请 %s",
	name_denied_your_trade_invitation = "~b~%s~w~ 拒绝了您的贸易邀请",
	you_denied_trade_invitation_of_name = "您拒绝了的贸易邀请 %s",
	you_already_trading = "您已经在交易",
	other_already_trading = "另一个玩家已经在交易",

	other_player_not_enough_money = "~r~交易失败。 另一个玩家没有足够的钱.",
	you_player_not_enough_money = "~r~交易失败。 你没有足够的钱.",
	other_player_not_enough_item = "~r~交易失败。 另一位玩家的物品不足.",
	you_player_not_enough_item = "~r~交易失败。 您没有足够的物品.",
	success_trade = "~g~交易已确认.",
	fail_trade_other_player = "~r~交易失败，其他玩家离开.",
	trade_other_full_item = "~r~交易失败，其他玩家没有足够的存储空间.",
	trade_full_for_item = "~r~交易失败，您没有足够的存储空间.",

	press_e_to_loot_inv = "按 ~INPUT_CONTEXT~ 掠夺库存",
	press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~ 按 ~INPUT_CONTEXT~ 与 ~b~%s~HUD_COLOUR_NET_PLAYER27~ 互动.",
	press_e_to = "按 ~INPUT_CONTEXT~ 到 ~b~%s~w~.",
	press_e_to_open_catalog = "按 ~b~E~w~ 读取~g~目录~w~.",
	this_person = "这个人",
	the_shop = "这家商店",
	you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~您不可以这样做.",

	no_weapon = "~r~您没有装备任何武器.",
	no_need_ammo = "~r~您无需与此武器一起使用任何弹药.",
	not_right_ammo = "~r~您使用的弹药不正确，需要使用 ~b~%s~w~.",
	you_used_ammo = " 您在~b~%s~w~上装有~b~x%s~w~弹药.",

	choose_a_destination = "选择一个 ~b~目的地",
	open_your_chest = "打开你的储物箱",
	no_enough_money = "~r~你负担不起.",
	you_paid = "您为~g~$%s~w~支付了 ~b~%s~w~.",
	you_paid_basket = "您为购物篮支付了 ~g~$%s~w~.",
	you_sell_basket = " 您因出售 ~g~$%s~w~ 项目而收到 b~x%s~w~ 款项.",

	you_repaired_your_vehicle = "~g~你修好你的车.",
	repairing_your_vehicle = "修理您的车辆",
	wheels_are_fine = "~r~车轮已经好了.",
	changing_wheel = "换轮",
	you_repaired_the_wheels = "~g~您修理了车轮.",

	front_post_ls = "前哨所Los Santos",
	front_post_ls_2 = "前哨所Los Santos 2",
	front_post_bc = "前哨Blaine County",
	front_post_bc_2 = "前哨 Blaine County 2",
	main_post_ls = "平安城市 Los Santos",
	main_post_bc = "平安城市 Blaine County",
	random_zone = "随机区 (landing)",

	this_item_is_equipped = "~r~该物品已配备，请将其从快捷方式中删除.",
	only_in_safezone = "~r~您不能在安全区域外进行操作.",
	-- commerce stuff
	feature_gold_only = "此功能仅适用于 ~b~金卡会员~w~.",
	feature_diamond_only = "此功能仅适用于 ~b~钻石会员~w~.",
	you_turned_into = "你变成了 ~g~%s~w~.",
	wait_between_transformation = "~r~请稍等片刻，然后再次使用变体模式.",
	wait_between = "~r~再次这样做之前，请稍等片刻.",
	available_morphs = "可用的变形",
	animal_models = "动物模型",
	zombie_models = "僵尸模型",
	success_update_name = "您将角色的名称更改为 ~b~%s~w~.",
	success_reset_stats = "~g~您已成功重置统计信息。 (排行榜稍后会更新)",

	-- animals
	boar = "公猪",
	cat = "猫",
	chop = "罗威纳犬 (Chop)",
	rottweiler = "罗威纳犬",
	cow = "牛",
	coyote = "土狼",
	deer = "鹿",
	hen = "母鸡",
	husky = "母鸡",
	mtlion = "狮子",
	pig = "猪",
	poodle = "贵宾犬",
	pug = "哈巴狗",
	rabbit = "兔子",
	rat = "鼠",
	retriever = "猎犬狗",
	shepherd = "牧羊犬",
	westy = "威斯汀狗",

	player_id = "玩家编号",
	bounty = "赏金",
	reason = "原因",
	id_player_not_found = "~r~没有玩家绑定到该ID.",

	ammo_dealer = "弹药经销商",
	misc_dealer = "设备店",
	veh_dealer = "V汽车店",
	custom_dealer = "LS Customs",
	gun_dealer = "枪店",

	bounty_created = "您支付 ~g~$%s~w~ 来创建 ~b~%s~w~ 的赏金合同.",
	contract_success = " 您在 ~r~%s~w~ 上创建的赏金已发送至 ~b~%s~w~ .",
	a_contract_on_your_head = "~r~你头上有赏金。 您的杀手获得了赏金.",
	reward_for_contract = "赏金猎人！ 您因杀死 ~g~$%s~w~ 而获得了 ~b~%s~w~ 奖励.",

	hey_can_help_you = "喂，有什么可以帮您的吗?",
	i_want_to_buy_items = "我想买东西s",
	i_want_to_sell_items = "我想卖东西",

	press_context_or_jump_to_get_up = " 按 ~INPUT_CONTEXT~ 或 ~INPUT_JUMP~ 直到 ~b~起床~w~.",
	server_restart_warning = "服务器将重新启动..",
	auto_restart_in = "在 %s 秒内自动重启服务器.",

	not_allowed_create_character = "您无权创建新角色.",
	character_not_yours = "这个角色不是你的.",
	character_does_not_exist = "该字符不存在或不再存在.",
	loading_character = "加载你的性格...",

	playtime_is = "~b~您在Extinction上的播放时间:\n~w~%s",
	dont_spam = "^1不要垃圾邮件!",

	babygod_warning = "~b~您离开了安全区，一段时间内无敌了，找到了安全的地方!",

	-- LS Custom
	modifications_classiques = "经典修改",
	modifications_custom = "特殊修改",
	modifications_benny = "Benny's的修改",
	paint = "涂料",
	custom_your_car = "定制你的车",
	wheels_modifications = "车轮修改",
	performances = "性能",
	neons = "霓虹灯",
	extra = "额外",
	klaxon = "车喇叭",
	teinte_fenetre = "窗户色调",
	phares_xenons = "氙气大灯",
	modele_plaque = "牌照",
	livery = "汽车贴花",
	headlight_color = "大灯颜色",
	wheel_type = "轮型",
	primary_wheel_type = "主轮类型",
	back_wheel_type = "后轮类型",
	wheel_color = "轮毂颜色",
	tire_smoke = "轮胎冒烟",
	custom_color = "自定义颜色",
	custom_wheel = "定制轮",
	custom_back_wheel = "定制后轮",
	suspension = "汽车悬架",
	transmission = "汽车变速箱",
	moteur = "汽车引擎",
	frein = "刹车",
	turbo = "涡轮",
	primary_color = "原色",
	secondary_color = "二次色",
	interior_color = "内部颜色",
	dashboard_color = "仪表板颜色",
	color_effect = "色彩效果",
	left_neon = "左霓虹灯",
	right_neon = "右霓虹灯",
	front_neon = "前霓虹灯",
	back_neon = "回霓虹灯",

	aileron = "汽车扰流板",
	pc_front = "前保险杠",
	pc_back = "后保险杠",
	carroserie = "侧裙",
	exhaust = "排气",
	cadre = "车架",
	calandre = "汽车格栅",
	capot = "汽车引擎盖",
	gb_left = "左护舷",
	gb_right = "右护舷",
	roof = "车顶",
	plate_support = "车牌架",
	front_plate = "前车牌",
	interior_style = "汽车内饰风格",
	figurine = "塑像",
	motif_dashboard = "仪表盘样式",
	cadran = "表盘设计",
	haut_parleur_portes = "音箱门",
	motif_sieges = "座位样式",
	volant = "方向盘",
	levier = "汽车变速杆",
	logo_custom = "商标",
	ice = "ICE",
	haut_parleur_coffre = "音箱后门",
	hydrolique = "汽车液压",
	moteur = "E汽车引擎",
	filtres_air = "空气过滤器",
	entretoises = "汽车垫片",
	arc_couverture = "拱门",
	antenne = "天线",
	motif_exterieur = "外观风格",
	reservoir = "储气罐",
	window = "车窗",
	style = "风格",
	default = "默认",
	type = "类型",
	normal = "正常",
	black = "黑色",
	black_smoke = "黑烟",
	simple_smoke = "简单冒烟",
	stock = "默认库存",
	limo = "豪华轿车",
	sa_black = "圣安地列斯黑色",
	sa_blue = "圣安地列斯蓝色",
	sa_white = "圣安地列斯白颜色",
	simple_white = "简单的白色",
	ny_white = "北扬克顿白",
	race = "种族",
	sport = "跑",
	stock = "股票",
	street = "街头赛",
	discount = "折扣",
	select_your_car = "选择你的车",
	select_car_custom = "选择您要自定义的车辆。 箭头之间的数字是项目键.",
	loading_vehicle = "创造车辆",
	invalid_vehicle = "~r~无效的车辆实体.",
	invalid_vehicle_please_spawn = "~r~无效的车辆项目。 请尝试将其生成一次，然后再尝试执行任何操作.",
	free_take_and_validate = "一切都是免费的。 采取你想要的并确认!",
	car_custom_saved = "~g~您的汽车修改已保存.",

	-- Character creation
	character_creation = "角色创作",
	confirm = "确认",
	start_playing = "开始玩",
	appearance = "个人形象",
	character_list = "角色清单",
	face_features = "面部特征",
	parents = "父母",
	parent = "父母",
	mix = "混合",
	skin = "皮肤",
	desc_mix = "选择您的面部形状是否更受父亲/母亲的影响.",
	desc_skin = "选择您的皮肤是否更受父亲/母亲的影响.",
	identity = "身份",
	player_name = "选手姓名",
	new_character = "新角色",
	warning_headblend = "~r~您尚未选择角色的父母.",
	warning_overlays = "~r~您尚未选择头发，眉毛或胡须.",
	warning_identity = "~r~警报.~n~~w~您忘记填写身份标签.",

	-- kits
	kit_does_not_exist = "~r~该套件不存在.",
	kit_needs_rank = "您没有 ~r~%s~w~ 级.",
	wait_before_using_kit = "请稍等 ~r~%s~w~ 在使用此套件之前.",
	received_kit = "您收到了您的套件 ~b~%s~w~.",
	no_kit = "你没有任何套件.",

	unable_to_find_booster = "找不到具有此ID的助推器。",
	wait_already_player_boost = "请稍等片刻，然后再使用此增强器。 已经有一个游戏玩家员助推器处于活动状态.",
	wait_already_crew_boost = "请稍等片刻，然后再使用此增强器。 已经有一个乘务员助推器处于活动状态.",
	wait_already_server_boost = "请稍等片刻，然后再使用此增强器。 已经有一个服务器增强器处于活动状态.",
	booster_activated = "助推器已激活 ~g~%s 分钟s~w~! ~b~XP +%s%%",
	server_booster_activated = "~b~%s~w~ 激活了服务器助推器 ~g~%s 分钟~z~! ~b~XP +%s%%",
	crew_booster_activated = "~b~%s~w~ 激活了一个船员助推器 ~g~%s 分钟~z~! ~b~XP +%s%%",
	no_booster = "你没有助推器.",

	rank_expired = "~r~您的支持者角色已过期。",
	supporter_role = "~g~支持者角色:~w~ %s",
	no_rank_warning = "您没有任何支持者角色.\n~r~如果您已购买商品，请链接您的Fivem帐户.",
	no_fivem_id = "您的FiveM帐户未与游戏关联.\n~r~验证您是否拥有FiveM帐户，并且该帐户已与游戏关联.",
	no_queue_warning = "您不必在队列中的任何包.\n~r~等一下或尝试 /getRank 如果您正在寻找自己的排名.",
	package_sync_success = "~g~您的包裹已正确同步，请享用！!\n~w~有用的命令: /getRank, /booster",

	level_required = "您需要达到 %s 级.",
	rank_required = "您需要达到 %s 秩.",
	level_required_2 = "~r~您需要达到 %s 级.",

	updated_deathmessage = "~g~您更新了死亡讯息.",
	updated_deatheffect = "~g~您更新了杀死效果.",
	use = "用",
	test = "试",

	-- zombie
	you_bitten = "~r~你被咬了.",
	infection_rate = "感染率： ~r~%s%%",

	-- ranks
	thug = "暴徒",
	hustler = "骗子",
	soldier = "士兵",
	trigger = "触发",
	enforcer = "执法者",
	facilitator = "主持人",
	public_enemy = "公敌",
	shot_caller = "重要的人",
	street_boss = "街头老大",
	kingpin = "主销",
	-- Tattoo
	tattoo = "纹身",
	tattoos = "更多纹身",
	torso = "躯干",
	head = "头",
	left_arm = "左臂",
	right_arm = "右臂",
	left_leg = "左腿",
	right_leg = "右腿",
	unknown = "未知",
	other = "其他",
	remove_tattoo = "删除所有纹身",
	-- Hairdress
	haircuts = "剪发",
	makeup = "化妆",
	face = "面对",
	eyebrows = "眉毛",
	facial_hair = "胡子",
	body_hair = "体毛",
	barber_shop = "理发店",
	face_makeup = "面对化妆",
	lipstick = "口红",
	face_foundation = "脸部粉底",
	skin_blemishes = "皮肤瑕疵",
	skin_ageing = "皮肤老化",
	moles_freckles = "痣和雀斑",
	sun_damage = "皮肤损伤",
	skin_complexion = "皮肤肤色",
	body_blemishes = "身体瑕疵",
	body_blemishes_2 = "身体瑕疵 2",
	opacity = "不透明",
	variations = "变化",
	filter = "滤镜",
	eyes_color = "眼睛颜色",
	-- Mask
	masks = "Masks",
	-- Items
	money = "Money",
	-- Ammo
	["9mm"] = "9mm",
	["300_mag"] = ".300 Magnum",
	["7_62mm"] = "7.62mm",
	["calibre_12"] = "Calibre 12",
	["45_acp"] = ".45 ACP",
	["5_56mm"] = "5.56mm",
	-- Food
	["fish_1"] = "大嘴鲈鱼",
	["fish_2"] = "虹鳟鱼",
	["fish_3"] = "小金鱼",
	["fish_4"] = "北极茴鱼",
	["fish_5"] = "鲈鱼",
	["fish_6"] = "小嘴鲈鱼",
	["fish_7"] = "匙吻鲟",
	["fish_8"] = "鳟鱼",
	["fish_9"] = "鳟鱼",
	["fish_10"] = "奇努克鱼",
	["fish_11"] = "白鲟鱼",
	["fish_12"] = "三文鱼",

	misc_meat = "生肉",
	rabbit_meat = "生兔",
	lion_meat = "生狮子肉",
	rare_plume = "罕见的羽毛",
	dog_meat = "生狗肉",
	cat_meat = "生猫肉",
	rare_fish = "生鱼肉",

	mask = "口罩",
	malette = "手提箱",
	malette_metal = "金属手提箱",
	ciseaux = "剪刀",
	clean_kit = "清洁套件",
	fishing_rod = "钓竿",
	meuble = "家具类",
	tissu = "布",
	accessory = "配件",
	radio = "收音机",
	recyclor = "回收商",
	medkit = "药盒",
	kevlar = "身体护具",
	gps = "GPS",
	repair_tool = "修理包",
	jvn = "JVN",
	engine_veh = "发动机",
	wheel_veh = "轮",
	vetement = "服装",
	bloc_note = "记事本",
	paint_spray = "喷漆",
	spike = "尖刺",
	paracetamol = "扑热息痛",
	bandage = "绷带",
	gaz_mask = "防毒面具",
	filter = "过滤",
	tattoo_tool = "纹身工具",
	drug_med = "药品",
	antizin = "抗僵尸药物",

	pickup_spikestrip = "捡起尖刺",
	you_dropped_spikestrip = "你掉了 ~g~尖刺~w~.",
	you_pickup_spikestrip = "你接了 ~g~尖刺~w~.",

	you_have_been_killed_by = "你被~r~%s (%s)杀了 ",
	kill_notif = "~m~被杀",
	you_killed = "你杀了 ~r~%s~w~",
	already_used_reset_only = "~r~您已经重置了角色.\n~w~只有 %s~w~ 会员可以重置自己的性格不止一次.",

	hud_options = "HUD选项",
	advanced_hud = "显示高级HUD",
	players = "玩家",
	health = "健康",
	player_menu = "玩家菜单",

	you_are_now_zombie = "~r~你现在是僵尸.",

	my_weapons = "我的武器装备",
	customize_weapons = "自定义我的武器装备",
	weapon_skin = "着色",

	-- camo
	skin_classic = "默认颜色",
	skin_green = "绿色",
	skin_yellow = "黄色",
	skin_pink = "粉色",
	skin_gold = "金色",
	skin_blue = "蓝色",
	skin_orange = "橙色",

	-- new
	airdrop_coming = "~r~一个是空投到达，看看你的地图.",
	killed_by_cheater = "~r~一个游戏作弊者杀死了你.\n~w~我们禁止他，您的死亡被取消.",
}

AddLanguage("zh", my_language)
