local my_language = {
	give_vehicle = "Hai aggiunto ~b~%s~w~ al tuo inventario.",
	store_vehicle_command = "Parcheggia il veicolo che stai guidando.",
	no_entity_vehicle = "~r~Il veicolo non esiste oppure è troppo lontano da te.",
	no_entity_vehicle_id = "~r~Il veicolo è Buggato.",
	store_vehicle = "~b~Hai depositato il tuo veicolo.",
	teleported_former_position = "~g~Sei stato teletrasportato alla tua ultima posizione salvata.",
	not_enough_of = "~r~Non hai abbastanza %s.",
	max_storage_chest = "~r~La cassa è piena.",
	cant_carry_more_items = "~r~Il tuo inventario è pieno.",
	put_item = "Hai messo: ~g~x%s~w~ %s~w~.",
	take_item = "Hai preso: ~g~x%s~w~ %s~w~.",
	delete_item = "Hai rimosso: ~r~x%s~w~ %s~w~.",
	you_equiped_item = "Hai equipaggiato: ~g~%s~w~.",
	bind_weapon_command = "Scorciatoia per slot per armi %s",
	kevlar_broke = "~r~AHH!~n~~w~La tua armatura si è rotta.",
	inventory_command = "Rimozione forzata dell\'inventario",
	press_enter_to_join = "Premi ~g~INVIO~w~ per iniziare a giocare.",
	new_character = "Nuovo personaggio",
	survivor = "Sopravvissuto",
	right = "Destra",
	left = "Sinistra",
	male = "Maschio",
	female = "Femmina",
	ped = "Ped",
	name = "Nome",
	sex = "Sesso",
	title = "Titolo",
	select_this_character = "Seleziona questo personaggio",
	no_entity_zombie = "Lo Zombie non esiste oppure è troppo lontano da te.",
	you_found = "Hai trovato ~g~%sx %s~w~.",
	you_found_nothing = "Non hai trovato ~g~Niente~w~.",
	press_e_to_loot = "Premi ~b~[E]~w~ per Lootare",
	full_for_item = "~r~Non hai abbastanza spazio per questo item.",
	put_item_container = "Hai messo ~g~x%s~w~ %s~w~ nel tuo container.",
	take_item_container = "Hai preso ~g~x%s~w~ %s~w~ dal tuo container.",
	not_allowed_here = "~r~Non hai il permesso di farlo qui.",
	cant_store_moving_veh = "~r~Non puoi parcheggiare un veicolo in movimento.",
	use_repair_tool = "Usa il kit di riparazione",
	please_get_closer = "~b~Avvicinati, non ci sono entità nelle vicinanze.",
	you_cancel_action = "~r~Hai annullato l'azione.",
	selected_target_message = "Target selezionato:~n~%s~n~~r~premi ~b~Y~r~ per annullare~n~~r~premi ~g~X~r~ per continuare.",
	target_you = "~b~TU",
	target_screen = "~g~Visualizzato",
	take_this_path = "Prendi questa strada",

	-- hud
	default_hud = "HUD Predefinito",
	cinema_hud = "HUD Cinematografico",
	no_hud = "Senza HUD",

	-- perms
	kick_member = "Espelli Membri",
	edit_member = "Modifica Membri",
	edit_rank = "Modifica Rank",
	create_rank = "Crea Rank",
	delete_rank = "Elimina Rank",
	edit_structure = "Modifica Info Della Crew",
	edit_permissions = "Modifica Permessi",
	permission_level = "Permessi Concessi",
	red_delete = "Elimina",
	rank = "Rank",
	red_kick = "Espelli",
	crew_name = "Nome della Crew",
	slogan = "Motto della Crew",
	information = "Informazioni",
	boss_rank = "Nome rank del Boss",
	member_rank = "Nome rank dei Membri",
	member = "Membri",

	permissions_manager = "Gestione Rank",
	members_manager = "Gestisci Membri",
	ranks_manager = "Gestisci Rank",
	ranks_list = "Lista Rank",
	members_list = "Lista Membri",
	create_a_rank = "Crea Un Rank",
	invite_someone = "Invita qualcuno",
	stats = "Statistiche",
	total_ranks = "Rank Totali",
	total_members = "Membri Totali",
	level = "Livelli",
	actions = "Azioni",
	crew_manager = "Gestisci Crew",
	you_created_a_new_crew = "Hai creato una nuova crew: %s",
	you_deleted_your_crew = "Hai eliminato la tua crew.",
	you_are_not_in_a_crew = "Non sei in una crew",
	you_joined_the_crew = "Sei entrato in una nuova crew '%s'",
	kick_failed = "Impossibile espellere l'utente, ragione: %s",
	already_in_crew = "Sei già in una crew.",
	no_invitation = "Non hai nessun invito in sospeso.",
	left_crew = "Hai lasciato la crew.",
	permission_updated = "I permessi per <C>~g~%s</C>~w~ sono stati aggiornati.",
	incorrect_name = "~r~Il formato del nome è sbagliato",
	incorrect_rank_perm = "~r~Errore\n~w~Il nome del rank o il livello del permesso è invalido.",
	warn_rank_limit = "~r~Hai raggiunto il rank massimo.",
	create_rank_success = "~g~Successo\n~w~Hai creato un nuovo rank <C>~b~%s</C>~w~ con i livelli di permesso di <C>~b~%s</C>~w~.",
	crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~Non puoi interagire con un membro che ha il livello di permesso superiore al tuo.",
	you_sent_an_invitation = "Hai mandato un invito a <C>~g~%s</C>~w~ per farlo entrare nella tua crew.",
	you_received_an_invitation = "Hai ricevuto un invito per entrare in una crew.\nfai ~b~/%s per accettare.",
	invitation_expired = "L\'invito è scaduto.",
	crew_kick_success = "Hai espulso <C>~b~%s</C>~w~ dalla crew.",
	first_rank_warning = "Il primo rank è quello 'predefinito'.",
	you_entered_crew_pro = "Sei entrato nella casa Crew",

	you_updated_this = "Hai aggiornato %s a ~g~<C>%s</C>~w~.",
	changes_saved_on = "Il cambiamento su <C>~g~%s</C>~w~ è stato salvato.",
	yes = "si",
	no = "no",
	none = "Nope",
	character_id = "ID Personaggio",
	server_id = "ID Server",
	report = "Segnala",
	rename = "Rinomina",
	trade_with = "Scambia",

	please_wait_x_before = "~r~Per favore aspetta %s secondi prima di farlo.",

	-- cloth
	take_outfit = "Compra questo outfit",
	wardrobe_options = "Impostazioni guardaroba",
	wardrobe = "Guardaroba",
	manual_options = "Opzioni manuali",
	manual_mode = "Modalità manuale",
	save_outfit = "Salva questo outfit",
	variation = "Variazioni",
	outfits = "Outfits",
	cloth_shop = "Negozio di Vestiti",
	ped_cloth_shop = "Negozio di Vestiti per PED",
	manual_props = "Props manuali",
	manuel = "manuali",
	new_name = "Nuovo Nome",
	outfit_name = "Nome Dell'Outfit",
	variations_saved = "~g~Successo.~n~~w~le variazioni al tuo personaggio sono state salvate.",
	equipped_new_outfit = "Hai equipaggiato il tuo nuovo outfit: ~b~%s",
	warning_limit_outfits = "Hai raggiunto il numero massimo di outfit che puoi salvare. ~g~(%s)",
	saved_new_outfit = "Hai salvato un nuovo outfit: ~b~%s~w~.",
	rename_outfit = "Il tuo outfit ~b~%s~w~ è stato rinominato come ~g~%s~w~.",
	delete_outfit = "Il tuo outfit: ~b~%s~w~ è stato cancellato.",

	torso = "Torso",
	props = "Props",
	top = "Top",
	tops = "Tops",
	badge = "Badge",
	pants = "Pantaloni",
	pant = "Pant",
	shoes = "Scarpe",
	bags = "Borsoni",
	undershirt = "Canottiera",
	neck = "Catene",
	bracelets = "Bracciali",
	montres = "Orologi",
	earrings = "Orecchini",
	glasses = "Occhiali",
	hats = "Cappelli",
	graphiques = "Decorazioni",

	-- health
	inconscious = "Incosciente",
	doing_something = "Facendo qualcosa",
	time_before_respawn = "Tempo prima del respawn",
	you_died = "~r~Sei morto.",
	healing_wounds = "Ti stai curando le ferite",
	already_doing_something = "~r~Stai gia facendo qualcos'altro.",
	you_have_been_healed = "~g~Ti sei curato.",
	you_respawned = "~g~Sei respawnato.",

	player_too_far_to_interact = "~r~Il giocatore con cui vuoi interagire è troppo lontano da te.",
	send_trade_invitation_to = "Hai mandato un invito per uno scambio a ~b~%s~w~.\n~b~Aspetta che il giocatore accetti.",
	receive_invitation_from = "Hai ricevuto un invito per uno scambio da ~b~%s~w~.\n~b~Scrivi ~w~/trade accept %s~b~ per iniziare lo scambio.",

	invalid_command_args = "Argomenti del comando non validi: %s",
	start_trade_command_help = "Inizia uno scambio con un'altro giocatore",
	accept_trade_command_help = "Accetta l'invito per lo scambio",
	deny_trade_command_help = "Nega l'invito per lo scambio",
	invalid_invitation = "L'invito non è valido oppure è scaduto",
	name_accepted_your_trade_invitation = "~b~%s~w~ Ha accettato l'invito per lo scambio ricevuto",
	you_accepted_trade_invitation_of_name = "Hai accettato l'invito per lo scambio ricevuto da %s",
	name_denied_your_trade_invitation = "~b~%s~w~ Ha rifiutato l'invito per lo scambio",
	you_denied_trade_invitation_of_name = "Hai rifiutato l'invito per lo scambio ricevuto da %s",
	you_already_trading = "Stai già effettuando uno scambio",
	other_already_trading = "L'altro giocatore sta già facendo uno scambio",

	other_player_not_enough_money = "~r~Lo scambio è fallito. L'altro giocatore non aveva abbastanza soldi.",
	you_player_not_enough_money = "~r~Lo scambio è fallito. Non hai abbastanza soldi.",
	other_player_not_enough_item = "~r~Lo scambio è fallito. L'altro giocatore non aveva abbastanza di alcuni oggetti.",
	you_player_not_enough_item = "~r~Lo scambio è fallito. Non avevi abbastanza di alcuni oggetti.",
	success_trade = "~g~Lo scambio è stato completato.",
	fail_trade_other_player = "~r~Lo scambio è fallito, L'altro giocatore ha abbandonato.",
	trade_other_full_item = "~r~Lo scambio è fallito, L'altro giocatore non ha abbastanza spazio.",
	trade_full_for_item = "~r~Lo scambio è fallito, non hai abbastanza spazio.",

	press_e_to_loot_inv = "Premi ~INPUT_CONTEXT~ per lootare l'inventario.",
	press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~Premi ~INPUT_CONTEXT~ per interagire con ~b~%s~HUD_COLOUR_NET_PLAYER27~.",
	press_e_to = "Premi ~INPUT_CONTEXT~ per ~b~%s~w~.",
	press_e_to_open_catalog = "Premi ~b~E~w~ per leggere il ~g~Catalogo~w~.",
	this_person = "Questa persona",
	the_shop = "Questo negozio",
	you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~Non hai il permesso per farlo qui.",

	no_weapon = "~r~Non hai nessuna arma equipaggiata.",
	no_need_ammo = "~r~Quest'arma non necessita di munizioni.",
	not_right_ammo = "~r~Non stai utilizzando le giuste munizioni, hai bisogno di ~b~%s~w~.",
	you_used_ammo = "Hai caricato ~b~%s~w~ con ~b~x%s~w~ di ~b~%s~w~.",

	choose_a_destination = "Scegli una ~b~destinazione",
	open_your_chest = "Apri la tua cassa",
	no_enough_money = "~r~Non hai abbastanza soldi.",
	you_paid = "Hai pagato ~g~$%s~w~ per ~b~%s~w~.",
	you_paid_basket = "Hai pagato ~g~$%s~w~ per il tuo cestino.",
	you_sell_basket = "Hai ricevuto ~g~$%s~w~ per aver venduto ~b~x%s~w~.",

	you_repaired_your_vehicle = "~g~Hai riparato il tuo veicolo.",
	repairing_your_vehicle = "Stai riparando il veicolo",
	wheels_are_fine = "~r~Le ruote del veicolo sono già a posto.",
	changing_wheel = "Stai cambiando la ruota",
	you_repaired_the_wheels = "~g~Hai riparato le ruote del veicolo.",

	front_post_ls = "Avamposto Los Santos",
	front_post_ls_2 = "Avampsoto Los Santos 2",
	front_post_bc = "Avamposto Blaine Country",
	front_post_bc_2 = "Avamposto Blaine County 2",
	main_post_ls = "Città Safe Los Santos",
	main_post_bc = "Città Safe Blaine County",
	random_zone = "Zona Casuale (Con Paracadute)",

	this_item_is_equipped = "~r~Questo item è equipaggiato, rimuovilo dai tasti rapidi.",
	only_in_safezone = "~r~Non puoi farlo al di fuori di una zona sicura.",
	-- commerce stuff
	feature_gold_only = "Questa opzione è solamente per i ~y~membri oro~w~.",
	feature_diamond_only = "Questa opzione è solamente per i ~b~membri diamante~w~.",
	you_turned_into = "Ti sei trasformato in un	 ~g~%s~w~.",
	wait_between_transformation = "~r~Perfavore aspetta un momento prima di usare la morfina nuovamente.",
	wait_between = "~r~Perfavore aspetta un momento prima di rifarlo.",
	available_morphs = "Morfina disponibile",
	animal_models = "Modelli Animali",
	zombie_models = "Modelli Zombie",
	success_update_name = "Hai cambiato il nome del tuo personaggio ~b~%s~w~.",
	success_reset_stats = "~g~Hai ripristinato correttamente le tue statistiche. (La Classifica Verrà Aggiornata a Breve)",

	-- animals
	boar = "Cinghiale",
	cat = "Gatto",
	chop = "Rottweiler (Chop)",
	rottweiler = "Rottweiler",
	cow = "Mucca",
	coyote = "Coyote",
	deer = "Cervo",
	hen = "Gallina",
	husky = "Husky",
	mtlion = "Leone",
	pig = "Maiale",
	poodle = "Barboncino",
	pug = "Carlino",
	rabbit = "Coniglio",
	rat = "Ratto",
	retriever = "Cane da riporto",
	shepherd = "Pastore",
	westy = "Westy",

	player_id = "ID del Giocatore",
	bounty = "Bounty",
	reason = "Motivo",
	id_player_not_found = "~r~Non esistono giocatori con questo di.",

	ammo_dealer = "Venditore Di Munizioni",
	misc_dealer = "Negozio Di Attrezzature",
	veh_dealer = "Venditore Di Veicoli",
	custom_dealer = "LS Custom",
	gun_dealer = "Venditore Di Armi",

	bounty_created = "Hai pagato ~g~$%s~w~ per mettere una taglia sulla testa a ~b~%s~w~.",
	contract_success = "La taglia che hai messo sulla testa a ~r~%s~w~ è stata mandata a ~b~%s~w~.",
	a_contract_on_your_head = "~r~E' stata riscattata una taglia sulla tua testa. Il tuo killer ha ottenuto la ricompensa.",
	reward_for_contract = "Cacciatore di taglie! Hai ottenuto una ricompensa di ~g~$%s~w~ per aver ucciso ~b~%s~w~.",

	hey_can_help_you = "Hey, come posso aiutarti?",
	i_want_to_buy_items = "Voglio comprare qualcosa",
	i_want_to_sell_items = "Voglio vendere qualcosa",

	press_context_or_jump_to_get_up = "Press ~INPUT_CONTEXT~ or ~INPUT_JUMP~ to ~b~get up~w~.",
	server_restart_warning = "Il server è in fase di riavvio..",
	auto_restart_in = "Riavvio automatico tra %s secondi.",

	not_allowed_create_character = "Non hai il permesso di creare un nuovo personaggio.",
	character_not_yours = "Questo personaggio non è tuo.",
	character_does_not_exist = "Questo personaggio non esiste o non esiste più.",
	loading_character = "Caricando il tuo personaggio...",

	playtime_is = "~b~Tempo Di Gioco Su Extinction:\n~w~%s",
	dont_spam = "^1Non Spammare!",

	babygod_warning = "~b~Sei uscito dalla safe zone, sarai invincibile per circa 15 secondi, trova un posto sicuro!",

	-- LS Custom
	modifications_classiques = "Modifiche Classiche",
	modifications_custom = "Modifiche Speciali",
	modifications_benny = "Modifichhe Benny",
	paint = "Dipingi",
	custom_your_car = "Personalizza la tua auto",
	wheels_modifications = "Modifiche alle ruote",
	performances = "Performance",
	neons = "Neon",
	extra = "Extra",
	klaxon = "Tromba",
	teinte_fenetre = "Colore Finestrini",
	phares_xenons = "Colore Fari",
	modele_plaque = "Modello Targa",
	livery = "Livrea",
	headlight_color = "Headlights color",
	wheel_type = "Tipo Di Ruota",
	primary_wheel_type = "Tipo Di Ruota Anteriore",
	back_wheel_type = "Tipo Ruota Posteriore",
	wheel_color = "Colore Ruota",
	tire_smoke = "Fumo Della Ruota",
	custom_color = "Colore Personalizzato",
	custom_wheel = "Ruota Anteriore Personalizzata",
	custom_back_wheel = "Ruota posteriore personalizzata",
	suspension = "Sospensioni",
	transmission = "Trasmissioni",
	moteur = "Motore",
	frein = "Freni",
	turbo = "Turbo",
	primary_color = "Colore Primario",
	secondary_color = "Colore Secondario",
	interior_color = "Colore Interno",
	dashboard_color = "Colore cruscotto",
	color_effect = "Colore",
	left_neon = "Neon Sinistro",
	right_neon = "Neon Destro",
	front_neon = "Neon Frontale",
	back_neon = "Neon Posteriore",

	aileron = "Spoiler",
	pc_front = "Paraurti anteriore",
	pc_back = "Paraurti posteriore",
	carroserie = "Minigonna laterale",
	exhaust = "Scarico",
	cadre = "Frame",
	calandre = "Griglia",
	capot = "Cappuccio",
	gb_left = "Parafango sinistro",
	gb_right = "Parafango destro",
	roof = "Tetto",
	plate_support = "Targa Posteriore",
	front_plate = "Targa Frontale",
	interior_style = "Stile degli interni",
	figurine = "Figurine",
	motif_dashboard = "Stile dashboard",
	cadran = "Dial design",
	haut_parleur_portes = "Altoparlanti nelle porte",
	motif_sieges = "Seat style",
	volant = "Steering wheel",
	levier = "Shifter leavers",
	logo_custom = "Logo",
	ice = "ICE",
	haut_parleur_coffre = "Altoparlanti nelle porte posteriori",
	hydrolique = "Idraulici",
	moteur = "Motore",
	filtres_air = "Filtro D'aria",
	entretoises = "Spacers",
	arc_couverture = "Arch",
	antenne = "Antenna",
	motif_exterieur = "Stile Esterno",
	reservoir = "Tank",
	window = "Finestra",
	style = "Stile",
	default = "Predefinito",
	type = "Tipo",
	normal = "Normale",
	black = "Nero",
	black_smoke = "Fumo nero",
	simple_smoke = "Resina semplice",
	stock = "Stock",
	limo = "Limousine",
	sa_black = "San Andreas nero",
	sa_blue = "San Andreas blu",
	sa_white = "San Andreas bianco",
	simple_white = "Bianco semplice",
	ny_white = "North Yankton bianco",
	race = "Gara",
	sport = "Sport",
	stock = "Stock",
	street = "Strada",
	discount = "Discount",
	select_your_car = "Seleziona il tuo veicolo.",
	select_car_custom = "Seleziona il veicolo che vuoi modificare. Il numero tra le freccie è l\'elemento.",
	loading_vehicle = "Sto caricando il veicolo.",
	invalid_vehicle = "~r~L\'entità del veicolo non è valida.",
	invalid_vehicle_please_spawn = "~r~Invalid vehicle item. Please spawn it one time before trying to do anything.",
	free_take_and_validate = "E\' tutto gratis. Prendi quello che vuoi e conferma!",
	car_custom_saved = "~g~Le modifiche alla tua auto sono state salvate.",

	-- Character creation
	character_creation = "Creazione del personaggio",
	confirm = "Conferma",
	start_playing = "Inizia a giocare",
	appearance = "Aspetto",
	character_list = "Lista personaggi",
	face_features = "face features",
	parents = "Parenti",
	parent = "Parente",
	mix = "mix",
	skin = "skin",
	desc_mix = "Seleziona se la forma del tuo viso è maggiormente influenzata da tuo padre / tua madre.",
	desc_skin = "Seleziona se la tua pelle è più influenzata da tuo padre / tua madre.",
	identity = "Identità",
	player_name = "Nome Del Giocatore",
	new_character = "Nuovo personaggio",
	warning_headblend = "~r~Non hai selezionato i parenti del tuo personaggio.",
	warning_overlays = "~r~Non hai selezionato i capelli, colore degli occhi oppure la barba.",
	warning_identity = "~r~Attenzione.~n~~w~Hai dimenticato di compilare la scheda Identità.",

	-- kits
	kit_does_not_exist = "~r~Questo kit non esiste.",
	kit_needs_rank = "Non hai il rank ~r~%s~w~.",
	wait_before_using_kit = "Per favore aspetta ~r~%s~w~ prima di usare questo kit.",
	received_kit = "Hai ricevuto il tuo kit ~b~%s~w~.",
	no_kit = "Non hai alcun kit.",

	unable_to_find_booster = "Impossibile trovare un booster con questo id.",
	wait_already_player_boost = "Attendi un momento prima di utilizzare il potenziamento. C'è gia un'altro giocatore con il potenziamento attivo.",
	wait_already_crew_boost = "Attendi un momento prima di utilizzare il potenziamento. È già attivo un potenziamento nella tua crew.",
	wait_already_server_boost = "Attendi un momento prima di utilizzare il potenziamento. È già attivo un potenziamento per il server.",
	booster_activated = "Potenziamento attivato ~g~%s minuti~w~! ~b~XP +%s%%",
	server_booster_activated = "Potenziamento per il Server attivato ~b~%s~w~ per ~g~%s minuti~z~! ~b~XP +%s%%",
	crew_booster_activated = "Potenziamento per la Crew attivato ~b~%s~w~ per ~g~%s minuti~z~! ~b~XP +%s%%",
	no_booster = "Non hai nessun potenziamento disponibile.",

	rank_expired = "~r~Il tuo ruolo di sostenitore è scaduto.",
	supporter_role = "~g~Ruolo sostenitore:~w~ %s",
	no_rank_warning = "Non hai alcun ruolo di sostenitore.\n~r~Se hai acquistato qualcosa, collega il tuo account FiveM.",
	no_fivem_id = "Il tuo account FiveM non è collegato al gioco.\n~r~Verifica di avere un account FiveM e che sia collegato al gioco.",
	no_queue_warning = "Non hai nessun pacchetto in coda.\n~r~Aspetta un momento o prova / getRank se stai cercando il tuo grado.",
	package_sync_success = "~g~I tuoi pacchetti sono stati sincronizzati correttamente!\n~w~Comandi utili: /getRank, /booster",

	level_required = "Hai bisogno di essere livello %s.",
	rank_required = "Hai bisogno di essere rank %s.",
	level_required_2 = "~r~Hai bisogno di essere livello %s.",

	updated_deathmessage = "~g~Hai aggiornato il tuo messaggio di morte.",
	updated_deatheffect = "~g~Hai aggiornato il tuo effetto di morte.",
	use = "Usa",
	test = "Test",

	-- zombie
	you_bitten = "~r~Sei stato morso.",
	infection_rate = "Tasso di infezione: ~r~%s%%",

	-- ranks
	thug = "Teppista",
	hustler = "Hustler",
	soldier = "Soldato",
	trigger = "Grilletto Facile",
	enforcer = "Enforcer",
	facilitator = "Facilitator",
	public_enemy = "Nemico Pubblico",
	shot_caller = "Shot Caller",
	street_boss = "Boss della strada",
	kingpin = "Kingpin",
	-- Tattoo
	tattoo = "negozio di tatuaggi",
	tattoos = "tatuaggi",
	torso = "torso",
	head = "testa",
	left_arm = "braccio sinistro",
	right_arm = "braccio destro",
	left_leg = "gamba sinistra",
	right_leg = "gamba destra",
	unknown = "sconosciuto",
	other = "altro",
	remove_tattoo = "Rimuovi tutti i tatuaggi",
	-- Hairdress
	haircuts = "Taglio di capelli",
	makeup = "Trucco",
	face = "Faccia",
	eyebrows = "Sopracciglia",
	facial_hair = "Peli del viso",
	body_hair = "Peluria",
	barber_shop = "Barbiere",
	face_makeup = "Face make up",
	lipstick = "Rossetto",
	face_foundation = "Face foundation",
	skin_blemishes = "Skin blemishes",
	skin_ageing = "Rughe",
	moles_freckles = "Lentiggini",
	sun_damage = "Imperfezioni",
	skin_complexion = "Skin complexion",
	body_blemishes = "Imperfezioni della pelle",
	body_blemishes_2 = "Imperfezioni della pelle 2",
	opacity = "Opacità",
	variations = "Variazioni",
	filter = "Filtro",
	eyes_color = "Colore degli occhi",
	-- Mask
	masks = "Maschere",
	-- Items
	money = "Dollari",
	-- Ammo
	["9mm"] = "9mm",
	["300_mag"] = ".300 Magnum",
	["7_62mm"] = "7.62mm",
	["calibre_12"] = "Calibro 12",
	["45_acp"] = ".45 ACP",
	["5_56mm"] = "5.56mm",
	rocket = "Razzi",
	flare = "Bengala",
	grenade = "Granata",
	-- Food
	["fish_1"] = "Persico Trota",
	["fish_2"] = "Trota iridea",
	["fish_3"] = "Kokanee",
	["fish_4"] = "Temolo Artico",
	["fish_5"] = "Rock Bass",
	["fish_6"] = "Smallmouth Bass",
	["fish_7"] = "Pesce spatola",
	["fish_8"] = "Trota toro",
	["fish_9"] = "Trota di lago",
	["fish_10"] = "Chinook",
	["fish_11"] = "Pallid Sturgeon",
	["fish_12"] = "Salmone",

	misc_meat = "Carne cruda",
	rabbit_meat = "Coniglio crudo",
	lion_meat = "Leone crudo",
	rare_plume = "Piuma rara",
	dog_meat = "Cane crudo",
	cat_meat = "Gatto crudo",
	rare_fish = "Pesce raro",

	mask = "Maschera",
	malette = "Valigia",
	malette_metal = "Valigia di metallo",
	ciseaux = "Forbici",
	clean_kit = "Kit di pulizia",
	fishing_rod = "Canna da pesca",
	meuble = "Forniture",
	tissu = "Pelle",
	accessory = "Accessori",
	radio = "Radio",
	recyclor = "Riciclatore",
	medkit = "Medikit",
	kevlar = "Giubotto antiproiettile",
	gps = "GPS",
	repair_tool = "Kit di riparazione",
	jvn = "JVN",
	engine_veh = "Motore",
	bag = "Sac",
	wheel_veh = "Ruota",
	vetement = "Top",
	bloc_note = "Blocco note",
	paint_spray = "Vernice spray",
	spike = "Strisce chiodate",
	paracetamol = "Paracetamolo",
	bandage = "Benda",
	gaz_mask = "Maschera antigas",
	filter = "Filtro",
	tattoo_tool = "Strumento per tatuaggio",
	drug_med = "Drug",
	drug_antizin = "Siringa di Antizin",
	drug_stamina = "Siringa di Stamina",
	drug_berserker = "Siringa di Salute",

	pickup_spikestrip = "Raccogli strisce chiodate",
	you_dropped_spikestrip = "Hai posizionato le ~g~strisce chiodate~w~.",
	you_pickup_spikestrip = "Hai raccolto da terra le ~g~strisce chiodate~w~.",

	you_have_been_killed_by = "Sei stato ucciso da ~r~%s",
	kill_notif = "~m~Ucciso",
	you_killed = "Hai ucciso ~r~%s~w~",
	already_used_reset_only = "~r~Hai già resettato il tuo personaggio.\n~w~Solo i membri %s~w~ possono farlo più di una volta.",
	already_used_reset_only2 = "~r~Lo hai già fatto.\n~w~Solo i membri %s~w~ possono farlo più di una volta.",

	hud_options = "Impostazioni HUD",
	advanced_hud = "Mostra impostazioni avanzate HUD",
	players = "Giocatori",
	health = "Vita",
	player_menu = "Menu giocatore",

	you_are_now_zombie = "~r~Sei diventato uno zombie.",

	my_weapons = "Le mie armi",
	customize_weapons = "Personalizza le mie armi",
	weapon_skin = "Skin Arma",

	-- camo
	skin_classic = "Predefinito",
	skin_green = "Verde",
	skin_yellow = "Giallo",
	skin_pink = "Rosa",
	skin_gold = "Oro",
	skin_blue = "Blu",
	skin_orange = "Arancione",

	weapon_katana = "Katana",
	weapon_sledgehammer = "Sledge Hammer",

	-- new
	airdrop_coming = "~r~Un approvvigionamento sta arrivando, controlla la mappa.",
	killed_by_cheater = "~r~Sei stato ucciso da un cheater.\n~w~Lo abbiamo bannato e ti abbiamo annullato la morte.",

	corrupted_vehicle = "~r~Questo veicolo è stato duplicato, ed è stato rimosso dal tuo inventario. Scusa se sei stato scammato.",

	-- Discord
	join_discord_for_kit = "Entra nel nostro discord per ottenere un Kit Discord!\n~g~discord.gg/gtalife",
	discord_account_not_linked = "~r~Hai bisogno di collegare il tuo account Discord con FiveM.",
	discord_account_not_guild = "~r~Non sei dentro il nostro server discord.\n~w~Entra su discord.gg/gtalife",

	already_done_recently = "~r~Riprova piu tardi, lo hai già fatto recentemente.",
	update_country = "Aggiorna Nazione",

	prestige_info = "~b~Hai raggiunto il livello massimo.\n~w~Digita /prestige per avere informazioni aggiuntive riguardo il sistema di prestigio.",
	prestige_not_max_level = "~r~Non hai ancora raggiunto il livello massimo.",
	max_prestige_reached = "~r~Hai raggiunto l'ultimo prestigio.",
	prestige_info_cmd = [[^3Sistema di Prestigi^7
Il tuo Prestigio attuale è: ^4%s^7 e sei livello: ^5%s^7.

Se raggiungi il livello massimo (%s) potrai scegliere se prestigiare e resettare tutti i tuoi punti XP e ricominciare dal livello 0.
Prestigiando riceverai un badge speciale e dei nuovi benefici come: un loot migliore, nuovi oggetti, più soldi ed il limite di spazio sarà aumentato.
^2Se vuoi effettuare il prestigio e RITORNARE al livello 0 digita ^1/setprestige^2
]],

	new_prestige = "Hai eseguito un prestigio!\n~g~Ora sei al %s prestigio.",
	cant_store_event_veh = "~r~Non puoi depositare veicoli speciali.",

	you_are_no_longer_in_combat = "🛡️ ~b~Non sei più in combattimento.",
	you_are_in_combat_mode = "🛡️ ~b~Sei in combattimento.\nSe ti disconnetterai verrai automaticamente ucciso.",
	you_disconnected_in_combat = "💀 Ti sei disconnesso durante un combattimento, sei morto.",

	not_enough_prestige_points = "~r~Non hai abbastanza punti prestigio.",
	you_reached_max_prestige_stats_rank = "~r~Hai raggiunto il livello massimo per questo prestigio.",
	new_prestige_stats_upgrade = "Hai aggiornato il tuo ~b~%s~w~\n~g~%s/%s",

	legendary_vehicle_pop = "~r~E\' apparso un veicolo leggendario, controlla la mappa.",

	-- poll one
	poll1_q1 = "What kind of game server would you like to see?",

	poll1_q1_a1 = "Battle Royale",
	poll1_q1_a2 = "Private missions solo or with 1-4 friends (Payday / Heist / Hitman like)",
	poll1_q1_a3 = "Race / Freeroam",
	poll1_q1_a4 = "Murder / Horror game",

	-- poll two
	poll2_q1 = "Parli bene l\'Inglese? forse potrebbe interessarti il nostro Server RP, GLife RP.",

	poll2_q1_a1 = "No",
	poll2_q1_a2 = "Sì",

	combat_mode_container_disabled = "~r~Sei in combattimento.\n~w~Non puoi depositare oggetti.",
	gcoins_wallet_updated = "~g~Il tuo portafoglio GCoins è stato aggiornato.\n~w~+%s GCoins",
	not_enough_gcoins = "~r~Non hai abbastanza GCoins.",
	gcoins_something_went_wrong = "~r~Ops! Qualcosa è andato storto.",
	you_bought_with_gcoins = "Hai acquistato ~g~%s~w~ per ~b~%s GCoins~w~.",

	equiping_armor = "Stai equipaggiando l'armatura",

	toggle_mute_player = "Disattiva Audio",
	you_muted_this_player = "~b~Hai disattivato l'audio di questo giocatore.",
	you_unmuted_this_player = "~b~Hai riattivato l'audio di questo giocatore.",

	already_purchased = "~r~Hai già comprato questo oggetto.",
	weapon_camo_preview = "Stai visualizzando l'anteprima del modello base, potrebbero mancare alcuni accessori.\n~INPUT_CELLPHONE_CANCEL~ per uscire dalla preview.",

	already_using_a_seringue_booster = "~r~Ti sei già iniettato.",
	seringue_effect_done = "~b~L'effetto dell'iniezione è passato.",
	you_injected_a_seringue_boost = "Ti sei iniettato con una ~b~Siringa~w~.",

	put_item_permission = "Posare oggetti",
	take_item_permission = "Prendere oggetti",
	put_money_permission = "Posare soldi",
	take_money_permission = "Prendere soldi",

	preferred_badge_set = "Hai impostato il tuo ~g~badge preferito~w~.",
	preferred_badge_not_set = "~r~Impossibile impostare il tuo badge.",

	marketplace_received_money_sales = "Hai ricevuto ~g~$%s~w~ da ~b~%s~w~ per una vendita.",
	marketplace_no_sales = "~r~Non hai venduto nulla.",
	marketplace_you_paid_for = "Hai pagato ~g~$%s~w~ per ~b~%s~w~.",

	deleted_sell_offer = "~b~Hai cancellato la tua offerta di vendita.",
	deleted_buy_offer = "~b~Hai cancellato la tua offerta di acquisto.",
	deleted_sell_offers = "~b~You deleted your sell offers.",
	deleted_buy_offers = "~b~You deleted your sell offers.",

	marketplace_offer_does_not_exist = "~r~Questa offerta non esiste.",

	marketplace_create_sell_offer = "Hai creato un'offerta di vendita ~b~%sx %s ~w~di ~g~$%s~w~ per pezzo.",
	marketplace_create_buy_offer = "Hai creato un'offerta di acquisto ~b~%sx %s ~w~di ~g~$%s~w~ per pezzo.",

	i_want_to_enter_in_my_property = "Voglio accedere alla mia proprietà.",
	i_want_to_exit_private_world = "Voglio ritornare nel mondo pubblico.",
	public_world = "Mondo Pubblico",
	private_world = "Mondo Privato",

	dailymission_playerkill = "Giocatori uccisi",
	dailymission_zombiekill = "Zombie uccisi",
	dailymission_playerheadshotkill = "Colpi alla testa (Giocatori)",
	dailymission_zombieheadshotkill = "Colpi alla testa (Zombie)",
	dailymission_zombiesurvivorkill = "Zombie Sopravvissuti uccisi",
	dailymission_zombiearmoredkill = "Zombie Corazzati uccisi",
	dailymission_zombiehazmatkill = "Zombie Hazmat uccisi",
	dailymission_zoombieboomerkill = "Zombie Boomer uccisi",
	dailymission_sellitems = "Oggetti venduti",
	dailymission_buyitems = "Oggetti comprati",
	dailymission_lootitems = "Oggetti lootati",
	dailymission_createselloffer = "Offerta di vendita create",
	dailymission_killtopkill25crew = "Giocatori di una Crew uccisi",
	dailymission_killtopkill50players = "Giocatori uccisi",
	dailymission_getintolegendaryvehicle = "Veicoli leggendari",
	dailymission_killzombiewithweapon = "Zombie uccisi con armi",
	dailymission_killplayerwithweapon = "Giocatori uccisi con armi",
	dailymission_darkzonesurvivingtime = "Tempo di sopravvivenza nella Darkzone",
	dailymission_redzoneplayerkill = "Giocatori uccisi nella RedZone",
	dailymission_redzonezombiekill = "Zombie uccisi nella RedZone",
	dailymission_darkzoneplayerkill = "Giocatori uccisi nella DarkZone",
	dailymission_darkzonezombiekill = "Zombie uccisi nella DarkZone",
	dailymission_useitem = "Oggetti utilizzati",
	dailymission_playtime = "Tempo di gioco",
	dailymission_xpharvest = "Harvested XO",
	dailymission_sellofferpurchased = "Offerte di vendita mie acquistate da altri giocatori",
	dailymission_sellofferpurchasedbyme = "Offerte di vendita acquistate da me",
	dailymission_tradeitems = "Oggetti scambiati",
	dailymission_createbuyoffer = "Offerte di acquisto casse",

	dailymission_completed = "~g~Hai completato la missione giornaliera!\n~b~+%s XP\n~y~+1 Chiave Dungeon",

	character_creation_mix_desc = "Scegli se la forma del tuo viso è influenzata maggiormente da tuo padre o tua madre.",
	character_creation_skin_desc = "Scegli se il colore della tua pelle è influenzato maggiormente da tuo padre o tua madre.",

	ff_1 = "Larghezza del naso",
	ff_2 = "Altezza del naso",
	ff_3 = "Lunghezza del naso",
	ff_4 = "Naso cadente",
	ff_5 = "Punta del naso",
	ff_6 = "Torsione del naso",
	ff_7 = "Larghezza delle sopracciglia",
	ff_8 = "Profondità delle sopracciglia",
	ff_9 = "Larghezza degli zigomi",
	ff_10 = "Altezza degli zigomi",
	ff_11 = "Larghezza delle guance",
	ff_12 = "Apertura degli occhi",
	ff_13 = "Spessore delle labbra",
	ff_14 = "Larghezza della mascella",
	ff_15 = "Lunghezza della mascella posteriore",
	ff_16 = "Abbassamento del mento",
	ff_17 = "Lunghezza del mento",
	ff_18 = "Larghezza del mento",
	ff_19 = "Fossetta del mento",
	ff_20 = "Spessore del collo",

	airdrop_taken_by = "^1%s has taken %s from the airdrop.",

	available_death_effects = "Available death effects",
	available_modes = "Available modes",

	you_changed_your_ped_model = "~g~You successfully changed your ped model.",
	i_want_to_change_my_ped = "I want to change my ped",

	poll4_q1 = "What do you expect from the next season?",
	poll4_q1_a4 = "New world event like airdrops, zone capture etc.",
	poll4_q1_a1 = "More PvE content like dungeons",
	poll4_q1_a2 = "More games like casino / races",
	poll4_q1_a3 = "PvP content",

	poll4_q2 = "Would you like to have more ranked/tournament modes?",
	poll4_q2_a1 = "Yes",
	poll4_q2_a2 = "No",

	poll4_q3 = "Would you like to have snipers in shops?",
	poll4_q3_a1 = "Yes",
	poll4_q3_a2 = "No",

	poll4_q4 = "What do you enjoy the most on Extinction?",
	poll4_q4_a1 = "PvP",
	poll4_q4_a2 = "PvE",
	poll4_q4_a3 = "Trading",

	dungeon_no_more_time = "~r~Sei stato troppo lento. Il Dungeon si è chiuso.",
	dungeon_participant_left = "~r~%s è uscito dal Dungeon.",
	started_dungeon_party = "~b~Hai creato una sala Dungeon.",
	dungeon_party_no_longer_exists = "~r~Non esiste ancora nessun invito di gruppo per il Dungeon.",
	dungeon_invitation_expired = "~r~l'invito di gruppo per il Dungeon è scaduto.",
	dungeon_join_party = "~g~Sei entrato nel gruppo per il Dungeon.",
	dungeon_too_late_for_invitation = "~r~Sei arrivato troppo tardi. Non puoi partecipare al Dungeon a questo punto della partita. (Il Dungeon è già iniziato)",
	dungeon_already_invited_this_player = "~r~Hai già invitato questo giocatore.",
	dungeon_invitation_received = "Hai ricevuto un invito da ~b~%s~w~ per entrare nel suo gruppo (Dungeon).\nDigita ~g~/dungeon join %s~w~ per partecipare al gruppo.",
	dungeon_invitation_sent = "Hai invitato ~g~%s~w~ nel tuo gruppo (Dungeon).",

	i_want_to_enter_a_dungeon = "I want to enter in a dungeon",
	dungeon_list = "Dungeon list",
	dungeon = "Dungeon",
	dungeons = "Dungeons",
	you_need_x_keys = "You need ~y~%s dungeon keys~w~ to enter the dungeon.",
	time_remaining = "Time remaining",
	you_killed_the_dungeon_boss = "~r~You killed the dungeon boss.",
	dungeon_kill_final_boss = "You are in the final room. Kill the boss to get the treasure.",

	dungeon_died_remaining = "You died, you have ~r~%s~w~ remaining lives.",
	dungeon_died = "~r~You no longer have any remaining lives. You died.",
	dungeon_already_in_party = "~r~You already are in a dungeon party.\n~w~Type /dungeon quit to leave.",
	dungeon_does_not_exist = "~r~This dungeon does not exist.",
	dungeon_ready = "~g~%s~w~ is ready.",
	dungeon_not_ready = "~r~%s~w~ is not ready.",

	not_released_yet = "This is not released yet.",
	feature_only_supporters = "~b~This feature is in beta-testing and only Diamond/Gold supporters can use it now.",
	feature_not_enabled = "~b~This feature is not enabled yet.\n~w~Please wait for the activation later today.",
	dungeon_charid_required = "~r~Please include your friend character id (top-right of its screen) after the command.\nExample: /dungeon invite 1234",

	poll5_q1 = "Would you accept that our anticheat captures cheaters's entire screen if they're suspected of wallhack or aimbots? (It may shows a part of your desktop if the game is in windowed mode but these captures will not be saved and only used by reliable moderators)",
	poll5_q1_a1 = "skip - ignore",
	poll5_q1_a2 = "Yes, I agree to this new method",
	poll5_q1_a3 = "No, I disagree",

	-- S4
	redzone_kill_leader_killed = "The ~r~redzone kill leader~w~ was killed.",
	redzone_kill_leader_fled = "The ~r~redzone kill leader~w~ fled.",
	redzone_get_back_kill_leader_before_x = "You are ~r~outside the redzone~w~ get back or you will loose your title in ~r~%s seconds~w~.",
	redzone_kill_leader_new_xp_step = "~r~Redzone XP Multiplier\n~b~+%s%~w~ bonus",
	remaining_lives = "Remaining lives",

	name_tag = "Crew tag",
	redzone_changed = "~r~Red zones moved to a new position.",

	-- Squad
	squad_not_leader = "~r~You are not the leader of your squad.",
	squad_kicked_by_x = "You have been ~r~kicked~w~ from your squad by ~r~%s~w~.",
	squad_you_kicked_x = "You kicked ~r~%s~w~ from your squad.",
	squad_invited_x = "You invited ~r~%s~w~ to your squad.",
	squad_invited_you_x = "~r~%s~w~ invited you to its squad.\nType ~r~/squad join %s~w~ to join the squad.",
	squad_you_set_new_leader = "You set ~r~%s~w~ as the new ~r~leader~w~ of the squad.",
	squad_you_are_new_leader = "~g~You are the new leader of the squad.",
	squad_not_invited = "~r~You have not been invited to the squad.",
	squad_joined_squad = "~g~You joined the squad.",
	squad_left = "~r~You left the squad.",
	squad_already_in = "~r~You are already in a squad.",
	squad_created_x = "You created a new squad. ~b~(%s)",
	squad_x_joined = "~b~%s~w~ joined the squad.",
	squad_leader_deleted = "~r~The leader deleted the squad.",
	write_yes_to_confirm = "Type yes to confirm",
	invite_a_player_write_char_id = "Invite a player. Type its character id",

	-- Help stuff
	press_enter_beginner_guide = "Press ~INPUT_ENTER~ to start the beginner guide.",
	welcome_glife = "Welcome on ~r~GLife Extinction~w~!",
	you_are_playing_server_x_with_x = "You are playing on server ~b~#%s~w~ with ~b~%s players~w~.",
	start_beginner_guide = "Start the beginner guide",
	play_now = "~g~Play now!",
	interact_npc_fast_travel = "Interact with the fast travel NPC",

	-- Tutorial
	tutorial_beginner_end_msg = "~r~Thank you for your time!\n~w~Have fun playing Extinction, if you have any question use the chat or find us on discord.",
	tutorial_beginner_start_msg = "~r~Welcome on GLife Extinction!\n~w~This short guide aims to explain how to begin on this gamemode.",
	tutorial_beginner_camera_01 = "~r~~BLIP_557~ ~r~Main safezone\n~w~This is a safe area where you can shop and store items, but also personalize your equipment and trade with other players.",
	tutorial_beginner_camera_02 = "~BLIP_568~ ~r~Storage chests\n~w~Here you can access your private storage and store your precious items.",
	tutorial_beginner_camera_03 = "~BLIP_567~~BLIP_556~~BLIP_658~ ~r~NPC Shops\n~w~You can buy and sell your items in many shops like the weapon, vehicle or equipment dealer.",
	tutorial_beginner_camera_04 = "~BLIP_84~ ~r~Public bounties\n~w~If you manage to find and kill the target, you will get the associated reward.",
	tutorial_beginner_camera_05 = "~BLIP_176~ ~r~Hostile world\n~w~You will meet zombies and hostile players. They will all want to get you killed, but they are the best way to get XP and great loot.",
	tutorial_beginner_camera_06 = "~BLIP_303~ ~r~World redzones\n~w~There you can find better loot and earn more experiences from your kills.",
	tutorial_beginner_camera_07 = "~BLIP_648~ ~r~Darkzone Island\n~w~Here you cannot save items nor flee easily, but it is the best place to find high-tier loot like MK2 weapons or snipers.",
	tutorial_beginner_camera_08 = "~BLIP_575~ ~r~Loot and exploration opportunities\n~w~You can fight for airdrop crates but also explore and beat dungeon boss.",
	tutorial_beginner_training_01 = "~g~You joined the training room.\n~w~Jump with ~INPUT_JUMP~ when you are ready.",
	tutorial_beginner_training_02 = "~g~Let's use the inventory.\n~w~Press ~%s~ to open your inventory.",
	tutorial_beginner_training_03 = "~g~Equip a weapon.\n~w~Open the inventory and drag a weapon in the shortcut bar.\nPress the corresponding key ~b~1/2/3/4/5/6/7~w~.\n~r~If you do not have any weapon use ~b~/kit newbie.",
	tutorial_beginner_training_04 = "~g~Fill your weapon ammo.\n~w~Equip a gun and put a box of ammo in your shortcut bar. Then press the shortcut key.",
	tutorial_beginner_training_05 = "~g~Finally vehicles.\n~w~You can spawn vehicles just like you equip a weapon. Once spawned, you can store it with ~%s~ while driving it. Press the key to confirm.",
	tutorial_beginner_training_success_01 = "~g~Great job, we can begin now!",
	tutorial_beginner_training_success_02 = "~g~Nice, you got it.\n~w~It is the same process to use all items.",
	tutorial_beginner_training_success_03 = "~g~Nice, you got it.\n~w~It is the same process to use all items.",
	tutorial_beginner_training_success_04 = "~g~Nice, you got it.\n~w~We are done now.",

	-- Darkzone stuff
	contaminated = "contaminated",
	darkzone_boat_leaving_in = "Boat leaving in",
	darkzone_exit = "Exit spot",
	purificator = "Purificator",
	you_entered_the_darkzone = "~r~Sei entrato nella DarkZone.",
	you_left_the_darkzone = "~r~Sei uscito dalla DarkZone.",
	cannot_enter_darkzone_time = "~r~La DarkZone non è ancora aperta, attendi.",
	darkzone_is_full = "~r~La DarkZone è piena, per favore attendi.",
	darkzone_exit_allowed = "~r~Sono arrivate le navi per andartene dalla DarkZone, corri se vuoi scappare.",
	darkzone_close_time = "Closing in",
	darkzone_surviving_since = "Surviving since",
	darkzone_points = "Points",
	darkzone_points_x = "~r~Darkzone points: ~w~+%s",
	darkzone_landing_in_x = "Landing available in ~b~%s minutes~w~.\nIf enough players.",
	darkzone_open_press_context = "The darkzone is open~w~.\nPress ~INPUT_CONTEXT~ to land ~m~on the darkzone~w~.",
	darkzone_outside_warning = "~r~You are outside the darkzone, come back or die.",
	darkzone_close_warning = "~r~The darkzone is closing soon~w~.\nYou should not stay here too long.",
	darkzone_close_damage = "The darkzone closed, the entire area is now contaminated.",
	darkzone_not_enough_points_to_exit = "You need ~r~%sx points~w~ to exit the darkzone.",
	press_e_to_exit_the_darkzone = "Press ~INPUT_CONTEXT~ to exit the darkzone.\n~r~You need x%s darkzone points.",
	use_purificator = "use the purificator",
	darkzone_not_enough_points_to_start_purificator = "You need ~r~%sx points~w~ to start the purificator.",
	darkzone_not_enough_points_to_refill_purificator = "You need ~r~%sx points~w~ to refill the purificator.",
	darkzone_too_far_from_purificator = "~r~You are too far from the purificator.",
	darkzone_cant_remove_while_running_purificator = "~r~You cannot remove items while the purificator is running.",
	darkzone_purificator_running = "~r~You cannot put items while the purificator is running.",
	darkzone_purificator_running_refill = "~r~You cannot refill the machine while the purificator is running.",
	darkzone_put_x_in_purificator = "You put ~r~%s~w~ in the purificator.",
	darkzone_you_took_x_from_purificator = "You took ~r~%s~w~ from the purificator.",
	darkzone_purificator_does_not_need_refill = "You do not need to ~r~refill this purificator~w~.",
	darkzone_refilled_purificator_x = "You used ~r~x%s points~w~ to refill the purificator.",
	darkzone_open = "Darkzone landing are available.\n~r~Find a transporter in any safezone.",
	darkzone_item_clean = "This item is already clean.\n~r~You can only put contaminated items.",
	
	dungeon_cooldown_between = "Please wait ~r~%s minutes~w~ before starting a dungeon again.",
	set_as_default = "Set as default custom for vehicle model",
	car_custom_presets_saved = "Your customization presets for ~g~%s~w~ have been saved.",
	marketplace_you_received_x_x = "You received ~b~%sx ~g~%s~w~.",

	above_level_x_no_longer_possible_loot_safe = "Player above rank %s cannot loot zombies in safezones.",
	preferred_component_desc = "This set will be the default set of all %s weapon you hold.",
	set_as_preferred_component_class = "Set as preferred component set",
	weapon_presets_updated = "You have set the default component presets for your ~g~%s~w~.",

	-- New survey
	poll6_q1 = "Would you like the crew member limit to be set to 25 members? (more competition, smaller groups)",
	poll6_q2 = "Is your main server fine for your ping? (Is your average ping ok?)",
	poll6_q3 = "Are you playing in private worlds?",
	poll6_q4 = "Should headshots be enabled for season 4?",
	
	casino_dungeon_desc = "⚠️ ~r~You may need flashlight on your weapon to see well here.",
	dungeon_destroy_wall_obj = "Destroy the wall blocking your path.",
	dungeon_use_key_obj = "Use the key to open the door.",
	dungeon_kill_zombies_obj = "Kill all zombies.",
	dungeon_kill_zombies_obj_x = "~b~Kill all zombies.~w~\n%s/%s of players have killed their zombies.",
	dungeon_use_key_to_open_door = "Use the key to open the door.",
	dungeon_find_key_obj = "Find a key to open the door in the room.",
	take_key = "take the key",
	open_the_door = "open the door",
	dungeon_quit_notif = "Type ~g~/dungeon quit~w~ to leave the dungeon.",
	dungeon_generator_obj = "Find the generator and get the power back.",
	dungeon_press_generator = "Press ~INPUT_CONTEXT~ to toggle the generator.",
	power_generator = "Power generator",
	dungeon_find_c4_obj = "There are blocks of C4 hidden somewhere, find them.",
	dungeon_use_c4_obj = "Use your C4 to blow up the vault door.",
	dungeon_party_help = "Type ~b~\"/dungeon\"~w~ to manage the dungeon party.",
	press_x_to = "Press %s to %s",

	quest_clean_zone = "Clean the zone: %s",
	quest_clean_zone_desc = "Reach %s and clean the area of zombies.",

	loot_crate_light = "Light Loot Crate",
	loot_crate_medium = "Medium Loot Crate",
	loot_crate_high = "High Loot Crate",
	
	dailymission_killzombieinzoneid = "Zombies killed in the zone",
	dailymission_dungeonbosskilled = "Dungeon boss killed",

	quest_too_far_npc = "~r~You are too far from the quest NPC.",
	quest_already_started_quest = "~r~You have already started this quest.",
	quest_redo_in_x = "~r~You have already done this quest.\n~w~You will be able to redo this quest in ~b~%s",
	quest_max_quests_reached = "~r~You can only accept %s quests.",
	quest_new_accepted = "~g~You accepted a new quest.",
	quest_gave_up = "~r~You gave up this quest.",
	quest_not_completed = "~r~You need to complete all objectives of the quest.",
	quest_already_completed = "~r~You already have completed this quest.",
	quest_all_completed = "~g~You successfully completed all objectives.",
	dungeon_key = "Dungeon key",
	darkzone_cannot_enter_min_levels = "You must be level ~b~%s~w~ to enter the darkzone.",
	darkzone_you_survived_x = "You survived ~r~%s minute(s)~w~ in the darkzone.",
	questmenu_command = "Open the quest menu",
	squadmenu_command = "Open the squad menu",
	airdrop_coming_darkzone = "~r~An airdrop is coming in the darkzone check your map.",
	darkzone_full_crew = "There is already ~r~%s members~w~ of your crew in the darkzone, wait for someone to leave.",

	crew_join_cooldown_x = "You need to wait ~r~%s~w~ before joining this crew.",
	darkzone_not_enough_players_darkzone = "The darkzone will not open.\n~r~Not enough players.",

	dungeon_loot_boss_box = "~g~A chest appeared in the center of the room.",
	drug_antizin_bar = "Antizin effect",
	drug_stamina_bar = "Stamina effect",
	drug_berserker_bar = "Health effect",
}

AddLanguage("it", my_language)
