local my_language = {
    give_vehicle = "인벤토리에 ~b~%s~w~을(를) 추가했습니다.",
    store_vehicle_command = "차량을 저장합니다.",
    no_entity_vehicle = "~r~주변에 차량이 존재하지 않거나 너무 멀리 떨어져 있습니다.",
    no_entity_vehicle_id = "~r~차량의 소유권을 잃었음으로, 저장 할 수 없습니다.",
    store_vehicle = "~b~차량이 저장되었습니다.",
    teleported_former_position = "~g~마지막에 저장된 위치로 순간이동 되었습니다.",
    not_enough_of = "~r~%s가 충분하지 않습니다.",
    max_storage_chest = "~r~가방이 가득 찼습니다.",
    cant_carry_more_items = "~r~이 아이템을 저장할 공간이 없습니다.",
    put_item = "~g~x%s~w~ %s~w~을(를) 보관하였습니다.",
    take_item = "~g~x%s~w~ %s~w~을(를) 꺼냈습니다.",
    delete_item = "~r~x%s~w~ %s~w~을(를) 삭제하였습니다.",
    you_equiped_item = "~g~%s~w~을(를) 착용하였습니다.",
    bind_weapon_command = "%s을(를) 단축키에 저장합니다.",
    kevlar_broke = "~r~야발~n~~w~방탄복이 파괴되었습니다.",
    inventory_command = "인벤토리 단축키",
    press_enter_to_join = "시작하려면 ~g~ENTER~w~ 를 누르세요.",
    new_character = "새로운 캐릭터",
    survivor = "생존",
    right = "오른쪽",
    left = "왼쪽",
    male = "남성",
    female = "여성",
    ped = "스킨",
    name = "이름",
    sex = "성",
    title = "제목",
    select_this_character = "이 캐릭터를 선택합니다.",
    no_entity_zombie = "좀비가 존재하지 않거나 너무 멀리 떨어져 있습니다.",
    you_found = "~g~%sx %s~w~을(를) 찾았습니다.",
    you_found_nothing = "아무것도 찾지 못했습니다.",
    press_e_to_loot = "~b~[E]~w~을(를) 눌러 수색하세요.",
    full_for_item = "~r~해당 아이템을 위한 공간이 충분하지 않습니다.",
    put_item_container = "~g~x%s~w~ %s~w~를 컨테이너에 보관하였습니다.",
    take_item_container = "컨테이너에서 ~g~x%s~w~ %s~w~을(를) 꺼냈습니다.",
    not_allowed_here = "~r~이곳에서는 할 수 없습니다.",
    cant_store_moving_veh = "~r~움직이는 차량은 저장할 수 없습니다.",
    use_repair_tool = "수리도구를 사용함",
    please_get_closer = "~b~ 범위 내에 물체가 없습니다, 가까이 가세요.",
    you_cancel_action = "~r~행동을 중단합니다.",
    selected_target_message = "타겟 선택:~n~%s~n~~r~취소하려면 ~b~Y~r~ 누르십시오.~n~~r~ 재개하려면 ~g~X~r~ 누르십시오.",
    target_you = "~b~목표",
    target_screen = "목표~g~조준",
    take_this_path = "이 방향으로 이동",
 
    -- hud
    default_hud = "HUD 기본",
    cinema_hud = "HUD 영화관",
    no_hud = "HUD 없음",
 
    -- perms
    kick_member = "크루원 추방",
    invite_someone = "크루 초대",
    edit_member = "크루원 편집",
    edit_rank = "계급 편집",
    create_rank = "계급 생성",
    delete_rank = "계급 삭제",
    edit_structure = "크루 정보 편집",
    edit_permissions = "권한 편집",
    permission_level = "권한",
    red_delete = "삭제",
    rank = "계급",
    red_kick = "추방",
    crew_name = "크루명",
    slogan = "슬로건",
    information = "정보",
    boss_rank = "보스 계급",
    member_rank = "크루원 계급",
    member = "크루원",
 
    permissions_manager = "관리자 권한",
    members_manager = "멤버 권한",
    ranks_manager = "계급 권한",
    ranks_list = "계급 목록",
    members_list = "크루원 목록",
    create_a_rank = "계급 생성",
    invite_someone = "초대하기",
    stats = "통계",
    total_ranks = "계급 ",
    total_members = "크루원 수",
    level = "레벨",
    actions = "활동",
    crew_manager = "크루 관리자",
    you_created_a_new_crew = "새로운 크루 만들기: %s",
    you_deleted_your_crew = "크루 삭제하기.",
    you_are_not_in_a_crew = "크루에 속해있지 않습니다.",
    you_joined_the_crew = "새로운 크루에 가입하기. '%s'",
    kick_failed = "추방 실패, 사유: %s",
    already_in_crew = "이미 크루에 속해 있습니다.",
    no_invitation = "초대를 받지 못했습니다.",
    left_crew = "크루를 탈퇴했습니다.",
    permission_updated = "<C>~g~%s</C>~w~의 권한이 수정되었습니다.",
    incorrect_name = "~r~잘못된 이름 형식",
    incorrect_rank_perm = "~r~Error\n~w~잘못된 등급 이름 또는 권한 레벨.",
    warn_rank_limit = "~r~권한 제한에 도달했습니다.",
    create_rank_success = "~g~Success\n~w~새로운 권한인 <C>~b~%s</C>~w~를 <C>~b~%s</C>~w~권한으로 생성하였습니다.",
    crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~본인보다 높은 등급의 멤버에게 접근할 수 없습니다.",
    you_sent_an_invitation = " <C>~g~%s</C>~w~에게 크루 가입 초대를 보냈습니다.",
    you_received_an_invitation = "크루 가입 초대를 받았습니다. 수락하려면 \n~b~/%s .",
    invitation_expired = "초대가 만료되었습니다.",
    crew_kick_success = " <C>~b~%s</C>~w~을(를) 크루에서 추방했습니다.",
    first_rank_warning = "처음 등급은 'default' 입니다.",
 
    you_updated_this = " %s to ~g~<C>%s</C>~w~을(를) 수정하였습니다.",
    changes_saved_on = " <C>~g~%s</C>~w~이(가) 저장되었습니다.",
    yes = "예",
    no = "아니오",
    none = "없음",
    character_id = "캐릭터 ID",
    server_id = "서버 ID",
    report = "신고",
    rename = "이름 변경",
    trade_with = "거래",
    
    please_wait_x_before = "~r~잠시 %s초만 기다려주십시오.",
 
    -- cloth
    take_outfit = "이 복장을 구매합니다.",
    wardrobe_options = "옷장 옵션",
    wardrobe = "옷장",
    manual_options = "상세 옵션",
    manual_mode = "상세 모드",
    save_outfit = "복장 저장",
    variation = "변경",
    outfits = "복장",
    cloth_shop = "옷 가게",
    ped_cloth_shop = "패드 옷 가게",
    manual_props = "상세 소품",
    manuel = "상세사항",
    new_name = "새로운 이름",
    outfit_name = "복장 이름",
    variations_saved = "~g~성공.~n~~w~캐릭터 외형이 저장됩니다.",
    equipped_new_outfit = "새로운 복장을 착용하였습니다.: ~b~%s",
    warning_limit_outfits = "복장 저장 최대치에 도달했습니다.~g~(%s)",
    saved_new_outfit = "새로운 복장을 저장하였습니다.: ~b~%s~w~.",
    rename_outfit = " ~b~%s~w~ 복장이  ~g~%s~w~로 이름이 변경되었습니다.",
    delete_outfit = ": ~b~%s~w~ 복장이 삭제되었습니다.",
 
    torso = "몸통",
    props = "소품",
    top = "상의",
    tops = "겉옷",
    badge = "뱃지",
    pants = "바지",
    pant = "스킨",
    shoes = "신발",
    bags = "가방",
    undershirt = "내복",
    neck = "목",
    bracelets = "팔찌",
    montres = "시계",
    earrings = "귀걸이",
    glasses = "안경",
    hats = "모자",
    graphiques = "그래픽",
 
    -- health
    inconscious = "의식을 잃었습니다.",
    doing_something = "행동중입니다.",
    time_before_respawn = "부활하기까지 남은 시간",
    you_died = "~r~사망했습니다.",
    healing_wounds = "치료중",
    already_doing_something = "~r~다른 행동중입니다.",
    you_have_been_healed = "~g~치료되었습니다.",
    you_respawned = "~g~부활하였습니다.",
 
    player_too_far_to_interact = "~r~접근할려는 플레이어가 주변에 없습니다.",
    send_trade_invitation_to = " ~b~%s~w~에게 거래요청을 보냈습니다. \n~b~수락하기를 기다리는중.",
    receive_invitation_from = " ~b~%s~w~의 거래요청을 받았습니다. \n~b~거래요청을 수락하기위해 ~w~/trade accept %s~b~을(를) 입력하십시오.",
 
    invalid_command_args = "무효한 커맨더입니다. : %s",
    start_trade_command_help = "다른 플레이어와 거래를 합니다.",
    accept_trade_command_help = "거래요청을 수락합니다.",
    deny_trade_command_help = "거래요청을 거부합니다.",
    invalid_invitation = "요청이 존재하지 않습니다.",
    name_accepted_your_trade_invitation = "~b~%s~w~이(가) 거래요청을 수락하였습니다.",
    you_accepted_trade_invitation_of_name = " %s의 거래요청을 수락하였습니다.",
    name_denied_your_trade_invitation = "~b~%s~w~이(가) 거래요청을 거부하였습니다.",
    you_denied_trade_invitation_of_name = " %s의 거래요청을 거부하였습니다.",
    you_already_trading = "이미 거래중입니다",
    other_already_trading = "다른 플레이어가 이미 거래중입니다.",
 
    other_player_not_enough_money = "~r~거래를 실패했습니다. 상대방의 돈이 충분하지 않습니다.",
    you_player_not_enough_money = "~r~거래를 실패했습니다. 돈이 충분하지 않습니다.",
    other_player_not_enough_item = "~r~거래를 실패했습니다. 상대방의 아이템이 충분하지 않습니다.",
    you_player_not_enough_item = "~r~거래를 실패했습니다. 아이템이 충분하지 않습니다.",
    success_trade = "~g~거래가 성사되었습니다.",
    fail_trade_other_player = "~r~거래를 실패했습니다, 상대방이 거래를 취소했습니다.",
    trade_other_full_item = "~r~거래를 실패했습니다, 상대방의 가방 공간이 부족합니다.",
    trade_full_for_item = "~r~거래를 실패했습니다, 가방 공간이 부족합니다.",
 
    press_e_to_loot_inv = "가방을 수색하기위해 ~INPUT_CONTEXT~ 눌러주십시오.",
    press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~이용하려면 ~INPUT_CONTEXT~를 눌러주십시오. ~b~%s~HUD_COLOUR_NET_PLAYER27~.",
    press_e_to = "~b~%s~w~하려면 ~INPUT_CONTEXT~ 를 눌러주십시오.",
    press_e_to_open_catalog = " ~g~이용~w~하려면 ~b~E~w~을(를) 눌러주십시오.",
    this_person = "이 사람",
    the_shop = "이 가게",
    you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~ 이 행동은 할 수 없습니다.",
 
    no_weapon = "~r~어떠한 무기도 장착하고있지 않습니다.",
    no_need_ammo = "~r~이 무기는 어떠한 탄약도 필요로 하지 않습니다.",
    not_right_ammo = "~r~올바른 탄약을 사용하고있지 않습니다, ~b~%s~w~가 필요합니다.",
    you_used_ammo = " ~b~%s~w~에  ~b~x%s~w~만큼의 ~b~%s~w~을(를) 장전하였습니다.",
 
    choose_a_destination = " ~b~다른 지역으로 순간이동",
    open_your_chest = "보관함을 이용",
    no_enough_money = "~r~돈이 충분하지 않습니다.",
    you_paid = "~b~%s~w~을(를) 구매하기위해 ~g~$%s~w~을(를) 지불하였습니다 .",
    you_paid_basket = "물건을 구매하기위해 ~g~$%s~w~을(를) 지불하였습니다.",
    you_sell_basket = " ~g~$%s~w~을(를) 받고 ~b~x%s~w~개를 팔았습니다.",
 
    you_repaired_your_vehicle = "~g~차량을 수리하였습니다.",
    repairing_your_vehicle = "차량을 수리하는중",
    wheels_are_fine = "~r~차량의 타이어가 정상입니다.",
    changing_wheel = "타이어를 교체하는중",
    you_repaired_the_wheels = "~g~차량의 타이어를 교체하였습니다.",
 
    front_post_ls = "Front post Los Santos",
    front_post_ls_2 = "Front post Los Santos 2",
    front_post_bc = "Front post Blaine County",
    front_post_bc_2 = "Front post Blaine County 2",
    main_post_ls = "Safe City Los Santos",
    main_post_bc = "Safe City Blaine County",
    random_zone = "랜덤 (낙하)",
 
    this_item_is_equipped = "~r~아이템이 장착되었습니다, 컨테이너에 보관할 수 없습니다.",
    only_in_safezone = "~r~세이프존밖에서는 할 수 없습니다.",
    -- commerce stuff
    feature_gold_only = "~y~gold members~w~만 가능합니다.",
    feature_diamond_only = "~b~diamond members~w~만 가능합니다.",
    you_turned_into = " ~g~%s~w~로 변했습니다.",
    wait_between_transformation = "~r~Morph Mode를 다시 사용하기 위해서 잠시만 기다려주십시오.",
    wait_between = "~r~재사용하기위해 잠시만 기다려주십시오.",
    available_morphs = "이용가능한 morphs",
    animal_models = "동물",
    zombie_models = "좀비",
    success_update_name = " ~b~%s~w~로 닉네임이 변경되었습니다.",
    success_reset_stats = "~g~스탯을 성공적으로 초기화하였습니다. (리더보드는 잠시후에 변경됩니다.)",
 
    -- animals
    boar = "멧돼지",
    cat = "고양이",
    chop = "춉",
    rottweiler = "로트와일러",
    cow = "소",
    coyote = "코요태",
    deer = "사슴",
    hen = "암탉",
    husky = "허스키",
    mtlion = "Lion",
    pig = "돼지",
    poodle = "푸들",
    pug = "퍼그",
    rabbit = "토끼",
    rat = "쥐",
    retriever = "리트리버",
    shepherd = "셰퍼드",
    westy = "웨스티",
 
    player_id = "플레이어 ID",
    bounty = "현상금",
    reason = "사유",
    id_player_not_found = "~r~이 ID에 연결된 플레이어가 존재하지 않습니다.",
 
    ammo_dealer = "탄약 상점",
    misc_dealer = "기타 상점",
    veh_dealer = "차량 상점",
    custom_dealer = "차량 튜닝샵",
    gun_dealer = "총기 상점",
 
    bounty_created = "~b~%s~w~에게 현상금으로 ~g~$%s~w~을(를) 걸었습니다.",
    contract_success = "~r~%s~w~에게 걸었던 현상금이 ~b~%s~w~에게 지급되었습니다.",
    a_contract_on_your_head = "~r~현상금이 걸렸습니다. 죽이는 사람에게 현상금이 지급될 것입니다.",
    reward_for_contract = "현상금사냥꾼! ~b~%s~w~을(를) 죽이고 ~g~$%s~w~을(를) 받았습니다.",
 
    hey_can_help_you = "무엇을 도와드릴까요?",
    i_want_to_buy_items = "물건을 구매하고싶습니다.",
    i_want_to_sell_items = "물건을 판매하고싶습니다.",
 
    press_context_or_jump_to_get_up = " ~b~일어나려면~w~ ~INPUT_CONTEXT~ or ~INPUT_JUMP~을(를) 누르십시오.",
    server_restart_warning = "서버가 재시작됩니다..",
    auto_restart_in = "자동 서버 재시작까지 %s 초.",
 
    not_allowed_create_character = "새로운 캐릭터를 생성할 수 없습니다.",
    character_not_yours = "본인의 캐릭터가 아닙니다.",
    character_does_not_exist = "이 캐릭터는 존재하지 않거나, 더이상 존재하지 않습니다.",
    loading_character = "캐릭터를 불러오는중입니다.",
 
    playtime_is = "~b~플레이타임:\n~w~%s",
    dont_spam = "^1스팸 금지!",
 
    babygod_warning = "~b~안전구역을 벗어났습니다, 잠시동안 무적입니다!",
 
    -- Customs
    modifications_classiques = "일반 튜닝",
    modifications_custom = "특별 튜닝",
    modifications_benny = "Benny의 튜닝",
    paint = "도색",
    custom_your_car = "차량을 튜닝합니다.",
    wheels_modifications = "휠 튜닝",
    performances = "성능",
    neons = "네온",
    extra = "Extra",
    klaxon = "경적",
    teinte_fenetre = "틴팅",
    phares_xenons = "제논 전조등",
    modele_plaque = "플레이트 종류",
    livery = "Livery",
    headlight_color = "전조등 색상",
    wheel_type = "휠 종류",
    primary_wheel_type = "휠 종류",
    back_wheel_type = "리어 휠 종류",
    wheel_color = "휠 색상",
    tire_smoke = "타이어 연기",
    custom_color = "색상 튜닝",
    custom_wheel = "타이어 튜닝",
    custom_back_wheel = "리어 휠 튜닝",
    suspension = "서스펜션",
    transmission = "트랜스미션",
    moteur = "엔진",
    frein = "브레이크",
    turbo = "터보",
    primary_color = "1차 색상",
    secondary_color = "2차 색상",
    interior_color = "인테리어 색상",
    dashboard_color = "대쉬보드 색상",
    color_effect = "광택 색상",
    left_neon = "좌측 네온",
    right_neon = "우측 네온",
    front_neon = "전면 네온",
    back_neon = "후면 네온",
 
    aileron = "스포일러",
    pc_front = "앞 범퍼",
    pc_back = "뒷 범퍼",
    carroserie = "측면 스커트",
    exhaust = "배기구",
    cadre = "차체",
    calandre = "그릴",
    capot = "후드",
    gb_left = "좌측 펜더",
    gb_right = "우측 펜더",
    roof = "지붕",
    plate_support = "플레이트 홀더",
    front_plate = "전면 플레이트",
    interior_style = "인테리어 스타일",
    figurine = "입상",
    motif_dashboard = "대쉬보드 색상",
    cadran = "다이얼 디자인",
    haut_parleur_portes = "도어 스피커",
    motif_sieges = "의자 스타일",
    volant = "스티어링",
    levier = "싱크대",
    logo_custom = "브랜드 로고",
    ice = "얼음",
    haut_parleur_coffre = "후면 도어스피커",
    hydrolique = "유압",
    moteur = "엔진",
    filtres_air = "공기 필터",
    entretoises = "스페이서",
    arc_couverture = "아치 덮개",
    antenne = "안테나",
    motif_exterieur = "외부 패턴",
    reservoir = "연료탱크",
    window = "창문",
    style = "스타일",
    default = "순정",
    type = "종류",
    normal = "기본",
    black = "검은색",
    black_smoke = "진한 틴팅",
    simple_smoke = "기본 틴팅",
    stock = "순정",
    limo = "리무진",
    sa_black = "San Andreas 검은색",
    sa_blue = "San Andreas 파란색",
    sa_white = "San Andreas 하얀색",
    simple_white = "하얀색",
    ny_white = "North Yankton 하얀색",
    race = "레이스",
    sport = "스포츠",
    stock = "순정",
    street = "스트리트",
    discount = "할인",
    select_your_car = "차량을 선택해주십시오.",
    select_car_custom = "튜닝할 차량을 선택하여주십시오.",
    loading_vehicle = "차량을 불러오는 중",
    invalid_vehicle = "~r~유효하지 않은 차량입니다.",
    invalid_vehicle_please_spawn = "~r~유효하지 않은 차량입니다. 차량을 한 번 소환 후 재시도해주십시오.",
    free_take_and_validate = "차량 튜닝은 무료입니다.",
    car_custom_saved = "~g~차량 튜닝이 저장되었습니다.",
 
    -- Character creation
    character_creation = "캐릭터 생성",
    confirm = "확정하다",
    start_playing = "게임 시작",
    appearance = "외모",
    character_list = "캐릭터 목록",
    face_features = "얼굴 특징",
    parents = "유전",
    parent = "유전",
    mix = "혼합",
    skin = "피부",
    desc_mix = " 얼굴을 아버지 / 어머니 중 어느쪽의 영향을 더 받을지 선택해주십시오.",
    desc_skin = " 피부를 아버지 / 어머니 중 어느쪽의 영향을 더 받을지 선택해주십시오.",
    identity = "identity",
    player_name = "플레이어 이름",
    new_character = "새 캐릭터",
    warning_headblend = "~r~캐릭터의 유전자를 선택해주십시오.",
    warning_overlays = "~r~캐릭터의 헤어스타일, 눈썹, 수염을 선택해주십시오.",
    warning_identity = "~r~Warning.~n~~w~신원을 입력해주십시오.",
 
    -- kits
    kit_does_not_exist = "~r~이 키트는 존재하지 않습니다.",
    kit_needs_rank = "이 키트를 사용하려면 ~r~%s~w~등급이 필요합니다.",
    wait_before_using_kit = "이 키트는 ~r~%s~w~ 뒤에 사용 가능합니다.",
    received_kit = " ~b~%s~w~ 를 받았습니다.",
    no_kit = "사용할 수 있는 키트가 없습니다.",
 
    unable_to_find_booster = "보유 중인 부스터를 찾을 수 없습니다.",
    wait_already_player_boost = "이미 부스터가 활성화되어있습니다.",
    wait_already_crew_boost = "이미 크루 부스터가 활성화되어있습니다.",
    wait_already_server_boost = "이미 서버부스터가 활성화되었습니다.",
    booster_activated = " ~b~XP +%s%% 부스터가 ~g~%s분~w~ 남았습니다.",
    server_booster_activated = "~b~%s~w~ ~b~XP +%s%% 부스터가 ~g~%s분~z~ 남았습니다.",
    crew_booster_activated = "~b~%s~w~ ~b~XP +%s%%부스터가 ~g~%s분~z~ 남았습니다.",
    no_booster = "보유 중인 부스터가 없습니다.",
 
    rank_expired = "~r~후원등급이 만료되었습니다.",
    supporter_role = "~g~후원등급:~w~ %s",
    no_rank_warning = "후원등급이 존재하지 않습니다.\n~r~결제를 진행했다면 FiveM계정을 로그인하십시오.",
    no_fivem_id = "FiveM 계정이 게임과 연동되어있지 않습니다.\n~r~FiveM계정을 연동하십시오.",
    no_queue_warning = "보유 중인 패키지가 존재하지 않습니다. \n~r~후원등급을 확인하려면 /getRank 를 입력하십시오.",
    package_sync_success = "~g~패키지가 적용되었습니다! \n~w~ 명령어: /getRank, /booster",
 
    level_required = " %s 만큼의 레벨이 필요합니다.",
    rank_required = " %s 만큼의 등급이 필요합니다.",
    level_required_2 = "~r~ %s 만큼의 레벨이 필요합니다.",
 
    updated_deathmessage = "~g~킬 메세지를 수정하였습니다.",
    updated_deatheffect = "~g~킬 효과를 수정하였습니다.",
    use = "사용하기",
    test = "실험하기",
 
    -- zombie
    you_bitten = "~r~좀비에게 물렸습니다.",
    infection_rate = "감염율: ~r~%s%%",
 
    -- ranks
    thug = "자객",
    hustler = "사기꾼",
    soldier = "군인",
    trigger = "방아쇠",
    enforcer = "집행자",
    facilitator = "협력자",
    public_enemy = "공공의 적",
    shot_caller = "결정권자",
    street_boss = "골목대장",
    kingpin = "주인공",
    -- Tattoo
    tattoo = "문신",
    tattoos = "문신",
    torso = "몸",
    head = "머리",
    left_arm = "왼쪽 팔",
    right_arm = "오른쪽 팔",
    left_leg = "왼쪽 다리",
    right_leg = "오른쪽 다리",
    unknown = "알 수 없음",
    other = "기타",
    remove_tattoo = "문신 전체 제거",
    -- Hairdress
    haircuts = "헤어스타일",
    makeup = "메이크업",
    face = "얼굴",
    eyebrows = "눈썹",
    facial_hair = "수염",
    body_hair = "체모",
    barber_shop = "이발소",
    face_makeup = "얼굴화장",
    lipstick = "립스틱",
    face_foundation = "얼굴 파운데이션",
    skin_blemishes = "피부 결점",
    skin_ageing = "피부 노령화",
    moles_freckles = "점 & 주근깨",
    sun_damage = "피부 손상",
    skin_complexion = "피부색",
    body_blemishes = "몸 잡티",
    body_blemishes_2 = "몸 잡티 2",
    opacity = "투명도",
    variations = "변형",
    filter = "필터",
    eyes_color = "눈 색깔",
    -- Mask
    masks = "가면",
    -- Items
    money = "달러",
    -- Ammo
    ["9mm"] = "9mm",
    ["300_mag"] = ".300 매그넘",
    ["7_62mm"] = "7.62mm",
    ["calibre_12"] = "12게이지",
    ["45_acp"] = ".45 ACP",
    ["5_56mm"] = "5.56mm",
 
    mask = "가면",
    clean_kit = "청소도구",
    radio = "라디오",
    recyclor = "재활용",
    medkit = "구급상자",
    kevlar = "방탄복",
    gps = "GPS",
    repair_tool = "수리도구",
    engine_veh = "엔진",
    wheel_veh = "타이어",
    paint_spray = "페인트",
    spike = "스파이크",
    bandage = "붕대",
    gaz_mask = "가스 마스크",
    filter = "필터",
 
    pickup_spikestrip = "스파이크 줍기",
    you_dropped_spikestrip = "~g~스파이크~w~를 깔았습니다.",
    you_pickup_spikestrip = "~g~스파이크~w~를 주웠습니다.",
 
    you_have_been_killed_by = "~r~%s 에 의해 사망했습니다.",
    kill_notif = "~m~처치",
    you_killed = "~r~%s~w~을(를) 처치하였습니다",
    already_used_reset_only = "~r~이미 캐틱터를 초기화했습니다.\n~w~오직 %s~w~멤버만이 캐릭터를 두 번 이상 초기화가 가능합니다.",
    already_used_reset_only2 = "~r~이미 했습니다.\n~w~오직 %s~w~만 두 번 이상 가능합니다.",
 
    hud_options = "HUD 옵션",
    advanced_hud = "보조 HUD 표시",
    players = "플레이어",
    health = "체력",
    player_menu = "플레이어 메뉴",
 
    you_are_now_zombie = "~r~이제 좀비입니다.",
 
    my_weapons = "내 무기",
    customize_weapons = "내 무기를 커스텀하다",
    weapon_skin = "무기 스킨",
 
    -- camo
    skin_classic = "기본",
    skin_green = "초록색",
    skin_yellow = "노란색",
    skin_pink = "핑크색",
    skin_gold = "황금색",
    skin_blue = "파란색",
    skin_orange = "주황색",
 
    -- new
    airdrop_coming = "~r~공중보급이 투하됩니다, 지도에서 위치를 확인하세요.",
    killed_by_cheater = "~r~부정프로그램 사용자에게 사망하였습니다.\n~w~부정프로그램 사용자를 추방하고 사망은 무효화됩니다.",
 
    corrupted_vehicle = "~r~이 차량은 중복된 차량입니다, 이 차량은 인벤토리에서 삭제되었습니다. 만약 오해가 있었다면 죄송합니다.",
 
    -- Discord
    join_discord_for_kit = "디스코드 키트를 무료로 지원받기위해 우리의 디스코드에 가입하세요!!\n~g~discord.gg/gtalife",
    discord_account_not_linked = "~r~디스코드 계정과 FiveM의 연동이 필요합니다.",
    discord_account_not_guild = "~r~디스코드서버에 가입되어있지 않습니다.\n~w~가입하세요, discord.gg/gtalife",
 
    already_done_recently = "~r~잠시후에 다시 시도해주십시오, 이미 최근에 그것을 했습니다.",
    update_country = "국가 수정",
 
    prestige_info = "~b~최대레벨에 도달했습니다.\n~w~/prestige 로 명성 시스템에 대해 알아보십시오.",
    prestige_not_max_level = "~r~최대레벨에 도달하지 않았습니다.",
    max_prestige_reached = "~r~더이상 환생 할 수 없습니다.",
    prestige_info_cmd = [[^3Prestige leveling system^7
현재 환생 ^4%s^7번, 레벨 ^5%s^7입니다.
 
만약 최대레벨에 도달했다면 (%s) 환생할 수 있습니다. 명성을 얻고 경험치를 1레벨로 초기화합니다.
새로운 명성을 얻으면 더 좋은 전리품, 새로운 아이템, 더 많은 돈 또는 더 높은 최대 가방 무게 같은 특별한 배지와 새로운 특전이 제공됩니다.
^2환생하려면  ^1/setprestige^2를 입력해주십시오.
]],
    new_prestige = "새로운 명성 포인트를 획득하였습니다!\n~g~현재 %s 보유 명성 포인트.",
    cant_store_event_veh = "~r~특별 차량은 보관 할 수 없습니다.",
 
    you_are_no_longer_in_combat = "🛡️ ~b~전투상태가 해제되었습니다.",
    you_are_in_combat_mode = "🛡️ ~b~전투상태에 돌입합니다.\n접속을 종료하면 캐릭터가 사망합니다.",
    you_disconnected_in_combat = "💀 이전에 전투상태에서 접속을 종료하였습니다, 캐릭터가 사망했습니다.",
 
    not_enough_prestige_points = "~r~포인트가 충분하지 않습니다.",
    you_reached_max_prestige_stats_rank = "~r~이미 업그레이드 최대치에 도달했습니다",
    new_prestige_stats_upgrade = "~b~%s~w~\n~g~%s/%s을(를) 업그레이드 하였습니다.",
 
    legendary_vehicle_pop = "~r~특별 차량이 생성 됐습니다 지도를 확인하세요.",
 
    combat_mode_container_disabled = "~r~전투상태 입니다.\n~w~컨테이너에 아이템을 보관할 수 없습니다.",
    gcoins_wallet_updated = "~g~GCoins이 업데이트 되었습니다. \n~w~+%s GCoins",
    not_enough_gcoins = "~r~보유중인 GCoin이 부족합니다.",
    gcoins_something_went_wrong = "~r~무언가가 잘못되었습니다.",
    you_bought_with_gcoins = "~g~%s~w~을(를) ~b~%s GCoins~w~에 구입하였습니다.",
 
    equiping_armor = "방탄복을 착용중",
 
    toggle_mute_player = "차단",
    you_muted_this_player = "~b~를 차단했습니다.",
    you_unmuted_this_player = "~b~의 차단을 해제하였습니다.",
}
 
AddLanguage("ko", my_language)