local my_language = {
    give_vehicle = "Adicionaste ~b~%s~w~ ao teu inventário.",
    store_vehicle_command = "Guardar o veículo atual.",
    no_entity_vehicle = "~r~Veículo inexistente ou longe de ti.",
    no_entity_vehicle_id = "~r~Veículo sem ID associado, não o podes guardar.",
    store_vehicle = "~b~Guardaste o teu veículo.",
    teleported_former_position = "~g~Foste teleportado para a tua última localização.",
    not_enough_of = "~r~Falta-te: %s.",
    max_storage_chest = "~r~O teu baú está cheio.",
    cant_carry_more_items = "~r~O teu inventário está cheio.",
    put_item = "Colocaste ~g~x%s~w~ %s~w~.",
    take_item = "Retiraste ~g~x%s~w~ %s~w~.",
    delete_item = "Eliminaste ~r~x%s~w~ %s~w~.",
    you_equiped_item = "Equipaste ~g~%s~w~.",
    bind_weapon_command = "Atalho para arma %s",
    kevlar_broke = "~r~AHH!~n~~w~O teu kevlar partiu-se.",
    inventory_command = "Abrir inventário",
    press_enter_to_join = "Aperta ~g~ENTER~w~ para começar a jogar.",
    new_character = "Nova personagem",
    survivor = "Sobrevivente",
    right = "Direita",
    left = "Esquerda",
    male = "Masculino",
    female = "Feminino",
    ped = "Ped",
    name = "Nome",
    sex = "Sexo",
    title = "Título",
    select_this_character = "Seleciona esta personagem",
    no_entity_zombie = "Zombie não existe ou está demasiado longe de ti.",
    you_found = "Encontraste ~g~%sx %s~w~.",
    you_found_nothing = "Não encontraste ~g~nada~w~.",
    press_e_to_loot = "Aperta ~b~[E]~w~ para lootear",
    full_for_item = "~r~Não existe espaço para este item.",
    put_item_container = "Colocaste ~g~x%s~w~ %s~w~ no teu contentor.",
    take_item_container = "Retiraste ~g~x%s~w~ %s~w~ do teu contentor.",
    not_allowed_here = "~r~Não podes fazer isso aqui.",
    cant_store_moving_veh = "~r~Não podes guardar um veículo em movimento.",
    use_repair_tool = "Usa o kit de reparação",
    please_get_closer = "~b~Aproxima-te, nenhuma entidade perto.",
    you_cancel_action = "~r~Cancelaste a ação.",
    selected_target_message = "Alvo selecionado:~n~%s~n~~r~Aperta ~b~Y~r~ para cancelar~n~~r~Aperta ~g~X~r~ para continuar.",
    target_you = "~b~Tu",
    target_screen = "~g~Exibido",
    take_this_path = "Escolha este destino",
 
    -- hud
    default_hud = "Default HUD",
    cinema_hud = "Cinema HUD",
    no_hud = "No HUD",
 
    -- perms
    kick_member = "Expulsar membros",
    edit_member = "Editar membros",
    edit_rank = "Editar cargos",
    create_rank = "Criar cargos",
    delete_rank = "Eliminar cargos",
    edit_structure = "Editar informações da crew",
    edit_permissions = "Editar permissões",
    permission_level = "Nível de permissões",
    red_delete = "Eliminar",
    rank = "Cargo",
    red_kick = "Expulsar",
    crew_name = "Nome da crew",
    slogan = "TAG",
    information = "Informação",
    boss_rank = "Nome do cargo do fundador",
    member_rank = "Nome do cargo inicial",
    member = "Membro",
 
    permissions_manager = "Gerenciador de permissões",
    members_manager = "Gerenciador de membros",
    ranks_manager = "Gerenciador de cargos",
    ranks_list = "Lista de cargos",
    members_list = "Lista de membros",
    create_a_rank = "Criar um rank",
    invite_someone = "Convidar um jogador",
    stats = "Estatísticas",
    total_ranks = "Contador de cargos",
    total_members = "Contador de membros",
    level = "Nível",
    actions = "Ações",
    crew_manager = "Gerenciador da crew",
    you_created_a_new_crew = "Criaste uma nova crew: %s",
    you_deleted_your_crew = "Eliminaste a tua crew.",
    you_are_not_in_a_crew = "Não estás numa crew.",
    you_joined_the_crew = "Entraste na crew: '%s'",
    kick_failed = "A expulsão falhou, motivo: %s",
    already_in_crew = "Já estás numa crew.",
    no_invitation = "Não recebeste nenhum convite.",
    left_crew = "Saiste da crew atual.",
    permission_updated = "As permissões de <C>~g~%s</C>~w~ foram atualizadas.",
    incorrect_name = "~r~O formato do nome está incorreto.",
    incorrect_rank_perm = "~r~Erro\n~w~O nome do cargo ou o nível de permissão está inválido.",
    warn_rank_limit = "~r~Alcançaste o límite de cargos.",
    create_rank_success = "~g~Sucesso\n~w~Criaste um novo rank <C>~b~%s</C>~w~ com o nível de permissão a <C>~b~%s</C>~w~.",
    crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~Não podes interagir com um membro de cargo superior ao teu.",
    you_sent_an_invitation = "Enviaste um convite a <C>~g~%s</C>~w~ para se juntar à tua crew.",
    you_received_an_invitation = "Recebeste um convite para te juntares a uma crew.\n~b~/%s para aceitar.",
    invitation_expired = "O convite expirou.",
    crew_kick_success = "Expulsaste <C>~b~%s</C>~w~ da tua crew.",
    first_rank_warning = "O primeiro cargo é o 'default'.",
 
    you_updated_this = "Atualizaste %s para ~g~<C>%s</C>~w~.",
    changes_saved_on = "As mudanças feitas em <C>~g~%s</C>~w~ foram salvas.",
    yes = "sim",
    no = "não",
    none = "nenhum",
    character_id = "ID de personagem",
    server_id = "ID do servidor",
    report = "Reportar",
    rename = "Renomear",
    trade_with = "Troca",
    
    please_wait_x_before = "~r~Espera %s segundos antes de fazeres isso.",
 
    -- cloth
    take_outfit = "Comprar este outfit",
    wardrobe_options = "Opções de guarda-fatos",
    wardrobe = "guarda-fatos",
    manual_options = "Opções manuais",
    manual_mode = "Modo manual",
    save_outfit = "Salvar este outfit",
    variation = "variação",
    outfits = "outfits",
    cloth_shop = "Loja de roupa",
    ped_cloth_shop = "Loja de roupa de ped",
    manual_props = "props manuais",
    manuel = "manual",
    new_name = "Novo nome",
    outfit_name = "Nome do outfit",
    variations_saved = "~g~Successo.~n~~w~A variação da tua personagem foi salva.",
    equipped_new_outfit = "Equipaste o teu novo outfit: ~b~%s",
    warning_limit_outfits = "Alcançaste o limite de outfits. ~g~(%s)",
    saved_new_outfit = "Salvaste um novo outfit: ~b~%s~w~.",
    rename_outfit = "O teu outfit ~b~%s~w~ foi renomeado para ~g~%s~w~.",
    delete_outfit = "O teu outfit: ~b~%s~w~ foi eliminado.",
 
    torso = "Torso",
    props = "Props",
    top = "Camisas/Casacos",
    tops = "Tops",
    badge = "Badge",
    pants = "Calças",
    pant = "Calças",
    shoes = "Sapatos",
    bags = "Mochilas",
    undershirt = "T-shirts",
    neck = "pescoço",
    bracelets = "pulseiras",
    montres = "relógios",
    earrings = "ouvidos",
    glasses = "óculos",
    hats = "chapéus",
    graphiques = "decorações",
 
    -- health
    inconscious = "Inconsciente",
    doing_something = "Fazer algo",
    time_before_respawn = "Tempo até dar respawn",
    you_died = "~r~Morreste.",
    healing_wounds = "A curar-se",
    already_doing_something = "~r~Já estás a fazer algo.",
    you_have_been_healed = "~g~Estás curado.",
    you_respawned = "~g~Foste respawnado.",
 
    player_too_far_to_interact = "~r~O jogador com que queres interagir está demasiado longe de ti.",
    send_trade_invitation_to = "Enviaste um pedido de troca a ~b~%s~w~.\n~b~Espera que o jogador aceite.",
    receive_invitation_from = "Recebeste um pedido de troca de ~b~%s~w~.\n~b~Escreve ~w~/trade accept %s~b~ para começar a troca.",
 
    invalid_command_args = "Argumentos inválidos no comando: %s",
    start_trade_command_help = "Começa uma troca com um jogador",
    accept_trade_command_help = "Aceitar uma troca",
    deny_trade_command_help = "Rejeitar uma troca",
    invalid_invitation = "O pedido de troca está inválido ou já não existe.",
    name_accepted_your_trade_invitation = "~b~%s~w~ aceitou o teu pedido de troca",
    you_accepted_trade_invitation_of_name = "Aceitaste o pedido de troca de %s",
    name_denied_your_trade_invitation = "~b~%s~w~ recusou o teu pedido de troca",
    you_denied_trade_invitation_of_name = "Recusaste o pedido de troca de %s",
    you_already_trading = "Já estás a realizar uma troca",
    other_already_trading = "O outro jogador já está a realizar uma troca",
 
    other_player_not_enough_money = "~r~A troca falhou. O jogador não tinha dinheiro suficiente.",
    you_player_not_enough_money = "~r~A troca falhou. Não tinhas dinheiro suficiente.",
    other_player_not_enough_item = "~r~A troca falhou. O jogador não tinha um item suficiente.",
    you_player_not_enough_item = "~r~A troca falhou. Não tinhas um item suficiente.",
    success_trade = "~g~A troca foi sucedida.",
    fail_trade_other_player = "~r~A troca falhou, o jogador saiu.",
    trade_other_full_item = "~r~A troca falhou. O jogador não tinha espaço suficiente.",
    trade_full_for_item = "~r~A troca falhou. Não tinhas espaço suficiente.",
 
    press_e_to_loot_inv = "Aperta ~INPUT_CONTEXT~ para lootear o inventário.",
    press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~Aperta ~INPUT_CONTEXT~ para interagir com ~b~%s~HUD_COLOUR_NET_PLAYER27~.",
    press_e_to = "Aperta ~INPUT_CONTEXT~ para ~b~%s~w~.",
    press_e_to_open_catalog = "Aperta ~b~E~w~ ler o ~g~catálogo~w~.",
    this_person = "esta pessoa",
    the_shop = "esta loja",
    you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~Não podes fazer isso.",
 
    no_weapon = "~r~Não tens a tua arma equipada.",
    no_need_ammo = "~r~Não precisas de usar munição nesta arma.",
    not_right_ammo = "~r~Não estás a usar a munição certa, precisas de ~b~%s~w~.",
    you_used_ammo = "Carregaste a tua ~b~%s~w~ com ~b~x%s~w~ de ~b~%s~w~.",
 
    choose_a_destination = "escolhe um ~b~destino",
    open_your_chest = "abre o teu baú",
    no_enough_money = "~r~Não tens dinheiro suficiente.",
    you_paid = "Pagaste ~g~$%s~w~ por ~b~%s~w~.",
    you_paid_basket = "Pagaste ~g~$%s~w~ pelo teu cesto.",
    you_sell_basket = "Recebeste ~g~$%s~w~ por vender ~b~x%s~w~ item(s).",
 
    you_repaired_your_vehicle = "~g~Reparaste o teu veículo.",
    repairing_your_vehicle = "A reparar o veículo",
    wheels_are_fine = "~r~Os pneus do veículo estão boas.",
    changing_wheel = "A trocar os pneus",
    you_repaired_the_wheels = "~g~Trocaste os pneus do teu veículo.",
 
    front_post_ls = "Posto de Los Santos",
    front_post_ls_2 = "Posto de Los Santos 2",
    front_post_bc = "Posto de Blaine County",
    front_post_bc_2 = "Posto de Blaine County 2",
    main_post_ls = "Posto Avançado de Los Santos",
    main_post_bc = "Posto Avançado de Blaine County",
    random_zone = "Zona Aleatória (landing)",
 
    this_item_is_equipped = "~r~Este item está equipado, remove-o dos teus atalhos.",
    only_in_safezone = "~r~Não podes fazer isso fora de uma zona segura.",
    -- commerce stuff
    feature_gold_only = "Este recurso está apenas disponivel para membros ~y~gold~w~.",
    feature_diamond_only = "Este recurso está apenas disponivel para membros ~b~diamond~w~.",
    you_turned_into = "Tornaste-te num ~g~%s~w~.",
    wait_between_transformation = "~r~Aguarda um momento antes de usares o Morph Mode novamente.",
    wait_between = "~r~Aguarda um momento antes de fazeres isso novamente.",
    available_morphs = "Morphs disponíveis",
    animal_models = "Modelos de animais",
    zombie_models = "Modelos de zombies",
    success_update_name = "Mudaste o nome da tua personagem para ~b~%s~w~.",
    success_reset_stats = "~g~Redefiniste as tuas estatísticas. (Serão atualizadas em alguns minutos)",
 
    -- animals
    boar = "Javali",
    cat = "Gato",
    chop = "Rottweiler (Chop)",
    rottweiler = "Rottweiler",
    cow = "Vaca",
    coyote = "Coyote",
    deer = "Viado",
    hen = "Galinha",
    husky = "Husky",
    mtlion = "Leão",
    pig = "Porco",
    poodle = "Poodle",
    pug = "Pug",
    rabbit = "Coelho",
    rat = "Rato",
    retriever = "Retriever",
    shepherd = "Ovelha",
    westy = "Westy",
 
    player_id = "ID do jogador",
    bounty = "Recompensa",
    reason = "Motivo",
    id_player_not_found = "~r~Não existe nenhum jogador com este ID.",
 
    ammo_dealer = "Loja de munições",
    misc_dealer = "Loja de equipamentos",
    veh_dealer = "Loja de veículos",
    custom_dealer = "LS Custom",
    gun_dealer = "Loja de armas",
 
    bounty_created = "Pagaste ~g~$%s~w~ para criar uma caça ao homem a ~b~%s~w~.",
    contract_success = "A caça ao homem a ~r~%s~w~ foi enviada para ~b~%s~w~.",
    a_contract_on_your_head = "~r~Tens uma caça à tua cabeça. Quem te matou recebeu a recompensa.",
    reward_for_contract = "Caça ao homem! Foste recompensado com ~g~$%s~w~ por matar ~b~%s~w~.",
 
    hey_can_help_you = "Hey, como te posso ajudar?",
    i_want_to_buy_items = "Eu quero comprar items",
    i_want_to_sell_items = "Eu quero vender items",
 
    press_context_or_jump_to_get_up = "Aperta ~INPUT_CONTEXT~ ou ~INPUT_JUMP~ para ~b~ficares de pé~w~.",
    server_restart_warning = "O servidor irá reiniciar..",
    auto_restart_in = "Restart automático em %s segundos.",
 
    not_allowed_create_character = "Não podes criar uma nova personagem.",
    character_not_yours = "Esta personagem não é tua.",
    character_does_not_exist = "Esta personagem não existe ou já não existe.",
    loading_character = "A carregar a tua personagem...",
 
    playtime_is = "~b~O teu tempo de jogo no Extinction:\n~w~%s",
    dont_spam = "^1Não faças spam!",
 
    babygod_warning = "~b~Saiste da zona segura, estás invencível por algum tempo, encontra um local seguro!",
 
    -- LS Custom
    modifications_classiques = "Modificações clássicas",
    modifications_custom = "Modificações especiais",
    modifications_benny = "Benny's modifications",
    paint = "pintura",
    custom_your_car = "Modificar o teu veículo",
    wheels_modifications = "Modificações de pneus",
    performances = "Performances",
    neons = "Neons",
    extra = "Extra",
    klaxon = "Buzina",
    teinte_fenetre = "Películas de vidros",
    phares_xenons = "Faróis Xenon",
    modele_plaque = "Modelo de matrícula",
    livery = "Autocolantes",
    headlight_color = "Cor de faróis",
    wheel_type = "Tipo de roda",
    primary_wheel_type = "Tipo de roda frontal",
    back_wheel_type = "Tipo de roda traseira",
    wheel_color = "Cor da roda",
    tire_smoke = "Fumo do pneu",
    custom_color = "Cor personalizada",
    custom_wheel = "Roda personalizada",
    custom_back_wheel = "Roda traseira personalizada",
    suspension = "Suspensão",
    transmission = "Transmissão",
    moteur = "Motor",
    frein = "Travões",
    turbo = "Turbo",
    primary_color = "Cor primária",
    secondary_color = "Cor secundária",
    interior_color = "Cor interior",
    dashboard_color = "Cor do tablier",
    color_effect = "Cor de efeito",
    left_neon = "Neon esquerdo",
    right_neon = "Neon direito",
    front_neon = "Neon frontal",
    back_neon = "Neon traseiro",
 
    aileron = "Spoiler",
    pc_front = "Parachoque frontal",
    pc_back = "Parachoque traseiro",
    carroserie = "Saias laterais",
    exhaust = "Escape",
    cadre = "Frame",
    calandre = "Grelha",
    capot = "Capô",
    gb_left = "Pára-lama esquerdo",
    gb_right = "Pára-lama direito",
    roof = "Tejadilho",
    plate_support = "Suportes de matrícula",
    front_plate = "Matrícula frontal",
    interior_style = "Estilo do interior",
    figurine = "Figurino",
    motif_dashboard = "Estilo do tablier",
    cadran = "Dial design",
    haut_parleur_portes = "Colunas de portas",
    motif_sieges = "Estilo dos assentos",
    volant = "Volante",
    levier = "Manete de mudanças",
    logo_custom = "Logo",
    ice = "ICE",
    haut_parleur_coffre = "Colunas de portas traseiras",
    hydrolique = "Hidráulicas",
    moteur = "Motor",
    filtres_air = "Filtros de ar",
    entretoises = "Espaçadores",
    arc_couverture = "Arch",
    antenne = "Antena",
    motif_exterieur = "Estilo exterior",
    reservoir = "Tanque",
    window = "Janela",
    style = "Estilo",
    default = "Default",
    type = "Type",
    normal = "Normal",
    black = "Preto",
    black_smoke = "Fumo preto",
    simple_smoke = "Fumo simples",
    stock = "Estoque",
    limo = "Limousine",
    sa_black = "San Andreas preto",
    sa_blue = "San Andreas azul",
    sa_white = "San Andreas branco",
    simple_white = "Branco simples",
    ny_white = "North Yankton branco",
    race = "Corrida",
    sport = "Desportivo",
    stock = "Stock",
    street = "de Rua",
    discount = "Desconto",
    select_your_car = "Seleciona o teu veículo",
    select_car_custom = "Seleciona o veículo que queres modificar. Os números entre as setas são as item keys.",
    loading_vehicle = "A criar veículo",
    invalid_vehicle = "~r~Entidade de veículo inválida.",
    invalid_vehicle_please_spawn = "~r~Item de veículo inválido. Por favor spawna o veículo antes de o modificares.",
    free_take_and_validate = "É tudo grátis. Escolhe o que queres e confirma!",
    car_custom_saved = "~g~As modificações do veículo foram salvas.",
 
    -- Character creation
    character_creation = "Criação de personagem",
    confirm = "confirmar",
    start_playing = "Começar a jogar",
    appearance = "aparência",
    character_list = "lista de personagens",
    face_features = "Personalizações na cara",
    parents = "parentes",
    parent = "parente",
    mix = "mistura",
    skin = "pele",
    desc_mix = "Seleciona se a forma da tua cara é mais influenciada pelo teu pai / mãe.",
    desc_skin = "Seleciona se a tua pele é mais influenciada pelo teu pai / mãe.",
    identity = "identidade",
    player_name = "nome do jogador",
    new_character = "nova personagem",
    warning_headblend = "~r~Não selecionaste os parentes da tua personagem.",
    warning_overlays = "~r~Não selecionaste o cabelo, sobrancelhas ou barba.",
    warning_identity = "~r~Aviso.~n~~w~Esqueceste-te de preencher a aba de identidade.",
 
    -- kits
    kit_does_not_exist = "~r~Este kit não existe.",
    kit_needs_rank = "Não possuis ~r~%s~w~ rank.",
    wait_before_using_kit = "Por favor, espera ~r~%s~w~ antes de usares este kit.",
    received_kit = "Recebeste o teu kit ~b~%s~w~.",
    no_kit = "Não tens nenhum kit.",
 
    unable_to_find_booster = "Impossível encontrar um boost com este id.",
    wait_already_player_boost = "Por favor espera um momento antes de usares este boost. Já existe um boost ativo.",
    wait_already_crew_boost = "Por favor espera um momento antes de usares este boost. Já existe um boost de crew ativo.",
    wait_already_server_boost = "Por favor espera um momento antes de usares este boost. Já existe um boost de servidor ativo.",
    booster_activated = "Boost ativo por ~g~%s minutos~w~! ~b~XP +%s%%",
    server_booster_activated = "~b~%s~w~ ativou um boost ao servidor por ~g~%s minutos~z~! ~b~XP +%s%%",
    crew_booster_activated = "~b~%s~w~ ativou um boost de crew por ~g~%s minutos~z~! ~b~XP +%s%%",
    no_booster = "Não possuis nenhum boost.",
    
    dungeon_cooldown_between = "Aguarda ~r~%s minutos~w~ antes de começares outra dungeon.",
	set_as_default = "Define um preset para o teu veículo",
	car_custom_presets_saved = "O teu preset para ~g~%s~w~ foi guardado.",
    marketplace_you_received_x_x = "Recebeste ~b~%sx ~g~%s~w~.",

	above_level_x_no_longer_possible_loot_safe = "Jogadores acima do rank %s não podem lotear zombies dentro de zonas seguras.",
	preferred_component_desc = "Este será o teu preset para todas as %s que segurares.",
	set_as_preferred_component_class = "Definir preset para arma",
	weapon_presets_updated = "Guardaste o preset para ~g~%s~w~.",
 
    rank_expired = "~r~O teu rank expirou.",
    supporter_role = "~g~Rank:~w~ %s",
    no_rank_warning = "Não possuis nenhum rank.\n~r~Se compraste algo associa a tua conta de FiveM.",
    no_fivem_id = "A tua conta de FiveM não está associada ao jogo.\n~r~Verifica que tens uma conta de FiveM e associa-a ao jogo.",
    no_queue_warning = "Não tens nenhum pacote em espera.\n~r~Espera um momento ou experimenta /getRank se estás à procura do teu rank.",
    package_sync_success = "~g~Os teus pacotes foram sincronizados, disfruta!\n~w~Comandos que podes utilizar: /getRank, /booster",
 
    level_required = "Precisas de ser nível %s.",
    rank_required = "Precisas de ter rank %s.",
    level_required_2 = "~r~Precisas de ser nível %s.",
 
    updated_deathmessage = "~g~Atualizaste a tua mensagem de morte.",
    updated_deatheffect = "~g~Atualizaste os teus efeitos de morte.",
    use = "Usar",
    test = "Testar",
 
    -- zombie
    you_bitten = "~r~Foste mordido.",
    infection_rate = "Percentagem de infeção: ~r~%s%%",
 
    -- ranks
    thug = "Thug",
    hustler = "Hustler",
    soldier = "Soldier",
    trigger = "Trigger",
    enforcer = "Enforcer",
    facilitator = "Facilitator",
    public_enemy = "Public Enemy",
    shot_caller = "Shot Caller",
    street_boss = "Street Boss",
    kingpin = "Kingpin",
    -- Tattoo
    tattoo = "tattoo",
    tattoos = "tattoos",
    torso = "torso",
    head = "cabeça",
    left_arm = "braço esquerdo",
    right_arm = "braço direito",
    left_leg = "perna esquerda",
    right_leg = "perna direita",
    unknown = "desconhecido",
    other = "outro",
    remove_tattoo = "Remover todas as tatuagens",
    -- Hairdress
    haircuts = "Penteados",
    makeup = "Maquilhagem",
    face = "Rosto",
    eyebrows = "Sobrancelhas",
    facial_hair = "Pelo facial",
    body_hair = "Pelo corporal",
    barber_shop = "Barbeiro",
    face_makeup = "Maquilhagem facial",
    lipstick = "Baton",
    face_foundation = "Base facial",
    skin_blemishes = "Manchas na pele",
    skin_ageing = "Envelhecimento",
    moles_freckles = "Toupeiras e sardas",
    sun_damage = "Dano facial",
    skin_complexion = "Complemento da pele",
    body_blemishes = "Manchas no corpo",
    body_blemishes_2 = "Manchas no corpo 2",
    opacity = "Opacidade",
    variations = "Variações",
    filter = "Filtro",
    eyes_color = "Cor dos olhos",
    -- Mask
    masks = "Máscaras",
    -- Items
    money = "Dinheiro",
    -- Ammo
    ["9mm"] = "9mm",
    ["300_mag"] = ".300 Magnum",
    ["7_62mm"] = "7.62mm",
    ["calibre_12"] = "Calibre 12",
    ["45_acp"] = ".45 ACP",
    ["5_56mm"] = "5.56mm",
    rocket = "Rocket",
    flare = "Flare",
    grenade = "Grenade",
    -- Food
    ["fish_1"] = "Largemouth Bass",
    ["fish_2"] = "Rainbow Trout",
    ["fish_3"] = "Kokanee",
    ["fish_4"] = "Arctic Grayling",
    ["fish_5"] = "Rock Bass",
    ["fish_6"] = "Smallmouth Bass",
    ["fish_7"] = "Paddlefish",
    ["fish_8"] = "Bull Trout",
    ["fish_9"] = "Lake Trout",
    ["fish_10"] = "Chinook",
    ["fish_11"] = "Pallid Sturgeon",
    ["fish_12"] = "Salmon",
 
    misc_meat = "Raw meat",
    rabbit_meat = "Raw rabbit",
    lion_meat = "Raw lion",
    rare_plume = "Rare feather",
    dog_meat = "Raw dog",
    cat_meat = "Raw cat",
    rare_fish = "Rare fish",
 
    mask = "Mascarás",
    malette = "Mala",
    malette_metal = "Mala de metal",
    ciseaux = "Tesouras",
    clean_kit = "Kit de limpeza",
    fishing_rod = "Cana de pesca",
    meuble = "Mobília",
    tissu = "Pano",
    accessory = "Acessório",
    radio = "Rádio",
    recyclor = "Reciclador",
    medkit = "Kit Médico",
    kevlar = "Kevlar",
    gps = "GPS",
    repair_tool = "Kit de Reparação",
    jvn = "JVN",
    engine_veh = "Motor",
    wheel_veh = "Roda",
    vetement = "Roupas",
    bloc_note = "Bloco de notas",
    paint_spray = "Spray de tinta",
    spike = "Faixa de espigões",
    paracetamol = "Paracetamol",
    bandage = "Curativo",
    gaz_mask = "Máscara de gás",
    filter = "Filtro",
    tattoo_tool = "Máquina de tatuar",
    drug_med = "Droga",
    drug_antizin = "Shot de Antizin",
    drug_stamina = "Shot de Estamina",
    drug_berserker = "Shot de Vida",
 
    pickup_spikestrip = "Apanhar faixa de espigões",
    you_dropped_spikestrip = "Colocaste uma ~g~faixa de espigões~w~.",
    you_pickup_spikestrip = "Apanhaste uma ~g~faixa de espigões~w~.",
 
    you_have_been_killed_by = "Morreste para ~r~%s",
    kill_notif = "~m~Mataste",
    you_killed = "Mataste ~r~%s~w~",
    already_used_reset_only = "~r~Já refizeste a tua personagem.\n~w~Apenas membros %s~w~ podem fazer isso mais de uma vez.",
    already_used_reset_only2 = "~r~Já fizeste isso.\n~w~Apenas membros %s~w~ podem fazer isso mais de uma vez.",
 
    hud_options = "HUD options",
    advanced_hud = "Display advanced HUD",
    players = "Jogadores",
    health = "Vida",
    player_menu = "Menu de jogador",
 
    you_are_now_zombie = "~r~És um zombie.",
 
    my_weapons = "minhas armas",
    customize_weapons = "modificar arma",
    weapon_skin = "Pintura",
 
    -- camo
    skin_classic = "Default",
    skin_green = "Verde",
    skin_yellow = "Amarelo",
    skin_pink = "Rosa",
    skin_gold = "Dourado",
    skin_blue = "Azul",
    skin_orange = "Laranja",
 
    weapon_katana = "Katana",
    weapon_sledgehammer = "Martelo",
    -- new
    airdrop_coming = "~r~O airdrop está a caminho, verifica o teu mapa.",
    killed_by_cheater = "~r~Morreste para um cheater.\n~w~O jogador foi banido e a tua morte foi cancelada.",
 
    corrupted_vehicle = "~r~Este veículo está corrupto e foi duplicado no passado, foi removido do teu inventário. Desculpa se foste roubado.",
 
    -- Discord
    join_discord_for_kit = "Entra no nosso discord para receberes o kit discord!\n~g~discord.gg/gtalife",
    discord_account_not_linked = "~r~Precisas de associar o teu discord com o FiveM.",
    discord_account_not_guild = "~r~Não estás no nosso servidor de discord.\n~w~Entra em: discord.gg/gtalife",
 
    already_done_recently = "~r~Tenta novamente mais tarde, já fizeste isso recentemente.",
    update_country = "Atualizar país",
 
    prestige_info = "~b~Chegaste ao nível máximo.\n~w~Escreve /prestige para receberes informação do sistema de prestige.",
    prestige_not_max_level = "~r~Não chegaste ao nível máximo.",
    max_prestige_reached = "~r~Chegaste ao último prestige.",
    prestige_info_cmd = [[^3Sistema de prestiges^7
Atualmente estás no prestige ^4%s^7 e nível ^5%s^7.
 
Se chegares ao nível máximo (%s) podes escolher fazer prestige e reiniciares o teu XP e voltares ao nível 0.
Obter um novo prestige oferece-te um novo emblema especial e novos perks como melhor loot, novos items, mais dinheiro ou mais espaço no teu inventário.
^2Se quiseres fazer prestige e voltar ao nível 0 escreve ^1/setprestige^2
]],
    new_prestige = "Desbloqueaste um novo prestige!\n~g~Tens agora %s prestige(s)",
    cant_store_event_veh = "~r~Não podes guardar veículos lendários.",
 
    you_are_no_longer_in_combat = "🛡️ ~b~Já não estás em modo combate.",
    you_are_in_combat_mode = "🛡️ ~b~Estás em modo combate.\nSe saíres do servidor irás morrer.",
    you_disconnected_in_combat = "💀 Saíste do servidor em modo combate, morreste.",
 
    not_enough_prestige_points = "~r~Não tens pontos de prestige suficientes.",
    you_reached_max_prestige_stats_rank = "~r~Chegaste ao rank máximo para este perk.",
    new_prestige_stats_upgrade = "Melhoraste o teu ~b~%s~w~\n~g~%s/%s",
 
    legendary_vehicle_pop = "~r~Um veículo lendário apareceu no mapa.",
 
    combat_mode_container_disabled = "~r~Estás em combate.\n~w~Impossível guardar items.",
    gcoins_wallet_updated = "~g~A tua carteira de GCoins foi atualizada.\n~w~+%s GCoins",
    not_enough_gcoins = "~r~Não tens GCois suficientes.",
    gcoins_something_went_wrong = "~r~Algo correu mal.",
    you_bought_with_gcoins = "Compraste ~g~%s~w~ por ~b~%s GCoins~w~.",
 
    equiping_armor = "A equipar colete",
 
    toggle_mute_player = "Silenciar",
    you_muted_this_player = "~b~Silenciaste este jogador.",
    you_unmuted_this_player = "~b~Já podes ouvir este jogador.",
 
    already_purchased = "~r~Já compraste este item.",
    weapon_camo_preview = "Estás a pré-visualizar um modelo de arma, alguns attachs estão em falta.\n~INPUT_CELLPHONE_CANCEL~ para sair da pré-visualização.",
 
    already_using_a_seringue_booster = "~r~Já tomaste uma seringa disso.",
    seringue_effect_done = "~b~O efeito da seringa acabou.",
    you_injected_a_seringue_boost = "Injetaste um ~b~shot de seringa~w~ no teu sangue.",
 
    put_item_permission = "Colocar items",
    take_item_permission = "Retirar items",
    put_money_permission = "Colocar dinheiro",
    take_money_permission = "Retirar dinheiro",
 
    preferred_badge_set = "Definiste o teu  ~g~emblema preferido~w~.",
    preferred_badge_not_set = "~r~Impossível definir emblema.",
 
    marketplace_received_money_sales = "Recebeste ~g~$%s~w~ de ~b~%s~w~ venda(s).",
    marketplace_no_sales = "~r~Não vendeste nada.",
    marketplace_you_paid_for = "Pagaste ~g~$%s~w~ por ~b~%s~w~.",
 
    deleted_sell_offer = "~b~Apagaste a tua oferta de venda.",
    deleted_buy_offer = "~b~Apagaste a tua oferta de venda.",
 
    marketplace_offer_does_not_exist = "~r~Esta oferta já não existe.",
 
    marketplace_create_sell_offer = "Criaste uma oferta de venda de ~b~%sx %s ~w~por ~g~$%s~w~ por unidade.",
    marketplace_create_buy_offer = "Criaste uma oferta de compra de ~b~%sx %s ~w~por ~g~$%s~w~ por unidade.",
 
    i_want_to_enter_in_my_property = "Quero entrar na minha propriedade.",
    i_want_to_exit_private_world = "Quero voltar ao mundo público.",
    public_world = "Mundo Público",
    private_world = "Mundo Privado",
 
    dailymission_playerkill = "Jogadores Mortos",
    dailymission_zombiekill = "Zombies Mortos",
    dailymission_playerheadshotkill = "Headshots (Jogadores)",
    dailymission_zombieheadshotkill = "Headshots (Zombies)",
    dailymission_zombiesurvivorkill = "Zombies sobreviventes mortos",
    dailymission_zombiearmoredkill = "Zombies blindados mortos",
    dailymission_zombiehazmatkill = "Zombies hazmat mortos",
    dailymission_zoombieboomerkill = "Zombies boomers mortos",
    dailymission_sellitems = "Items vendidos",
    dailymission_buyitems = "Items comprados",
    dailymission_lootitems = "Items looteados",
    dailymission_createselloffer = "Oferta de venda criadas",
    dailymission_killtopkillcrew = "Jogadores mortos de crews",
    dailymission_killtopkillplayers = "Jogadores mortos",
    dailymission_getintolegendaryvehicle = "Veículos",
    dailymission_killzombiewithweapon = "Zombies mortos com arma",
    dailymission_killplayerwithweapon = "Jogadores mortos com arma",
    dailymission_darkzonesurvivingtime = "Tempo sobrevivido na Darkzone",
    dailymission_redzoneplayerkill = "Jogadores mortos na redzone",
    dailymission_redzonezombiekill = "Zombies mortos na redzone",
    dailymission_darkzoneplayerkill = "Jogadores mortos na darkzone",
    dailymission_darkzonezombiekill = "Zombies mortos na darkzone",
    dailymission_useitem = "Items usados",
    dailymission_playtime = "Tempo jogado",
    dailymission_xpharvest = "XP coletado",
    dailymission_sellofferpurchased = "Oferta de vendas compradas",
    dailymission_sellofferpurchasedbyme = "Oferta de vendas compradas",
    dailymission_tradeitems = "Items trocados",
    dailymission_createbuyoffer = "Ofertas de compras feitas",
 
    dailymission_completed = "~g~Completaste uma missão diária!\n~b~+%s XP\n~y~+1 Dungeon Key",
 
    character_creation_mix_desc = "Seleciona se a forma da tua cara é mais influenciada pelo teu pai/mãe.",
    character_creation_skin_desc = "Seleciona se a tua pele é mais influenciada pelo teu pai/mãe.",
 
    ff_1 = "Nose width",
    ff_2 = "Nose height",
    ff_3 = "Nose length",
    ff_4 = "Nose drooping",
    ff_5 = "Nose peak drop",
    ff_6 = "Nose twist",
    ff_7 = "Eyebrow height",
    ff_8 = "Eyebrow depth",
    ff_9 = "Cheekbone height",
    ff_10 = "Cheekbone width",
    ff_11 = "Cheek width",
    ff_12 = "Eyes opening",
    ff_13 = "Lip thickness",
    ff_14 = "Jaw width",
    ff_15 = "Jaw back length",
    ff_16 = "Chin lowering",
    ff_17 = "Chin bone length",
    ff_18 = "Chin Width",
    ff_19 = "Chin hole",
    ff_20 = "Neck thickness",
 
    	-- Darkzone stuff
	contaminated = "contaminado",
	darkzone_boat_leaving_in = "Barcos a sairem em",
	darkzone_exit = "Sair do spot",
	purificator = "Purificador",
	you_entered_the_darkzone = "~r~Entraste na darkzone.\n~w~Estão ~b~%s jogadores~w~ dentro.",
	you_left_the_darkzone = "~r~Saiste da darkzone.",
	cannot_enter_darkzone_time = "~r~A darkzone ainda não está aberta, aguarda.",
	darkzone_is_full = "~r~A darkzone está cheia, por favor aguarda.",
	darkzone_exit_allowed = "~r~Os barcos de saída chegaram, corre se quiseres escapar.",
	darkzone_close_time = "A fechar em",
	darkzone_surviving_since = "Sobrevivente à",
	darkzone_points = "Pontos",
	darkzone_points_x = "~r~Pontos darkzone: ~w~+%s",
	darkzone_landing_in_x = "Abertura em ~b~%s minutos~w~.\nSe houver jogadores suficientes.",
	darkzone_open_press_context = "A darkzone está aberta~w~.\nPressiona ~INPUT_CONTEXT~ para entrares ~m~na darkzone~w~.",
	darkzone_outside_warning = "~r~Estás fora da darkzone, volta ou irás morrer.",
	darkzone_close_warning = "~r~A darkzone vai fechar brevemente~w~.\nNão deves ficar muito mais tempo.",
	darkzone_close_damage = "Darkzone fechada, toda a zona está contaminada.",
	darkzone_not_enough_points_to_exit = "Precisas de ~r~%sx pontos~w~ para sair da darkzone.",
	press_e_to_exit_the_darkzone = "Pressiona ~INPUT_CONTEXT~ para sair da darkzone.\n~r~Precisas de x%s pontos da darkzone.",
	use_purificator = "usar purificador",
	darkzone_not_enough_points_to_start_purificator = "Precisas de ~r~%sx pontos~w~ para começares a purificar.",
	darkzone_not_enough_points_to_refill_purificator = "Precisas de ~r~%sx pontos~w~ para encher o purificador.",
	darkzone_too_far_from_purificator = "~r~Estás longe do purificador.",
	darkzone_cant_remove_while_running_purificator = "~r~Não podes remover nada enquanto o purificador estiver a trabalhar.",
	darkzone_purificator_running = "~r~Não podes colocar nada enquanto o purificador estiver a trabalhar.",
	darkzone_purificator_running_refill = "~r~Não podes encher o purificador enquanto estiver a trabalhar..",
	darkzone_put_x_in_purificator = "Colocaste ~r~%s~w~ no purificador.",
	darkzone_you_took_x_from_purificator = "Retiraste ~r~%s~w~ do purificador.",
	darkzone_purificator_does_not_need_refill = "Não precisas de ~r~encher este purificador~w~.",
	darkzone_refilled_purificator_x = "Usaste ~r~x%s pontos~w~ para encher o purificador.",
	darkzone_open = "A darkzone está aberta.\n~r~Encontra um transportador numa zona segura.",
	darkzone_item_clean = "Este item já está descontaminado.\n~r~Só podes colocar items contaminados.",
    
    exit_the_darkzone = "Sair da darkzone",
    you_entered_the_darkzone = "~r~Entraste na darkzone.",
    you_left_the_darkzone = "~r~Saiste da darkzone.",
    cannot_enter_darkzone_time = "~r~A darkzone ainda não está aberta, aguarda.",
    darkzone_is_full = "~r~A darkzone está cheia, aguarda.",
    darkzone_exit_allowed = "~r~Os barcos chegaram para abandonares a darkzone, corre para escapares.",
 
    airdrop_taken_by = "^1%s apanhou %s do airdrop.",
 
    available_death_effects = "Efeitos de morte disponíveis",
    available_modes = "Modos disponíveis",
 
    you_changed_your_ped_model = "~g~Alteraste o modelo do teu ped com sucesso.",
    i_want_to_change_my_ped = "Quero mudar o meu ped",
 
    dungeon_no_more_time = "~r~Foste muito lento. A dungeon fechou.",
    dungeon_participant_left = "~r~%s saiu da dungeon.",
    started_dungeon_party = "~b~Criaste uma sala de dungeon.",
    dungeon_party_no_longer_exists = "~r~Esta party de dungeon já não existe.",
    dungeon_invitation_expired = "~r~A party de dungeon expirou.",
    dungeon_join_party = "~g~Entraste na party de dungeon.",
    dungeon_too_late_for_invitation = "~r~Foste demasiado lento. Não podes entrar numa dungeon que já começou.",
    dungeon_already_invited_this_player = "~r~Já convidaste este jogador.",
    dungeon_invitation_received = "Recebeste um convite de ~b~%s~w~ para entrares na party de dungeon.\nEscreve ~g~/dungeon join %s~w~ para entrares na party.",
    dungeon_invitation_sent = "Convidaste ~g~%s~w~ para a party de dungeon.",
 
    i_want_to_enter_a_dungeon = "Quero entrar numa dungeon",
    dungeon_list = "Lista de Dungeon",
    dungeon = "Dungeon",
    dungeons = "Dungeons",
    you_need_x_keys = "Precisas de ~y~%s dungeon keys~w~ para entrar numa dungeon.",
    time_remaining = "Tempo restante",
    you_killed_the_dungeon_boss = "~r~Mataste o boss da dungeon.",
    dungeon_kill_final_boss = "Estás na fase final. Mata o boss para obteres o tesouro.",
 
    dungeon_died_remaining = "Morreste, tens ~r~%s~w~ vidas restantes.",
    dungeon_died = "~r~Não tens mais vidas. Morreste.",
    dungeon_already_in_party = "~r~Já estás numa party de dungeon.\n~w~Escreve /dungeon quit para sair.",
    dungeon_does_not_exist = "~r~Esta dungeon já não existe.",
    dungeon_ready = "~g~%s~w~ está pronto.",
    dungeon_not_ready = "~r~%s~w~ não está pronto.",
 
    not_released_yet = "Ainda não foi lançado.",
    feature_only_supporters = "~b~Este recurso está em beta-testing e apenas Diamond/Gold podem usar.",
    feature_not_enabled = "~b~Este recurso está em beta-testing.\n~w~Por favor aguarda até amanhã.",
    dungeon_charid_required = "~r~Por favor inclui o ID de personagem do teu amigo (canto superior esquerdo do ecrã dele) depois do comando.\nExemplo: /dungeon invite 1234",
 
    remaining_lives = "Vidas restantes",
}
 
AddLanguage("pt", my_language)
