local my_language = {
	give_vehicle = "Vous avez ajouté ~b~%s~w~ à votre inventaire",
	store_vehicle_command = "Ranger le véhicule que vous conduisez",
	no_entity_vehicle = "~r~Le véhicule est introuvable ou est trop loin de vous.",
	no_entity_vehicle_id = "~r~Le véhicule n'est lié à aucune ID, vous ne pouvez pas le ranger.",
	store_vehicle = "~b~Vous avez rangé votre véhicule.",
	teleported_former_position = "~g~Vous avez été replacé à votre ancienne position.",
	not_enough_of = "~r~Vous n'avez pas assez de %s.",
	max_storage_chest = "~r~Le coffre est plein.",
	cant_carry_more_items = "~r~Vous ne pouvez pas porter d'objets en plus.",
	put_item = "Vous avez déposé ~g~x%s~w~ %s~w~.",
	take_item = "Vous avez pris ~g~x%s~w~ %s~w~.",
	delete_item = "Vous avez supprimé ~r~x%s~w~ %s~w~.",
	you_equiped_item = "Vous avez équipé votre ~g~%s~w~.",
	bind_weapon_command = "Raccourci pour le slot arme %s",
	kevlar_broke = "~r~AHH!~n~~w~Votre kevlar s'est brisé.",
	inventory_command = "Ouvrir/Fermer l'inventaire",
	press_enter_to_join = "Appuyez sur ~g~ENTRER~w~ pour commencer à jouer.",
	new_character = "Nouveau personnage",
	survivor = "Survivant",
	right = "Droite",
	left = "Gauche",
	male = "Homme",
	female = "Femme",
	ped = "Ped",
	name = "Nom",
	sex = "Sexe",
	title = "Titre",
	select_this_character = "Sélectionner ce personnage",
	no_entity_zombie = "Le zombie est introuvable ou est trop loin de vous.",
	you_found = "Vous avez trouvé ~g~%sx %s~w~.",
	you_found_nothing = "Vous n'avez ~g~rien trouvé~w~.",
	press_e_to_loot = "Appuie sur ~b~[E]~w~ pour fouiller",
	full_for_item = "Il n'y a pas assez de place pour cet item.",
	put_item_container = "Vous avez déposé ~g~x%s~w~ %s~w~ de votre conteneur.",
	take_item_container = "Vous avez pris ~g~x%s~w~ %s~w~ de votre conteneur.",
	not_allowed_here = "~r~Vous n'avez pas le droit de faire ça ici.",
	cant_store_moving_veh = "~r~Vous ne pouvez pas ranger un véhicule qui bouge.",
	use_repair_tool = "utiliser l'outil de réparation",
	please_get_closer = "~b~Rapprochez-vous, aucune entité autour.",
	you_cancel_action = "~r~Vous avez annulé l'interaction.",
	selected_target_message = "Cible séléctionnée:~n~%s~n~~r~Appuyer sur ~b~Y~r~ pour annuler~n~~r~Appuyer sur ~g~X~r~ pour valider.",
	target_you = "~b~VOUS",
	target_screen = "~g~Affichée sur votre écran",
	take_this_path = "prendre ce chemin",

	-- hud
	default_hud = "HUD par défaut",
	cinema_hud = "HUD cinéma",
	no_hud = "Pas de HUD",

	-- perms
	kick_member = "Exclure un membre",
	edit_member = "Editer un membre",
	edit_rank = "Editer un rang",
	create_rank = "Créer un rang",
	delete_rank = "Supprimer un rang",
	edit_structure = "Editer la structure",
	edit_permissions = "Editer les permissions",
	permission_level = "Niveau de permission",
	red_delete = "~HUD_COLOUR_REDLIGHT~Supprimer",
	rank = "Rang",
	red_kick = "~HUD_COLOUR_REDLIGHT~Exclure",
	crew_name = "Nom du crew",
	slogan = "Devise",
	information = "information",
	boss_rank = "Nom du rang chef",
	member_rank = "Nom du rang membre",
	member = "Membre",

	permissions_manager = "gestion des permissions",
	members_manager = "gestion des membres",
	ranks_manager = "gestion des rangs",
	ranks_list = "liste des rangs",
	members_list = "liste des membres",
	create_a_rank = "Créer un rang",
	invite_someone = "Recruter quelqu'un",
	stats = "Statistiques",
	total_ranks = "Total des rangs",
	total_members = "Total des membres",
	level = "Level",
	actions = "actions",
	crew_manager = "gestion crew",
	you_created_a_new_crew = "Vous avez crée un nouveau crew: %s",
	you_deleted_your_crew = "Vous avez supprimé votre crew.",
	you_are_not_in_a_crew = "Vous n'êtes pas dans un crew.",
	you_joined_the_crew = "Vous avez rejoint un nouveau crew '%s'",
	kick_failed = "L'exclusion a échoué, raison: %s",
	already_in_crew = "Vous êtes déjà dans un crew.",
	no_invitation = "Vous n'avez reçu aucune invitation.",
	left_crew = "Vous avez quitté le crew.",
	permission_updated = "Les permissions de <C>~g~%s</C>~w~ ont été mises à jour.",
	incorrect_name = "~r~Le format du nom est incorrect.",
	incorrect_rank_perm = "~r~Incorrect\n~w~Le nom du grade ou le niveau de permission est incorrect.",
	warn_rank_limit = "~r~Vous avez atteint la limite de rangs.",
	create_rank_success = "~g~Validation\n~w~Vous avez créé un nouveau grade <C>~b~%s</C>~w~ avec un grant de <C>~b~%s</C>~w~.",
	crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~Vous ne pouvez pas modifier un membre qui dispose d'un niveau de permission supérieur au votre.",
	you_sent_an_invitation = "Vous avez envoyé une invitation à <C>~g~%s</C>~w~ pour rejoindre votre crew.",
	you_received_an_invitation = "Vous avez été invité à rejoindre un crew.\n~b~/%s pour accepter.",
	invitation_expired = "L'invitation a expiré.",
	crew_kick_success = "Vous avez exclu <C>~b~%s</C>~w~ de votre crew.",
	first_rank_warning = "Le premier rang sera toujours le rang par défaut.",

	you_updated_this = "Vous avez mis à jour %s pour ~g~<C>%s</C>~w~.",
	changes_saved_on = "Les changements effectués sur <C>~g~%s</C>~w~ ont été appliqués.",
	yes = "oui",
	no = "non",
	none = "Aucun",
	character_id = "ID personnage",
	server_id = "ID serveur",
	report = "Signaler",
	rename = "Renommer",
	trade_with = "Troc",

	please_wait_x_before = "~r~Patientez %s secondes avant d'effectuer cette action.",

	-- cloth
	take_outfit = "Acheter cette tenue",
	wardrobe_options = "option garde robe",
	wardrobe = "garge robe",
	manual_options = "choix manuel",
	manual_mode = "mode manuel",
	save_outfit = "Sauvegarder cette tenue",
	variation = "variation",
	outfits = "tenues",
	cloth_shop = "magasin",
	ped_cloth_shop = "magasin ped",
	manual_props = "props manuel",
	manuel = "manuel",
	new_name = "Nouveau nom",
	outfit_name = "Nom de la tenue",
	variations_saved = "~g~Validé.~n~~w~Les variations de votre personnage ont été sauvegardées.",
	equipped_new_outfit = "Vous avez équippé votre nouvelle tenue: ~b~%s",
	warning_limit_outfits = "Vous avez atteint la limite de tenues sauvegardées. ~g~(%s)",
	saved_new_outfit = "Vous avez sauvegardée une nouvelle tenue: ~b~%s~w~.",
	rename_outfit = "Votre tenue ~b~%s~w~ a été renommée: ~g~%s~w~.",
	delete_outfit = "Votre tenue: ~b~%s~w~ a été supprimée.",

	torso = "Torse",
	props = "Accessoires",
	top = "Haut",
	tops = "Hauts",
	badge = "Badge",
	pants = "Pantalons",
	pant = "Pantalon",
	shoes = "Chaussures",
	bags = "Sacs",
	undershirt = "sous-haut",
	neck = "cou",
	bracelets = "bracelets",
	montres = "montres",
	earrings = "boucles oreilles",
	glasses = "lunettes",
	hats = "chapeaux",
	graphiques = "graphiques",

	-- health
	inconscious = "Inconscient",
	doing_something = "Action en cours",
	time_before_respawn = "Temps avant la ré-apparition",
	you_died = "~r~Vous avez été tué.",
	healing_wounds = "Soin de vos blessures",
	already_doing_something = "~r~Vous êtes déjà entrain de réaliser quelque chose.",
	you_have_been_healed = "~g~Vous avez été soigné.",
	you_respawned = "~g~Vous avez respawn.",

	player_too_far_to_interact = "~r~Le joueur avec lequel vous voulez interagir est trop loin de vous.",
	send_trade_invitation_to = "Vous avez envoyé une invitation à échanger à ~b~%s~w~.\n~b~Attendez que l'autre joueur l'accepte.",
	receive_invitation_from = "Vous avez reçu une invitation à échanger de la part de ~b~%s~w~.\n~b~Tapez ~w~/trade accept %s~b~ pour commencer l'échange.",

	invalid_command_args = "Arguments de commande non valides: %s",
	start_trade_command_help = "Commencez un échange avec un autre joueur",
	accept_trade_command_help = "Accepter une invitation d'échange",
	deny_trade_command_help = "Refuser une invitation à échanger",
	invalid_invitation = "L'invitation n'est pas valable ou n'existe plus",
	name_accepted_your_trade_invitation = "~b~%s~w~ a accepté votre invitation commerciale",
	you_accepted_trade_invitation_of_name = "Vous avez accepté l'invitation à échanger de %s",
	name_denied_your_trade_invitation = "~b~%s~w~ a refusé l'invitation à échanger",
	you_denied_trade_invitation_of_name = "Vous avez refusé l'invitation à échanger de %s",
	you_already_trading = "Vous êtes déjà en train d'échanger",
	other_already_trading = "L'autre joueur est déjà en train de d'échanger",

	other_player_not_enough_money = "~r~L'échange a échoué. L'autre joueur n'avait pas assez d'argent.",
	you_player_not_enough_money = "~r~L'échange a échoué. Vous n'aviez pas assez d'argent.",
	other_player_not_enough_item = "~r~L'échange a échoué. L'autre joueur n'avait pas assez d'un certain objet.",
	you_player_not_enough_item = "~r~L'échange a échoué. Vous n'aviez pas assez d'un certain objet.",
	success_trade = "~g~L'échange a été confirmé.",
	fail_trade_other_player = "~r~L'échange a échoué, l'autre joueur est parti.",
	trade_other_full_item = "~r~L'échange a échoué, l'autre joueur n'a pas assez d'espace.",
	trade_full_for_item = "~r~L'échange a échoué, vous n'avez pas assez d'espace dans votre inventaire.",

	press_e_to_loot_inv = "Appuyez sur ~INPUT_CONTEXT~ pour fouiller l'inventaire.",
	press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~Appuyez sur ~INPUT_CONTEXT~ pour intéragir avec ~b~%s~HUD_COLOUR_NET_PLAYER27~.",
	press_e_to = "~HUD_COLOUR_NET_PLAYER27~Appuyez sur ~INPUT_CONTEXT~ pour %s~HUD_COLOUR_NET_PLAYER27~.",
	press_e_to_open_catalog = "Appuyez sur ~b~E~w~ pour lire le ~g~catalogue~w~.",
	this_person = "cet individu",
	the_shop = "ce magasin",
	you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~Vous n'avez pas l'autorisation de faire cela.",

	no_weapon = "~r~Vous n'avez aucune arme équipée.",
	no_need_ammo = "~r~Vous n'avez pas besoin de munition pour cette arme.",
	not_right_ammo = "~r~Vous n'utilisez pas les bonnes munitions, vous avez besoin de ~b~%s~w~.",
	you_used_ammo = "Vous avez chargé votre ~b~%s~w~ avec ~b~x%s~w~ de ~b~%s~w~.",

	choose_a_destination = "choisir une ~b~destination",
	press_to_open_your_chest = "ouvrir le coffre",
	no_enough_money = "~r~Vous n'avez pas assez d'argent.",
	you_paid = "Vous avez payé ~g~$%s~w~ pour ~b~%s~w~.",
	you_paid_basket = "Vous avez payé ~g~$%s~w~ pour votre panier.",
	you_sell_basket = "Vous avez reçu ~g~$%s~w~ pour avoir vendu ~b~x%s~w~ objet(s).",

	you_repaired_your_vehicle = "~g~Vous avez terminé de réparer le véhicule.",
	repairing_your_vehicle = "Réparation en cours",
	wheels_are_fine = "~r~Les roues du véhicule sont déjà réparées.",
	changing_wheel = "Changement de la roue",
	you_repaired_the_wheels = "~g~Vous avez réparé les roues du véhicules.",

	front_post_ls = "Avant-poste Los Santos",
	front_post_ls_2 = "Avant-poste Los Santos 2",
	front_post_bc = "Avant-poste Blaine County",
	front_post_bc_2 = "Avant-poste Blaine County 2",
	main_post_ls = "Zone sécurisée Los Santos",
	main_post_bc = "Zone sécurisée Blaine County",
	random_zone = "Zone random (parachute)",

	this_item_is_equipped = "~r~Cet item est équipé, supprimez l'item de vos raccourcis.",
	only_in_safezone = "~g~Vous ne pouvez pas faire cela en dehors de la safe-zone.",
	-- Commerce
	feature_gold_only = "Cette fonctionnalité est réservée aux ~y~membres gold~w~.",
	feature_diamond_only = "Cette fonctionnalité est réservé aux ~b~membres diamond~w~.",
	you_turned_into = "Vous vous êtes transformé en ~g~%s~w~.",
	wait_between_transformation = "~r~Veuillez patienter un moment avant d'utiliser le MorphMod de nouveau.",
	wait_between = "~r~Veuillez patienter un moment avant de réaliser cette action.",
	available_morphs = "Transformations disponible",
	animal_models = "Models d'animaux",
	zombie_models = "Models de zombie",
	success_update_name = "Vous avez changé le nom de votre personnage pour ~b~%s~w~.",
	success_reset_stats = "~g~Vous avez réinitialisé vos statistiques. (Les classements seront mis à jour plus tard)",

	-- animals
	boar = "Sanglier",
	cat = "Chat",
	chop = "Rottweiler (Chop)",
	rottweiler = "Rottweiler",
	cow = "Vache",
	coyote = "Coyote",
	deer = "Biche",
	hen = "Poule",
	husky = "Husky",
	mtlion = "Lion",
	pig = "Cochon",
	poodle = "Poodle",
	pug = "Bulldog",
	rabbit = "Lapin",
	rat = "Rat",
	retriever = "Labrador",
	shepherd = "Chien",
	westy = "Caniche",

	player_id = "ID du joueur",
	bounty = "Prime",
	reason = "Raison",
	id_player_not_found = "~r~Aucune joueur n'est lié à cet id.",

	ammo_dealer = "Vendeur de munitions",
	misc_dealer = "Vendeur d'équipements",
	veh_dealer = "Vendeur de véhicules",
	custom_dealer = "LS Custom",
	gun_dealer = "Vendeur d'armes",

	bounty_created = "Vous avez payé ~g~$%s~w~ pour créer un contrat sur la tête de ~b~%s~w~.",
	contract_success = "La prime que vous avez déposé sur ~r~%s~w~ a été récupérée par ~b~%s~w~.",
	a_contract_on_your_head = "~r~Il y avait une prime sur votre tête. Votre tueur a reçu la prime.",
	reward_for_contract = "Chasseur de prime! Vous avez été récompensé de ~g~$%s~w~ pour la mort de ~b~%s~w~.",
	
	hey_can_help_you = "Hey, comment puis-je vous aider?",
	i_want_to_buy_items = "Je souhaite acheter des items",
	i_want_to_sell_items = "Je souhaite vendre des items",

	press_context_or_jump_to_get_up = "Appuyez sur ~INPUT_CONTEXT~ ou ~INPUT_JUMP~ pour ~b~vous relever~w~.",
	server_restart_warning = "Le serveur va redémarrer..",
	auto_restart_in = "Restart automatique du serveur dans %s secondes.",

	not_allowed_create_character = "Vous n'avez pas eu l'autorisation de créer un autre personnage.",
	character_not_yours = "Ce personnage ne vous appartient pas.",
	character_does_not_exist = "Ce personnage n'existe pas ou plus.",
	loading_character = "Changement du personnage en cours...",

	playtime_is = "~b~Votre temps de jeu sur Extinction:\n~w~%s",
	dont_spam = "^1Ne spammez pas!",

	babygod_warning = "~b~Vous avez quitté la zone sécurisée, vous êtes invincible pour un moment trouvez un lieu sûr!",

	-- LS Custom
	modifications_classiques = "Modifications classiques",
	modifications_custom = "Modifications spéciales",
	modifications_benny = "Modifications de Benny",
	paint = "peinture",
	custom_your_car = "Personnalisez votre voiture",
	wheels_modifications = "Modification des roues",
	performances = "Performances",
	neons = "Néons",
	extra = "Extra",
	klaxon = "Klaxon",
	teinte_fenetre = "Teinte des vitres",
	phares_xenons = "Phares xénon",
	modele_plaque = "Modèle de plaque",
	livery = "Livery",
	headlight_color = "Couleur des phares",
	wheel_type = "Type de roue",
	primary_wheel_type = "Type de roue avant",
	back_wheel_type = "Type de roue arrière",
	wheel_color = "Couleur des roues",
	tire_smoke = "Fumée des pneus",
	custom_color = "Couleur personnalisée",
	custom_wheel = "Roue personnalisée",
	custom_back_wheel = "Roue arrière personnalisée",
	suspension = "Suspension",
	transmission = "Transmission",
	moteur = "Moteur",
	frein = "Frein",
	turbo = "Turbo",
	primary_color = "Couleur primaire",
	secondary_color = "Couleur secondaire",
	interior_color = "Couleur de l'intérieur",
	dashboard_color = "Couleur du tableau de bord",
	color_effect = "Effet couleur",
	left_neon = "Néon gauche",
	right_neon = "Néon droit",
	front_neon = "Néon avant",
	back_neon = "Néon arrière",

	aileron = "Aileron",
	pc_front = "Pare-chocs avant",
	pc_back = "Pare-chocs arrière",
	carroserie = "Carroserie",
	exhaust = "Échappement",
	cadre = "Cadre",
	calandre = "Calandre",
	capot = "Capot",
	gb_left = "Aile gauche",
	gb_right = "Aile droit",
	roof = "Toit",
	plate_support = "Supports de plaque",
	front_plate = "Plaque avant",
	interior_style = "Style intérieur",
	figurine = "Figurine",
	motif_dashboard = "Motif dashboard",
	cadran = "Cadran",
	haut_parleur_portes = "Haut-parleur portes",
	motif_sieges = "Style des sièges",
	volant = "Volant",
	levier = "Levier",
	logo_custom = "Logo",
	ice = "ICE",
	haut_parleur_coffre = "Haut parleur coffre",
	hydrolique = "Hydrolique",
	moteur = "Moteur",
	filtres_air = "Filtres air",
	entretoises = "Entretoises",
	arc_couverture = "Arche",
	antenne = "Antenne",
	motif_exterieur = "Style extérieur",
	reservoir = "Réservoir",
	window = "Fenêtre",
	style = "Style",
	default = "Défaut",
	type = "Type",
	normal = "Normal",
	black = "Noir",
	black_smoke = "Fumée noire",
	simple_smoke = "Fumée simple",
	stock = "Stock",
	limo = "Limousine",
	sa_black = "San Andreas bleu",
	sa_blue = "San Andreas bleu",
	sa_white = "San Andreas blanc",
	simple_white = "Simple blanc",
	ny_white = "North Yankton blanc",
	race = "Race",
	sport = "Sport",
	stock = "Stock",
	street = "Street",
	discount = "Discount",
	select_your_car = "Choisissez votre voiture",
	select_car_custom = "Sélectionnez le véhicule que vous souhaitez personnaliser.",
	loading_vehicle = "Création du véhicule",
	invalid_vehicle = "~r~Entité non valide.",
	invalid_vehicle_please_spawn = "~r~Le véhicule n'est pas valide. Veuillez le faire apparaître une fois avant d'essayer de faire quoi que ce soit.",
	free_take_and_validate = "Tout est gratuit. Prenez ce que vous voulez et confirmez !",
	car_custom_saved = "~g~Les modifications de votre voiture ont été sauvegardées.",

	-- Character creation
	character_creation = "Création de personnage",
	confirm = "confirmer",
	start_playing = "Commencer à jouer",
	appearance = "apparence",
	character_list = "liste des personnages",
	face_features = "traits du visage",
	parents = "parents",
	parent = "parent",
	mix = "ressemblance",
	skin = "peau",
	desc_mix = "Sélectionnez si la forme de votre visage est plus influencée par celle de votre père / mère.",
	desc_skin = "Sélectionnez si votre peau est plus influencée par celle de votre père / mère.",
	identity = "identité",
	player_name = "Nom du joueur",
	new_character = "nouveau personnage",
	warning_headblend = "~r~Vous n'avez pas renseigné l'héritage de votre personnage.",
	warning_overlays = "~r~Vous n'avez pas mis de sourcils/barbes/etc...",
	warning_identity = "~r~Attention.~n~~w~Vous n'avez pas correctement indiqué le nom RP de votre personnage.",

	-- kits
	kit_does_not_exist = "~r~Ce kit n'existe pas.",
	kit_needs_rank = "Vous devez avoir le rang ~r~%s~w~ pour ce kit.",
	wait_before_using_kit = "Veuillez patienter ~r~%s~w~ avant d'utiliser ce kit.",
	received_kit = "Vous avez reçu votre kit ~b~%s~w~.",
	no_kit = "Vous n'avez aucun kit.",

	unable_to_find_booster = "Impossible de trouver un booster avec cette id.",
	wait_already_player_boost = "Veuillez patienter avant d'utiliser votre booster. Il y a déjà un booster joueur actif.",
	wait_already_crew_boost = "Veuillez patienter avant d'utiliser votre booster. Il y a déjà un booster crew actif.",
	wait_already_server_boost = "Veuillez patienter avant d'utiliser votre booster. Il y a déjà un booster serveur actif.",
	booster_activated = "Booster activé pour ~g~%s minutes~w~! ~b~XP +%s%%",
	server_booster_activated = "~b~%s~w~ a activé un booster serveur pour ~g~%s minutes~z~! ~b~XP +%s%%",
	crew_booster_activated = "~b~%s~w~ a activé un booster de crew pour ~g~%s minutes~z~! ~b~XP +%s%%",
	no_booster = "Vous n'avez aucun booster.",
	
	rank_expired = "~r~Votre rang boutique a expiré.",
	supporter_role = "~g~Rang boutique:~w~ %s",
	no_rank_warning = "Vous n'avez aucun rôle boutique.\n~r~Si vous avez acheté quelque chose, liez votre compte FiveM au jeu.",
	no_fivem_id = "Votre compte FiveM n'est pas lié.\n~r~Vérifiez que vous avez un compte FiveM et qu'il est lié au jeu.",
	no_queue_warning = "Vous n'avez aucun package en attente.\n~r~Patientez un moment ou essayez /getRank si vous souhaitez avoir votre rang.",
	package_sync_success = "~g~Vos packages ont été synchronisés, enjoy!\n~w~Commandes utiles: /getRank, /booster",

	level_required = "Vous devez être level %s",
	rank_required = "Vous devez avoir le rang %s.",
	level_required_2 = "~r~Vous devez être level %s.",

	updated_deathmessage = "~g~Vous avez mis à jour votre message de mort.",
	updated_deatheffect = "~g~Vous avez mis à jour votre effet de kill.",
	use = "Utiliser",
	test = "Tester",

	-- zombie
	you_bitten = "~r~Vous avez été mordu.",
	infection_rate = "Taux d'infection: ~r~%s%",

	-- ranks
	thug = "Racaille",
	hustler = "Escroc",
	soldier = "Soldat",
	trigger = "Gâchette",
	enforcer = "Homme de main",
	facilitator = "Conseiller",
	public_enemy = "Ennemi public",
	shot_caller = "Gros bonnet",
	street_boss = "Gros caïd",
	kingpin = "Parrain",
	-- Tattoo
	tattoo = "tatouage",
	tattoos = "tatouages",
	torso = "Torse",
	head = "Tête",
	left_arm = "Bras gauche",
	right_arm = "Bras droit",
	left_leg = "Jambe gauche",
	right_leg = "Jambe droite",
	unknown = "Inconnu",
	other = "Autre",
	remove_tattoo = "Enlever tous les tatouages",
	-- Hairdress
	haircuts = "Coiffures",
	makeup = "Maquillage",
	face = "Visage",
	eyebrows = "Sourcils",
	facial_hair = "Pilosité faciale",
	body_hair = "Pilosité torse",
	barber_shop = "Salon de coiffure",
	face_makeup = "Maquillage visage",
	lipstick = "Rouge à lèvres",
	face_foundation = "Fond de teint",
	skin_blemishes = "Problème de peau",
	skin_ageing = "Rides",
	moles_freckles = "Tâches et boutons",
	sun_damage = "Dégâts peau",
	skin_complexion = "Complexité de la peau",
	body_blemishes = "Tâche corps",
	body_blemishes_2 = "Tâche corps 2",
	opacity = "Opacité",
	variations = "Variations",
	filter = "Filtre",
	eyes_color = "Couleur des yeux",
	-- Mask
	masks = "Masques",
	-- Items
	money = "Argent",
	-- Ammo
	["9mm"] = "9mm",
	["300_mag"] = ".300 Magnum",
	["7_62mm"] = "7.62mm",
	["calibre_12"] = "Calibre 12",
	["45_acp"] = ".45 ACP",
	["5_56mm"] = "5.56mm",
	rocket = "Roquette",
	flare = "Fusée de détresse",
	grenade = "Grenade",
	-- Food
	["fish_1"] = "Grande bouche",
	["fish_2"] = "Truie arc-en-ciel",
	["fish_3"] = "Kokanee",
	["fish_4"] = "Omble de l'arctique",
	["fish_5"] = "Perche rock",
	["fish_6"] = "Petite bouche",
	["fish_7"] = "Spatules",
	["fish_8"] = "Truite bull",
	["fish_9"] = "Truite de lac",
	["fish_10"] = "Chinook",
	["fish_11"] = "Esturgeon pâle",
	["fish_12"] = "Saumon",

	misc_meat = "Viande crue",
	rabbit_meat = "Lapin cru",
	lion_meat = "Lion cru",
	rare_plume = "Plume rare",
	dog_meat = "Chien cru",
	cat_meat = "Chat cru",
	rare_fish = "Poisson rare",

	mask = "Masque",
	malette = "Malette",
	malette_metal = "Malette en métal",
	ciseaux = "Ciseaux",
	clean_kit = "Kit de lavage",
	fishing_rod = "Canne à pêche",
	meuble = "Meuble",
	tissu = "Tissu",
	accessory = "Accessoire",
	radio = "Radio",
	recyclor = "Recycleur",
	medkit = "Trousse de soin",
	kevlar = "Kevlar",
	gps = "GPS",
	repair_tool = "Trousse à outils",
	jvn = "JVN",
	engine_veh = "Moteur",
	bag = "Sac",
	wheel_veh = "Roue de secours",
	vetement = "Vêtement",
	bloc_note = "Bloc-note",
	paint_spray = "Bombe de peinture",
	spike = "Herse",
	paracetamol = "Paracétamol",
	bandage = "Bandage",
	gaz_mask = "Masque à gaz",
	filter = "Filtre",
	tattoo_tool = "Outil tatouage",
	drug_med = "Médicament",
	drug_antizin = "Antizin shot",
	drug_stamina = "Stamina shot",
	drug_berserker = "Berserker shot",

	pickup_spikestrip = "ramasser la herse",
	you_dropped_spikestrip = "Vous avez posé une ~g~herse~w~ au sol.",
	you_pickup_spikestrip = "Vous avez récupéré votre ~g~herse~w~ au sol.",

	you_have_been_killed_by = "Vous avez été tué par ~r~%s",
	kill_notif = "~m~Tué",
	you_killed = "Vous avez tué ~r~%s~w~",
	already_used_reset_only = "~r~Vous avez déjà réinitialisé votre personnage.\n~w~Seulement les membres %s~w~ peuvent refaire leur personnage plus d'une fois.",
	already_used_reset_only2 = "~r~Vous avez déjà fait cela.\n~w~Seulement les membres %s~w~ peuvent le faire plus d'une fois.",

	hud_options = "Options du HUD",
	advanced_hud = "Afficher le HUD avancé",
	players = "Joueurs",
	health = "Santé",
	player_menu = "Menu joueur",

	you_are_now_zombie = "~r~Vous êtes désormais un zombie.",

	my_weapons = "mes armes",
	customize_weapons = "customisation de mon arme",
	weapon_skin = "Camouflage",

	-- camo
	skin_classic = "Classique",
	skin_green = "Vert",
	skin_yellow = "Jaune",
	skin_pink = "Rose",
	skin_gold = "Or",
	skin_blue = "Bleu",
	skin_orange = "Orange",

	weapon_katana = "Katana",
	weapon_sledgehammer = "Marteau de forgeron",

	-- new
	airdrop_coming = "~r~Un larguage est en chemin regardez votre map.",
	killed_by_cheater = "~r~Vous avez été tué par un cheater.\n~w~Nous l'avons banni et votre mort a été annulée.",

	corrupted_vehicle = "~r~Ce véhicule est corrompu et a été dupliqué par le passé, il a été supprimé de votre inventaire. Désolé si vous avez été arnaqué.",

	-- Discord
	join_discord_for_kit = "Rejoingez notre discord pour un kit gratuit!\n~g~discord.gg/gtalife",
	discord_account_not_linked = "~r~Vous devez lier votre compte discord avec FiveM.",
	discord_account_not_guild = "~r~Vous n'êtes pas sur notre serveur discord.\n~w~Rejoignez discord.gg/gtalife",

	already_done_recently = "~r~Réessayez plus tard, vous l'avez déjà fait aujourd'hui.",
	update_country = "Mettre à jour le pays",

	prestige_info = "~b~Vous avez atteint le niveau maximum.\n~w~Tapez /prestige pour avoir des infos sur le système de prestige.",
	prestige_not_max_level = "~r~Vous n'avez pas atteint le niveau maximum.",
	max_prestige_reached = "~r~Vous avez atteint le dernier prestige.",
	prestige_info_cmd = [[^3Système de prestige^7
Vous êtes actuellement prestige ^4%s^7 et niveau ^5%s^7.

Si vous atteignez le niveau maximum (%s), vous pouvez choisir d'obtenir un prestige et de recommencer votre progression XP pour revenir au niveau 0.
L'obtention d'un nouveau prestige vous donne un badge spécial et de nouveaux avantages comme du meilleur loot, des nouveaux items, plus d'argent ou un poids maximum d'inventaire plus élevé.
^2Si vous voulez obtenir un prestige et RECOMMENCER level 0 tapez ^1/setprestige^2
]],
	new_prestige = "Vous avez débloqué un nouveau prestige!\n~g~Vous êtes désormais prestige %s.",
	cant_store_event_veh = "~r~Vous ne pouvez pas ranger les véhicules spéciaux.",

	you_are_no_longer_in_combat = "🛡️ ~b~Vous n'êtes plus en combat.",
	you_are_in_combat_mode = "🛡️ ~b~Vous êtes en combat.\nSi vous déconnectez vous mourrez.",
	you_disconnected_in_combat = "💀 Vous avez déconnecté en combat, vous êtes mort.",

	not_enough_prestige_points = "~r~Vous n'avez pas suffisamment de point de prestige.",
	you_reached_max_prestige_stats_rank = "~r~Vous avez atteint le niveau maximum pour cette amélioration.",
	new_prestige_stats_upgrade = "Vous avez amélioré votre ~b~%s~w~\n~g~%s/%s",

	legendary_vehicle_pop = "~r~Un véhicule légendaire est apparu sur la carte.",

	-- poll one
	poll1_q1 = "Quel genre de serveur souhaiteriez-vous voir?",

	poll1_q1_a1 = "Battle Royale",
	poll1_q1_a2 = "Mission privée solo ou avec 1-4 amis (comme Payday / Heist / Hitman)",
	poll1_q1_a3 = "Course",
	poll1_q1_a4 = "Murder / Horreur",

	-- poll two
	poll2_q1 = "Are you an English speaker and would you be interested in a GLife RP Server?",

	poll2_q1_a1 = "No",
	poll2_q1_a2 = "Yes",

	combat_mode_container_disabled = "~r~Vous êtes en combat.\n~w~Vous ne pouvez pas ranger d'objet.",
	gcoins_wallet_updated = "~g~Vos GCoins ont été mis à jour.\n~w~+%s GCoins",
	not_enough_gcoins = "~r~Vous n'avez pas suffisamment de GCoins.",
	gcoins_something_went_wrong = "~r~Quelque chose s'est mal passé.",
	you_bought_with_gcoins = "Vous avez acheté ~g~%s~w~ pour ~b~%s GCoins~w~.",

	equiping_armor = "Kevlar",

	toggle_mute_player = "Muter/Demuter",
	you_muted_this_player = "~b~Vous avez muté ce joueur.",
	you_unmuted_this_player = "~b~Vous avez démuté ce joueur.",

	already_purchased = "~r~Vous avez déjà acheté cet item.",
	weapon_camo_preview = "Vous prévisualisez le modèle de base de l'arme, certaines pièces jointes sont manquantes.\n~INPUT_CELLPHONE_CANCEL~ pour quitter l'aperçu.",

	already_using_a_seringue_booster = "~r~Vous avez déjà pris un shot de cela.",
	seringue_effect_done = "~b~L'effet booster de la seringue est parti.",
	you_injected_a_seringue_boost = "Vous avez injecté une ~b~seringue~w~ dans votre sang.",

	put_item_permission = "Poser des items",
	take_item_permission = "Prendre des items",
	put_money_permission = "Poser de l'argent",
	take_money_permission = "Prendre de l'argent",

	preferred_badge_set = "Vous avez défini votre badge ~g~préféré~w~.",
	preferred_badge_not_set = "~r~Impossible de définir votre badge préféré.",

	marketplace_received_money_sales = "Vous avez reçu ~g~$%s~w~ de ~b~%s~w~ vente(s).",
	marketplace_no_sales = "~r~Vous n'avez rien vendu.",
	marketplace_you_paid_for = "Vous avez payé ~g~$%s~w~ pour ~b~%s~w~.",

	deleted_sell_offer = "~b~Vous avez supprimé votre offre de vente.",
	deleted_buy_offer = "~b~Vous avez supprimé votre offre d'achat.",
	deleted_sell_offers = "~b~Vous avez supprimé vos offres de vente.",
	deleted_buy_offers = "~b~Vous avez supprimé vos offres de'achat.",

	marketplace_offer_does_not_exist = "~r~Cette offre n'existe plus.",

	marketplace_create_sell_offer = "Vous avez créé une offre de vente pour ~b~%sx %s ~w~pour ~g~$%s~w~ par unité.",
	marketplace_create_buy_offer = "Vous avez créé une offre d'achat pour ~b~%sx %s ~w~de ~g~$%s~w~ par unité.",

	i_want_to_enter_in_my_property = "Je veux entrer dans ma propriété.",
	i_want_to_exit_private_world = "Je veux revenir dans le monde public.",
	public_world = "Monde public",
	private_world = "Monde privé",

	dailymission_playerkill = "Joueurs tués",
	dailymission_zombiekill = "Zombies tués",
	dailymission_playerheadshotkill = "Tir dans la tête joueurs",
	dailymission_zombieheadshotkill = "Tir dans la tête zombies",
	dailymission_zombiesurvivorkill = "Zombies survivant tués",
	dailymission_zombiearmoredkill = "Zombies blindé tués",
	dailymission_zombiehazmatkill = "Zombies hazmat tués",
	dailymission_zoombieboomerkill = "Zombies boomer tués",
	dailymission_sellitems = "Articles vendus",
	dailymission_buyitems = "Articles achetés",
	dailymission_lootitems = "Objets récoltés",
	dailymission_createselloffer = "Offre de vente créée",
	dailymission_killtopkillcrew = "Joueurs tués du crew",
	dailymission_killtopkillplayers = "Joueurs tués du top",
	dailymission_getintolegendaryvehicle = "Véhicules",
	dailymission_killzombiewithweapon = "Zombies tués avec l'arme",
	dailymission_killplayerwithweapon = "Joueurs tués avec l'arme",
	dailymission_darkzonesurvivingtime = "Temps de survie dans la Darkzone",
	dailymission_redzoneplayerkill = "Joueurs tués dans la redzone",
	dailymission_redzonezombiekill = "Zombies tués dans la redzone",
	dailymission_darkzoneplayerkill = "Joueurs tués dans la darkzone",
	dailymission_darkzonezombiekill = "Zombies tués dans la darkzone",
	dailymission_useitem = "Objets utilisés",
	dailymission_playtime = "Temps de jeu",
	dailymission_xpharvest = "XP récoltée",
	dailymission_sellofferpurchased = "Objets achetés dans le marché par des clients",
	dailymission_sellofferpurchasedbyme = "Objets achetés dans le marché par vous",
	dailymission_tradeitems = "Articles échangés",
	dailymission_createbuyoffer = "Offres d'achat créées",

	dailymission_completed = "~g~Vous avez terminé une mission quotidienne!\n~b~+%s XP\n~y~+1 Clé de donjon",

	character_creation_mix_desc = "Sélectionnez si la forme de votre visage est plus influencée par celle de votre père / mère.",
	character_creation_skin_desc = "Sélectionnez si votre peau est plus influencée par celle de votre père / mère.",

	ff_1 = "Largeur nez",
	ff_2 = "Hauteur nez",
	ff_3 = "Longueur nez",
	ff_4 = "Abaissement du nez",
	ff_5 = "Abaissement pic du nez",
	ff_6 = "Torsion du nez",
	ff_7 = "Hauteur sourcils",
	ff_8 = "Profondeur sourcils",
	ff_9 = "Hauteur des pommettes",
	ff_10 = "Largeur des pommettes",
	ff_11 = "Largeur des joues",
	ff_12 = "Ouverture des yeux",
	ff_13 = "Épaisseur des lèvres",
	ff_14 = "Largeur de la mâchoire",
	ff_15 = "Longueur du dos de la mâchoire",
	ff_16 = "Abaissement du menton",
	ff_17 = "Longueur de l'os du menton",
	ff_18 = "Largeur du menton",
	ff_19 = "Trou du menton",
	ff_20 = "Epaisseur du cou",

	airdrop_taken_by = "^1%s a pris %s du airdrop.",

	available_death_effects = "Effets de mort disponibles",
	available_modes = "Modes disponibles",

	you_changed_your_ped_model = "~g~Vous avez changé votre modèle de ped.",
	i_want_to_change_my_ped = "Je souhaite changer de ped",

	poll4_q1 = "Qu'attendez-vous de la nouvelle saison?",
	poll4_q1_a4 = "Plus d'event dans le monde comme les airdrops, les captures de zone etc.",
	poll4_q1_a1 = "Plus de contenu PvE comme les donjons",
	poll4_q1_a2 = "Plus de jeux comme le casino / courses",
	poll4_q1_a3 = "Du contenu PvP",

	poll4_q2 = "Voulez-vous plus de tournois et mode ranked?",
	poll4_q2_a1 = "Oui",
	poll4_q2_a2 = "Non",

	poll4_q3 = "Voulez-vous voir les snipers dans les magasins?",
	poll4_q3_a1 = "Oui",
	poll4_q3_a2 = "Non",

	poll4_q4 = "Qu'aimez-vous le plus sur Extinction?",
	poll4_q4_a1 = "PvP",
	poll4_q4_a2 = "PvE",
	poll4_q4_a3 = "Echanges",

	dungeon_no_more_time = "~r~Vous avez été trop lent. Le donjon est fer,é.",
	dungeon_participant_left = "~r~%s a quitté le donjon.",
	started_dungeon_party = "~b~Vous avez créé une partie pour un donjon.",
	dungeon_party_no_longer_exists = "~r~Cette partie de donjon n'existe plus.",
	dungeon_invitation_expired = "~r~L'invitation pour ce donjon n'existe plus.",
	dungeon_join_party = "~g~Vous avez rejoint une partie pour un donjon.",
	dungeon_too_late_for_invitation = "~r~Vous avez été trop lent. Vous ne pouvez pas rejoindre un donjon en plein jeu.",
	dungeon_already_invited_this_player = "~r~Vous avez déjà invité ce joueur.",
	dungeon_invitation_received = "Vous avez reçu une invitation de ~b~%s~w~ pour rejoindre son donjon.\nTapez ~g~/dungeon join %s~w~ pour rejoindre la partie.",
	dungeon_invitation_sent = "Vous avez invité ~g~%s~w~ dans votre partie donjon.",

	i_want_to_enter_a_dungeon = "Je souhaite rentrer dans un donjon",
	dungeon_list = "Liste des donjons",
	dungeon = "Donjon",
	dungeons = "Donjons",
	you_need_x_keys = "Vous avez besoin de ~y~%s clés de donjon~w~ pour rentrer dans ce donjon",
	time_remaining = "Temps restant",
	you_killed_the_dungeon_boss = "~r~Vous avez tué le boss du donjon.",
	dungeon_kill_final_boss = "Vous êtes dans la salle finale. Tuez le boss pour récupérer son trésor.",

	dungeon_died_remaining = "Vous êtes mort, il vous reste ~r~%s~w~ vie(s).",
	dungeon_died = "~r~Vous n'avez plus aucune vie, le donjon se termine. Vous êtes mort.",
	dungeon_already_in_party = "~r~Vous êtes déjà dans une partie de donjon.\n~w~Tapez /dungeon quit pour quitter.",
	dungeon_does_not_exist = "~r~Ce donjon n'existe pas.",
	dungeon_ready = "~g~%s~w~ est prêt.",
	dungeon_not_ready = "~r~%s~w~ n'est pas prêt.",

	not_released_yet = "Ceci n'est pas encore publié.",
	feature_only_supporters = "~b~Cette fonctionnalité est en phase de test bêta et seuls les supporters Diamant/Or peuvent l'utiliser dès maintenant.",
	feature_not_enabled = "~b~Cette fonction n'est pas encore activée.\n~w~Veuillez attendre l'activation plus tard dans la journée.",
	dungeon_charid_required = "~r~Veuillez inclure l'identifiant de votre ami (en haut à droite de son écran) après la commande.\nExemple: /dungeon invite 1234",

	poll5_q1 = "Accepteriez-vous que notre anticheat capture l'écran entier des cheaters si ils sont soupçonnés de wallhack ou aimbot? (Il est possible que cela capture une partie de votre bureau si vous jouez en fenêtré, toutefois les captures ne seront jamais sauvegardées et seuls les modérateurs les plus fiables pourront utiliser cet outil)",
	poll5_q1_a1 = "skip - ignorer",
	poll5_q1_a2 = "Oui, j'approuve cette stratégie",
	poll5_q1_a3 = "Non, je n'approuve pas",

	-- S4
	redzone_kill_leader_killed = "Le ~r~kill leader de la redzone~w~ a été tué.",
	redzone_kill_leader_fled = "Le ~r~kill leader de la redzoner~w~ a fui.",
	redzone_get_back_kill_leader_before_x = "Vous êtes ~r~en dehors de la redzone~w~ revenez ou vous perdrez votre titre dans ~r~%s secondes~w~.",
	redzone_kill_leader_new_xp_step = "~r~XP Multiplicateur redzone\n~b~+%s%~w~ bonus",
	remaining_lives = "Vies restantes",

	name_tag = "Tag du crew",
	redzone_changed = "~r~Les redzones ont été déplacées vers une nouvelle position.",

	-- Squad
	squad_not_leader = "~r~Vous n'êtes pas le chef de votre escouade.",
	squad_kicked_by_x = "Vous avez été ~r~viré ~w~ de votre escouade par ~r~%s~w~.",
	squad_you_kicked_x = "Vous avez viré ~r~%s~w~ de votre escouade.",
	squad_invited_x = "Vous avez invité ~r~%s~w~ dans votre escouade.",
	squad_invited_you_x = "~r~%s~w~ vous a invité dans son escouade.\nTapez ~r~/squad join %s~w~ pour rejoindre l'escouade.",
	squad_you_set_new_leader = "Vous avez mis~r~%s~w~ comme nouveau ~r~cjef~w~ de l'escouade.",
	squad_you_are_new_leader = "~g~Vous êtes le nouveau leader de l'escouade.",
	squad_not_invited = "~r~Vous n'avez pas été invité dans l'escouade.",
	squad_joined_squad = "~g~Vous avez rejoint l'escouade.",
	squad_left = "~r~Vous avez quitté l'escouade.",
	squad_already_in = "~r~Vous êtes déjà dans une escouade.",
	squad_created_x = "Vous avez créé une nouvelle escouade. ~b~(%s)",
	squad_x_joined = "~b~%s~w~ a rejoint l'escouade.",
	squad_leader_deleted = "~r~Le chef a supprimé l'escouade.",
	write_yes_to_confirm = "Tapez oui pour confirmer",
	invite_a_player_write_char_id = "Invitez un joueur. Tapez son identifiant de personnage",

	-- Help stuff
	press_enter_beginner_guide = "Appuyez sur ~INPUT_ENTER~ pour commencer le guide du débutant.",
	welcome_glife = "Bienvenue sur ~r~GLife Extinction~w~!",
	you_are_playing_server_x_with_x = "Vous jouez sur le serveur ~b~#%s~w~ avec ~b~%s joueurs~w~.",
	start_beginner_guide = "Commencer le guide du débutant",
	play_now = "~g~Jouer!",
	interact_npc_fast_travel = "Discutez avec le PNJ voyage rapide",

	-- Tutorial
	tutorial_beginner_end_msg = "~r~Merci de votre temps!\n~w~Amusez-vous bien en jouant à Extinction, si vous avez des questions, utilisez le chat ou retrouvez-nous sur discord.",
	tutorial_beginner_start_msg = "~r~Bienvenue sur GLife Extinction!\n~w~Ce petit guide a pour but d'expliquer comment débuter sur ce mode de jeu.",
	tutorial_beginner_camera_01 = "~r~~BLIP_557~ ~r~Safezone principale\n~w~Il s'agit d'une zone sécurisée où vous pouvez faire des achats et stocker des objets, mais aussi personnaliser votre équipement et échanger avec d'autres joueurs.",
	tutorial_beginner_camera_02 = "~BLIP_568~ ~r~Coffres de stockage\n~w~Vous pouvez y accéder à votre stockage privé et y déposer vos objets précieux.",
	tutorial_beginner_camera_03 = "~BLIP_567~~BLIP_556~~BLIP_658~ ~r~Magasins PNJ\n~w~Vous pouvez acheter et vendre vos objets dans de nombreux magasins comme le vendeur d'armes, de véhicules ou d'équipements.",
	tutorial_beginner_camera_04 = "~BLIP_84~ ~r~Primes publiques\n~w~Si vous parvenez à trouver et à tuer la cible, vous obtiendrez la récompense associée.",
	tutorial_beginner_camera_05 = "~BLIP_176~ ~r~Monde hostile\n~w~Vous rencontrerez des zombies et des joueurs hostiles. Ils voudront tous vous tuer, mais ils sont le meilleur moyen d'obtenir de l'XP et du butin.",
	tutorial_beginner_camera_06 = "~BLIP_303~ ~r~Les zones rouge\n~w~Vous pourrez y trouver un meilleur butin et gagner plus d'expériences en tuant des gens.",
	tutorial_beginner_camera_07 = "~BLIP_648~ ~r~Île Darkzone\n~w~Ici, vous ne pouvez pas sauvegarder des objets ni fuir facilement, mais c'est le meilleur endroit pour trouver du butin de haut niveau comme des armes MK2 ou des snipers.",
	tutorial_beginner_camera_08 = "~BLIP_575~ ~r~Opportunités de loot et d'exploration\n~w~Vous pouvez vous battre pour obtenir des caisses de largage, mais aussi explorer et battre le boss du donjon.",
	tutorial_beginner_training_01 = "~g~You joined the training room.\n~w~Jump with ~INPUT_JUMP~ when you are ready.",
	tutorial_beginner_training_02 = "~g~Let's use the inventory.\n~w~Press ~%s~ to open your inventory.",
	tutorial_beginner_training_03 = "~g~Equip a weapon.\n~w~Open the inventory and drag a weapon in the shortcut bar.\nPress the corresponding key ~b~1/2/3/4/5/6/7~w~.\n~r~If you do not have any weapon use ~b~/kit newbie.",
	tutorial_beginner_training_04 = "~g~Fill your weapon ammo.\n~w~Equip a gun and put a box of ammo in your shortcut bar. Then press the shortcut key.",
	tutorial_beginner_training_05 = "~g~Finally vehicles.\n~w~You can spawn vehicles just like you equip a weapon. Once spawned, you can store it with ~%s~ while driving it. Press the key to confirm.",
	tutorial_beginner_training_success_01 = "~g~Bon travail, nous pouvons commencer maintenant !",
	tutorial_beginner_training_success_02 = "~g~Bien, tu as compris.\n~w~Il s'agit du même processus pour utiliser tous les items.",
	tutorial_beginner_training_success_03 = "~g~Cool, tu as compris.\n~w~Il s'agit du même processus pour utiliser tous les items.",
	tutorial_beginner_training_success_04 = "~g~Bien, tu as compris.\n~w~Nous avons fini maintenant.",

	-- Darkzone stuff
	contaminated = "contaminé",
	darkzone_boat_leaving_in = "Départ des bateaux",
	darkzone_exit = "Spot de sortie",
	purificator = "Purificateur",
	you_entered_the_darkzone = "~r~Vous êtes entré dans la darkzone.\n~w~Il y a actuellement ~b~%s joueurs~w~ à l'intérieur.",
	you_left_the_darkzone = "~r~Vous avez quitté la darkzone.",
	cannot_enter_darkzone_time = "~r~La darkzone n'est pas encore ouverte, patientez.",
	darkzone_is_full = "~r~La darkzone est pleine, veuillez patienter.",
	darkzone_exit_allowed = "~r~Des bateaux sont arrivés pour sortir de la darkzone, courez si vous voulez vous échapper..",
	darkzone_close_time = "Fermeture",
	darkzone_surviving_since = "Survivant depuis",
	darkzone_points = "Points",
	darkzone_points_x = "~r~Points de darkzone: ~w~+%s",
	darkzone_landing_in_x = "Atterrissage disponible dans ~b~%s minutes~w~.\nSi suffisamment de joueurs.",
	darkzone_open_press_context = "La darkzone est ouverte~w~.\nAppuyez sur ~INPUT_CONTEXT~ pour atterir ~m~sur la darkzone~w~.",
	darkzone_outside_warning = "~r~Vous êtes en dehors de la darkzone, revenez ou mourez..",
	darkzone_close_warning = "~r~La darkzone va bientôt fermer~w~.\nVous ne devriez pas rester ici trop longtemps.",
	darkzone_close_damage = "La darkzone s'est refermée, toute la zone est maintenant contaminée.",
	darkzone_not_enough_points_to_exit = "Vous avez besoin de ~r~%sx points~w~ pour sortir de la darkzone.",
	press_e_to_exit_the_darkzone = "Appuyez sur ~INPUT_CONTEXT~ pour sortir de la darkzone.\n~r~Vous avez besoin de x%s darkzone points.",
	use_purificator = "utiliser le purificateur",
	darkzone_not_enough_points_to_start_purificator = "Vous avez besoin de ~r~%sx points~w~ pour démarrer le purificateur.",
	darkzone_not_enough_points_to_refill_purificator = "Vous avez besoin de ~r~%sx points~w~ pour recharger le purificateur.",
	darkzone_too_far_from_purificator = "~r~Vous êtes trop loin du purificateur.",
	darkzone_cant_remove_while_running_purificator = "~r~Vous ne pouvez pas retirer des articles pendant que le purificateur est en marche.",
	darkzone_purificator_running = "~r~Vous ne pouvez pas mettre d'objets pendant que le purificateur est en marche.",
	darkzone_purificator_running_refill = "~r~Vous ne pouvez pas remplir la machine pendant que le purificateur est en marche.",
	darkzone_put_x_in_purificator = "Vous avez mis ~r~%s~w~ dans le purificateur.",
	darkzone_you_took_x_from_purificator = "Vous avez pris ~r~%s~w~ du purificateur.",
	darkzone_purificator_does_not_need_refill = "Vous n'avez pas besoin de ~r~lancer le purificateur~w~.",
	darkzone_refilled_purificator_x = "Vous avez utilisé ~r~x%s points~w~ pour activer le purificateur.",
	darkzone_open = "Les atterrissages en Darkzone sont disponibles.\n~r~Trouvez un transporteur dans n'importe quelle safezone.",
	darkzone_item_clean = "Cet objet est déjà propre.\n~r~Vous ne pouvez mettre que des articles contaminés.",
	
	dungeon_cooldown_between = "Veuillez patienter ~r~%s minutes~w~ avant de recommencer le donjon une nouvelle fois.",
	set_as_default = "Défini comme customisation personnalisée par défaut pour le modèle de véhicule",
	car_custom_presets_saved = "Votre présélection de personnalisation pour ~g~%s~w~ ont été sauvegardés.",
	marketplace_you_received_x_x = "Vous avez reçu ~b~%sx ~g~%s~w~.",

	above_level_x_no_longer_possible_loot_safe = "Les joueurs au-dessus du rang %s ne peuvent pas piller les zombies dans les safezones.",
	preferred_component_desc = "Cet ensemble sera l'ensemble par défaut de tous les %s que vous tiendrez.",
	set_as_preferred_component_class = "Définir comme ensemble de composants préférés",
	weapon_presets_updated = "Vous avez défini les composants par défaut pour votre ~g~%s~w~.",

	-- New survey
	poll6_q1 = "Would you like the crew member limit to be set to 25 members? (more competition, smaller groups)",
	poll6_q2 = "Is your main server fine for your ping? (Is your average ping ok?)",
	poll6_q3 = "Are you playing in private worlds?",
	poll6_q4 = "Should headshots be enabled for season 4?",
	
	casino_dungeon_desc = "⚠️ ~r~Vous pouvez avoir besoin d'une lampe sur votre arme pour bien voir ici.",
	dungeon_destroy_wall_obj = "Détruisez le mur qui bloque votre chemin.",
	dungeon_use_key_obj = "Utilisez la clé pour ouvrir la porte.",
	dungeon_kill_zombies_obj = "Tuez tous les zombies.",
	dungeon_kill_zombies_obj_x = "~b~Tuez tous les zombies.~w~\n%s/%s des joueurs ont tué leurs zombies.",
	dungeon_use_key_to_open_door = "Utilisez la clé pour ouvrir la porte.",
	dungeon_find_key_obj = "Trouvez une clé pour ouvrir la porte dans la pièce.",
	take_key = "prendre la clé",
	open_the_door = "ouvrir la porte",
	dungeon_quit_notif = "Tapez ~g~/dungeon quit~w~ pour quitter le donjon.",
	dungeon_generator_obj = "Trouvez le générateur et ré-activez le courant.",
	dungeon_press_generator = "Appuyez sur ~INPUT_CONTEXT~ pour activer le générateur.",
	power_generator = "Générateur d'électricité",
	dungeon_find_c4_obj = "Il y a des blocs de C4 cachés quelque part, trouvez-les.",
	dungeon_use_c4_obj = "Utilisez votre C4 pour faire sauter la porte du coffre.",
	dungeon_party_help = "Tapez ~b~\"/dungeon\"~w~ pour gérer la partie du donjon.",
	press_x_to = "Appuyez sur %s pour %s",

	quest_clean_zone = "Nettoyage de la zone: %s",
	quest_clean_zone_desc = "Rendez-vous: %s et nettoyez la zone des zombies.",

	loot_crate_light = "Caisse de butin légère",
	loot_crate_medium = "Caisse de butin moyenne",
	loot_crate_high = "Caisse de butin élevée",
	
	dailymission_killzombieinzoneid = "Zombies tués dans la zone",
	dailymission_dungeonbosskilled = "Boss du donjon tué",

	quest_too_far_npc = "~r~Vous êtes trop loin du PNJ de la quête.",
	quest_already_started_quest = "~r~Vous avez déjà commencé cette quête.",
	quest_redo_in_x = "~r~Vous avez déjà fait cette quête.\n~w~Vous pourrez refaire cette quête dans ~b~%s",
	quest_max_quests_reached = "~r~Vous ne pouvez accepter que %s quêtes.",
	quest_new_accepted = "~g~Vous avez accepté une nouvelle quête.",
	quest_gave_up = "~r~Vous avez abandonné cette quête.",
	quest_not_completed = "~r~Vous devez remplir tous les objectifs de la quête.",
	quest_already_completed = "~r~Vous avez déjà accompli cette quête.",
	quest_all_completed = "~g~Vous avez réussi à atteindre tous les objectifs.",
	dungeon_key = "Clé de donjon",
	darkzone_cannot_enter_min_levels = "Vous devez être niveau ~b~%s~w~ pour entrer en darkzone.",
	questmenu_command = "Ouvrir le menu des quêtes",
	squadmenu_command = "Ouvrir le menu des escouades",
	airdrop_coming_darkzone = "~r~Un larguage est en chemin en darkzone.",
	darkzone_full_crew = "Il y a déjà ~r~%s membres~w~ de votre crew dans la darkzone, attendez que quelqu'un en sorte.",

	crew_join_cooldown_x = "Vous devez patienter ~r~%s~w~ avant de joindre ce crew.",
	darkzone_not_enough_players_darkzone = "La darkzone n'ouvrira pas.\n~r~Pas suffisamment de joueurs.",

	dungeon_loot_boss_box = "~g~Un coffre est apparu au centre de la pièce.",
	drug_antizin_bar = "Effet Antizin",
	drug_stamina_bar = "Effet Endurance",
	drug_berserker_bar = "Effet Vie",
}

AddLanguage("fr", my_language)
