-- Put your Lua here
local my_language = {
	give_vehicle = " ~b~%s~w~ Envanterine eklendi.",
	store_vehicle_command = "Sürmekte olduğunuz aracı saklayın",
	no_entity_vehicle = "~r~Araç mevcut değil veya sizden çok uzak.",
	no_entity_vehicle_id = "~r~Araç herhangi bir kimliğe bağlı değildir, saklayamazsınız.",
	store_vehicle = "~b~Aracı envanterine koydun.",
	teleported_former_position = "~g~En son kaydedilen konumunuza ışınlandınız.",
	not_enough_of = "~r~Yeteri kadar %s yok.",
	max_storage_chest = "~r~Depolama alanı dolu.",
	cant_carry_more_items = "~r~Envanterin daha fazla ürün depolayamaz(dolu).",
	put_item = "~g~x%s~w~ %s~w~ Koydun.",
	take_item = "~g~x%s~w~ %s~w~ Aldın.",
	delete_item = "~r~x%s~w~ %s~w~ Sildin.",
	you_equiped_item = " ~g~%s~w~ Kullandın.",
	bind_weapon_command = "Silah koymak için kısayol %s",
	kevlar_broke = "~r~AHH!~n~~w~Zırhın kırıldı.",
	inventory_command = "Envanteri aç",
	press_enter_to_join = "Oynamak için ~g~ENTER~w~ bas.",
	new_character = "Yeni karakter",
	survivor = "Hayatta kalan",
	right = "Sağ",
	left = "Sol",
	male = "Erkek",
	female = "Kadın",
	ped = "Ped",
	name = "İsim",
	sex = "Cinsiyet",
	title = "Ünvan",
	select_this_character = "Karakteri seç",
	no_entity_zombie = "Zombi yok ya da senden çok uzak.",
	you_found = " ~g~%sx %s~w~ Buldun.",
	you_found_nothing = " ~g~Bir şey~w~ bulamadın.",
	press_e_to_loot = "Yağmalamak için ~b~[E]~w~ tuşuna bas",
	full_for_item = "~r~Bu eşya için yeterli alan yok.",
	put_item_container = " ~g~x%s~w~ %s~w~ konteynerine koydun.",
	take_item_container = " ~g~x%s~w~ %s~w~ konteynerden aldın.",
	not_allowed_here = "~r~Bunu burada yapmana izin yok.",
	cant_store_moving_veh = "~r~Hareket halindeki bir aracı depolayamazsın.",
	use_repair_tool = "Tamir kitini kullan",
	please_get_closer = "~b~Lütfen yaklaşın, yakında bir canlı yok.",
	you_cancel_action = "~r~ Eylemi iptal ettin.",
	selected_target_message = "Hedef seçildi:~n~%s~n~~r~İptal etmek için ~b~Y~r~ tuşuna basın~n~~r~Devam etmek için ~g~X~r~ tuşuna basın.",
	target_you = "~b~SEN",
	target_screen = "~g~Görüntüle",
	take_this_path = "Işınlayıcıyı kullanmak",

	-- hud
	default_hud = "Default HUD",
	cinema_hud = "Cinema HUD",
	no_hud = "No HUD",

	-- perms
	kick_member = "Üye at",
	edit_member = "Üyeleri düzenle",
	edit_rank = "Rütbeleri düzenle",
	create_rank = "Rütbe oluştur",
	delete_rank = "Rütbe sil",
	edit_structure = "Ekip bilgilerini Düzenle",
	edit_permissions = "Yetkileri düzenle",
	permission_level = "Yetki Verme",
	red_delete = "Sil",
	rank = "Rütbe",
	red_kick = "At",
	crew_name = "Ekip ismi",
	slogan = "Ekip açıklaması",
	information = "Ekip bilgisi",
	boss_rank = "Yetkili rütbesi ismi",
	member_rank = "Yeni üye yetkisi ismi",
	member = "Üye",

	permissions_manager = "Yetki yönetimi",
	members_manager = "Üye yönetimi",
	ranks_manager = "Rütbe yönetimi",
	ranks_list = "Rütbe listesi",
	members_list = "Üye listesi",
	create_a_rank = "Rütbe oluştur",
	invite_someone = "Davet et",
	stats = "İstatistikler",
	total_ranks = "Rütbe sayısı",
	total_members = "Üye sayısı",
	level = "Seviye",
	actions = "Eylemler",
	crew_manager = "Ekip yönetimi",
	you_created_a_new_crew = "Yeni ekip oluşturuldu: %s",
	you_deleted_your_crew = "Ekip silindi.",
	you_are_not_in_a_crew = "Bir ekipte değilsin",
	you_joined_the_crew = "'%s' Ekibine Katıldın",
	kick_failed = "Atma başarısız oldu, Sebep: %s",
	already_in_crew = "Zaten bir ekiptesin",
	no_invitation = "Herhangi bir ekip davetin yok.",
	left_crew = "Ekipten ayrıldın.",
	permission_updated = " <C>~g~%s</C>~w~ Yetkisi güncellendi.",
	incorrect_name = "~r~İsim formatı yanlış",
	incorrect_rank_perm = "~r~Hata\n~w~Geçersiz rütbe ismi yada yetki seviyesi.",
	warn_rank_limit = "~r~Rütbe sınırına ulaştın.",
	create_rank_success = "~g~Başarılı\n~w~ <C>~b~%s</C>~w~ Yetki seviyesinde <C>~b~%s</C>~w~ rütbesi oluşturuldu",
	crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~Seninkinden yüksek bir yetki düzeyine sahip bir üyeyle etkileşimde bulunamazsın.",
	you_sent_an_invitation = " <C>~g~%s</C>~w~ ekibe davet edildi .",
	you_received_an_invitation = "Bir ekibe katılmak için bir davet aldınız.\n~b~/%s accept.",
	invitation_expired = "Davet süresi doldu",
	crew_kick_success = "<C>~b~%s</C>~w~ Kişisini ekipten attın.",
	first_rank_warning = "İlk sıra 'varsayılan' rütbedir.",

	you_updated_this = "Güncelledin %s ~g~<C>%s</C>~w~.",
	changes_saved_on = " <C>~g~%s</C>~w~ Yapılan değişikler kaydedildi.",
	yes = "Evet",
	no = "Hayır",
	none = "Yok",
	character_id = "Karakter ID",
	server_id = "Server ID",
	report = "Raporla",
	rename = "Yeniden adlandır",
	trade_with = "Takas",

	please_wait_x_before = "~r~Lütfen %s saniye bekleyin.",

	-- cloth
	take_outfit = "Bu kıyafeti satın al",
	wardrobe_options = "Kıyafet dolabı seçenekleri",
	wardrobe = "Kıyafet dolabı",
	manual_options = "Manuel seçenekler",
	manual_mode = "Manuel mod",
	save_outfit = "Bu kıyafeti kaydet",
	variation = "Varyasyonlar",
	outfits = "Kıyafetler",
	cloth_shop = "Kıyafet mağazası",
	ped_cloth_shop = "Ped kıyafet mağazası",
	manual_props = "Manuel dekor",
	manuel = "Manuel",
	new_name = "Yeni İsim",
	outfit_name = "Kıyafet adı",
	variations_saved = "~g~Başarılı.~n~~w~Karakter varyasyonlarınız kaydedildi.",
	equipped_new_outfit = " ~b~%s Kıyafetini giydin ",
	warning_limit_outfits = "Kaydedilecek kıyafet limitine ulaştın. ~g~(%s)",
	saved_new_outfit = " ~b~%s~w~ Kıyafetini kaydettin",
	rename_outfit = " ~b~%s~w~ İsimli kıyafet ~g~%s~w~ olarak değiştirildi.",
	delete_outfit = " ~b~%s~w~ İsimli kıyafet silindi.",

	torso = "Kol",
	props = "Aksesuarlar",
	top = "Üst Giyim",
	tops = "Üst Giyimler",
	badge = "Rozetler",
	pants = "Alt Giyimler",
	pant = "Alt Giyim",
	shoes = "Ayakkabılar",
	bags = "Çantalar",
	undershirt = "Üst Giyim",
	neck = "Boyun",
	bracelets = "Kolyeler",
	montres = "Saatler",
	earrings = "Küpeler",
	glasses = "Gözlükler",
	hats = "Şapkalar",
	graphiques = "Dekorasyonlar",

	-- health
	inconscious = "Bilinçsiz",
	doing_something = "Bir şeyler yap",
	time_before_respawn = "Yeniden doğma süresi",
	you_died = "~r~Öldün.",
	healing_wounds = "İyileşiyorsun...",
	already_doing_something = "~r~Zaten bir şeyler yapıyorsun.",
	you_have_been_healed = "~g~İyileştirildin.",
	you_respawned = "~g~Yeniden doğdun.",

	player_too_far_to_interact = "~r~Etkileşime geçmek istediğin oyuncu senden çok uzakta.",
	send_trade_invitation_to = " ~b~%s~w~ kişisine takas için davet yolladın.\n~b~Oyuncunun kabul etmesi bekleniyor.",
	receive_invitation_from = "~b~%s~w~ kişisinden bir takas daveti aldın.\n~w~Kişinin takas davetini kabul etmek için ~b~/trade accept %s~b~ yaz.",

	invalid_command_args = "Geçersiz komut argümanı: %s",
	start_trade_command_help = "Başka bir oyuncuyla takas başlatın",
	accept_trade_command_help = "Takas davetini kabul edin",
	deny_trade_command_help = "Takas davetini reddedin",
	invalid_invitation = "Davet geçersiz yada süresi geçmiş",
	name_accepted_your_trade_invitation = "~b~%s~w~ Takas davetinizi kabul etti",
	you_accepted_trade_invitation_of_name = "%s kişisinin takas davetini kabul ettiniz",
	name_denied_your_trade_invitation = "~b~%s~w~ takas davetinizi reddetti",
	you_denied_trade_invitation_of_name = "%s kişisinin takas davetini reddettin",
	you_already_trading = "Zaten bir takastasın",
	other_already_trading = "Diğer oyuncu şuan zaten bir takasta",

	other_player_not_enough_money = "~r~Takas iptal edildi. Diğer oyuncu yeterli paraya sahip değil.",
	you_player_not_enough_money = "~r~Takas iptal edildi. Yeterli paraya sahip değilsin.",
	other_player_not_enough_item = "~r~Takas iptal edildi. Diğer oyuncu gerekli eşyalara sahip değil.",
	you_player_not_enough_item = "~r~Takas iptal edildi. Gerekli eşyalara sahip değilsin.",
	success_trade = "~g~Takas onaylandı.",
	fail_trade_other_player = "~r~Takas iptal edildi, diğer oyuncu ayrıldı.",
	trade_other_full_item = "~r~Takas iptal edildi, diğer oyuncu yeterli depolomaya sahip değil.",
	trade_full_for_item = "~r~Takas iptal edildi, yeterli depolamaya sahip değilsin.",

	press_e_to_loot_inv = "Yağmalamak için ~INPUT_CONTEXT~ tuşuna bas.",
	press_e_to_interact_with = " ~HUD_COLOUR_NET_PLAYER27~ Etkileşime geçmek için ~INPUT_CONTEXT~ tuşuna bas: ~b~%s~HUD_COLOUR_NET_PLAYER27~.",
	press_e_to = "~b~%s~w~ için ~INPUT_CONTEXT~ tuşuna bas.",
	press_e_to_open_catalog = "~g~Katalog~w~ için ~b~E~w~ tuşuna bas.",
	this_person = "Bu kişiyle",
	the_shop = "Mağaza",
	you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~Bunu yapmana izin yok.",

	no_weapon = "~r~Elinde herhangi bir silah yok.",
	no_need_ammo = "~r~Bu silahla herhangi bir mühimmat kullanmana gerek yok.",
	not_right_ammo = "~r~Yanlış mühimmat kullanıyorsun, ~b~%s~w~ kullanmalısın.",
	you_used_ammo = "~b~%s~w~ silahına ~b~x%s~w~ tane ~b~%s~w~ mühimmat koydunuz.",

	choose_a_destination = "Bir ~b~konum seçmek",
	open_your_chest = "Sandığı açmak",
	no_enough_money = "~r~Yeterli paran yok.",
	you_paid = "~g~$%s~w~ Ödeyerek ~b~%s~w~ Satın aldın.",
	you_paid_basket = "Sepetin için ~g~$%s~w~ ödedin.",
	you_sell_basket = "~g~$%s~w~ Fiyatına ~b~x%s~w~ Eşya sattın.",

	you_repaired_your_vehicle = "~g~Aracını tamir ettin.",
	repairing_your_vehicle = "Aracın tamir ediliyor",
	wheels_are_fine = "~r~Araç tekerlekleri zaten iyi.",
	changing_wheel = "Tekerlek değiştiriliyor",
	you_repaired_the_wheels = "~g~Tekerlekleri tamir ettin.",

	front_post_ls = "Front post Los Santos",
	front_post_ls_2 = "Front post Los Santos 2",
	front_post_bc = "Front post Blaine County",
	front_post_bc_2 = "Front post Blaine County 2",
	main_post_ls = "Safe City Los Santos",
	main_post_bc = "Safe City Blaine County",
	random_zone = "Rastgele Konum",

	this_item_is_equipped = "~r~Silah elinde, depolamak için kısayoldan kaldır.",
	only_in_safezone = "~r~Bunu sadece güvenli bölge de yapabilirsin.",
	-- commerce stuff
	feature_gold_only = "Bu özellik sadece ~y~gold üyeler~w~ içindir.",
	feature_diamond_only = "Bu özellik sadece ~b~diamond üyeler~w~ içindir.",
	you_turned_into = " ~g~%s~w~ Pedine dönüştün.",
	wait_between_transformation = "~r~Değişim modunu tekrar kullanmadan önce lütfen biraz bekleyin.",
	wait_between = "~r~Lütfen bunu tekrar yapmadan önce biraz bekleyin.",
	available_morphs = "Mevcut değişimler",
	animal_models = "Hayvan modelleri",
	zombie_models = "Zombi modelleri",
	success_update_name = "Karakterinin adını ~b~%s~w~ olarak değiştirdin.",
	success_reset_stats = "~g~İstatistiklerini başarıyla sıfırladın. (Lider tablosu daha sonra güncellenecektir)",

	-- animals
	boar = "Yaban domuzu",
	cat = "Kedi",
	chop = "Rottweiler (Chop)",
	rottweiler = "Rottweiler",
	cow = "İnek",
	coyote = "Çakal",
	deer = "Geyik",
	hen = "Tavuk",
	husky = "Husky",
	mtlion = "Aslan",
	pig = "Domuz",
	poodle = "Kaniş",
	pug = "Pug",
	rabbit = "Tavşan",
	rat = "Sıçan",
	retriever = "Av köpeği",
	shepherd = "Alman kurdu",
	westy = "Teriyer",

	player_id = "Oyuncunun ID'si",
	bounty = "Ödül",
	reason = "Sebep",
	id_player_not_found = "~r~Hiçbir oyuncu bu ID'ye bağlı değil.",

	ammo_dealer = "Mühimmat Satıcısı",
	misc_dealer = "Ekipman Satıcısı",
	veh_dealer = "Araç Satıcısı",
	custom_dealer = "LS Custom",
	gun_dealer = "Silah Satıcısı",

	bounty_created = "~b~%s~w~ Adlı oyuncunun başına  ~g~$%s~w~ ödül koydun.",
	contract_success = "~r~%s~w~ Adlı oyuncunun başına koyduğunuz ödül ~b~%s~w~ Kişisine gönderildi.",
	a_contract_on_your_head = "~r~Başında bir ödül vardı. Katiliniz ödülü aldı.",
	reward_for_contract = "Ödül Avcısı! ~b~%s~w~ adlı oyuncuyu öldürdüğün için ~g~$%s~w~ aldın.",

	hey_can_help_you = "Hey, nasıl yardımcı olabilirim?",
	i_want_to_buy_items = "Esya almak istiyorum",
	i_want_to_sell_items = "Esya satmak istiyorum",

	press_context_or_jump_to_get_up = "~b~Kalkmak için~w~ ~INPUT_CONTEXT~ yada ~INPUT_JUMP~ tuşuna bas.",
	server_restart_warning = "Sunucu yeniden başlatılacak..",
	auto_restart_in = "Otomatik Yeniden başlatma  %s saniye sonra.",

	not_allowed_create_character = "Yeni bir karakter oluşturmana izin verilmiyor.",
	character_not_yours = "Bu karakter senin değil.",
	character_does_not_exist = "Bu karakter yok yada artık kullanılmıyor.",
	loading_character = "Karakterin yükleniyor...",

	playtime_is = "~b~Extinction oynama süresi:\n~w~%s",
	dont_spam = "^1Spam yapma!",

	babygod_warning = "~b~Güvenli alandan ayrıldın, bir süre dokunulmazsın, yeni bir güvenli alan bul!",

	-- LS Custom
	modifications_classiques = "Klasik modifikasyonlar",
	modifications_custom = "Özel modifikasyonlar",
	modifications_benny = "Benny's modifikasyonlar",
	paint = "Boya",
	custom_your_car = "Aracını özelleştir",
	wheels_modifications = "Tekerlek modifikasyonları",
	performances = "Performans",
	neons = "Neonlar",
	extra = "Ekstralar",
	klaxon = "Korna",
	teinte_fenetre = "Cam renk tonu",
	phares_xenons = "Xenon far",
	modele_plaque = "Plaka modeli",
	livery = "Çıkartmalar",
	headlight_color = "Far renkleri",
	wheel_type = "Tekerlek tipi",
	primary_wheel_type = "Ön tekerlek tipi",
	back_wheel_type = "Arka tekerlek tipi",
	wheel_color = "Tekerlek rengi",
	tire_smoke = "Lastik dumanı",
	custom_color = "Özel renk",
	custom_wheel = "Özel tekerlek",
	custom_back_wheel = "Özel arka tekerlek",
	suspension = "Süspansyon",
	transmission = "Vites",
	moteur = "Motor",
	frein = "Fren",
	turbo = "Turbo",
	primary_color = "İlk renk",
	secondary_color = "İkinci renk",
	interior_color = "İç renk",
	dashboard_color = "Gösterge paneli rengi",
	color_effect = "Renk efekti",
	left_neon = "Sol neon",
	right_neon = "Sağ neon",
	front_neon = "Ön neon",
	back_neon = "Arka neon",

	aileron = "Spoiler",
	pc_front = "Ön tampon",
	pc_back = "Arka tampon",
	carroserie = "Yan etek",
	exhaust = "Egzoz",
	cadre = "Çerçeve",
	calandre = "Izgara",
	capot = "Kaput",
	gb_left = "Sol çamurluk",
	gb_right = "Sağ çamurluk",
	roof = "Tavan",
	plate_support = "Plaka tutucular",
	front_plate = "Ön plaka",
	interior_style = "İç stil",
	figurine = "Heykelcik",
	motif_dashboard = "Gösterge paneli stili",
	cadran = "Kadran tasarımı",
	haut_parleur_portes = "Kapı hoparlörleri",
	motif_sieges = "Koltuk stili",
	volant = "Direksiyon",
	levier = "Vites kolu",
	logo_custom = "Logo",
	ice = "ICE",
	haut_parleur_coffre = "Arka kapı hoparlörler",
	hydrolique = "Hidrolikler",
	moteur = "Motor",
	filtres_air = "Hava filtresi",
	entretoises = "Ara parçalar",
	arc_couverture = "Kemer",
	antenne = "Anten",
	motif_exterieur = "Dış stil",
	reservoir = "Silah",
	window = "Pencere",
	style = "Stil",
	default = "Varsayılan",
	type = "Tip",
	normal = "Normal",
	black = "Siyah",
	black_smoke = "Siyah duman",
	simple_smoke = "Basit duman",
	stock = "Stok",
	limo = "Limuzin",
	sa_black = "San Andreas siyah",
	sa_blue = "San Andreas mavi",
	sa_white = "San Andreas beyaz",
	simple_white = "Basit beyaz",
	ny_white = "North Yankton beyaz",
	race = "Yarış",
	sport = "Spor",
	stock = "Stok",
	street = "Sokak",
	discount = "Kısık",
	select_your_car = "Aracını seç",
	select_car_custom = "Özelleştirmek istediğin aracı seç.",
	loading_vehicle = "Araç oluşturuluyor",
	invalid_vehicle = "~r~Geçersiz araç varlığı.",
	invalid_vehicle_please_spawn = "~r~Geçersiz araç eşyası. Lütfen bir şey yapmaya çalışmadan önce onu bir kez oluşturun.",
	free_take_and_validate = "Herşey bedava. İstediğini al ve onayla!",
	car_custom_saved = "~g~Araç modifikasyonların kaydedildi.",

	-- Character creation
	character_creation = "Karakter yaratma",
	confirm = "Onayla",
	start_playing = "Oynamaya başla",
	appearance = "Görünüm",
	character_list = "Karakter listesi",
	face_features = "Yüz özellikleri",
	parents = "Ebeveynler",
	parent = "Ebeveyn",
	mix = "Karıştır",
	skin = "Deri",
	desc_mix = "Yüzünüzün şeklinin babanız/annenizden etkilenme oranını seçin.",
	desc_skin = "Cildinizin babanız/annenizden etkilenme oranını seçin.",
	identity = "Kimlik",
	player_name = "Oyuncu adı",
	new_character = "Yeni karakter",
	warning_headblend = "~r~Karakterinizin ebeveynlerini seçmediniz.",
	warning_overlays = "~r~Saç, kaş veya sakal seçmediniz.",
	warning_identity = "~r~Dikkat.~n~~w~Kimlik sekmesini doldurmayı unuttunuz.",

	-- kits
	kit_does_not_exist = "~r~Bu kit mevcut değil",
	kit_needs_rank = "~r~%s~w~ Üyeliğine sahip değilsin.",
	wait_before_using_kit = "Lütfen ~r~%s~w~ kitini kullanmadan önce bekleyin.",
	received_kit = "~b~%s~w~ Kitini aldın.",
	no_kit = "Herhangi bir kite sahip değilsin.",

	unable_to_find_booster = "Bu id'ye ait bir booster bulunamıyor.",
	wait_already_player_boost = "Lütfen booster kullanmadan önce bekleyin. Zaten bir booster aktif.",
	wait_already_crew_boost = "Lütfen booster kullanmadan önce biraz bekleyin. Zaten ekip boosterı aktif.",
	wait_already_server_boost = "Lütfen booster kullanmadan önce biraz bekleyin. Zaten sunucuda booster aktif.",
	booster_activated = "Booster ~g~%s dakika boyunca~w~! ~b~XP +%s%% özellikleriyle aktive oldu",
	server_booster_activated = "~b~%s~w~ ~g~%s dakika~z~! ~b~XP +%s%% özellikleriyle sunucu boosterı aktive etti",
	crew_booster_activated = "~b~%s~w~ ~g~%s dakika~z~! ~b~XP +%s%% özellikleriyle ekip boosterı aktive etti",
	no_booster = "Herhangi bir boostera sahip değilsin.",

	rank_expired = "~r~Satın alınan üyeliğin süresi bitti.",
	supporter_role = "~g~Üyelik durumu: ~w~ %s",
	no_rank_warning = "Herhangi bir üyeliğe sahip değilsin.\n~r~Eğer bir üyelik aldıysan, FiveM hesabını bağla.",
	no_fivem_id = "FiveM hesabın oyunla bağlı değil.\n~r~FiveM hesabını oyunla bağla.",
	no_queue_warning = "Sırada herhangi bir paketin yok.\n~r~Biraz bekle yada /getRank komutunu kullan.",
	package_sync_success = "~g~Paketlerin doğru şekilde senkronize edildi, eğlenmene bak!\n~w~Kullanılabilir komutlar: /getRank, /booster",

	level_required = "%s Seviyesine sahip olmalısın.",
	rank_required = "%s Üyeliğine sahip olmalısın.",
	level_required_2 = "~r~%s Seviyesine sahip olmalısın.",

	updated_deathmessage = "~g~Öldürme mesajını güncelledin.",
	updated_deatheffect = "~g~Öldürme efektini güncelledin.",
	use = "Kullan",
	test = "Test",

	-- zombie
	you_bitten = "~r~Isırıldın.",
	infection_rate = "Enfeksiyon oranı: ~r~%s%%",

	-- ranks
	thug = "Thug",
	hustler = "Hustler",
	soldier = "Soldier",
	trigger = "Trigger",
	enforcer = "Enforcer",
	facilitator = "Facilitator",
	public_enemy = "Public Enemy",
	shot_caller = "Shot Caller",
	street_boss = "Street Boss",
	kingpin = "Kingpin",
	-- Tattoo
	tattoo = "Dövme",
	tattoos = "Dövmeler",
	torso = "Kol",
	head = "Baş",
	left_arm = "Sol kol",
	right_arm = "Sağ kol",
	left_leg = "Sol bacak",
	right_leg = "Sağ bacak",
	unknown = "Bilinmiyor",
	other = "Diğer",
	remove_tattoo = "Tüm dövmeleri kaldır",
	-- Hairdress
	haircuts = "Saç",
	makeup = "Makyaj",
	face = "Yüz",
	eyebrows = "Kaş",
	facial_hair = "Sakal",
	body_hair = "Vücut kılı",
	barber_shop = "Kuaför",
	face_makeup = "Yüz makyajı",
	lipstick = "Ruj",
	face_foundation = "Fondöten",
	skin_blemishes = "Cilt lekeleri",
	skin_ageing = "Cilt yaşlanması",
	moles_freckles = "Benler ve Çiller",
	sun_damage = "Cilt hasarı",
	skin_complexion = "Cilt rengi",
	body_blemishes = "Vücut lekeleri",
	body_blemishes_2 = "Vücut lekeleri 2",
	opacity = "Opaklık",
	variations = "Varyasyonlar",
	filter = "Filtre",
	eyes_color = "Göz rengi",
	-- Mask
	masks = "Maskeler",
	-- Items
	money = "Para",
	-- Ammo
	["9mm"] = "9mm",
	["300_mag"] = ".300 Magnum",
	["7_62mm"] = "7.62mm",
	["calibre_12"] = "Calibre 12",
	["45_acp"] = ".45 ACP",
	["5_56mm"] = "5.56mm",
	rocket = "Rocket",
	flare = "Flare",
	grenade = "Grenade",
	-- Food
	["fish_1"] = "Largemouth Bass",
	["fish_2"] = "Rainbow Trout",
	["fish_3"] = "Kokanee",
	["fish_4"] = "Arctic Grayling",
	["fish_5"] = "Rock Bass",
	["fish_6"] = "Smallmouth Bass",
	["fish_7"] = "Paddlefish",
	["fish_8"] = "Bull Trout",
	["fish_9"] = "Lake Trout",
	["fish_10"] = "Chinook",
	["fish_11"] = "Pallid Sturgeon",
	["fish_12"] = "Salmon",

	misc_meat = "Raw meat",
	rabbit_meat = "Raw rabbit",
	lion_meat = "Raw lion",
	rare_plume = "Rare feather",
	dog_meat = "Raw dog",
	cat_meat = "Raw cat",
	rare_fish = "Rare fish",

	mask = "Maske",
	malette = "Suitcase",
	malette_metal = "Metal suitcase",
	ciseaux = "Scissors",
	clean_kit = "Clean kit",
	fishing_rod = "Fishing rod",
	meuble = "Furniture",
	tissu = "Cloth",
	accessory = "Accessory",
	radio = "Radio",
	recyclor = "Recycler",
	medkit = "Medkit",
	kevlar = "Kevlar",
	gps = "GPS",
	repair_tool = "Repair kit",
	jvn = "JVN",
	engine_veh = "Engine",
	wheel_veh = "Wheel",
	vetement = "Top",
	bloc_note = "Notepad",
	paint_spray = "Paint spray",
	spike = "Spike strip",
	paracetamol = "Paracetamol",
	bandage = "Bandaj",
	gaz_mask = "Gaz mask",
	tattoo_tool = "Tattoo tool",
	drug_med = "Drug",
	drug_antizin = "Antizin shot",
	drug_stamina = "Stamina shot",
	drug_berserker = "Health shot",

	pickup_spikestrip = "Dikenli tel al",
	you_dropped_spikestrip = "~g~Dikenli tel~w~ koydun.",
	you_pickup_spikestrip = "~g~Dikenli tel~w~ aldın.",

	you_have_been_killed_by = "~r~%s Tarafından öldürüldün",
	kill_notif = "~m~Öldürdün",
	you_killed = "~r~%s~w~ Adlı oyuncuyu öldürdün",
	already_used_reset_only = "~r~Zaten Karakterini sıfırladın.\n~w~Yalnızca %s~w~ üyeler birden fazla yapabilir.",
	already_used_reset_only2 = "~r~Zaten bu işlemi yaptın.\n~w~Sadece %s~w~ üyeler birden fazla yapabilir.",

	hud_options = "HUD seçenekleri",
	advanced_hud = "Gelişmiş HUD göster",
	players = "Oyuncular-",
	health = "Saglik",
	player_menu = "Oyuncu menüsü",

	you_are_now_zombie = "~r~Şuanda bir zombisin.",

	my_weapons = "Silahlarım",
	customize_weapons = "Silahını özelleştir",
	weapon_skin = "Renk tonu",

	-- camo
	skin_classic = "Varsayılan",
	skin_green = "Yeşil",
	skin_yellow = "Sarı",
	skin_pink = "Pembe",
	skin_gold = "Altın",
	skin_blue = "Mavi",
	skin_orange = "Turuncu",

	weapon_katana = "Katana",
	weapon_sledgehammer = "Balyoz",

	-- new
	airdrop_coming = "~r~Airdrop geliyor, haritanı kontrol et.",
	killed_by_cheater = "~r~Bir hileci tarafından öldürüldün.\n~w~Hileciyi sunucudan attık ve ölümünü iptal ettik.",

	corrupted_vehicle = "~r~Bu araç bozulmuş ve geçmişte kopyalanmış, envanterinden kaldırıldı. Dolandırıldıysan özür dileriz :(",

	-- Discord
	join_discord_for_kit = "Discordumuza katıl ve ücretsiz discord kitini al!\n~g~discord.gg/gtalife",
	discord_account_not_linked = "~r~Discord hesabını ve Fivem hesabını bağlamalısın.",
	discord_account_not_guild = "~r~Discord sunucumuzda değilsin.\n~w~Buraya katıl discord.gg/gtalife",

	already_done_recently = "~r~Daha sonra tekrar deneyin, son zamanlarda zaten yaptın.",
	update_country = "Ülkeni güncelle",

	prestige_info = "~b~Maksimum seviyeye ulaştın.\n~w~Prestij level sistemi hakkında bilgi almak için /prestige yaz.",
	prestige_not_max_level = "~r~Maksimum seviyeye ulaşmadın.",
	max_prestige_reached = "~r~Son prestij seviyesine ulaştın.",
	prestige_info_cmd = [[^3Prestij level sistemi^7
	Şuanki prestijin ^4%s^7 ve levelin ^5%s^7.

	Maksimum seviyeye (% s) ulaşırsan, prestij almayı seçebilir ve seviye 0'a dönmek için XP ilerlemeni yeniden başlatabilirsin.
	Yeni bir prestij kazanmak size özel bir rozet ve daha iyi ganimet, yeni eşyalar, daha fazla para veya daha yüksek taşıma kapasitesi gibi yeni avantajlar sağlar.
	^2Bir prestij almak ve 0 seviyeye dönmek istiyorsan ^1/setprestige^2 yazın
	]],
	new_prestige = "Yeni bir prestij açtın!\n~g~Şuanda %s prestije sahipsin",
	cant_store_event_veh = "~r~Özel araçları depolayamazsın.",

	you_are_no_longer_in_combat = "🛡️ ~b~Artık savaşta değilsin.",
	you_are_in_combat_mode = "🛡️ ~b~Savaştasın.\nEğer bağlantın kesilirse ölürsün.",
	you_disconnected_in_combat = "💀 Savaş modunda bağlantınız kesildi, öldün.",

	not_enough_prestige_points = "~r~Yeterli prestij puanınız yok.",
	you_reached_max_prestige_stats_rank = "~r~Bu prestij yükseltmesi için maksimum rütbeye ulaştın.",
	new_prestige_stats_upgrade = "~b~%s~w~\n~g~%s/%s Güncelledin",

	legendary_vehicle_pop = "~r~Haritada efsanevi bir araç belirdi!",

	-- poll one
	poll1_q1 = "Ne tür bir oyun sunucusu görmek istersiniz?",

	poll1_q1_a1 = "Battle Royale",
	poll1_q1_a2 = "Tek başına veya 1-4 arkadaşla özel görevler(Payday / Heist / Hitman gibi)",
	poll1_q1_a3 = "Yarış / Serbest sürüş",
	poll1_q1_a4 = "Katil / Korku oyunu",

	-- poll two
	poll2_q1 = "İngilizce konuşuyor musunuz ve bir GLife RP Sunucusuyla ilgilenir misiniz?",

	poll2_q1_a1 = "Hayır",
	poll2_q1_a2 = "Evet",

	combat_mode_container_disabled = "~r~Savaştasın.\n~w~Eşyanı depolayamazsın.",
	gcoins_wallet_updated = "~g~GCoins cüzdanın güncellendi.\n~w~+%s GCoins",
	not_enough_gcoins = "~r~Yeteri kadar GCoins'e sahip değilsin.",
	gcoins_something_went_wrong = "~r~Bir şeyler yanlış gitti.",
	you_bought_with_gcoins = "~b~%s GCoinsle~w~ ~g~%s~w~ aldın.",

	equiping_armor = "Zırh kullanılıyor...",

	toggle_mute_player = "Sessizliği Aç/Kapat",
	you_muted_this_player = "~b~Oyuncuyu susturdun.",
	you_unmuted_this_player = "~b~Oyuncunun sesini açtın.",

	already_purchased = "~r~Bu ürünü zaten satın aldın.",
	weapon_camo_preview = "Silah temel modeli gösteriliyor, bazı eklentiler eksik. Gösterimden çıkmak için \n~INPUT_CELLPHONE_CANCEL~.",

	already_using_a_seringue_booster = "~r~Şırınga zaten aktif.",
	seringue_effect_done = "~b~Şırınga efekti bitti.",
	you_injected_a_seringue_boost = "~b~Şırınga~w~ enjekte ettin.",

	put_item_permission = "Eşyaları koy",
	take_item_permission = "Eşyaları al",
	put_money_permission = "Parayı koy",
	take_money_permission = "Para al",

	preferred_badge_set = "~g~Tercih edilen rozeti~w~ ayarladın.",
	preferred_badge_not_set = "~r~Tercih edilen rozet ayarlanamıyor.",

	marketplace_received_money_sales = "~g~$%s~w~ Kazancı ~b~%s~w~ Satıştan elde ettin.",
	marketplace_no_sales = "~r~Hiçbir şey satmadın.",
	marketplace_you_paid_for = "~g~$%s~w~ Fiyatında ~b~%s~w~ aldın.",

	deleted_sell_offer = "~b~Satış teklifini sildin.",
	deleted_buy_offer = "~b~Satış teklifini sildin.",

	marketplace_offer_does_not_exist = "~r~Bu teklif artık mevcut değil.",

	marketplace_create_sell_offer = "~b~%sx %s ~w~İçin ~g~$%s~w~ Değerinde satış teklifi oluşturdun.",
	marketplace_create_buy_offer = "~b~%sx %s ~w~İçin ~g~$%s~w~ Değerinde alış yaptın.",

	i_want_to_enter_in_my_property = "Takım deposuna girmek istiyorum.",
	i_want_to_exit_private_world = "Herkese açık dünyaya dönmek istiyorum.",
	public_world = "Herkese açık dünya",
	private_world = "Özel dünya",

	dailymission_playerkill = "Öldürülen oyuncular",
	dailymission_zombiekill = "Öldürülen zombiler",
	dailymission_playerheadshotkill = "Oyuncu kafadan vuruşları",
	dailymission_zombieheadshotkill = "Zombi kafadan vuruşları",
	dailymission_zombiesurvivorkill = "Öldürülen survivor zombi",
	dailymission_zombiearmoredkill = "Öldürülen armored zombi",
	dailymission_zombiehazmatkill = "Öldürülen  hazmat zombi",
	dailymission_zoombieboomerkill = "Öldürülen boomer zombi",
	dailymission_sellitems = "Eşya satıldı",
	dailymission_buyitems = "Eşya alındı",
	dailymission_lootitems = "Eşyalar yağmalandı",
	dailymission_createselloffer = "Satış teklifi oluşturuldu",
	dailymission_killtopkillcrew = "Öldürülen ekip oyuncuları",
	dailymission_killtopkillplayers = "Öldürülen oyuncular",
	dailymission_getintolegendaryvehicle = "Araçlar",
	dailymission_killzombiewithweapon = "Silahla öldürülen zombiler",
	dailymission_killplayerwithweapon = "Silahla öldürülen oyuncular",
	dailymission_darkzonesurvivingtime = "Darkzone'da hayatta kalınan süre",
	dailymission_redzoneplayerkill = "Redzone'da öldürülen oyuncular",
	dailymission_redzonezombiekill = "Redzone'da öldürülen zombiler",
	dailymission_darkzoneplayerkill = "Darkzone'da öldürülen oyuncular",
	dailymission_darkzonezombiekill = "Darkzone'da öldürülen zombiler",
	dailymission_useitem = "Kullanılan eşyalar",
	dailymission_playtime = "Oynama süresi",
	dailymission_xpharvest = "Toplanan XP",
	dailymission_sellofferpurchased = "Satın alınan teklifler",
	dailymission_sellofferpurchasedbyme = "Satın alınan teklifler",
	dailymission_tradeitems = "Eşya takaslandı",
	dailymission_createbuyoffer = "Alış teklifi oluşturuldu",

	dailymission_completed = "~g~Günlük görevleri tamamladın!\n~b~+%s XP\n~y~+1 Zindan anahtarı",

	character_creation_mix_desc = "Yüzünüzün annenizin/babanızın şeklinden ne kadar etkileneceğini seçin.",
	character_creation_skin_desc = "Cildinizin annenizin/babanızın cildinden ne kadar etkileneceğini seçin.",

	ff_1 = "Burun genişliği",
	ff_2 = "Burun yüksekliği",
	ff_3 = "Burun uzunluğu",
	ff_4 = "Burun sarkması",
	ff_5 = "Burun tepe düşüşü",
	ff_6 = "Burun bükülmesi",
	ff_7 = "Kaş yüksekliği",
	ff_8 = "Kaş derinliği",
	ff_9 = "Elmacık kemiği yüksekliği",
	ff_10 = "Elmacık kemiği genişliği",
	ff_11 = "Yanak genişliği",
	ff_12 = "Göz açıklığı",
	ff_13 = "Dudak kalınlığı",
	ff_14 = "Çene genişliği",
	ff_15 = "Çene arka uzunluğu",
	ff_16 = "Çene indirme",
	ff_17 = "Çene kemiği uzunluğu",
	ff_18 = "Çene Genişliği",
	ff_19 = "Çene deliği",
	ff_20 = "Boyun kalınlığı",

	exit_the_darkzone = "Darkzone'dan çıkılıyor",
	you_entered_the_darkzone = "~r~Darkzone'a girdin.",
	you_left_the_darkzone = "~r~Darkzone'dan ayrıldın.",
	cannot_enter_darkzone_time = "~r~Darkzone henüz açılmadı, bekle.",
	darkzone_is_full = "~r~Darkzone tamamen dolu, lütfen bekle.",
	darkzone_exit_allowed = "~r~Darkzone'dan çıkmak için tekneler geldi, kaçmak istiyorsan koş.",

	airdrop_taken_by = "^1%s Airdroptan çıkan %s eşyasını aldı.",

	available_death_effects = "Mevcut ölüm efektleri",
	available_modes = "Mevcut modlar",

	you_changed_your_ped_model = "~g~Ped modelini başarıyla değiştirdin.",
	i_want_to_change_my_ped = "Farklı bir ped modeli kullan",

	poll4_q1 = "Önümüzdeki sezondan ne bekliyorsunuz?",
	poll4_q1_a4 = "Airdrop, bölge kapma vb.Gibi yeni dünya etkinliği.",
	poll4_q1_a1 = "Zindanlar gibi daha fazla PvE içeriği",
	poll4_q1_a2 = "Casino / yarışlar gibi daha fazla oyun",
	poll4_q1_a3 = "PvP içeriği",

	poll4_q2 = "Daha fazla sıralama/turnuva moduna sahip olmak ister misiniz?",
	poll4_q2_a1 = "Evet",
	poll4_q2_a2 = "Hayır",

	poll4_q3 = "Keskin nişancıların dükkanlarda satılmasını ister misiniz?",
	poll4_q3_a1 = "Evet",
	poll4_q3_a2 = "Hayır",

	poll4_q4 = "Extinction'da en çok neyden zevk alıyorsunuz?",
	poll4_q4_a1 = "PvP",
	poll4_q4_a2 = "PvE",
	poll4_q4_a3 = "Ticaret",

	dungeon_no_more_time = "~r~Çok yavaştın. Zindan kapatıldı.",
	dungeon_participant_left = "~r~%s Zindandan ayrıldı.",
	started_dungeon_party = "~b~Bir zindan odası oluşturdun.",
	dungeon_party_no_longer_exists = "~r~Bu zindan partisi artık yok.",
	dungeon_invitation_expired = "~r~Zindan partisi davetinin süresi doldu.",
	dungeon_join_party = "~g~Zindan partisine katıldın.",
	dungeon_too_late_for_invitation = "~r~Çok geç kaldın. Oyunun bu aşamasında zindana katılamazsın.",
	dungeon_already_invited_this_player = "~r~Bu oyuncuyu zaten davet ettin.",
	dungeon_invitation_received = "~b~%s~w~ Oyuncusundan zindan partisine davet aldın .\nPartisine katılmak için ~g~/dungeon join %s~w~ yaz.",
	dungeon_invitation_sent = "~g~%s~w~ Oyuncusunu zindan partisine davet ettin.",

	i_want_to_enter_a_dungeon = "Zindan'a girmek istiyorum.",
	dungeon_list = "Zindan listesi",

	dungeon = "Zindan",
	dungeons = "Zindanlar",

	you_need_x_keys = "Zindan'a katılmak için ~y~%s adet zindan anahtarına~w~ ihtiyacın var.",
	time_remaining = "Kalan Süre",
	you_killed_the_dungeon_boss = "~r~Zindan canavarını öldürdün.",
	dungeon_kill_final_boss = "Son odadasın. Hazineyi almak için canavarı öldür.",
	dungeon_died_remaining = "Öldün , ~r~%s~w~ Şansın kaldı dikkatli ol.",
	dungeon_died = "~r~Son şansını kullandın ve canın kalmadı , Öldün!",

	dungeon_already_in_party = "~r~Zaten zindan partisindesin , Partiden ayrılmak için \n~w~/dungeon quit yaz..",
	dungeon_does_not_exist = "~r~Bu zindan mevcut değil.",
	dungeon_ready = "~g~%s~w~ Hazır!",
	dungeon_not_ready = "~r~%s~w~ Henüz hazır değil.",
	not_released_yet = "Bu özellik henüz kullanılabilir değil!",
	feature_only_supporters = "~b~Bu özellik henüz test aşamasında sadece Diamond/Gold supporters üyeler kullanabilir.",

	feature_not_enabled = "~b~Bu özellik henüz aktif değil.\n~w~Lütfen aktif edilmesini bekleyin.",
	dungeon_charid_required = "~r~Lütfen yazdığınız komuttan sonra arkadaşınızın karakter id'sini ekleyin.(Ekranın sol üst tarafında) .\nÖrnek: /dungeon invite 1234",

	remaining_lives = "Kalan Can",

	poll5_q1 = "Wallhack veya aimbot'lardan şüpheleniyorlarsa, anticheat'imizin hilecilerin tüm ekranını yakalayacağını kabul eder misiniz? (Oyun pencereli moddaysa masaüstünüzün bir bölümünü gösterebilir, ancak bu yakalamalar kaydedilmeyecek ve yalnızca güvenilir moderatörler tarafından kullanılacaktır)",
	poll5_q1_a1 = "Atla - Yok say.",
	poll5_q1_a2 = "Evet, Yeni yöntemi kabul ediyorum",
	poll5_q1_a3 = "Hayır, Kabul etmiyorum",





	-- S4

	redzone_kill_leader_killed = "~r~Redzone Lideri~w~ Öldürüldü.",
	redzone_kill_leader_fled = "~r~Redzone Lideri~w~ Kaçtı.",
	redzone_get_back_kill_leader_before_x = "~r~Redzone Dışındasın~w~ ~r~%s Saniye~w~ İçerisinde geri dönmezsen ünvanını kaybedeceksin.",
	redzone_kill_leader_new_xp_step = "~r~Redzone XP Artışı\n~b~+%s%~w~ katı bonus",
	remaining_lives = "Kalan Can",

	name_tag = "Crew etiketi",
	redzone_changed = "~r~Redzone konumları değişti, Haritanı kontrol et!",

	-- Squad
	squad_not_leader = "~r~Takımın lideri değilsiniz.",
	squad_kicked_by_x = "~r~%s~w~ Tarafından ekipten ~r~Atıldın~w~",
	squad_you_kicked_x = "~r~%s~w~ isimli oyuncuyu ekipten attın.",
	squad_invited_x = "Takıma ~r~%s~w~ isimli oyuncuyu davet ettin.",
	squad_invited_you_x = "~r~%s~w~ seni takıma davet etti.\nKatılmak için ~r~/squad join %s~w~ yaz.",
	squad_you_set_new_leader = "~r~%s~w~ İsimli oyuncuyu yeni takım ~r~Lideri~w~ yaptın.",
	squad_you_are_new_leader = "~g~Takımın yeni liderisin.",
	squad_not_invited = "~r~Takıma davet edilmediniz.",
	squad_joined_squad = "~g~Takıma katıldın.",
	squad_left = "~r~Takımdan ayrıldın.",
	squad_already_in = "~r~Zaten takımdasın.",
	squad_created_x = "Yeni takım oluşturdun. ~b~(%s)",
	squad_x_joined = "~b~%s~w~ Takıma katıldı.",
	squad_leader_deleted = "~r~Lider Takımı sildi.",
	write_yes_to_confirm = "Onaylamak için yes yazın.",
	invite_a_player_write_char_id = "Oyuncu Davet edin. Karakter id'sini yazın.",

	-- Help stuff
	press_enter_beginner_guide = "Öğretici moduna başlamak için ~INPUT_ENTER~ tuşuna basın",
	welcome_glife = "~r~GLife Extinction'a~w~ Hoşgeldin!",
	you_are_playing_server_x_with_x = "Oynadığın sunucu ~b~#%s~w~, Aktif olarak ~b~%s Oyuncu ile birlikte oynuyorsun.~w~",
	start_beginner_guide = "Başlangıç modunu başlat.",
	play_now = "~g~Şimdi oyna!",
	interact_npc_fast_travel = "Hızlı seyahat NPC'si ile etkileşime gir",

	-- Tutorial
	tutorial_beginner_end_msg = "~r~Zaman ayırdığın için teşekkürler!\n~w~Extinction oynarken iyi eğlenceler, Herhangi bir sorunuz varsa, sohbeti kullanın veya discord sunucumuza katılın. discord.gg/gtalife",
	tutorial_beginner_start_msg = "~r~GLife Extinction'a hoş geldiniz!\n~w~Bu kısa kılavuz, bu oyun moduna nasıl başlayacağınızı açıklamayı amaçlamaktadır.",
	tutorial_beginner_camera_01 = "~r~~BLIP_557~ ~r~Ana güvenli bölge\n~w~Alışveriş yapabileceğiniz ve eşya depolayabileceğiniz, aynı zamanda ekipmanınızı kişiselleştirebileceğiniz ve diğer oyuncularla ticaret yapabileceğiniz güvenli bir alandır.",
	tutorial_beginner_camera_02 = "~BLIP_568~ ~r~Depolama sandıkları\n~w~Burada özel deponuza erişebilir ve değerli eşyalarınızı saklayabilirsiniz.",
	tutorial_beginner_camera_03 = "~BLIP_567~~BLIP_556~~BLIP_658~ ~r~NPC Marketleri\n~w~Silah, araç veya ekipman gibi birçok eşyayı mağazadan satın alabilir ve satabilirsiniz.",
	tutorial_beginner_camera_04 = "~BLIP_84~ ~r~Ödül Avcısı\n~w~Hedefi bulup öldürmeyi başarırsanız, kişinin başına konulan ödülü kazanırsınız.",
	tutorial_beginner_camera_05 = "~BLIP_176~ ~r~Tehlikeli Dünya\n~w~Zombiler ve düşman oyuncularla tanışacaksınız. Hepsi seni öldürmek isteyecekler, ama deneyim (XP) ve büyük ganimet elde etmenin en iyi yolu onlar.",
	tutorial_beginner_camera_06 = "~BLIP_303~ ~r~Redzone Alanları\n~w~Orada daha iyi ganimet bulabilir ve öldürmelerinizden daha fazla deneyim (XP) kazanabilirsiniz.",
	tutorial_beginner_camera_07 = "~BLIP_648~ ~r~Darkzone Adası\n~w~Burada eşyalarını koruyamazsın ve kolayca kaçamazsınız, ancak MK2 silahları veya keskin nişancılar gibi üst düzey ganimetleri bulmak için en iyi yerdir.",
	tutorial_beginner_camera_08 = "~BLIP_575~ ~r~Loot ve keşif fırsatları\n~w~Airdrop kasaları için savaşabilir, aynı zamanda zindan patronunu keşfedip onunla savaşabilirsiniz.",
	tutorial_beginner_training_01 = "~g~Eğitim odasına katıldın.\n~w~Hazır olduğunda ~INPUT_JUMP~ tuşu ile zıpla.",
	tutorial_beginner_training_02 = "~g~Envanteri kullanalım.\n~w~  ~%s~ Tuşuna basarak envanterini aç.",
	tutorial_beginner_training_03 = "~g~Bir silah kuşan.\n~w~Envanteri açın ve kısayol çubuğuna bir silah sürükleyin.\n Ve envanteri kapatıp ilgili tuşa basın ~b~1/2/3/4/5/6/7~w~.\n~r~Eğer herhangi bir silahın yoksa ~b~/kit newbie komutunu kullan.",
	tutorial_beginner_training_04 = "~g~Silahınıza cephane doldurun.\n~w~Bir silah kuşanın ve kısayol çubuğunuza bir kutu cephane koyun. Ardından envanteri kapatıp kısayol tuşuna basın.",
	tutorial_beginner_training_05 = "~g~Son olarak araçlar.\n~w~Tıpkı bir silahı kuşandığınız gibi arabayı kısayol çubuğunuza sürükleyin ve kısayol tuşuna basın. Arabayı tekrar envantere almak için (saklamak için) ~%s~ tuşuna basın.",
	tutorial_beginner_training_success_01 = "~g~Harika , şimdi başlayabiliriz!",
	tutorial_beginner_training_success_02 = "~g~Güzel, Öğrenmeye başladın.\n~w~Tüm eşyaları bu şekilde kullanabilirsin.",
	tutorial_beginner_training_success_03 = "~g~Güzel, Öğrenmeye başladın.\n~w~Tüm eşyaları bu şekilde kullanabilirsin.",
	tutorial_beginner_training_success_04 = "~g~Güzel, Öğrenmeye başladın.\n~w~Eğitimi başarıyla geçtin.",

	-- Darkzone stuff
	contaminated = "Kirlenmiş",
	darkzone_boat_leaving_in = "Tekne ayrılıyor.",
	darkzone_exit = "Çıkış Noktası",
	purificator = "Arındırıcı",
	you_entered_the_darkzone = "~r~Darkzone'a girdiniz.",
	you_left_the_darkzone = "~r~Darkzone'dan ayrıldınız.",
	cannot_enter_darkzone_time = "~r~Darzone henüz açılmadı, lütfen bekleyin.",
	darkzone_is_full = "~r~Darkzone dolu, lütfen bekleyin.",
	darkzone_exit_allowed = "~r~Tekneler sizi darkzone'dan kaçırmak için geldi, kaçmak istiyorsan teknelere koş.",
	darkzone_close_time = "Kapanıyor",
	darkzone_surviving_since = "Surviving since",
	darkzone_points = "Puanlar",
	darkzone_points_x = "~r~Darkzone Puanları: ~w~+%s",
	darkzone_landing_in_x = "~b~%s Dakika~w~ içerisinde açılacak.",
	darkzone_open_press_context = "Darkzone Açıldı ~w~.\nDarkzone'a girmek için  ~INPUT_CONTEXT~ tuşuna bas.",
	darkzone_outside_warning = "~r~Darkzone'un dışındasın, geri dön ya da öl.",
	darkzone_close_warning = "~r~Darkzone yakında kapanıyor~w~.\nBurada uzun süre kalmamalısın.",
	darkzone_close_damage = "Darkzone kapandı, artık tüm alan kirlendi.",
	darkzone_not_enough_points_to_exit = "Darkzone'dan ayrılmak için ~r~%sx Puana~w~ ihtiyacın var",
	press_e_to_exit_the_darkzone = "Darkzone'dan ayrılmak için  ~INPUT_CONTEXT~ tuşuna bas.\n~r~Ayrılmak için x%s Darkzone puanına ihtiyacın var.",
	use_purificator = "Arındırıcıyı kullanın",
	darkzone_not_enough_points_to_start_purificator = "Arındırıcıyı başlatmak için ~r~%sx puana~w~ ihtiyacın var.",
	darkzone_not_enough_points_to_refill_purificator = "Arındırıcıyı başlatmak için ~r~%sx puana~w~ ihtiyacın var",
	darkzone_too_far_from_purificator = "~r~Arındırıcıdan çok uzaktasın.",
	darkzone_cant_remove_while_running_purificator = "~r~Arındırıcı çalışırken eşyaları alamazsın.",
	darkzone_purificator_running = "~r~Arındırıcı çalışırken eşya koyamazsın.",
	darkzone_purificator_running_refill = "~r~Arındırıcı çalışırken makineyi yeniden dolduramazsınız.",
	darkzone_put_x_in_purificator = "Arındırıcıya ~r~%s~w~ eşyasını koydunuz.",
	darkzone_you_took_x_from_purificator = "Arındırıcıdan ~r~%s~w~ eşyasını aldınız",
	darkzone_purificator_does_not_need_refill = "Arındırıcıyı ~r~doldurman~w~ gerekiyor.",
	darkzone_refilled_purificator_x = "Arındırıcıyı doldurmak için ~r~x%s puan~w~ harcadınız.",
	darkzone_open = "Darkzone girişleri açıldı.\n~r~Herhangi bir güvenli bölgede bir taşıyıcı bulun.",
	darkzone_item_clean = "Bu öğe zaten temiz.\n~r~Yalnızca kirli eşyaları koyabilirsiniz.",

	dungeon_cooldown_between = "Zindanı tekrardan başlatmak için ~r~%s dakika~w~ beklemelisin.",
	set_as_default = "Bu araç modeli için varsayılan olarak ayarla.",
	car_custom_presets_saved = "Modifiye  ~g~%s~w~  olarak kaydedildi.",
	marketplace_you_received_x_x = "~b~%sx ~g~%s~w~ Aldın.",

	above_level_x_no_longer_possible_loot_safe = "%s sıralaması üzerindeki oyuncular, güvenli bölgelerdeki zombileri yağmalayamaz."
}

AddLanguage("tr", my_language)
